[MTM-48946] Added a best practices section for micro frontends
SoftwareAG/c8y-docs pull request #1015
Opened 2023-05-03 14:03 UTC by janhommes

2023-05-03 14:37 UTC, reey commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +Basically all developer stories start with our CLI tool. You can scaffold a new application and decide, which demo you want to use. E.g. for a plugin you can try the `widget-plugin` demo. This chapte
typo `it ws already` => `it was already`
`what makes a application` => `what makes an application`

2023-05-03 14:37 UTC, reey commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + > The *manifest file* contains all the options that are stored in the `package.json` `c8y.application` property. On build it will be compiled to a cumulocity.json file. When you upload a archive con
`a archive` => `an archive`

2023-05-03 14:37 UTC, reey commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + - `version`: This is the version that is used and displayed to the end-user. This version will be pinned if a plugin is installed and you cannot upload the same version twice. Therefore you should u
`semver or similar`
afaik it should always be semver, right? also repo connect will only sync semver

2023-05-03 14:37 UTC, reey commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +#### How can I bundle assets correctly into my package?
Maybe also mention how to use the copy plugin for e.g. screenshots in the README?

2023-05-03 14:37 UTC, reey commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + 1. Contribute to our open source plugins. A list can be found [here](https://github.com/topics/cumulocity-package). There is a official repository which is managed by the internal R&D team of Cumulo
I guess the `Cumulocity` terms and links to the SAG GitHub need to be somehow adjusted for customers branding this documentation?

2023-05-05 08:45 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + - `homepage` use this to point to an external application where more information can be found.
```suggestion
 - `homepage`: Use this to point to an external application where more information can be found.
```

2023-05-05 08:45 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +Additional you can add more information inside a detailed readme.md file which is then displayed in the package detail view. Those packages, are the released artefact. As soon as you are ready, you d
```suggestion
Additional you can add more information inside a detailed readme.md file which is then displayed in the package detail view. Those packages, are the released artefact. As soon as you are ready, you deploy a package to the platform which anyone can use to extend (plugin) existing or install (blueprint) a new application. The next section explains what a package is and what is contained.
```

2023-05-05 08:45 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +As pointed out in the user-stories, you can develop two different kind of micro frontends: Blueprint and/or plugins. Both are in the end only applications uploaded to the application API and hosted.
```suggestion
As pointed out in the user-stories, you can develop two different kind of micro frontends: Blueprint and/or plugins. Both are in the end only applications uploaded to the application API and hosted. As any of those hosted applications could contain more than one plugin or even a combination of blueprints and plugins, a new conceptual unit was introduced called 'packages'. Packages allow you to bundle multiple plugins and/or a blueprint into one package and additional versioning those. An optimal package should contain:
```

2023-05-05 08:45 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +> Tip: From 10.17 up you have now typed helper function called `hook<<Name>>`. For example you can use `hookNavigator()` in a provider to hook a node into the navigator.
format as admonition

2023-05-05 08:45 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + We definitely recommend using option 2. and if needed verify your application with option 3. Option 1. should be avoided, as you could run into common pitfalls explained in the next chapter.
```suggestion
 We definitely recommend using option 2. and if needed verify your application with option 3. Option 1. should be avoided, as you could run into common pitfalls explained in the next section.
```

2023-05-05 08:45 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +`http://<<instance>>/apps/<<context-path>>@<<version>>/my-image.png`. As you see, you might not want to change the version on each deployment. Therefore we recommend to let the bundler handle images.
```suggestion
`http://<<instance>>/apps/<<context-path>>@<<version>>/my-image.png`. As you see, you might not want to change the version on each deployment. Therefore we recommend to let the bundler handle images. This is done by simply importing an image into an typescript file. The bundler will always return the correct path to the image. For example, create an `assets/assets.ts` and write the following:
```

2023-05-05 08:45 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + > Note: This is only needed if you want to share an application with every Cumulocity customer. If you want to share a package with your customers (for example on an enterprise tenant) you can simpl
format as admonition

2023-05-05 14:42 UTC, rssag requested changes

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + 1. Classic: Run your application and simply import your module into the AppModule. You can then simply start your application by running `c8ycli serve`
```suggestion
 1. Classic: Run your application and import your module into the AppModule. Then start your application by running `c8ycli serve`.
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + 2. Lazy-Loaded: Run your application but don't import the module. Instead point the remote to your module (this is basically a self imported plugin). Here you only need to point the `c8y.application
```suggestion
 2. Lazy loading: Run your application but don't import the module. Instead, point the remote to your module (this is basically a self imported plugin). Point the `c8y.application.remotes` option to your module:
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + This has a big benefit, as your application then "acts" as a shell and you already can see, where you might have issues with lazy loading.
```suggestion
 This has the benefit that your application acts as a shell and you can see where you might have issues with lazy loading.
```

Also, this and the code listing above should be indented to properly render below the second list item.

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + 3. Shell: Run the application and point it to any shell by running `c8ycli serve --shell cockpit`. This has the benefit of testing it in a real application. But as the shell application is already d
```suggestion
 3. Shell: Run the application and point it to any shell by running `c8ycli serve --shell cockpit`. This has the benefit of testing it in a real application. But as the shell application is already deployed, you might be getting unhelpful error-stacks.
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +#### What are common developer pitfalls when developing a plugin?
```suggestion
#### Common developer pitfalls when developing a plugin
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +There are several issues you might want to avoid:
```suggestion
There are several issues to avoid:
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +2. Lazy loading: Remember that every plugin is imported lazily. Meaning, that the rules of lazy loaded modules apply to those modules. Meaning: Don't use `forRoot` on the ngx-components `CoreModule`
```suggestion
2. Lazy loading: remember that every plugin is imported lazily. This means that the rules of lazily loaded modules apply to those modules.  Don't use `forRoot` on the ngx-components `CoreModule` or the `RoutingModule`. Use `forRoot` for any newly introduced dependency. 
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +3. Injectors: As of the lazy loaded approach, injectors are sometimes an issue. Usually you have a new injector per plugin. This is done automatically as long as you use the hooks without a factory f
```suggestion
3. Injectors: With the lazy loading approach, injectors are sometimes an issue. Usually you have a new injector per plugin. This is done automatically as long as you use the hooks without a factory function. If you use a factory function, you must provide the injector:
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +(1): This is important if your component provided wants to use a service that is only available in your plugin. If you don't define the injector, it will use the root injector and therefore will lead
```suggestion
`(1)`: This is important if the component you provided wants to use a service that is only available in your plugin. If you don't define the injector, it will use the root injector and therefore will lead to injector issues.
```

Also, this and the code listing above should be indented to properly render below the third list item.

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +#### How can I bundle assets correctly into my package?
```suggestion
#### How to bundle assets in a package
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + > Note: This is only needed if you want to share an application with every Cumulocity customer. If you want to share a package with your customers (for example on an enterprise tenant) you can simpl
```suggestion
{{< c8y-admon-info >}}
This is only needed if you want to share an application with every {{< product-c8y-iot >}} customer. If you want to share a package with your customers (for example on an enterprise tenant) you can simply upload them in the Packages view and set the availability to 'shared'.
{{< /c8y-admon-info >}}
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +Typescript will throw an error, as the it does not know how to handle `.png` files. You can tell typescript to accept such files by declaring them as module in a `assets/index.d.ts`file:
```suggestion
Typescript will throw an error, as the it does not know how to handle PNG files.
Tell typescript to accept such files by declaring them as a module in the * assets/index.d.ts* file:
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +Now somewhere in your plugin/blueprint you can simply import the asset and use the path to display the image:
```suggestion
Now import the asset somewhere in your plugin or blueprint and use the path to display the image:
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +The `assetPaths.previewImage` can now simply be used in any component or in a hook. You can see a full example when you scaffold the *widget-plugin* with `c8ycli new` (Note the feature and example wa
```suggestion
The `assetPaths.previewImage` can now be used in any component or in a hook.
You can see a full example when you scaffold the *widget-plugin* with `c8ycli new`.
Note that the feature and example was added with version 10.17.0.
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +#### What about translations?
```suggestion
#### Translations

```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +Translations should work out of the box as for standard custom application. Add a .po file to your repository and import it into your `index.ts` file. Translation of a plugin might overwrite existing
```suggestion
Translations should work out of the box as for standard custom application.
Add a `.po` file to your repository and import it into your *index.ts* file.
The translation of a plugin might overwrite existing translations, as they are merged at run-time.
An example is created when you scaffold the *widget-plugin* with `c8ycli new`.
Note that there is a limitation: A plugin cannot add a new language. It can only extend the translated strings in the existing application.
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +#### What about styling? Is branding supported?
```suggestion
#### Styling and branding
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +Yes, branding is fully supported. It is recommended to use component-based styling for your applications. However you can also add customs global css styling by importing it.
```suggestion
Branding is fully supported.
We recommend you to use component-based styling for your applications.
However you can also add custom global CSS styling by importing it.
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +Again an example exist if you scaffold the *widget-plugin* with `c8ycli new`.
```suggestion
Again an example is created if you scaffold the *widget-plugin* with `c8ycli new`.
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +#### How to ensure that my application is always compatible?
```suggestion
#### How to ensure application compatibility

```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +1. You can only add plugins to so called "custom" applications. Custom applications basically means that you need to own the application. One side-effect is, that you don't get any automatic update a
```suggestion
1. You can only add plugins to so called "custom" applications. Custom applications mean that you must own the application. As a side effect, you don't get automatic updates. This ensures that any platform update does not break your application.
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +For plugin developers that want to provide always the most compatible version of their plugin, we recommend to look at our [community plugin Github project](https://github.com/SoftwareAG/cumulocity-c
```suggestion
For plugin developers who want to always provide the most compatible version of their plugin, we recommend to have a look at our [community plugin Github project](https://github.com/SoftwareAG/cumulocity-community-plugins), which includes some CI/CD workflows to test and verify that the newest version of a plugin still works. 
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +#### What is repository connect and how can I use it?
```suggestion
#### How to use repository connect

```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +Repository connect is a microservice which synchronies plugins or blueprints with an instance of our platform. It needs to be installed on the management tenant and you can connect multiple repositor
```suggestion
Repository connect is a microservice which synchronizes plugins or blueprints with an instance of the {{< product-c8y-iot >}} platform.
It must be installed on the management tenant and you can connect multiple repositories.
Currently, only our Software AG public GitHub is connected.
You can participate and share blueprints or plugins in multiple ways:
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + 1. Contribute to our open source plugins. A list can be found [here](https://github.com/topics/cumulocity-package). There is a official repository which is managed by the internal R&D team of Cumulo
```suggestion
 1. Contribute to our open source plugins. A list can be found in our [{{< product-c8y-iot >}} GitHub packages](https://github.com/topics/cumulocity-package). There is an [official repository](https://github.com/SoftwareAG/cumulocity-community-plugins) which is managed by the internal R&D team of {{< product-c8y-iot >}}.
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + 1. Contribute to our open source plugins. A list can be found [here](https://github.com/topics/cumulocity-package). There is a official repository which is managed by the internal R&D team of Cumulo
i don't think we have a shortcode link to that. there's some shortcodes for links, here's a list:
https://github.com/SoftwareAG/c8y-docs/tree/develop/themes/c8ydocs/layouts/shortcodes

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +For synchronization the micro services searches for all repositories with a certain topic (for Software AG it's `cumulocity-package`) and a release. The release should only be one ZIP file containing
```suggestion
For synchronization the micro services searches for all repositories with a certain topic and a release (for {{< company-sag >}} it's `cumulocity-package`).
The release should be a single ZIP file containing the plugin or blueprint.
There is a security mechanism in place which is called scoping which disallows uploading an application without a certain prefix.
This is to avoid that any synced package can overwrite a default application like cockpit or administration.
Prefix the `key` and `contextPath` with the configured prefix (for {{< company-sag >}} it's `sag-pkg`).
```

2023-05-05 14:42 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +All applications that are uploaded via repository connect are labeled as `community` plugins and the user is informed of the license and maintenance agreements up on installation (from version 10.18
```suggestion
All applications that are uploaded via repository connect are labeled `community` plugins and the user is informed of the license and maintenance agreements on installation (from version 10.18.0).
```

2023-05-05 15:17 UTC, rssag commented
what are the target versions?

2023-05-08 10:54 UTC, janhommes commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + 1. Contribute to our open source plugins. A list can be found [here](https://github.com/topics/cumulocity-package). There is a official repository which is managed by the internal R&D team of Cumulo
Can we add one more here?

2023-05-09 07:36 UTC, janhommes commented
> 

@rssag Not sure, best would be 10.16. But as we mention some features that only went to 10.18 or 10.17 I am not sure if this is possible?

2023-05-09 11:00 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> + 1. Contribute to our open source plugins. A list can be found [here](https://github.com/topics/cumulocity-package). There is a official repository which is managed by the internal R&D team of Cumulo
added one, gonna commit it in a bit

2023-05-09 11:02 UTC, rssag approved these changes

2023-05-10 06:46 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +This chapter explains our vision of this journey and describes our best practices regarding development.
```suggestion
This section explains our vision of this journey and describes our best practices regarding development.
```

2023-05-10 06:46 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +For the micro frontend story the target audience are solution architects with little developer experience.
```suggestion
For the micro frontend story, the target audience are solution architects with little developer experience.
```

2023-05-10 06:47 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +2. The blueprint should guides through the configuration of the application. One step is, for example, the installation of the required **microservices or plugins**.
```suggestion
2. The blueprint guides through the configuration of the application. One step is, for example, the installation of the required **microservices or plugins**.
```

2023-05-10 06:53 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +If you instead use the Web SDK you get a lot of functionality out of the box and by branding the application, you are able to make it look and feel like a product of your own development.
```suggestion
If you use the Web SDK instead, you get a lot of functionality out of the box and by branding the application, you are able to make it look and feel like a product of your own development.
```

2023-05-10 06:53 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +Furthermore you can provide it as an application blueprint to your customers enabling them to brand it to according to their needs.
```suggestion
Furthermore, you can provide it as an application blueprint to your customers, enabling them to brand it according to their needs.
```

2023-05-17 09:40 UTC, DawidSAG approved these changes

2023-05-17 09:40 UTC, DawidSAG commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +As pointed out in the user-stories, you can develop two kinds of micro frontends: Blueprints and plugins.
Blueprints => blueprints?

2023-05-17 10:21 UTC, janhommes commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +As pointed out in the user-stories, you can develop two kinds of micro frontends: Blueprints and plugins.
Guess as it is after a `:` uppercase is fine. But not sure. @MWindel ?

2023-05-22 09:16 UTC, MWindel commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +As pointed out in the user-stories, you can develop two kinds of micro frontends: Blueprints and plugins.
@DawidSAG @janhommes Yes, after a colon ":" we use uppercase.

2023-05-22 09:17 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +This section is about explaining the developer story of blueprints and plugins and will explain those details as well as the best practices to apply.
```suggestion
The next section explains the developer story of blueprints and plugins in detail and provides best practices.
```

2023-05-22 09:17 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +As pointed out in the user-stories, you can develop two kinds of micro frontends: Blueprints and plugins.
uppercase after ":"

2023-05-22 09:22 UTC, rssag commented on content/web/microfrontends-bundle/best-practices-for-packages.md
> +2. Lazy loading: remember that every plugin is imported lazily. This means that the rules of lazily loaded modules apply to those modules.  Don't use `forRoot` on the ngx-components `CoreModule` or t
```suggestion
2. Lazy loading: Remember that every plugin is imported lazily. This means that the rules of lazily loaded modules apply to those modules.  Don't use `forRoot` on the ngx-components `CoreModule` or the `RoutingModule`. Use `forRoot` for any newly introduced dependency.
```

(applying our own rule :D )

2023-05-22 09:53 UTC, merged

2023-05-22 09:59 UTC, rssag commented
cherry-picked to 10.18.0