MTM-53068 improvements and refresh in microservice sdk docs.
SoftwareAG/c8y-docs pull request #1017
Opened 2023-05-04 20:55 UTC by jkot-softwareag

- security general aspects (service and bootstap users, owner and subscriber tenants)
- up to date default jvm arguments
- additional notes in general development area

2023-05-05 06:26 UTC, slc-softwareag approved these changes

2023-05-05 06:26 UTC, slc-softwareag commented on content/microservice-sdk/rest-bundle/microservice-development.md
> +Note: All devices channel (*) is deprecated and should be avoided. Subscription on this channel may cause performance issues
:+1:

2023-05-05 07:20 UTC, d-mariak approved these changes

2023-05-05 07:40 UTC, pawelkowalczyksag approved these changes

2023-05-05 07:40 UTC, pawelkowalczyksag commented on content/microservice-sdk/rest-bundle/microservice-development.md
> +Note: All devices channel (*) is deprecated and should be avoided. Subscription on this channel may cause performance issues
```suggestion
Note: A channel for all devices (*) is deprecated and should be avoided. Subscription on this channel may cause performance issues 
```
I find it a bit weirdly worded. How about this?

2023-05-05 15:55 UTC, rssag requested changes

2023-05-05 15:55 UTC, rssag commented on content/microservice-sdk/concept-bundle/security.md
> +These permissions are visualized in the Administration application. The permissions are associated with the service user that is created when a platform administration associates a microservice with
```suggestion
These permissions are visualized in the Administration application. The permissions are associated with the service user that is created when a platform administration associates a microservice with a tenant (subscribes to it). The owner tenant must also be subscribed to if you intend to use microservice features on it. 
```

2023-05-05 15:55 UTC, rssag commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +The following locations are searched for Logback configuration file:
```suggestion
The following locations are searched for the Logback configuration file:
```

2023-05-05 15:55 UTC, rssag commented on content/microservice-sdk/rest-bundle/microservice-development.md
> +Refer to the [Inventory Child Operations](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Child-operations) in the {{< openapi >}} for more details.
```suggestion
{{< c8y-admon-info >}}
You can link multiple child assets or multiple child devices to the same parent in a single request. 
Refer to inventory child operations in the [Inventory API](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Child-operations) in the {{< openapi >}} for more details.
{{< /c8y-admon-info >}}
```

2023-05-05 15:55 UTC, rssag commented
what are the target versions?

2023-05-06 18:01 UTC, jkot-softwareag commented on content/microservice-sdk/rest-bundle/microservice-development.md
> +Note: All devices channel (*) is deprecated and should be avoided. Subscription on this channel may cause performance issues
(*) means the channel ending with *, which means listening to notifications from all devices and not a single one.
Examples
/events/1331421   - channel for notifications of events from device 1331421
/events/*   - channel for notifications of events from all devices (may be too much for subscribed client to handle)

2023-05-06 18:11 UTC, jkot-softwareag commented
> what are the target versions?

I have added target versions, from 10.16 up. In fact I think all of this is truth for longer, but 10.16 will be soon released as docs and version installed on cumulocity cloud environments.

2023-05-08 06:49 UTC, BeateRixen commented on content/microservice-sdk/concept-bundle/security.md
> +At the installation time of the microservice, an application is created in the owner tenant (usually "super-tenant") reflecting the new microservice. In addition, a bootstrap user is created in the o
We do not use the term "super tenant" as this is unclear. Could we say "usually the {{< management-tenant >}}"?

2023-05-08 06:50 UTC, BeateRixen commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +The following locations are searched for the Logback configuration file:
```suggestion
The following locations are searched for the logback configuration file:
```

2023-05-08 06:52 UTC, BeateRixen commented on content/microservice-sdk/rest-bundle/microservice-development.md
> +on both the client and the server side, and this options may be removed in future versions of {{< product-c8y-iot >}}.
```suggestion
on both the client and the server side, and this option may be removed in future versions of {{< product-c8y-iot >}}.
```

2023-05-08 07:10 UTC, jkot-softwareag commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +The following locations are searched for the Logback configuration file:
"logback" is the library, like "Spring". It is up to you to decide @BeateRixen. For Spring we usually use big letter, for Logback I am not sure.

2023-05-08 07:14 UTC, jkot-softwareag commented on content/microservice-sdk/concept-bundle/security.md
> +At the installation time of the microservice, an application is created in the owner tenant (usually "super-tenant") reflecting the new microservice. In addition, a bootstrap user is created in the o
well, somebody told me "super-tenant" is "management or EE tenant" when I wanted to remove it from another place in the code. The problem with previous explanation was a claim that only management can create microservices, and in fact every tenant with subscibed feature-microservice-hosting can do it. Many EE tenants use this feature and microservices are subscribed to their subtenants.

Maybe 
`(usually management or Enterprise Edition tenant)` 
?

2023-05-08 13:25 UTC, BeateRixen commented on content/microservice-sdk/concept-bundle/security.md
> +At the installation time of the microservice, an application is created in the owner tenant (usually "super-tenant") reflecting the new microservice. In addition, a bootstrap user is created in the o
I would then phrase it "usually a {{< management-tenant >}} or {{< enterprise-tenant >}}". We use short codes for the tenant types. Btw, it is just Enterprise tenant, not Enterprise edition tenant :-).

I will change the terminology in the other place as well then, thanks for the link. We should be really clear with these terms.

2023-05-08 13:36 UTC, jkot-softwareag commented on content/microservice-sdk/rest-bundle/microservice-development.md
> +on both the client and the server side, and this options may be removed in future versions of {{< product-c8y-iot >}}.
done and improvement squashed with previous commit

2023-05-09 07:34 UTC, BeateRixen approved these changes

2023-05-09 07:36 UTC, merged