remove POP from 1015
SoftwareAG/c8y-docs pull request #1032
Opened 2023-05-09 20:39 UTC by mmed-softwareag

2023-05-10 07:52 UTC, BeateRixen approved these changes

2023-05-12 11:30 UTC, rssag commented
@mmed-softwareag this needs another approval by someone from your team

2023-05-23 08:52 UTC, kowalczykmike requested changes

2023-05-23 08:52 UTC, kowalczykmike commented on content/device-sdk/mqtt-bundle/device-certificates.md
>  However, if you need some certificates between the CA certificate and the device certificate then it is the way to go.
Not all changes introduced by this PR  https://github.com/SoftwareAG/c8y-docs/pull/569 were reverted so maybe we can just revert it than creating new commit with removals?

2023-06-01 23:29 UTC, mmed-softwareag commented on content/device-sdk/mqtt-bundle/device-certificates.md
>  However, if you need some certificates between the CA certificate and the device certificate then it is the way to go.
done

2023-06-05 08:38 UTC, kowalczykmike approved these changes

2023-06-05 13:45 UTC, merged