Bugherd # 698 - Removing reference to Esper
SoftwareAG/c8y-docs pull request #1126
Opened 2023-05-24 13:54 UTC by MWindel

Removed sentence in Cockpit > Smart rules which was refering to Esper.

All changes will be cherry-picked to the respective release branches.

2023-05-24 13:58 UTC, BeateRixen approved these changes

2023-05-24 14:25 UTC, rthrippleton requested changes

2023-05-24 14:25 UTC, rthrippleton commented on content/users-guide/cockpit-bundle/smart-rules.md
> +{{< product-c8y-iot >}} includes a rule engine to analyze data in realtime and to perform actions based on data.
Realising that "rule engine" isn't a good description for the streaming analytics component:
```suggestion
{{< product-c8y-iot >}} includes Streaming Analytics which can analyze data in realtime and perform actions based on data.
```

2023-05-24 14:25 UTC, rthrippleton commented on content/users-guide/cockpit-bundle/smart-rules.md
> +{{< product-c8y-iot >}} includes a rule engine to analyze data in realtime and to perform actions based on data.
You might also want to xref to the Streaming Analytics guide.

2023-05-24 14:44 UTC, kailol-sag commented on content/users-guide/cockpit-bundle/smart-rules.md
> +{{< product-c8y-iot >}} includes a rule engine to analyze data in realtime and to perform actions based on data.
I'd put it as "... includes the Streaming Analytics application which ...."

2023-05-25 08:17 UTC, MWindel commented
@rthrippleton @kailol-sag In which target versions should this be as well?

2023-05-25 08:24 UTC, kailol-sag commented on content/users-guide/cockpit-bundle/smart-rules.md
> +{{< product-c8y-iot >}} includes Streaming Analytics which can analyze data in realtime and perform actions based on data.
```suggestion
{{< product-c8y-iot >}} includes the Streaming Analytics application which can analyze data in realtime and perform actions based on data.
```

2023-05-25 12:31 UTC, merged