Added requirements for connectivity and sms
SoftwareAG/c8y-docs pull request #1137
Opened 2023-05-30 15:13 UTC by BeateRixen

2023-05-30 15:15 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
> +ROLES & PERMISSIONS:
I only found this sentence and moved it into the requirements section. I didn´t find any info which team is responsible for the properties library.

2023-05-30 15:17 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
>  ### Providing SMS provider credentials
@l2p- Please have this reviewed and if needed enhanced by your team.

2023-05-30 15:17 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
> +ROLES & PERMISSIONS:
@l2p- Please have this reviewed and if needed enhanced by your team.

2023-05-30 15:24 UTC, BeateRixen commented
I have added some more requirements for the "Changing settings" chapter. I only added what I could find in the text, i.e. the requirements for connectivity and SMS. For applications and properties library, I assume the PlaMa team is responsible? Couldn´t find it in the feature & teams sheet.

2023-07-27 10:26 UTC, l2p- requested changes

2023-07-27 10:26 UTC, l2p- commented on content/users-guide/administration-bundle/changing-settings.md
> +To modify SMS provider configurations: ADMIN permission for the permission type "SMS"
```suggestion
To set or remove SMS provider configurations: ADMIN permission for the permission type "SMS"
```

2023-07-27 10:26 UTC, l2p- commented on content/users-guide/administration-bundle/changing-settings.md
> +To add or replace credentials: ADMIN permission for the permission type "Connectivity"
```suggestion
To set or remove connectivity provider configuration: ADMIN permission for the permission type "Connectivity"
```

2023-07-31 07:34 UTC, Airdroplet commented on content/users-guide/administration-bundle/changing-settings.md
> +ROLES & PERMISSIONS:
This looks ok from my perspective. Properties lib belong to Platform team.

2023-07-31 07:34 UTC, Airdroplet approved these changes

2023-07-31 07:58 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +To set or remove connectivity provider configuration: ADMIN permission for the permission type "Connectivity"
```suggestion
To set or remove connectivity provider configurations: ADMIN permission for the permission type "Connectivity"
```

2023-07-31 07:58 UTC, rssag approved these changes
1 suggestion + approval

2023-07-31 08:09 UTC, merged