Convert Device management library document into markdown
SoftwareAG/c8y-docs pull request #115
Opened 2021-12-01 14:04 UTC by JoshuaAdemola

2021-12-13 13:10 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +Devices may announce their supported capabilities using the ```c8y_SupportedOperations``` fragment in their own managed object. The fragment itself is an array of strings. It may contain built-in ope
with their meaning detailed below > where below? Not sure where this refers to. Also better have something like "see below for details"

2021-12-13 13:11 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +Some capabilities also introduce their own ```c8y_Supported<...>``` fragments with a similar concept. These fragment allow devices announce the ability to handle certain types of log files or configu
These fragment > These fragments
allow devices announce > allow devices to announce

2021-12-13 13:12 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +Devices are responsible for communicating their current status to Cumulocity IoT. Status is usually communicated in the device's own managed object. We provide specific fragments for each capability.
Status > The status
We provide > Cumulocity IoT provides

2021-12-13 13:14 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +In practice this usually means that a device should publish its local state concerning all of its supported capabilities during startup, when it was requested to change its local state, and whenever
when it was requested to change its local state > when requested to change its local change
and whenever any external change was detected > and whenever any external change has been detected

2021-12-13 13:15 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +Operations are always created with status PENDING. Devices are responsible for moving operations along into different statuses in their lifecycle. Before beginning processing an operation the device
Before beginning processing > Before beginning to process

2021-12-13 13:15 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +We provide the static templates 501, 502, and 503 to manipulate the operation status. These templates take the operation type as input parameter and always update the oldest operation in the precedin
We provide > Cumulocity IoT provides

2021-12-13 13:17 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +If any error occurs during the processing of an operation the device must set the operation status to FAILED and provide a failure reason as descriptive as possible. This includes any unexpected or e
to be completed fully > to be fully completed 
in an operation that contains multiple distinct steps > in an operation with multiple distinct steps

2021-12-13 13:22 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +In cases where a device receives an operation that requests a state that is already present, it is up to the device how the operation should be handled. This case may happen when a device is requeste
This case may happen > This may for example be the case

2021-12-13 13:23 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +1. Consider the package as already installed and skip its installation because the requested state is already present
Add full stops at the end of each entry

2021-12-13 13:23 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +The ideal option depends on the use case and the concrete operation. Regardless of which option is chosen the device must ensure that its local state and the on communicated to Cumulocity IoT remains
and the on  > and the one

2021-12-13 13:29 UTC, BeateRixen commented on content/reference/device-management-library-bundle/device-info.md
> +![Device status](/images/reference-guide/device-status.png)
The image is too large and shows Dafinas name. You can probably just create your own image.

2021-12-13 13:31 UTC, BeateRixen commented on content/reference/device-management-library-bundle/device-info.md
> +In order to receive any operation a device must declare the agent marker fragment in its own managed object. This will enable the platform to send operations to this device and for all child devices
and for all child devices in its child hierarchy that don’t carry this fragment themselves. > not sure if I get this. Should this mean "and to all child devices in its child hierarchy"

2021-12-13 13:33 UTC, BeateRixen commented on content/reference/device-management-library-bundle/device-info.md
> +Devices capable of restarting remotely can announce this capability by adding the ```c8y_Restart``` operation to the device's own ```c8y_SupportedOperations``` fragment. Then the device details page
device details page > **Device details** page

2021-12-13 13:34 UTC, BeateRixen commented on content/reference/device-management-library-bundle/device-info.md
> +Upon clicking the restart button in Device management UI an operation as follows is sent:
in Device management UI > in the Device Management application

2021-12-13 13:35 UTC, BeateRixen commented on content/reference/device-management-library-bundle/device-info.md
> +|serialNumber|String|No|The hardware serial number of the device.|
The details column sometimes has full stops and sometimes not, please unify

2021-12-13 13:36 UTC, BeateRixen commented on content/reference/device-management-library-bundle/alarms.md
> +A device may raise an alarm at any time. Typically alarms are used to communicate problem statuses un the devices environment.
un the devices > in the devices

2021-12-13 13:43 UTC, BeateRixen commented on content/reference/device-management-library-bundle/child-devices.md
> +In order to link a device the parent device should post to its inventory API the following request containing the id of the child device.
should > must
id > ID

2021-12-13 13:44 UTC, BeateRixen commented on content/reference/device-management-library-bundle/child-devices.md
> +To add child device to existing device you need to connect as existing device and call child create template:
To add child device to existing device > To add a child device to an existing device
you need to  > you must
to connect as existing device and call child create template > I don´t get that

2021-12-13 13:45 UTC, BeateRixen commented on content/reference/device-management-library-bundle/child-devices.md
> +Using the agent marker fragment ```com_cumulocity_model_Agent``` on the parent device, but not on child devices effectively declares the device as a connected gateway for its children. The children a
remove comma after device

2021-12-13 13:46 UTC, BeateRixen commented on content/reference/device-management-library-bundle/child-devices.md
> +Our built-in static SmartREST response templates always include a device identifier as first parameter to determine the targeted child device. Here is an example of the 510 static response template f
Our > Also rephrase with Cumulocity IoT

2021-12-13 13:47 UTC, BeateRixen commented on content/reference/device-management-library-bundle/child-devices.md
> +Custom response templates also contain the targeted device's external ID as first parameter. We recommend implementing a similar mechanism there as well.
We recommend implementing > to implement? Not sure but I think this is the rule

2021-12-13 13:48 UTC, BeateRixen commented on content/reference/device-management-library-bundle/remote-access.md
> +The tab will be visible if the following criteria are met:
The tab > the **Remote access** tab
will be visible > is available

2021-12-13 13:49 UTC, BeateRixen commented on content/reference/device-management-library-bundle/remote-access.md
> +* Cloud Remote Access microservice is subscribed to the needed tenant
Cloud Remote Access microservice > the Cloud Remote Access microservice

2021-12-13 13:49 UTC, BeateRixen commented on content/reference/device-management-library-bundle/remote-access.md
> +* 'c8y_RemoteAccessConnect' is added to the device's c8y_SupportedOperations
'c8y_RemoteAccessConnect' > format as code
c8y_SupportedOperations > format as code

2021-12-13 13:50 UTC, BeateRixen commented on content/reference/device-management-library-bundle/remote-access.md
> +When a user selects a remote access endpoint and presses the connect button a c8y_RemoteAccessConnect operation is created.
c8y_RemoteAccessConnect > format as code

2021-12-13 13:52 UTC, BeateRixen commented on content/reference/device-management-library-bundle/remote-access.md
> +|connectionKey|String|Yes|Shared secret to authenticate the connection request from device side.|
In the details column you usually do not have full stops, so I would remove them for consistency here as well

2021-12-13 13:53 UTC, BeateRixen commented on content/reference/device-management-library-bundle/remote-access.md
> +Cumulocity IoT currently supports VNC, SSH, and telnet. The device agent should be implemented independently of the remote access protocol used. The operation intentionally does not transfer the prot
telnet > Telnet
The agent must be capable of forward > The agent must be capable of forwarding

2021-12-13 13:54 UTC, BeateRixen commented on content/reference/device-management-library-bundle/remote-access.md
> +The operation is set to SUCCESSFUL after the connection is established. Disconnecting happens silently. Even if the connection was not terminated gracefully by any of the involved components, the ope
add full stop at the end

2021-12-13 13:55 UTC, BeateRixen commented on content/reference/device-management-library-bundle/remote-access.md
> +The 530 static response template is available for receiving c8y_RemoteAccessConnect operations:
c8y_RemoteAccessConnect > format as code 2x

2021-12-13 13:57 UTC, BeateRixen commented on content/reference/device-management-library-bundle/software.md
> +The **Device details** offer a **Software** tab for devices that announce ```c8y_SoftwareList``` and/or ```c8y_SoftwareUpdate``` in their ```c8y_SupportedOperations``` fragment in their device manage
**Device details** > **Device details** page
offer > shows

2021-12-13 13:58 UTC, BeateRixen commented on content/reference/device-management-library-bundle/software.md
> +| name | String | Yes | Name of the software. |
remove full stops in details column

2021-12-13 13:59 UTC, BeateRixen commented on content/reference/device-management-library-bundle/software.md
> +Devices should upload the complete list of installed software during startup. Additionally the list should be updated any time a local change is triggered or detected. This includes cases where a cha
Cumulocity UI > the Cumulocity IoT UI

2021-12-13 13:59 UTC, BeateRixen commented on content/reference/device-management-library-bundle/software.md
> +Within the **Software** tab users are able to select software to install, to update, and to uninstall for a device. After confirming, the desired software configuration is sent to the device as an op
are able to > can

2021-12-13 14:00 UTC, BeateRixen commented on content/reference/device-management-library-bundle/software.md
> +| name | String | Yes | Name of the software. |
remove full stops in the details column

2021-12-13 14:00 UTC, BeateRixen commented on content/reference/device-management-library-bundle/software.md
> +The device is expected to perform the following actions
add colon at the end

2021-12-13 14:02 UTC, BeateRixen commented on content/reference/device-management-library-bundle/software.md
> +If a device supports the ```c8y_SoftwareUpdate``` operation in it's ```c8y_SupportedOperations``` fragment the **Software** tab will create ```c8y_SoftwareUpdate``` operations for the device. Concept
in it's > in its

2021-12-13 14:02 UTC, BeateRixen commented on content/reference/device-management-library-bundle/software.md
> +|version |String | Yes | A version identifier of the software.|
remove full stops

2021-12-13 14:02 UTC, BeateRixen commented on content/reference/device-management-library-bundle/software.md
> +The device is expected to perform the following actions
add colon at the end

2021-12-13 14:03 UTC, BeateRixen commented on content/reference/device-management-library-bundle/software.md
> +1. Receive c8y_SoftwareUpdate operation <br>
c8y_SoftwareUpdate > format as code

2021-12-13 14:04 UTC, BeateRixen commented on content/reference/device-management-library-bundle/tracking.md
> +<td>ID of the source device.</td>
remove full stop

2021-12-13 14:05 UTC, BeateRixen commented on content/reference/device-management-library-bundle/tracking.md
> +<td>Description of the event. This parameter is required because it is a required for events in general. There are no further semantics applied to the text in the context of tracking devices</td>
In this case, I would actually add a full stop at the end, otherwise it looks uncomplete

2021-12-13 14:05 UTC, BeateRixen commented on content/reference/device-management-library-bundle/tracking.md
> +The current device position is represented using the c8y_Position fragment in the device’s own managed object.
c8y_Position > format as code

2021-12-13 14:06 UTC, BeateRixen commented on content/reference/device-management-library-bundle/tracking.md
> +In Cumulocity IoT tracking over time is done using events and the current position is represented as fragment in the device's own managed object (see above for details). In practice devices usually d
using 402 static template > using the 402 static template

2021-12-14 09:54 UTC, BeateRixen commented on content/reference/device-management-library-bundle/child-devices.md
> +To add child device to an existing device you must connect an existing device and call child create template:
To add child device > To add a child device
connect an existing device > probably "the connected device"
and call child create template > and call the child create template

2021-12-14 09:55 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +### Text based configuration
Text based > Text-based

2021-12-14 09:56 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +The most basic form of configuration is a simple text based configuration. Here the configuration is stored and transferred directly as string. We recommend using this form for small human readable c
We recommend using > Please check in the style guide on which wording we agreed and change everywhere. I think it is "We recommend you to"

2021-12-14 10:03 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +We recommend uploading the current configuration only on demand to save transfer data volume and device resources. There are specific operations designed to trigger a device to upload its current con
We recommend > see above

2021-12-14 10:03 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +For devices that include ```c8y_SendConfiguration``` in their ```c8y_SupportedOperations``` the **Configuration** tab offers a button to trigger a configuration upload from the device to {{< product-
pressed > clicked
add full stop

2021-12-14 10:04 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +There is no built in static response template available for the ```c8y_SendConfiguration``` operation. Devices must create a custom template to implement this capability. Here is an example how such
built in > built-in

2021-12-14 10:06 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +The 513 static response template is available to recewith ```c8y_Configuration``` operations:
recewith > something is missing here

2021-12-14 10:06 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +### Legacy file based configuration
file based > file-based (several times in the text below as well)

2021-12-14 10:06 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +Devices that want to manage configuration as files can achieve a basic form using legacy file based configuration. For new device integrations we recommend implementing typed file based configuration
we recommend > see above

2021-12-14 10:07 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +As the name suggests, this approach stores and transfers configuration as binary files.
As the name suggests > remove

2021-12-14 10:07 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +Devices may signal their support for uploading their current configuration to {{< product-c8y-iot >}} by adding ```c8y_UploadConfigFile``` to their ```c8y_SupportedOperations```. This enables a "Get
"Get snapshot from device" > format bold

2021-12-14 10:08 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +When uploading its configuration, the device must first upload the configuration file into {{< product-c8y-iot >}} inventory binaries, and then create a configuration repository entry as a managed ob
We recommend > see above. I will no longer comment this, please check throughout the files :-)

2021-12-14 10:09 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +|type|string|Yes|Type of the configuration repository entry object. Must always be "c8y_ConfigurationDump"|
Probably better "object; must" to avoid punctuation

2021-12-14 10:10 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +Devices that are capable of installing configuration remotely can announce this by adding ```c8y_DownloadConfigFile``` to their ```c8y_SupportedOperations```. Then the **Configuration** tab offers a
a button to "Send configuration to device" > a **Send configuration to device** button
pressed > clicked

2021-12-14 10:11 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +### Typed file based configuration
file based > file-based  ( several times)

2021-12-14 10:12 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +Cumulocity IoT does not validate or further process configuration types. From a platform perspective they are simple strings. Associating these type strings to configuration files is responsibility o
is responsibility > the repsonsibility
Cumulocity IoT > variable

2021-12-14 10:13 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +Similarly to legacy configuration, uploading typed configuration is announced by adding the ```c8y_UploadConfigFile``` to the ```c8y_SupportedOperations```. In this case pressing the button creates a
pressing > clicking; please check generally for this term

2021-12-14 10:14 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +Then the device must create an event with the type equal to the configuration type. We use events here instead of the inventory like in legacy file based config because events are automatically assoc
We > Cumulocity IoT
legacy file based config > the legacy file-based configuration
including > included

2021-12-14 10:15 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +In order to attach the configuration file to the just uploaded event, Event [binaries API](https://{{< domain-c8y >}}/api/#operation/postEventBinaryResource) should be used. The file is attached usin
Event > the Event

2021-12-14 10:16 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +Installing typed configuration also works very similarly to the legacy configuration. Adding the ```c8y_DownloadConfigFile``` to the device's ```c8y_SupportedOperations``` controls the availability o
pressed > clicked

2021-12-14 10:17 UTC, BeateRixen commented on content/reference/device-management-library-bundle/configuration.md
> +When the device has downloaded and installed the configuration it must update the currently installed configuration of this specific type in its own managed object. This shall be done by adding the `
shall > should

2021-12-14 10:19 UTC, BeateRixen commented on content/reference/device-management-library-bundle/connectivity.md
> +1. Connectivity microservice is subscribed and configured.
remove full stop to be consistent with other lists

2021-12-14 10:20 UTC, BeateRixen commented on content/reference/device-management-library-bundle/connectivity.md
> +Depending on the configured connectivity provider either MSISDN or ICCID may be used to identify the SIM present in the device. We recommend to always include both into the ```c8y_Mobile fragment```.
We recommend to > we recommend you?

2021-12-14 10:22 UTC, BeateRixen commented on content/reference/device-management-library-bundle/device-profile.md
> +The **Device profile** tab shows the different parameters of the added device profiles. From a device agent perspective, device profiles are a combination of firmware update, software update, and typ
file based > file-based

2021-12-14 10:22 UTC, BeateRixen commented on content/reference/device-management-library-bundle/device-profile.md
> +Device profile functionality is enabled when the device announces the ```c8y_DeviceProfile``` operation in its ```c8y_SupportedOperations```. The **Device profile** tab allows users to apply a profil
potential > the potential

2021-12-14 10:23 UTC, BeateRixen commented on content/reference/device-management-library-bundle/device-profile.md
> +After completing each of the three subsections the device must announce its current state in its own managed object the same way as described in the individual operations using the fragments ```c8y_F
shall > should

2021-12-14 10:24 UTC, BeateRixen commented on content/reference/device-management-library-bundle/device-profile.md
> +|profileExecuted|boolean|Yes|Indicator showing if the profile has been applied fully. Must be true in this context|
applied fully. Must be > applied fully; must be

2021-12-14 10:30 UTC, BeateRixen commented on content/reference/device-management-library-bundle/firmware.md
> +The **Firmware** tab displays currently installed firmware of a device and allows users to install a different version. A device can have only one firmware installed at a time. {{< product-c8y-iot >}
{{< product-c8y-iot >}} does not provide a concrete definition of what a firmware is. > That sounds negative. Perhaps rephrase: "It depends on the device, what a firmware can be in {{< product-c8y-iot >}}. Typical use cases are "
Operating > operating
micro controller > we had microcontroller somewhere else, please unify

2021-12-14 10:32 UTC, BeateRixen commented on content/reference/device-management-library-bundle/firmware.md
> +When a user selects a complete firmware image for installation, an operation with a similar ```c8y_Firmware``` fragment as found in the device managed object is created. This operation should be cons
state, > remove comma

2021-12-14 10:32 UTC, BeateRixen commented on content/reference/device-management-library-bundle/firmware.md
> +Updating a devices often changes fundamental system components. This operation should always be considered as a critical operation. The device must ensure that all of its connection parameters to {{<
uses and > uses an

2021-12-14 10:34 UTC, BeateRixen commented on content/reference/device-management-library-bundle/firmware.md
> +The 515 static response template is designed to deal with installing firmware images:
is designed to deal > not sure but shouldn´t it be "is designed for dealing"? I like this phrasing better then "is prepared for" which we have in other places. Perhaps unify?

2021-12-14 10:34 UTC, BeateRixen commented on content/reference/device-management-library-bundle/firmware.md
> +In case a user selects a firmware patch to install on a device, a ```c8y_Firmware``` operation is created. In this case two additional parameters are included to help with installation of a firmware
to install > to be installed

2021-12-14 10:35 UTC, BeateRixen commented on content/reference/device-management-library-bundle/firmware.md
> +|url|String|Yes|A url pointing to the location of the firmware file|
url > URL

2021-12-14 10:36 UTC, BeateRixen commented on content/reference/device-management-library-bundle/firmware.md
> +The 525 static response template is designed to deal with installing firmware patches. It works very similarly to the 515 template, it just adds the dependency parameter as fifth parameter. The fact
is designed to deal > see above

2021-12-14 10:58 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +Devices may announce their supported capabilities using the ```c8y_SupportedOperations``` fragment in their own managed object. The fragment itself is an array of strings. It may contain built-in ope
see below for details > still not sure what this means and where this refers to :-); perhaps this refers to the entire library, but this is not clear

2021-12-14 11:00 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +Devices are responsible for communicating their current status to {{< product-c8y-iot >}}. Status is usually communicated in the device's own managed object. We provide specific fragments for each ca
Status > The status
We provide > Cumulocity IoT provides

2021-12-14 11:01 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +**SmartREST2**
SmartREST2 > I think we call it SmartREST 2.0?

2021-12-14 11:02 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +If any error occurs during the processing of an operation the device must set the operation status to FAILED and provide a failure reason as descriptive as possible. This includes any unexpected or e
to be  fully > extra space

2021-12-14 11:04 UTC, BeateRixen commented on content/reference/device-management-library-bundle/identity.md
> +In the context of MQTT the Client ID is used as the device’s external ID. Upon connecting the MQTT client ID is used to automatically associate the connection to a device in the inventory. Furthermor
Client > client
Furthermore, no identity bindings > No additional identity bindings

2021-12-14 11:05 UTC, BeateRixen commented on content/reference/device-management-library-bundle/identity.md
> +Creating device by a device connected to {{< product-c8y-iot >}}:
device > a device

2021-12-14 11:05 UTC, BeateRixen commented on content/reference/device-management-library-bundle/logs.md
> +The **Logs** tab is used to extract logs from the device. The **Logs** tab will be available if the fragment ```c8y_LogfileRequest``` is present in the ```c8y_SupportedOperations``` of the device.
will be > is

2021-12-14 11:07 UTC, BeateRixen commented on content/reference/device-management-library-bundle/logs.md
> +Supported log types shall be announced by devices using the ```c8y_SupportedLogs``` fragment in the device’s own managed object.
shall
not sure on "shall" versus "should" versus "must" here. We usually do not use "shall". Please check and unify in similar cases. Are just have "Supported log types are announced"?
What is your take @rssag ?

2021-12-14 11:08 UTC, BeateRixen commented on content/reference/device-management-library-bundle/logs.md
> +|logFile|String|Yes|Type of log for the specific device. (c8y_SupportedLogs)|
remove full stop

2021-12-14 11:09 UTC, BeateRixen commented on content/reference/device-management-library-bundle/logs.md
> +If desired the device may also include the ```c8y_LogfileRequest``` fragment from the operation or the operation ID into the event. The file is the attached to the event using it’s event ID and event
is the > is then

2021-12-14 11:09 UTC, BeateRixen commented on content/reference/device-management-library-bundle/logs.md
> +After successful completion of the upload, the device must include a URL to the uploaded file into the ```c8y_LogfileRequest``` fragment of the operation. The link must be presented as property "file
add full stop

2021-12-14 11:09 UTC, BeateRixen commented on content/reference/device-management-library-bundle/logs.md
> +|logFile|String|Yes|Type of log for the specific device. (c8y_SupportedLogs)|
remove full stop

2021-12-14 11:10 UTC, BeateRixen commented on content/reference/device-management-library-bundle/logs.md
> +{{< product-c8y-iot >}} offers the 522 static response template for receiving ```c8y_LogfileRequest``` operations. When the log file is uploaded the device may use the implicit parameter functionalit
offers > provides

2021-12-14 11:11 UTC, BeateRixen commented on content/reference/device-management-library-bundle/measurements.md
> +There are several static templates prepared to create measurements in the 2xx range of message IDs. We provide the 200 static template to create a measurement with a dynamic fragment and series:
prepared > available

2021-12-14 11:12 UTC, BeateRixen commented on content/reference/device-management-library-bundle/network.md
> +The **Network** tab displays network information. It will only be visible if the ```c8y_Network``` fragment is present in the device managed object. There are three subsections: WAN, LAN and DHCP. Ea
will only be visible > is shown

2021-12-14 11:13 UTC, BeateRixen commented on content/reference/device-management-library-bundle/network.md
> +If the device contains the ```c8y_Network``` operation in its ```c8y_SupportedOperations``` users may also update a device's network configuration in the **Network** tab. Changed configuration is sen
Changed > The changed

2021-12-14 11:14 UTC, BeateRixen commented on content/reference/device-management-library-bundle/network.md
> +Changes to network configuration potentially impacts the device’s ability to connect to the {{< product-c8y-iot >}} platform. We recommend implementing a connection test with the new settings. If the
to network > to the

2021-12-14 11:16 UTC, BeateRixen commented on content/reference/device-management-library-bundle/reference.md
> +The **Shell** tab gives the possibility to send arbitrary device specific commands to the device. It appears if the ```c8y_Command``` operation is present in the device's ```c8y_SupportedOperations``
gives the possibility > allows
device specific device-specific
It appears > It is shown

2021-12-14 11:17 UTC, BeateRixen commented on content/reference/device-management-library-bundle/reference.md
> +After completing the execution, the device must provide a return string for the command in addition to setting the operation status to SUCCESSFUL. The result shall be provided as string property nest
shall > see above

2021-12-14 11:18 UTC, BeateRixen commented on content/reference/device-management-library-bundle/tracking.md
> +The **Tracking** tab allows the device's path to be visualized. To achieve that the device must periodically send tracking events and update its position.
To achieve that > To achieve this

2021-12-14 11:25 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +This list can be manipulated through the device fragments.
device fragments. > device fragments, i.e. which tabs are shown
depends on which capability > depends on the capabilities the device supports.
mostly > mainly
This will be explained in more details in the firmware section. > remove, this is confusing here as this is only an example

2021-12-14 11:27 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +To begin with device management, open the All devices tab in the Devices menu and choose a device. Click on the device to open the device details of this particular device. You see a list of tabs and
To begin with > To get a first impression of
All devices tab > **All devices** tab
Devices menu > ** Devices** menu
choose > select
information within every one of them > particular information in each of them

2021-12-14 11:30 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +This section describes the device managed object and more importantly its fragments. Here you will find the most important functionalities a device has and all of the corresponding fragments to them.
more importantly > remove
Here you will find the > You will find descriptions of the 
 a device has > of a device
all of the corresponding fragments to them > all its corresponding fragments 
We will show the connection between the UI view > We will explain the relation between the Cumulocity IoT UI, ...

2022-01-04 18:25 UTC, manasesjesus requested changes

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/logs.md
> +|c8y_SupportedLogs|array|Yes|String array or supported log types|
```suggestion
|c8y_SupportedLogs|array|Yes|Array of strings of the supported log types|
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/logs.md
> +|maximumLines|String|Yes|Maximum amount of lines to transfer|
```suggestion
|dateFrom|string|Yes|Start date for log lines|
|dateTo|string|Yes|End date for log lines|
|logFile|string|Yes|Type of log for the specific device (c8y_SupportedLogs)|
|searchText|string|Yes|A text filter to apply to individual log lines|
|maximumLines|string|Yes|Maximum amount of lines to transfer|
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/logs.md
> +
format it as http code block

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/logs.md
> +|text|String|Yes|Event text|
```suggestion
|source|string|Yes|ID of the device|
|type|string|Yes|Type of the log file|
|time|string|Yes|Time when the event occurred|
|text|string|Yes|Event text|
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/logs.md
> +```http
```suggestion
POST /event/events/<eventId>/binaries

```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/logs.md
> +|file|String|Yes|URL where the log file was uploaded to|
```suggestion
|status|string|Yes|Operation status|
|dateFrom|string|Yes|Start date for log lines|
|dateTo|string|Yes|End date for log lines|
|logFile|string|Yes|Type of log for the specific device (c8y_SupportedLogs)|
|searchText|string|Yes|A text filter to apply to individual log lines|
|maximumLines|integer|Yes|Maximum amount of lines to transfer|
|file|string|Yes|URL where the log file was uploaded to|
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/reference.md
> +|c8y_Command.text|String|Yes|The command text to be executed by the device|
```suggestion
|c8y_Command.text|string|Yes|The command text to be executed by the device|
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/reference.md
> +PUT /devicecontrol/operations/<operation ID>
```suggestion
PUT /devicecontrol/operations/<operationId>
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/reference.md
> +|status|String|Yes|Operation status indicating if the operation was completed as intended|
```suggestion
|status|string|Yes|Operation status indicating if the operation was completed as intended|
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/remote-access.md
> +* 'c8y_RemoteAccessConnect' is added to the device's ```c8y_SupportedOperations```
```suggestion
* `c8y_RemoteAccessConnect` is added to the device's ```c8y_SupportedOperations```
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/remote-access.md
> +|port|Number|Yes|Port to be used on the local network endpoint|
```suggestion
|connectionKey|string|Yes|Shared secret to authenticate the connection request from device side|
|hostname|string|Yes|Endpoint on local network to connect to|
|port|integer|Yes|Port to be used on the local network endpoint|
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/remote-access.md
> +With this operation the device must open a websocket connection to the microservice endpoint using the connection key for authentication `(wss://<c8y host>/service/remoteaccess/device/<connectionKey>
```suggestion
With this operation the device must open a WebSocket connection to the microservice endpoint using the connection key for authentication `(wss://<c8y host>/service/remoteaccess/device/<connectionKey>)` and a local socket to the specified hostname and port. Then it must establish bidirectional forwarding of data between the WebSocket and the local socket.
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/remote-access.md
> +4. Establish bidirectional forwarding between websocket and local socket
```suggestion
2. Establish WebSocket connection to remote access microservice
3. Establish local socket connection to the specified host and port
4. Establish bidirectional forwarding between WebSocket and local socket
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/remote-access.md
> +The operation is set to SUCCESSFUL after the connection is established. Disconnecting happens silently. Even if the connection was not terminated gracefully by any of the involved components, the ope
```suggestion
The operation is set to SUCCESSFUL after the connection is established. Disconnecting happens silently. Even if the connection was not terminated gracefully by any of the involved components, the operation status must stay in SUCCESSFUL. Whenever one of the connections is terminated (WebSocket or TCP) the device agent should consider the session as ended and should also terminate both connections.
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/remote-access.md
> +3. Establish websocket connection using HTTP
```suggestion
3. Establish WebSocket connection using HTTP
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/remote-access.md
> +{{< product-c8y-iot >}} currently supports VNC, SSH, and telnet. The device agent should be implemented independently of the remote access protocol used. The operation intentionally does not transfer
```suggestion
{{< product-c8y-iot >}} currently supports VNC, SSH, and Telnet. The device agent should be implemented independently of the remote access protocol used. The operation intentionally does not transfer the protocol. The agent must be capable of forward arbitrary data between both its established sockets.
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/software.md
> +| url | String | No | A URL pointing to the location where the software file was obtained from|
```suggestion
| name | string | Yes | Name of the software|
| version | string | Yes | A version identifier of the software|
| url | string | No | A URL pointing to the location where the software file was obtained from|
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/software.md
> +| url | String | Yes | A URL pointing to the location where the software file should be downloaded from|
```suggestion
| name | string | Yes | Name of the software|
| version | string | Yes | A version identifier of the software|
| url | string | Yes | A URL pointing to the location where the software file should be downloaded from|
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/software.md
> +|action |String |Yes |Action to be executed from the device on the software (possible values: "install" or "delete")|
```suggestion
|name |string |Yes |Name of the software|
|version |string | Yes | A version identifier of the software|
|url |string |Yes |A URL pointing to the location where the software file should be downloaded from|
|action |string |Yes |Action to be executed from the device on the software (possible values: "install" or "delete")|
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/tracking.md
> +    	"id":"10300"
```suggestion
    	"id": "10300"
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/tracking.md
> +      	"lat": 51.151977
```suggestion
    	"alt": 67,
      "lng": 6.95173,
      "lat": 51.151977
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/tracking.md
> +<td>Object</td>
```suggestion
<td>object</td>
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/tracking.md
> +<td>String</td>
```suggestion
<td>string</td>
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/tracking.md
> +<td>Object</td>
```suggestion
<td>object</td>
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/tracking.md
> +<td>String</td>
```suggestion
<td>string</td>
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/tracking.md
> +<td>String</td>
```suggestion
<td>string</td>
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/tracking.md
> +PUT /inventory/managedObjects/deviceId>
```suggestion
PUT /inventory/managedObjects/<deviceId>
```

2022-01-04 18:25 UTC, manasesjesus commented on content/reference/device-management-library-bundle/tracking.md
> +      	"lat": 51.151977
```suggestion
    	"alt": 67,
      "lng": 6.95173,
      "lat": 51.151977
```

2022-01-06 12:18 UTC, MWindel commented on content/reference/device-management-library-bundle/logs.md
> +
Done

2022-01-06 14:55 UTC, manasesjesus approved these changes

2022-01-10 16:04 UTC, dafkk submitted a review, later dismissed
Everything from the content looks okay. Just something weird in the side navigation. Some menu items are not loaded correctly - on the same level as Device management library there are broken links to different chapters 

![Screenshot 2022-01-10 at 18 00 33](https://user-images.githubusercontent.com/92030501/148797864-dbd5085a-cc87-4fb6-9b30-74db15eb84a9.png)

2022-01-10 16:20 UTC, BeateRixen commented
> Everything from the content looks okay. Just something weird in the side navigation. Some menu items are not loaded correctly - on the same level as Device management library there are broken links to different chapters
> 
> ![Screenshot 2022-01-10 at 18 00 33](https://user-images.githubusercontent.com/92030501/148797864-dbd5085a-cc87-4fb6-9b30-74db15eb84a9.png)

Looks good in my Hugo preview, perhaps some Hugo issue in your side.

2022-01-11 12:45 UTC, BeateRixen approved these changes

2022-01-11 13:09 UTC, MWindel submitted a review, later dismissed

2022-01-11 15:41 UTC, BeateRixen approved these changes

2022-01-11 15:53 UTC, rssag approved these changes

2022-01-11 16:05 UTC, merged