DM-2433 Operations clean-up after agent crash.
SoftwareAG/c8y-docs pull request #1175
Opened 2023-06-25 16:29 UTC by MaciekSoftwareAG

2023-06-26 06:30 UTC, BeateRixen commented on content/reference/device-management-library-bundle/general-concepts.md
> +Device may get to know its operations ids by querying devicecontrol API, by subscribing to operation JSON topic, or by using custom response template which includes the ids. In these cases device may
```suggestion
Devices can find their operations IDs by querying the Device Control API, by subscribing to the operation JSON topic, or by using a custom response template which includes the IDs, that is, template 504, 505, or 506, which enable setting the status of operations with a known ID.
```

2023-06-28 11:03 UTC, rssag commented on content/reference/device-management-library-bundle/general-concepts.md
> +{{< product-c8y-iot >}} provides the static templates 501, 502, and 503 to manipulate the operation status. These templates take the operation type as input parameter and always update the oldest ope
```suggestion
{{< product-c8y-iot >}} provides the static templates 501, 502, and 503 to manipulate the operation status. These templates take the operation type as input parameter and always update the oldest operation in the preceding status. We recommend you to let all operations be handled sequentially in the order they arrive at the device.
```

2023-06-28 11:03 UTC, rssag commented on content/reference/device-management-library-bundle/general-concepts.md
> +Devices can find their operations IDs by querying the Device Control API, by subscribing to the operation JSON topic, or by using a custom response template which includes the IDs, that is, template
```suggestion
Devices can find their operation IDs by querying the Device Control API, by subscribing to the operation JSON topic, or by using a custom response template which includes the IDs, that is, template 504, 505, or 506, which enable setting the status of operations with a known ID.
```

2023-06-28 11:03 UTC, rssag commented on content/reference/device-management-library-bundle/general-concepts.md
> +After unexpected restart device must set status to FAILED for operations which processing was interrupted. First it needs to learn the operations ids:
```suggestion
After an unexpected restart a device must set the status to FAILED for operations for which processing was interrupted. First it must learn the operation IDs:
```

2023-06-28 11:03 UTC, rssag commented on content/reference/device-management-library-bundle/general-concepts.md
> +Then one by one change the statuses:
```suggestion
Then it must change the statuses one by one:
```

2023-06-28 11:03 UTC, rssag commented on content/reference/device-management-library-bundle/general-concepts.md
> +Alternatively the static template 507 may be used. The template changes status from EXECUTING to FAILED for all operations of given type or of any type.
```suggestion
Alternatively the static template 507 may be used. The template changes the status from EXECUTING to FAILED for all operations of the given type or for all types.
```

2023-06-28 11:04 UTC, rssag commented
what are the target versions?

2023-06-29 10:03 UTC, rssag approved these changes

2023-07-06 08:28 UTC, rssag commented
@MaciekSoftwareAG 
this needs another approval by your team
what are the target versions?

2023-07-11 18:46 UTC, l2p- requested changes
I left suggestions for changes

2023-07-12 11:52 UTC, rssag commented on content/reference/device-management-library-bundle/general-concepts.md
> +After an unexpected restart a device must cleanly recover its status. This includes all status parameters communicated with the platform and all ongoing operations. Recovering status can be done by u
```suggestion
After an unexpected restart a device must cleanly recover its status. This includes all status parameters communicated with the platform and all ongoing operations. Recovering the status can be done by updating all values in the cloud with the current values on the device. Recovering ongoing operations is more difficult. Devices are expected to keep track of all operations they moved to status EXECUTING. Typically devices keep information of longer-running operations in a persistent storage so that they can be resumed. In unexpected shutdown or crash scenarios this may not always be possible. In this case the device may cancel all ongoing operations to reset its own status.
```

2023-07-13 18:51 UTC, l2p- approved these changes

2023-07-17 21:54 UTC, merged