DM-2432 Removing sensor-library chapter. Ranamed device-management-library.
SoftwareAG/c8y-docs pull request #1181
Opened 2023-06-27 23:29 UTC by MaciekSoftwareAG

2023-06-28 07:58 UTC, rssag commented on content/reference/device-integrator-library-bundle/relay.md
> +For devices with `c8y_Relay` fragment [relay control widget](/users-guide/cockpit#relay-control) can be used.
```suggestion
For devices with the `c8y_Relay` fragment the [Relay control widget](/users-guide/cockpit#relay-control) can be used.
```

2023-06-28 07:58 UTC, rssag commented on content/reference/device-integrator-library-bundle/relay.md
> +1. Device receives command via 518 static response template <br>
```suggestion
1. The device receives the command via the 518 static response template<br>
```

2023-06-28 07:58 UTC, rssag commented on content/reference/device-integrator-library-bundle/relay.md
> +2. Device sets operation status to EXECUTING <br>
```suggestion
2. The device sets the operation status to EXECUTING<br>
```

2023-06-28 07:58 UTC, rssag commented on content/reference/device-integrator-library-bundle/relay.md
> +3. Device confirms successful execution by setting operation status to SUCCESSFUL <br>
```suggestion
3. The device confirms successful execution by setting the operation status to SUCCESSFUL<br>
```

2023-06-28 07:58 UTC, rssag commented on content/reference/device-integrator-library-bundle/relay.md
> +For devices with `c8y_Relay` fragment [relay array control widget](/users-guide/cockpit#relay-array-control) can be used.
```suggestion
For devices with the `c8y_Relay` fragment the [Relay array control widget](/users-guide/cockpit#relay-array-control) can be used.
```

2023-06-28 07:58 UTC, rssag commented on content/reference/device-integrator-library-bundle/relay.md
> +1. Device receives command via 518 static response template <br>
```suggestion
1. The device receives the command via the 519 static response template<br>
```

2023-06-28 07:58 UTC, rssag commented on content/reference/device-integrator-library-bundle/relay.md
> +2. Device sets operation status to EXECUTING <br>
```suggestion
2. The device sets the operation status to EXECUTING<br>
```

2023-06-28 07:58 UTC, rssag commented on content/reference/device-integrator-library-bundle/relay.md
> +3. Device confirms successful execution by setting operation status to SUCCESSFUL <br>
```suggestion
3. The device confirms successful execution by setting the operation status to SUCCESSFUL<br>
```

2023-07-03 21:04 UTC, MaciekSoftwareAG commented on content/reference/device-integrator-library-bundle/relay.md
> +3. Device confirms successful execution by setting operation status to SUCCESSFUL <br>
Probably I will never comprehend where to use "the" in a (the?) programming context.

2023-07-04 11:24 UTC, rssag approved these changes

2023-07-04 11:25 UTC, rssag commented
what are the target versions?

2023-07-06 08:28 UTC, rssag commented
@MaciekSoftwareAG 
this needs another approval by your team
what are the target versions?

2023-07-11 19:10 UTC, l2p- requested changes

2023-07-11 19:10 UTC, l2p- commented on content/reference/device-integrator-library-bundle/relay.md
>  ---
This whole file needs to be aligned with the rest of this documentation. This doc explains ho device integrations can implement certain functionalities into their devices. The focus should be on the fuctionality of monitoring and managing a single or multiple two-position switches on a device.
There are two separate relay relay widgets in Cockpit: Relay control (for a single switch) and Relay array control (for multiple switches) for each of these we need a chapter for how a device can announce the status to the platform and a section how controlling them works. All of those with JSON data model examples of the fragments a device should put into its MO and the operation, examples with SmartREST ad descriptions of steps expected from the device.

2023-07-13 19:24 UTC, l2p- commented on content/reference/device-integrator-library-bundle/relay.md
>  ---
If you look at other segments in this doc they are structured in a very particular way that is specifically around explaining how to integrate certain functionalities into a device and what the platform expects from a device. A good example for this chapter is the network section. This is a much more complex operation but ultimately a very similar concept with announcing the status and the request chang operation which are always separate flows. Here is the structure that I would have expected:

### Relays
Text is ok example and link should be moved to the respective sub section

#### Single Relay
Text similar to: "To manage and monitor a single relay Cumulocity offers the Relay control widget"

##### Relay status
Text similar to: "Devices may announce their relay status by updating the c8y_Relay Fragment in their managed object"
<JSON example>
<SmartREST example>

##### Setting relay position
Text similar to: "Devices that support changing the relay position remotely may add the c8y_Relay operation to c8y_SupportedOperations. Then Users can request an update to the relay position in the Relay control widget. This creates an operation of fragment type c8y_Relay for the device.
<JSON example>
<Steps expected from the device>

1. set op to executing
2. Apply requested relay position
3. update relay status in MO
4. set op to successful

<SmartREST examples of all steps>

#### Multiple relays
<Repeat similar structure>

2023-07-14 08:05 UTC, l2p- requested changes
see comment

2023-07-17 21:53 UTC, MaciekSoftwareAG commented on content/reference/device-integrator-library-bundle/relay.md
>  ---
Ok, tried one more time.

2023-07-18 18:15 UTC, l2p- requested changes
I have added one suggestion. Please also accept the suggestions from Richard

2023-07-18 18:15 UTC, l2p- commented on content/reference/device-integrator-library-bundle/relay.md
> +   `503,c8y_RelayArray`
```suggestion
3. The device confirms successful execution by setting the operation status to SUCCESSFUL and sets the relay array state with the implicit parameters in the 503 static template<br>
   `503,c8y_RelayArray,OPEN,CLOSED,CLOSED,OPEN`
```

2023-07-19 18:36 UTC, l2p- approved these changes

2023-07-20 08:18 UTC, merged