DM-2434 Updated "How does the platform support developing agents?" section.
SoftwareAG/c8y-docs pull request #1193
Opened 2023-07-03 22:09 UTC by MaciekSoftwareAG

2023-07-04 11:23 UTC, rssag commented on content/concepts/interfacing-devices-bundle/developing-agents.md
> +* There are a number of full-featured open source agents and drivers in {{< company-c8y >}}'s [github.com](https://github.com/SoftwareAG/cumulocity-examples) and [mbed.org](http://mbed.org/users/vwoc
```suggestion
* There are a number of full-featured open source agents and drivers in {{< company-c8y >}}'s [github.com](https://github.com/SoftwareAG/cumulocity-examples) and [mbed.org](http://mbed.org/users/vwochnik/code/) repositories, for example, the [{{< product-c8y-iot >}} Device Management Reference Agent](https://github.com/SoftwareAG/cumulocity-devicemanagement-agent) in Python.
```

2023-07-04 11:25 UTC, rssag commented
what are the target versions?

2023-07-11 18:51 UTC, l2p- requested changes
cumulocity-examples does not contain a well supported and fully featured device agent. The mbed agent is also long dead. Both of these need to go. Please also add a link to thin-edge.

2023-07-12 11:54 UTC, rssag commented on content/concepts/interfacing-devices-bundle/developing-agents.md
> +* It supports open source agents and drivers, for example [{{< product-c8y-iot >}} Device Management Reference Agent](https://github.com/SoftwareAG/cumulocity-devicemanagement-agent) or [thin-edge.io
```suggestion
* It supports open source agents and drivers, for example [{{< product-c8y-iot >}} Device Management Reference Agent](https://github.com/SoftwareAG/cumulocity-devicemanagement-agent) or [thin-edge.io](https://thin-edge.github.io/thin-edge.io/).
```

2023-07-12 11:54 UTC, rssag approved these changes

2023-07-13 18:47 UTC, l2p- commented
> what are the target versions?

10.19

2023-07-13 18:48 UTC, l2p- approved these changes

2023-07-14 12:04 UTC, merged