Feature/mtm 53705/notification2 reference improvements
SoftwareAG/c8y-docs pull request #1228
Opened 2023-07-07 14:42 UTC by gapa-c8y

STILL IN PROGRESS.

The general purposes of this:
 - general improvement (better flow from one aspect to another, more staged/stepped introduction, diagrams)
 - improve awareness of some of the pitfalls/costs if miss-used (what is miss-use)

2023-07-25 07:46 UTC, rohitjoshi-softwareag commented on static/images/reference-guide/notification2/notifications2-backlog-lifecycle.svg
praise: the diagram is excellent and helps users visualize the entire process :)

2023-07-25 14:39 UTC, sagscmi reviewed
I made a lot of comments because it's me, but really there's very little I would insist on changing before this can be merged - it's a huge improvement on what was there before, nice work Gary!  Very happy to re-review and approve once the PR moves out of draft status.

2023-07-25 14:39 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +class, it has a public refresh method which does the above for you (internally on the client side).
typo/nitpick:
```suggestion
If you are using the {{< product-c8y-iot >}} Java SDK [TokenApi](https://github.com/SoftwareAG/cumulocity-clients-java/blob/develop/java-client/src/main/java/com/cumulocity/sdk/client/messaging/notifications/TokenApi.java) 
class, it has a public refresh method which does the above for you, internally on the client side.
```

2023-07-25 14:39 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +### Shared consumer tokens
note: There are a lot of things highlighted with `backquotes` in this section where you've used **bold** above for the same thing.  I know this is old material and TBH it doesn't need to change immediately, but we should try to be consistent in our formatting.

2023-07-25 14:39 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +There is a sample microservice available in the [cumulocity-examples repository](https://github.com/SoftwareAG/cumulocity-examples/tree/develop/hello-world-notification-microservice), so Java develop
todo: Confirm with @rohitjoshi-softwareag that this is still the best URL to use for the samples.

2023-07-25 14:39 UTC, sagscmi commented on static/images/reference-guide/notification2/notification2-consumers.svg
note: Just a reminder that **if** we decide to talk a bit more about "subscribers" this diagram might also need updating.

2023-07-25 14:39 UTC, sagscmi commented on static/images/reference-guide/notification2/notifications2-backlog-lifecycle.svg
praise: Agreed, all these diagrams are very nice and make the whole topic a lot easier to understand.

2023-07-25 14:39 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +// byte[] decoded = Base64.getDecoder().decode(tokenParts[1]);
issue: Commented out line declares (or actually doesn't as it's commented out) a variable that is then used two lines further down... TBH I think you could fold this section into the previous one and ditch the code snippet that clearly nobody has ever tried to run.

2023-07-25 15:11 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +### Shared consumer tokens
I'm going to do a formatting pass over the doc (once I recheck the guidelines) shortly. There might be a different between code and field formatting. And there's value formatting.

2023-07-25 15:30 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +### Consumers and tokens
I've deliberately avoided the conventional meaning of subscription and implying it with subscriber. I've favored use of consumer and client only.

I've also started referring to topic (or 'subscription topics'): we used to incorrectly say stuff such as 'use a token to receive from a subscription' when in fact it receives from a topic. Other cases might exist (these help aavoid using the word subscription fro anything other than the object we create using REST.

2023-07-25 15:33 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The diagram below shows 3 consumer (backlogs) have been created in the Messaging Service by four consumer clients.
Yeah - I thought I caught that (maybe there were 2). Agree and will change

2023-07-25 16:01 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The JSON fields sent in a [create subscription request](https://{{<domain-c8y>}}/api/{{< c8y-current-version >}}/#operation/postNotificationSubscriptionResource)
I'll find out about this - only an issue when backporting I think and any backport is subject to backporting policy anyway.

Anyway, the lower part of the path seems to be different in 1017 to that which is generated in develop (the URL base path variable has different structure in these branches). Probably also different in 1016 but maybe there are content variations too (maybe we haven't backported all API changes or the matching doc changes).

https://cumulocity.com/api/core/10.17.0/#operation/postNotificationTokenResource
https://cumulocity.com/api/10.19.0/#operation/postNotificationTokenUnsubscribeResource

2023-07-25 16:07 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The **source** fields can only be used if the **context** is "mo". It must be the value of a managed-object's global identifier
@sagscmi Your suggestion seems to be saying we have a source.id field nesting - we have a source field only. MOs have a source.id nested field.
Am I missing your point here. Not the nicest bit of this section - that's for sure. So happy to consider rewriting it

2023-07-25 16:10 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +"alarms", "alarms with children", "events", "events with children", "measurements", "managed objects" and "operations".
Yeah - what was I thinking (maybe copied from somewhere they were list as a description - and not as parameters)

2023-07-25 16:18 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +The **source** fields can only be used if the **context** is "mo". It must be the value of a managed-object's global identifier
I'm trying not to reply to everything immediately, but one of us seems to be missing something here.  The `/notification2/subscription` request body has a `source` which is an object with nested `id` and `name` fields, as shown in the example POST request:
```
{
  "source": {
    "id": "251982"
  },
  "context": "mo",
  "subscription": "testSubscription",
  "subscriptionFilter": {
    "apis": [
      "measurements",
      "events"
    ],
    "typeFilter": "c8y_Speed"
  },
  "fragmentsToCopy": [
    "c8y_MaxSpeedMeasurement"
  ],
  "nonPersistent": false
}
```
Nobody ever uses the `name` so IMHO having the structure is pointless, but it is what we expect people to use. Anyway, that's what I was referring to, although I didn't express it very well.

2023-07-25 16:27 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The **source** fields can only be used if the **context** is "mo". It must be the value of a managed-object's global identifier
That's what I thought you were referring to and thought you were wrong. I thought it was on only one layer but now assuming I must be miss-remembering this.

I'll change it (I'll double check first)

2023-07-25 16:29 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +The **source** fields can only be used if the **context** is "mo". It must be the value of a managed-object's global identifier
If I'm correct, feel free to re-word the whole sentence as I wasn't overly happy with my attempt anyway.

2023-07-25 16:38 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The diagram below shows 3 consumer (backlogs) have been created in the Messaging Service by four consumer clients.
Done

2023-07-25 16:39 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +There are two valid **context** values: "mo" (managed-object) and "tenant" and each only supports a subset of the available JSON fields, as follows:
Done in a find-replace in editor

2023-07-25 16:40 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The **source** fields can only be used if the **context** is "mo". It must be the value of a managed-object's global identifier
Yeah - It's either that or I change the world ... starting with the OpenAPI doc. The first step is the hardest!

2023-07-25 16:52 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The **source** fields can only be used if the **context** is "mo". It must be the value of a managed-object's global identifier
Done and fixed the small examples too

2023-07-25 16:54 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +It can then choose to create subscriptions with "mo" **context** for those managed-objects.
Done. Not 100% sure of accuracy. I think mo context must still use manageobjects API to get them and that they are also received in tenant context with manageobjects API. That would make sense

2023-07-25 17:08 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +// byte[] decoded = Base64.getDecoder().decode(tokenParts[1]);
My bad, I thought this was existing code that had been moved from somewhere else.  I was suggesting combining the "Creating tokens" and "Token expiration" into one section, maybe "Token management" or similar.  However you've convinced me that the code snippet is worth keeping around so let's leave it as it is.

2023-07-25 17:15 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +and should be unsubscribed if they are no longer needed or not needed for long periods.
Yep - good suggestion

2023-07-26 10:17 UTC, gapa-c8y commented on static/images/reference-guide/notification2/notification2-subscriptions.svg
Document done - diagrams still to do

2023-07-26 10:23 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +and should be unsubscribed if they are no longer needed or not needed for long periods.
Done

2023-07-26 10:25 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The JSON fields sent in a [create subscription request](https://{{<domain-c8y>}}/api/{{< c8y-current-version >}}/#operation/postNotificationSubscriptionResource)
The branch variations are managed by variables so not an issue.

Whether and where to backport and removing content that is not present in a release will come on each backport if we do them

2023-07-26 10:25 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The JSON fields sent in a [create subscription request](https://{{<domain-c8y>}}/api/{{< c8y-current-version >}}/#operation/postNotificationSubscriptionResource)
... so Done

2023-07-26 10:27 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +There is a sample microservice available in the [cumulocity-examples repository](https://github.com/SoftwareAG/cumulocity-examples/tree/develop/hello-world-notification-microservice), so Java develop
Done - updated URL for that which will be valid in about a week's time and changed (hopefully improved conversation around it with new link to C8y clients library)

2023-07-26 10:50 UTC, gapa-c8y commented on static/images/reference-guide/notification2/notification2-subscriptions.svg
Diagram done (and diagram commentary reflects it)

2023-07-26 11:02 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +and should be unsubscribed if they are no longer needed or not needed for long periods.
We now link to the location the new improved examples will be (within the next week - most likely before the doc is released). Also a link to Java clients Notification2 classes/package.

2023-07-26 14:37 UTC, rohitjoshi-softwareag commented on content/reference/notifications-bundle/overview.md
> +pattern, allowing use-cases to organise their desired selections of measurement, event, alarm and/or inventory messages
suggestion: I think operations too.

2023-07-26 14:43 UTC, rohitjoshi-softwareag commented on content/reference/notifications-bundle/overview.md
> +within {{< product-c8y-iot >}} creates a publisher (internally), that will forward {{< product-c8y-iot >}} messages that it matches (based
nitpick: I guess (internally) is redundant since you have already mentioned within.

2023-07-26 15:14 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +within {{< product-c8y-iot >}} creates a publisher (internally), that will forward {{< product-c8y-iot >}} messages that it matches (based
I don't think it is but might change 'within' to 'in'.
The subscription is created in (within) Cumulocity.

I add in brackets the the publisher is internal to Cumulocity as that is slightly unconventional: usually a 'client' application publishes (and thus creates a publisher externally). I want to emphasize that creating a subscription does this internally so they (user/developer) are clear they don't have to.

If anything I would prefer to lose the earlier in (within), but again, want to emphasize that the object lives in c8y (we have a horrendously unconventional usage of the word 'subscription')

2023-07-26 15:26 UTC, rohitjoshi-softwareag commented on content/reference/notifications-bundle/overview.md
> +subscription topic's messages if the topic is persistent and it has at least one known consumer.
thought: may be clarify that it can be a disconnected consumer too?

2023-07-26 15:30 UTC, rohitjoshi-softwareag commented on content/reference/notifications-bundle/overview.md
> +**subscription** is the first of two fields that identify which topic this subscription will forward messages to.
thought: maybe clarify that this is the subscription name and translates it to the topic name internally. Also worth reiterating that this name does not have to be unique.

2023-07-26 15:32 UTC, rohitjoshi-softwareag commented on content/reference/notifications-bundle/overview.md
> +The following summarizes the subscription fields.
nitpick: IMO unnecessary detail and I would just link to the API docs.

2023-07-26 15:37 UTC, rohitjoshi-softwareag commented on content/reference/notifications-bundle/overview.md
> +The JSON fields sent in a [create token request](https://{{<domain-c8y>}}/api/{{< c8y-current-version >}}/#operation/postNotificationTokenResource)
suggestion: It's worth mentioning that consumers are not booted out once connected using a token even if it expires. Tokens are only validated when consumers first connect and will not be booted out as long as the current session holds.

2023-07-26 15:49 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +### Consumers and tokens
Sure, to be honest I'm fine with what you've done - it's consistent and clarifies the points of confusion as much as possible without actually changing the names of things in the API.  If nobody else wants to offer a competing argument I have no objections to going with it as it is.

2023-07-26 15:51 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The JSON fields sent in a [create token request](https://{{<domain-c8y>}}/api/{{< c8y-current-version >}}/#operation/postNotificationTokenResource)
Good point

2023-07-26 15:52 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The following summarizes the subscription fields.
The summary tables are to help make the field descriptions above more comprehensible (trying to add order after an explosion of terms).

2023-07-26 15:53 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +There are two valid **context** values: "mo" (managed-object) and "tenant" and each only supports a subset of the available JSON fields, as follows:
Yes, confirmed that "managed-" no longer appears anywhere, thanks.

2023-07-26 15:54 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +The **source** fields can only be used if the **context** is "mo". It must be the value of a managed-object's global identifier
Yes, that's much better now.

2023-07-26 15:55 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +It can then choose to create subscriptions with "mo" **context** for those managed-objects.
I think that is correct, although you might want to ask @rohitjoshi-softwareag or @sag-tjegorow to absolutely confirm it.

2023-07-26 16:01 UTC, sagscmi approved these changes
Looks good from my perspective.  No objections to changes arising from @rohitjoshi-softwareag's comments but equally I'd be fine to merge it as it is.  We can always make further improvements later.

2023-07-26 16:02 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +**subscription** is the first of two fields that identify which topic this subscription will forward messages to.
I think that saying it identifies a topic is sufficient (it's not the Ops Doc). Such a topic conversation has to involve the nonPersistent field also. 

That and the non-unique aspect is covered in the existing sentence that follows I think: 'Multiple subscriptions will contribute to a single topic if they have they same values for both the subscription and nonPersistent fields'

BTW, I've not anywhere stated that subscriptions have names as they don't. Horrendously, subscriptions have subscriptions!!!

2023-07-26 16:04 UTC, rohitjoshi-softwareag commented on content/reference/notifications-bundle/overview.md
> +* Send the message `unsubscribe_subscriber` from the consumer's connected WebSocket client.
I understand. If you can change the diagram, please do. If not, create a follow on PR?

2023-07-26 16:05 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +subscription topic's messages if the topic is persistent and it has at least one known consumer.
I was trying to imply that by saying '_known_ consumer', but maybe that is too subtle. I'll look at this

2023-07-26 16:08 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +**subscription** is the first of two fields that identify which topic this subscription will forward messages to.
BTW continued ... I don't want us to cause customers/users to look for the name field in a subscription is my reason for being strict about not calling it a name anywhere (even though I informally do so in conversation sometimes)

2023-07-26 16:13 UTC, rohitjoshi-softwareag commented on content/reference/notifications-bundle/overview.md
> +**subscription** is the first of two fields that identify which topic this subscription will forward messages to.
Well, the subscribers are subscriptions in our case and the subscription field is really a topic name. Anyways, agreed.

2023-07-26 16:19 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +* Send the message `unsubscribe_subscriber` from the consumer's connected WebSocket client.
... damn, the diagram says 'unsubscribe_consumer'. That's wrong I guess (I'll check).

I may go with you here (hide it customers) as it clashes with out subscription object (concept).
This is the one place subscription/subscriber is used correctly (conventionally). We can't/shouldn't expose it to avoid overloading the term. 

Our subscription object is actually a topic-include-filter. And that's all it is.

2023-07-27 11:28 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +The JSON fields sent in a [create token request](https://{{<domain-c8y>}}/api/{{< c8y-current-version >}}/#operation/postNotificationTokenResource)
I've add an admon-info to the Token expiry section for this.

Done

2023-07-27 11:29 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +subscription topic's messages if the topic is persistent and it has at least one known consumer.
changed '... at least one known consumer' 
to '... at least one consumer for the topic that is or has been connected.

2023-07-27 14:07 UTC, slc-softwareag approved these changes
Clean and very details documentation, good work :+1: 
Just a few small remarks from my side.

2023-07-27 14:07 UTC, slc-softwareag commented on content/reference/notifications-bundle/overview.md
> +```
IMO we don't need to tell customers how our internal token structure looks like.

2023-07-27 14:45 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +* Send the message `unsubscribe_subscriber` from the consumer's connected WebSocket client.
Now only refer to REST unsubscribe approach and have updated diagram (a few additional change that hopefully are improvement too).

Done

2023-07-27 15:11 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +```
We don't need to, but this is useful information that may simplify how a customer implements their consumer (or consumer management). Without this, they need a variable (or other storage) to remember each token field in order to recreate it. 

Ideally the 'refresh' functionality would be provided as a REST endpoint - maybe when we introduced some for of consumer management there might be other options too. 

I'd like to keep this

2023-07-27 15:12 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +subscription topic's messages if the topic is persistent, and it has at least one consumer for the topic that is or has been connected.
okay

2023-07-27 15:36 UTC, rohitjoshi-softwareag approved these changes

2023-07-31 13:48 UTC, rssag requested changes

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +This will be the case for all such temporarily disconnected consumers,
```suggestion
This is the case for all such temporarily disconnected consumers,
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +they are *separate*, independent subscriptions, backed by separate topics.
```suggestion
they are separate, independent subscriptions, backed by separate topics.
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Deleting a subscription will prevent it adding further notification messages to its associated topic. Many subscriptions
```suggestion
Deleting a subscription prevents it from adding further notification messages to its associated topic. Many subscriptions 
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Deleting all the subscriptions associated with a topic will ensure no more notifications are added to it. This does not
```suggestion
Deleting all the subscriptions associated with a topic ensures no more notifications are added to it. This does not 
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Even though the topic will no longer accumulate new messages, there may still be consumers draining
```suggestion
Even though the topic no longer accumulates new messages, there may still be consumers draining 
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +the last of the messages from it. When all messages are consumed by all consumers, the topic will be empty and consume
```suggestion
the last of the messages from it. When all messages are consumed by all consumers, the topic is empty and consumes
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +using the subscription's **id** as the URL filename. For example to delete subscription with id 8765:
```suggestion
using the subscription's **id** as the URL filename. For example, to delete the subscription with ID 8765:
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +When a tenant is deleted from {{< product-c8y-iot >}}, all its subscriptions will be deleted. However, topics and consumers may
```suggestion
When a tenant is deleted from {{< product-c8y-iot >}}, all its subscriptions are deleted. However, topics and consumers may 
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +is [persistent or nonPersistent](../notifications/#non-persistent-topics) and therefore is a factor in identifying the topic only.
```suggestion
is [persistent or non-persistent](../notifications/#non-persistent-topics) and therefore is a factor in identifying the topic only. 
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +it to be recognised across connection interruptions, so allowing message delivery to be resumed after such interruptions
```suggestion
it to be recognized across connection interruptions, so allowing message delivery to be resumed after such interruptions
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +and thus reliable.
```suggestion
and thus be reliable.
```
double-check intended meaning

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +The **expiresInMinutes** field is the period that this token will remain valid for, defaulting to "1440" minutes (1 day).
```suggestion
The **expiresInMinutes** field is the period that this token remains valid for, defaulting to 1440 minutes (1 day).
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +<td>Must be true to identify a nonPersistent topic</td>
```suggestion
<td>Must be true to identify a non-persistent topic</td>
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Tokens *only* allow a consumer to connect to the Messaging Service. If a token expires while its consumer is connected,
```suggestion
Tokens only allow a consumer to connect to the Messaging Service. If a token expires while its consumer is connected, 
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +If a consumer disconnects, and their token has expired, the token will have to be recreated or refreshed in order that the consumer can reconnect.
```suggestion
If a consumer disconnects, and their token has expired, the token must be recreated or refreshed in order that the consumer can reconnect. 
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +they can be extracted from the token string as outlined in Java code below:
```suggestion
they can be extracted from the token string as outlined in the Java code below:
```

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +// Base64 decode the second section
probably out of scope, since these are JAVA comments, but the first ends with "." and from here they do not :) could be consistent

2023-07-31 13:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +All notifications for a given **id** will be delivered to the same consumer. Each consumer may receive notifications for many different **id**s.
```suggestion
All notifications for a given **id** are delivered to the same consumer. Each consumer may receive notifications for many different **id**s.
```

2023-08-01 13:37 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +<td>Determines which fragments are included in forwarded messages.</td>
```suggestion
<td>Determines which fragments are included in forwarded messages</td>
```

2023-08-01 13:41 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +// The token string's sections are delimited by dots.
```suggestion
// The token string's sections are delimited by dots
```

2023-08-01 13:42 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +in the [cumulocity-examples repository](https://github.com/SoftwareAG/cumulocity-examples/tree/develop/notification2-examples),
```suggestion
in the [cumulocity-examples repository](https://github.com/SoftwareAG/cumulocity-examples/tree/develop/notification2-examples).
```

2023-08-01 13:44 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +// Base64 decode the second section
Removed the full-stop from the one comment that one.

Done

2023-08-01 13:58 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +A token's lifetime is determined at creation time by the optional **expiresInMinutes** field, which defaults to "1440" (one day, expressed in minutes).
I've rewritten this line using same language as line 373 (adding 'lifetime' term in brackets) and added 'creation time' context to sentence.
@rssag I'm not sure if this has addressed you concern or not. Happy to try again if not right.

2023-08-01 13:59 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +<td>Determines which fragments are included in forwarded messages.</td>
Done (removed odd one)

2023-08-01 14:00 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +it to be recognised across connection interruptions, so allowing message delivery to be resumed after such interruptions
Done with suggestion but not auto-resolving

2023-08-01 14:04 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +<td>True if multiple clients can act collectively as this consumer.</td>
Removed odd full-stop (all without now)

Done

2023-08-01 14:06 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +in the [cumulocity-examples repository](https://github.com/SoftwareAG/cumulocity-examples/tree/develop/notification2-examples),
Corrected to a full-stop

Done

2023-08-01 14:44 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +A token's lifetime is determined at creation time by the optional **expiresInMinutes** field, which defaults to "1440" (one day, expressed in minutes).
should be good :) resolving

2023-08-01 14:45 UTC, rssag approved these changes

2023-08-01 14:45 UTC, rssag commented
what are the target versions?

2023-08-01 15:25 UTC, gapa-c8y commented
> what are the target versions?
I'm checking with @sagscmi (Product Owner). I think the intention is not to backport this, but I am wondering if we should do so for unreleased major versions

2023-08-01 15:58 UTC, merged

2023-08-02 06:06 UTC, rssag commented
tried the auto-backport, but doesn't work here. cherry-pick has to be carried out manually