Update OEE to 10.17 and Shifts feature.
SoftwareAG/c8y-docs pull request #1238
Opened 2023-07-11 12:22 UTC by MarkJMReynolds-SAG

2023-07-11 15:46 UTC, MWindel commented on content/oee/oee-administration-bundle/machine-profiles.md
> +The location indicates where the machine is located. It is used to apply a shift plan to this profile. See the [Shift Plans](/oee/oee-administration/#shiftplan) section for more details regarding shi
```suggestion
The location indicates where the machine is located. It is used to apply a shift plan to this profile. See [Working with shift plans](/oee/oee-administration/#shiftplan) for more details regarding shift plans and the calculation implications.
```

2023-07-19 05:36 UTC, haraldmeyer commented on content/oee/oee-administration-bundle/shiftplan.md
> +If a machine is in production mode, it is running and produces goods. If it is non-production mode, it might be in maintenance and no goods should be produced.
end the sentence with "it might be in maintenance or their might be a staff break". Then have a second sentence: "During non-production mode no goods are being produced".

2023-07-19 05:37 UTC, haraldmeyer commented on content/oee/oee-administration-bundle/shiftplan.md
> +-	non-production
shouldn't this be one line?

2023-07-19 05:41 UTC, haraldmeyer commented on content/oee/oee-dashboards-bundle/andon-board.md
> +<span style="color:red">TODO: Every 10 minutes still? Or is it influenced by machines and their intervals? checkme. </span>
Resolve todo before merge

2023-07-19 05:43 UTC, haraldmeyer commented on content/oee/oee-dashboards-bundle/machine-dashboard.md
> +Implausible values are taken into consideration for shift calculations. Most implausible values are caused by a too low Ideal Cycle Amount. Even if implausible conductivity values arise over short pe
conductivity -> productivity

2023-07-19 05:43 UTC, haraldmeyer commented on content/oee/oee-dashboards-bundle/machine-dashboard.md
>  ### Pareto chart
Why did you remove the explanation?

2023-07-19 05:44 UTC, haraldmeyer commented on content/oee/oee-dashboards-bundle/machine-park.md
> +New values are calculated at regular intervals. This interval is influenced by the default value set in Machine, Line and Site profiles. The precise timestamp is shown in the latest update informatio
use consistent capitalization.

2023-07-19 05:47 UTC, haraldmeyer commented on content/oee/oee-faq-bundle/production-plan.md
> +The optional Production & Shift plans control the way the OEE calculation is performed. They provide the baseline for the Availability & Performance calculation. More information about Production & S
"Production & Shift plans control ... Availability & Performance calculation"

As production plans affect performance and shift plans availability, I suggest to switch the order either at the beginning or the end of the sentence.

2023-07-19 05:48 UTC, haraldmeyer requested changes
See comments for suggested changes.

2023-07-19 10:08 UTC, MarkJMReynolds-SAG commented on content/oee/oee-administration-bundle/shiftplan.md
> +-	non-production
I think so. Good spot.

2023-07-19 10:17 UTC, MarkJMReynolds-SAG commented on content/oee/oee-dashboards-bundle/machine-dashboard.md
>  ### Pareto chart
@haraldmeyer Removed it because the section view is also removed as a feature. If the explanation applies also to the single chart, I can bring it back.

2023-07-26 15:05 UTC, thomaswinkler commented on content/oee/oee-dashboards-bundle/machine-dashboard.md
>  ### Pareto chart
Section view has been removed. Would agree to Marks change. @haraldmeyer Anything we need to change?

2023-07-26 15:07 UTC, thomaswinkler commented on content/oee/oee-dashboards-bundle/andon-board.md
> +<span style="color:red">TODO: Every 10 minutes still? Or is it influenced by machines and their intervals? checkme. </span>
@MarkJMReynolds-SAG Andon Board does also provide a dropdown where users can select intervals. Default interval is used as default.

![Bildschirmfoto 2023-07-26 um 17 07 00](https://github.com/SoftwareAG/c8y-docs/assets/9902/2aaf24a4-6333-4196-aad7-fe05f28bc5a0)

2023-07-28 12:16 UTC, MarkJMReynolds-SAG commented on content/oee/oee-dashboards-bundle/andon-board.md
> +<span style="color:red">TODO: Every 10 minutes still? Or is it influenced by machines and their intervals? checkme. </span>
@thomaswinkler Yes, will update the image to show that dropdown, since it's missing in the current one.
The big Q there is regarding Andon boards for Lines/Sites/Areas. Since those don't have a dropdown for the interval, what would it end up being?

2023-07-28 13:51 UTC, MarkJMReynolds-SAG commented on content/oee/oee-dashboards-bundle/machine-dashboard.md
>  ### Pareto chart
Removed info box as directed by Thomas.

2023-08-01 08:23 UTC, haraldmeyer approved these changes

2023-08-02 09:35 UTC, MWindel commented on content/oee/oee-administration-bundle/machine-profiles.md
> +Next, define the resolution intervals. The default interval is mandatory and will define the interval that is used for this machine in the Organization Overview. It will also influence OEE calculatio
```suggestion
Next, define the resolution intervals. The default interval is mandatory and will define the interval that is used for this machine in the **Overview**. It will also influence OEE calculation intervals for sites and lines that do not have a dedicated profile.
```

2023-08-02 10:01 UTC, MWindel commented on content/oee/oee-administration-bundle/organization.md
> +Click the **Add** button to add an entity (line, area, or machine) to another entity. It is possible to assign machines to multiple lines by adding them. This allows for modelling of setups where lin
```suggestion
Click the **Add** button to add an entity (line, area, or machine) to another entity. You can assign one or more machines to multiple lines. This allows for modelling of setups where lines can split, join, or share equipment between them.
```

2023-08-02 14:41 UTC, MWindel commented on content/oee/oee-dashboards-bundle/machine-dashboard.md
> +In the **Time range** field you can select a time range for which the OEE values will be displayed in the [**OEE status**](#oee-status) and [**OEE data**](#data) sections. By default, this will selec
```suggestion
In the **Time range** field you can select a time range for which the OEE values will be displayed in the [**OEE status**](#oee-status) and [**OEE data**](#data) sections. By default, this will select a 24-hour period based on the current date. The back and forward arrows will move the time range based on the difference betwen the start and end time, that is, if the difference between the two times is 4 hours, then the arrows will use steps of 4 hours. 
```

2023-08-02 15:09 UTC, MarkJMReynolds-SAG commented on content/oee/oee-administration-bundle/machine-profiles.md
> +Next, define the resolution intervals. The default interval is mandatory and will define the interval that is used for this machine in the Organization Overview. It will also influence OEE calculatio
It depends. In the drop-down boxes, they're one word and it's `Site`, `Line`. In the Overview, it can be a label in all caps. In other places throughout the UI, though it's just lower case.

2023-08-03 15:04 UTC, MWindel approved these changes

2023-08-03 16:20 UTC, merged