document notification2 token refresh
SoftwareAG/c8y-docs pull request #126
Opened 2021-12-07 11:39 UTC by andrekramer1

2021-12-08 09:52 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +### Token expiry
here and more occurrences: "expiry" -> "expiration"

2021-12-08 10:09 UTC, andrekramer1 commented on content/reference/notifications-bundle/overview.md
> +### Token expiry
British english / Archaic. I'll also spell check as I'm editing this as raw text.

2021-12-08 10:30 UTC, rssag commented
language review as commit. got some more comments coming

2021-12-08 17:42 UTC, sagscmi requested changes
No significant concerns about the content but I think there are changes here that should really be in at least 3 different PRs: 1) token expiry, 2) isShared/isVolatile (maybe these come together?), and 3) unsubscription.

I would split this change up and merge the doc only when the respective implementation/tests are also approved and ready to merge.

Also we should have Jira tickets associated with all these changes.

2021-12-08 17:42 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +### Shared subscription
I know we have an implementation for `isShared` but I don't recall if we have completed testing for it yet?  If not then we shouldn't push the doc for it until the testing is done and we're ready for the change to (in principle) go to customers.

2021-12-08 17:42 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +### Volatile subscriptions
As for `isShared` - is this fully tested yet?

2021-12-08 17:42 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +Note that there is no need to mark a subscription as shared - only the token is marked shared, but here it's both (token has isVolatile and isShared).
Not sure I follow this... what is the "here" in "here it's both" referring to?

2021-12-08 17:42 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +These count as separate subscriptions and can be consumed by a subscriber using a token with the corresponding `isVolatile` equals true or false.
"equals" --> "equal to"

2021-12-08 17:42 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +A separate REST endpoint is avaiable for this: <kbd>/notification2/unsubscibe</kbd>.
"avaiable" --> "available"

2021-12-08 17:42 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +### Unsubscribing a subscriber
Again, I don't think we can include this documentation until the implementation and testing are also done.

2021-12-08 17:59 UTC, andrekramer1 commented on content/reference/notifications-bundle/overview.md
> +### Shared subscription
Yes, it's doc first for once. We have a JIRA for the unsubscribe and a PR for enabling Shared and Volatile which we had there in disabled form but they require more testing (outside of the dev testing I've done so far).

2021-12-08 18:02 UTC, andrekramer1 commented on content/reference/notifications-bundle/overview.md
> +### Token expiry
done

2021-12-09 08:44 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +This can be done by calling token create with the same parameters as originally.
is "token create" a command? if so, we could use backticks to make it monospace font.

2021-12-09 09:20 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +There can be multiple subscription on a managed object, each receiving filtered notifications as specified by their individual subscriptions.
```suggestion
There can be multiple subscriptions on a managed object, each receiving filtered notifications as specified by their individual subscriptions.
```
the sentence reads like there are subscriptions of subscriptions. is that correct?

2021-12-09 09:21 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +In order to scale, shared subscriptions are required so that notifications are dispatched to one of a number of possible consumers that are part of the same logical subscriber or parallelised applica
```suggestion
In order to scale, shared subscriptions are required so that notifications are dispatched to one of a number of possible consumers that are part of the same logical subscriber or parallelized application.
```

2021-12-09 09:24 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +This can be achieved by creating a token with a subscription and subscriber name for the scalable application but with an optional boolean "isShared" request parameter set to true in the token create
```suggestion
This can be achieved by creating a token with a subscription and subscriber name for the scalable application with the optional boolean request parameter `isShared` set to true in the token create request.
```

2021-12-09 09:28 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +These all use a token for the same subscription and the subscriber and both the same subscription name, either by using the same shared token or using the same subscription name and subscriber when g
"These" -> "They"
"same subscription and the subscriber and both the same subscription name" - what is meant?
are "per instance tokens" special tokens?

2021-12-09 09:29 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +The subscription name defines the "topic" messages are published on, while the subscriber identifies the backend (north side) application that's usually used.
why is "topic" in quotes?

2021-12-09 09:30 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +However, a different consumer name is passed as the "consumer" query string argument.
```suggestion
However, a different consumer name is passed as the `consumer` query string argument.
```

2021-12-09 09:31 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +When subscribing, it is possible to pass in an optional boolean "isVolatile" query parameter set to true.
```suggestion
When subscribing, it is possible to pass in an optional boolean `isVolatile` query parameter set to true.
```

2021-12-09 09:32 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Note that there is no need to mark a subscription as shared - only the token is marked shared.
```suggestion
Note that there is no need to mark a subscription as shared - only the token is marked as shared. 
```

2021-12-09 09:33 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Both token and subscriptions have isVolatile but only token has both isVolatile and isShared.
```suggestion
Both the token and the subscriptions have `isVolatile` but only the token has both `isVolatile` and `isShared`.
```

2021-12-09 09:36 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +These will be deleted if a tenant is deleted but otherwise can take up considerable space in permanent storage for high frequency notification sources.
```suggestion
They will be deleted if a tenant is deleted but otherwise can take up considerable space in permanent storage for high frequency notification sources.
```

2021-12-09 09:36 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +It has a non-optional query parameter "token".
```suggestion
It has a non-optional query parameter `token`.
```

2021-12-09 09:37 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Note that there is no explicit subscribe subcriber using a token.
"subscribe subscriber" - is this correct?

2021-12-09 09:37 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Instead this happens when you first connect a Web Socket with a token for the subscription name and subscriber.
```suggestion
Instead this happens when you first connect a web socket with a token for the subscription name and subscriber.
```

2021-12-09 09:43 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +To unsubscribe an application, however, is an explicit act using a similar or the original token token.
```suggestion
However, unsubscribing an application is an explicit act using the original or a similar token.
```

2021-12-09 09:46 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Only if no consumer will ever run again should an unsubscribe subscriber be necessary.
```suggestion
Only if no consumer will ever run again should unsubscribing a subscriber be necessary.
```

2021-12-09 09:48 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +It's not possible to check if the unsubscribe succeeded as the connection always closes so this way of unsubscribing is mostly for testing.
```suggestion
It's not possible to check if the unsubscribe operation succeeded as the connection always closes so this way of unsubscribing is mostly for testing.
```

2021-12-09 10:25 UTC, andrekramer1 commented on content/reference/notifications-bundle/overview.md
> +This can be done by calling token create with the same parameters as originally.
Thanks for all these comments Richard. Unfortunately, it's still a bit of a work in progress but it allows us to have the text to fold in when we next release.

2021-12-09 10:26 UTC, andrekramer1 commented on content/reference/notifications-bundle/overview.md
> +The subscription name defines the "topic" messages are published on, while the subscriber identifies the backend (north side) application that's usually used.
removed quotes here

2021-12-10 07:09 UTC, rohitjoshi-softwareag commented on content/reference/notifications-bundle/overview.md
> +When creating a token, an expiration time must be given in minutes of validity from when the token was created.
I think we can skip this part: "When creating a token, an expiration time must be given in minutes of validity from when the token was created.
This security feature limits the potential damage due to leaking of a token." 
and just talk about refresh only.

2021-12-10 07:09 UTC, rohitjoshi-softwareag commented on content/reference/notifications-bundle/overview.md
> +### Shared subscription
I would prefer we just raise a separate PR for the token refresh for now.

2021-12-10 09:11 UTC, andrekramer1 commented on content/reference/notifications-bundle/overview.md
> +### Shared subscription
it can wait as it's just explaining. Maybe with unsubscribe if volatile/shared is internal only for now.

2021-12-10 09:12 UTC, andrekramer1 commented on content/reference/notifications-bundle/overview.md
> +When creating a token, an expiration time must be given in minutes of validity from when the token was created.
I think it's a reminder of why we are even talking about it. No harm?

2021-12-10 17:33 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +When creating a token, an expiration time must be given in minutes of validity from when the token was created.
Yeah, I don't see any harm in leaving this in.

2021-12-10 17:37 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +### Shared subscription
Definitely happy to see doc being written early!  I'm still going to be annoying and say that this should be split into several PRs though.

2022-01-04 10:51 UTC, andrekramer1 commented on content/reference/notifications-bundle/overview.md
> +### Shared subscription
I've split out shared and volatile to separate review now.

2022-01-10 09:59 UTC, rssag approved these changes

2022-01-12 11:44 UTC, gapa-c8y approved these changes

2022-01-13 12:53 UTC, sagscmi approved these changes
Sorry, hadn't realised this one was still waiting for me - PRs you've already reviewed don't show up as needing attention even if you requested specific changes.  In future feel free to re-request a review from me if I seem to be ignoring it.

Anyway all my concerns about the scope of the change have been addressed so happy to approve.

2022-01-14 13:08 UTC, merged