User guide update for Apama-ctrl
SoftwareAG/c8y-docs pull request #1285
Opened 2023-08-04 11:16 UTC by kailol-sag

Eliminate wrong Apama-ctrl info from the microservices table and make it simpler as suggested by Rob.
I suggest to backport this back to 10.17. Earlier versions cannot be auto-backported because of the link in the first column: in 10.17, the name of the folder changed from "apama" to "streaming-analytics".

2023-08-04 13:18 UTC, rthrippleton requested changes
(see suggestion)

2023-08-04 13:21 UTC, kailol-sag commented on content/users-guide/administration-bundle/managing-microservices.md
> +<td style="text-align:left">Streaming Analytics microservices, including runtime for Analytics Builder, EPL apps and smart rules. Capabilities and resources vary depending on the microservice variant
Looks like a convention (no matter whether I'm happy with that or not ...)

2023-08-04 13:22 UTC, rthrippleton commented on content/users-guide/administration-bundle/managing-microservices.md
> +<td style="text-align:left">Streaming Analytics microservices, including runtime for Analytics Builder, EPL apps and smart rules. Capabilities and resources vary depending on the microservice variant
Fair enough!

2023-08-04 13:22 UTC, rthrippleton approved these changes

2023-08-07 05:20 UTC, skom-sag approved these changes

2023-08-07 09:18 UTC, BeateRixen approved these changes

2023-08-07 13:18 UTC, merged

2023-08-07 13:45 UTC, BeateRixen commented
Chery-picked manually to 10.17 and 10.18 release branches.