MTM-42624 angular 12 upgrade
SoftwareAG/c8y-docs pull request #131
Opened 2021-12-14 11:27 UTC by DawidSAG

2021-12-14 12:53 UTC, rssag commented on content/web/upgrade-bundle/migration-angular-12.md
> +- **Enable IVY** (check the section "**How to enable IVY**").
```suggestion
- Enable IVY, see [How to enable IVY](#how-to-enable-ivy).
```

2021-12-14 12:53 UTC, rssag commented on content/web/upgrade-bundle/migration-angular-12.md
> +- **Use Node** version `14`.
```suggestion
- Use Node version `14`.
```

2021-12-14 12:55 UTC, rssag commented on content/web/upgrade-bundle/migration-angular-12.md
> +- edit **tsconfig.json** and change `enableIvy` to `true` or delete it as this setting is the default setting:
```suggestion
- Edit _tsconfig.json_ and set `enableIvy` to `true` or delete it as this setting is the default setting:
```
where is the tsconfig.json file located?

2021-12-14 12:56 UTC, rssag commented on content/web/upgrade-bundle/migration-angular-12.md
> +- edit **package.json** and add `postinstall` hook:
```suggestion
- Edit _package.json_ and add the `postinstall` hook:
```
where is the package.json file located?

2021-12-14 12:56 UTC, rssag commented on content/web/upgrade-bundle/migration-angular-12.md
> +- If you use `Jest (JavaScript Testing Framework)` check: [Jest - Angular IVY](https://thymikee.github.io/jest-preset-angular/docs/guides/angular-ivy) for the configuration.
```suggestion
- If you use Jest (JavaScript Testing Framework) check: [Jest - Angular IVY](https://thymikee.github.io/jest-preset-angular/docs/guides/angular-ivy) for the configuration.
```

2021-12-14 12:57 UTC, rssag commented on content/web/upgrade-bundle/migration-angular-12.md
> +> **Info:** `Deep imports` are not supported. For example, you need to import from **`@c8y/ngx-components/asset-navigator`** but not from the **`@c8y/ngx-components/asset-navigator/services/asset-ser
```suggestion
> **Info:** Deep imports are not supported. For example, you need to import from `@c8y/ngx-components/asset-navigator` but not from `@c8y/ngx-components/asset-navigator/services/asset-service`.
```

2021-12-14 12:58 UTC, rssag commented on content/web/upgrade-bundle/migration-angular-12.md
> +> **Info:** If you are using Visual Studio Code, make sure in the **Angular Language Service Plugin** option: **`"Use legacy View Engine language service"`** is unchecked.
```suggestion
> **Info:** If you are using Visual Studio Code, make sure that in the Angular Language Service Plugin the option `"Use legacy View Engine language service"` is unchecked.
```

2021-12-14 14:04 UTC, DawidSAG commented on content/web/upgrade-bundle/migration-angular-12.md
> +- edit **tsconfig.json** and change `enableIvy` to `true` or delete it as this setting is the default setting:
> where is the tsconfig.json file located?

It's in the root of the project.

2021-12-14 14:36 UTC, rssag submitted a review, later dismissed

2021-12-15 09:27 UTC, janhommes requested changes

2021-12-17 14:54 UTC, janhommes approved these changes

2021-12-20 09:04 UTC, BeateRixen approved these changes

2021-12-20 09:28 UTC, MWindel approved these changes

2021-12-20 16:51 UTC, aprimakina approved these changes

2021-12-21 08:25 UTC, BeateRixen approved these changes

2021-12-21 14:28 UTC, merged