MTM-51678 certificate crl settings user guide
SoftwareAG/c8y-docs pull request #1397
Opened 2023-09-05 13:59 UTC by sayanc8y

Requesting for review on initial version of CRL user guide.

2023-09-07 11:02 UTC, rssag requested changes

2023-09-07 11:02 UTC, rssag commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +Each file can hold at maximum `5000` revocation entries.
```suggestion
Each file can hold at maximum 5000 revocation entries.
```

2023-09-07 11:02 UTC, rssag commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +Multiple upload is allowed.In case of duplicate the latest one (last uploaded one) will be considered.
```suggestion
Multiple upload is allowed. In case of a duplicate, the latest one (last one uploaded) is used.
```

2023-09-07 11:02 UTC, rssag commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +To bulk upload, follow the below steps
```suggestion
To bulk upload, follow the steps below:
```

2023-09-07 11:02 UTC, rssag commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +1. Download CSV template from **Revoked certificates list** panel.
```suggestion
1. Download the CSV template from the **Revoked certificates list** panel.
```

2023-09-07 11:02 UTC, rssag commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +#### To download or view the offline CRL file
```suggestion
#### To download or view the offline CRL file {#to-download-or-view-the-offline-crl-file}
```

2023-09-07 11:02 UTC, rssag commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +Go to  **Revoked certificates list** panel and click **Download CRL file**.
```suggestion
In the **Revoked certificates list** panel, click **Download CRL file**.
```

2023-11-02 07:17 UTC, rssag commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +1. Click **CRL check** in the upper right corn#### To enable offline revocationer of the screen.
```suggestion
1. Click **CRL check** in the upper right corner to enable the offline revocation of the screen.
```

2023-12-28 07:53 UTC, rssag commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +Note: If the date is in future then that CRL entry is skipped. If the date field is empty, then the current date is used.
```suggestion
{{< c8y-admon-info >}}
If the date is in the future then the CRL entry is skipped. If the date field is empty, then the current date is used.
{{< /c8y-admon-info >}}
```

2024-01-05 08:08 UTC, rssag approved these changes

2024-01-18 08:01 UTC, sarangovindarajan requested changes
Please check my comments

2024-01-18 08:01 UTC, sarangovindarajan commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +Multiple upload is allowed. In case of a duplicate, the latest one (last one uploaded) is used.
do you mean, a serial number can be uploaded multiple times or mutiple file uploads are possible?

2024-01-18 11:13 UTC, sguhc8y commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +In {{< product-c8y-iot >}} terms, if there is a breach at device certificates signed by a trusted certificate, users
Done. Please have a look now.

2024-01-18 11:13 UTC, sguhc8y commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +    The trusted CA maintains the Certificate Revocation Lists with the list of certificate serial numbers that are
Done. Please have a look now.

2024-01-18 11:14 UTC, sguhc8y commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +   can manually upload the serial numbers of the revoked certificates.
Added in the `important` section, please have a look.

2024-01-18 11:14 UTC, sguhc8y commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +   | Serial number | Must be in `Hexadecimal Value`.|
Done. Please have a look now.

2024-01-18 11:15 UTC, sguhc8y commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +If the date is in the future then the CRL entry is skipped. If the date field is empty, then the current date is used.
Currently for manual entries the UI date picker doesn't allow to pick a future date. I have rephrased the wordings please have a look.

2024-01-18 11:15 UTC, sguhc8y commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +#### Offline bulk import {#offline-bulk-import}
Done. Please have a look now.

2024-01-18 11:17 UTC, sguhc8y commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +Multiple upload is allowed. In case of a duplicate, the latest one (last one uploaded) is used.
A serial no. can be uploaded multiple times. I have rephrased the wordings please have a look now.

2024-02-05 12:15 UTC, sarangovindarajan approved these changes

2024-02-08 09:50 UTC, Oezge-Akin approved these changes

2024-02-08 11:33 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +    content: "This section describes how to fine-tune various certificate configurations."
If this text should show up in the context help in the product then it should not describe what you describe in this section but what you can do on the respective UI page. Please compare other context help content.

2024-02-08 11:33 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +This section is meant for advance users, for granular control over certificates attributes like CRL, OCSP, Certificate
```suggestion
This section is meant for advance users, for granular control over certificates attributes like CRL, OCSP, Certificate
```
```suggestion
This section targets at advanced users for granular control over certificate attributes like CRL, OCSP, Certificate
```

2024-02-08 11:33 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +   To perform online revocation checks, the device administrator is expected to upload trusted CA
```suggestion
   To perform online revocation checks, the device administrator is expected to upload a trusted CA
```

2024-02-08 11:33 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +   who maintains the Certificate Revocation lists with the list of revoked certificate serial numbers
```suggestion
   which maintains the CRLs with the list of revoked certificate serial numbers 
```

2024-02-08 11:33 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +   and should provide this information in its CDP (CRL Distribution point) attribute.
```suggestion
   and should provide this information in its CDP attribute.
```

2024-02-08 11:33 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +   | Serial number | Must be in `Hexadecimal Value`.| 0b8a5b9dd501a88775399b9a048811a3 |
```suggestion
   | Serial number | Must be a hexadecimal value.| 0b8a5b9dd501a88775399b9a048811a3 |
```

2024-02-08 11:33 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +4. Click save to confirm your entries.
```suggestion
4. Click **Save** to confirm your entries.
```

2024-02-08 11:33 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +To bulk upload, follow the steps below:
```suggestion
To bulk upload, follow these steps:
```

2024-02-12 10:42 UTC, sguhc8y commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +    content: "This section describes how to fine-tune various certificate configurations."
Understood. Updated the content and informed to link to UI page help text.

2024-02-12 10:43 UTC, sguhc8y commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +This section is meant for advance users, for granular control over certificates attributes like CRL, OCSP, Certificate
done. please have a look.

2024-02-12 10:43 UTC, sguhc8y commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +   To perform online revocation checks, the device administrator is expected to upload trusted CA
done.

2024-02-13 09:52 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +    content: "This section helps the administrator configure the CRL settings (online or offline). If the revoked certificate information is maintained by the issuing CA, then Online check can be cho
```suggestion
    content: "Administrators can configure the Certificate Revocation List (CRL) settings (online or offline). If the revoked certificate information is maintained by the issuing Certificate Authority (CA), the online check option can be selected. If the CA does not maintain the CRL information, the offline setup can be selected. In offline setup, the revoked certificate serial number can either be added manually or can be uploaded in bulk using the file template attached."
```

2024-02-13 09:52 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +Currently, CRL (Certificate Revocation List) is supported.
```suggestion
Currently, Certificate Revocation List (CRL) is supported.
```

2024-02-13 09:53 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +In general, CRL (Certificate Revocation List) contains a list of serial numbers of revoked certificates.
```suggestion
In general, CRL contains a list of serial numbers of revoked certificates.
```

2024-02-13 09:54 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +In general, CRL contains a list of serial numbers of revoked certificates.
```suggestion
In general, Certificate Revocation List (CRL) contains a list of serial numbers of revoked certificates.
```

2024-02-13 09:55 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +These are issued by certificate authorities (CAs) periodically and published through an endpoint called CDP (CRL
```suggestion
These are issued by Certificate Authorities (CAs) periodically and published through an endpoint called CRL
```

2024-02-13 09:55 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificate-settings.md
> +Distribution Point).
```suggestion
Distribution Point (CDP).
```

2024-02-13 09:57 UTC, BeateRixen commented on content/device-management-application/managing-device-data-bundle/managing-trusted-certificates.md
> +  content: "Cumulocity IoT allows devices to connect via MQTT and LwM2M protocol using a X.509 certificate for authentication. To do so, the public certificate (Root or Intermediate) of the certifica
```suggestion
  content: "Cumulocity IoT allows devices to connect via MQTT and LWM2M protocol using a X.509 certificate for authentication. To do so, the public certificate (root or intermediate) of the certificate authority must be 'trusted' by Cumulocity IoT. This public certificate should be added to the trusted certificates."
```

2024-02-14 09:33 UTC, BeateRixen approved these changes

2024-02-14 09:55 UTC, merged