updated compatibility policy and glossary towards yearly releases and CD
SoftwareAG/c8y-docs pull request #1398
Opened 2023-09-06 10:24 UTC by BeateRixen

2023-09-07 07:59 UTC, rssag requested changes

2023-09-07 07:59 UTC, rssag commented on content/concepts/introduction-bundle/compatibility-policy.md
> +If changes result in breaking backward compatibility, to provide our customers with the time to change their solution, such changes will be announced at least 6 months ahead of the point in time, whe
```suggestion
If changes result in breaking backward compatibility, to provide our customers with the time to change their solution, such changes will be announced at least 6 months ahead of when the change becomes effective. Where the change has a wide-ranging impact, we will delay taking action until we have ascertained that the impact on our customers is minimal.
```

+ more occurrences.

2023-09-07 07:59 UTC, rssag commented on content/glossary/c.md
> +In the {{< product-c8y-iot >}} Continuous Deployment (CD) model, the different components of the {{< product-c8y-iot >}} platform are updated on a continuous basis, that is, small incremental improve
```suggestion
In the {{< product-c8y-iot >}} Continuous Deployment (CD) model, the different components of the {{< product-c8y-iot >}} platform are updated on a continuous basis, that is, small incremental improvements are deployed multiple times per week. Continuous updates provide customers with a steady stream of enhancements, bug fixes, and new functionalities as they become available. 
```

not wrong, but "per" is more formal (says google :D)

2023-09-07 07:59 UTC, rssag commented on content/glossary/c.md
> +See also [Private Preview](/glossary/p/#private preview), [Public Preview](/glossary/p/#public preview) and [General Availability](/glossary/g/#ga).
the anchor IDs don't look correct

edit: checked locally. the links fully break. "_" should be included.
i'd advise using "-" instead of "_" for the IDs though.

2023-09-07 09:27 UTC, BeateRixen commented on content/concepts/introduction-bundle/compatibility-policy.md
> +If changes result in breaking backward compatibility, to provide our customers with the time to change their solution, such changes will be announced at least 6 months ahead of the point in time, whe
I also do not like my phrasing but are you sure, your suggestion is correct? For me it sounds wrong :-). How about "ahead of the change becoming effective". I was thinking about that one earlier? What do you think, @MWindel ?

2023-09-07 09:30 UTC, BeateRixen commented on content/glossary/c.md
> +See also [Private Preview](/glossary/p/#private preview), [Public Preview](/glossary/p/#public preview) and [General Availability](/glossary/g/#ga).
I don´t get what you mean. What is the difference to the IDs we already have in place in the glossary?

2023-09-07 11:04 UTC, rssag commented on content/glossary/c.md
> +See also [Private Preview](/glossary/p/#private preview), [Public Preview](/glossary/p/#public preview) and [General Availability](/glossary/g/#ga).
the references break, because there's a space in the URL

updated the comment, the underscore did not show. i'd advise using hyphen instead of underscore in IDs.

2023-09-07 11:57 UTC, BeateRixen commented on content/glossary/c.md
> +See also [Private Preview](/glossary/p/#private preview), [Public Preview](/glossary/p/#public preview) and [General Availability](/glossary/g/#ga).
You are right, no idea, why I used underscores :-). Replaced them.

2023-09-07 13:26 UTC, MWindel commented on content/concepts/introduction-bundle/compatibility-policy.md
> +If changes result in breaking backward compatibility, to provide our customers with the time to change their solution, such changes will be announced at least 6 months ahead of the point in time, whe
@BeateRixen @rssag I like both versions. The gerund is a bit smoother in my opinion.

2023-09-08 06:53 UTC, rssag commented on content/concepts/introduction-bundle/compatibility-policy.md
> +If changes result in breaking backward compatibility, to provide our customers with the time to change their solution, such changes will be announced at least 6 months ahead of the point in time, whe
googled specifically for "ahead of when". seems to be common, doesn't sound wrong to me

2023-09-08 06:56 UTC, BeateRixen commented on content/concepts/introduction-bundle/compatibility-policy.md
> +If changes result in breaking backward compatibility, to provide our customers with the time to change their solution, such changes will be announced at least 6 months ahead of the point in time, whe
Just changed it now to the gerund :-). But if prefer the other way, I can again change it. This will be reviewed by Niko and Michael as this is of legal relevance. This is the reason why I was so precise with my phrasing. Let´s see what they suggest.

2023-09-08 07:20 UTC, MWindel approved these changes

2023-09-13 12:54 UTC, merged