MTM-49410 As a customer I need a MQTT Connect user documentation guide
SoftwareAG/c8y-docs pull request #1405
Opened 2023-09-07 13:06 UTC by slc-softwareag

2023-09-19 13:28 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +MQTT Connect is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
.. though something has to distinguish it from standard MQTT. So alternative text is not obvious.

2023-09-19 13:34 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +MQTT Connect is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
Something like '... will replace the existing MQTT implementation in a future release and provide richer functionality. It is currently only available under private preview. Speak to you or sales person/agent ...'

2023-09-19 13:38 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +* Cooperates with Messaging Service allowing to map any MQTT binary format into {{< product-c8y-iot >}} compatible one.
'The Messaging Service' seems like implementation detail. Also maybe we should state the the customer must provide the mapping functionality in a microservice' (or similar). I might be incorrect about the specifics of that last bit.

2023-09-19 13:41 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +* Minimum traffic overhead.
Regarding 'Minimum traffic overhead', do you mean this reduces the ingress traffic load on Cumulocity core? Maybe this is implementation detail also (but maybe useful for those that are considering whether to use it or not)

2023-09-19 13:45 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +MQTT Connect works together with the Messaging Service to provide as generic solution as possible.
```suggestion
MQTT Connect works together with the Messaging Service to provide as generic a solution as possible.
```

2023-09-19 13:45 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +Below diagram illustrates how the message flows, starting from the device, through the Messaging Service,
```suggestion
The diagram below illustrates how the message flows, starting from the device, through the Messaging Service, 
```

2023-09-19 13:47 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +Below diagram illustrates how the message flows, starting from the device, through the Messaging Service,
```suggestion
The diagram below illustrates the message flows, starting from the device, through the Messaging Service, 
```

2023-09-19 13:49 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +Below diagram illustrates how the message flows, starting from the device, through the Messaging Service,
```suggestion
The diagram below illustrates how a message flows, starting from the device, through the Messaging Service, 
```

2023-09-19 13:52 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +All MQTT messages coming to the MQTT Connect are forwarded to the Messaging Service, where they are persisted and waiting to be consumed.
Should we mention that this persistence gives us reliable ingress?

2023-09-19 13:54 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +Usually that's the place where your custom microservice comes into action. Knowing the topic and payload structure
'Usually' might imply there are (unusual) alternatives here. Can this, or do we intend that this, will be able to be done by some other means (that is, can this be a something other than a microservice that does this)?

2023-09-19 14:02 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +you will be able to easily write your own microservice which with the help of [Java Client](/device-integration/mqtt-connect#java-client)
```suggestion
you will be able to easily write your own microservice which consumes the MQTT messages using the [Java Client](/device-integration/mqtt-connect#java-client), 
translates them to the {{< product-c8y-iot >}} format using mapping you provide, and then uses the [Microservice SDK](/microservice-sdk/java) to push them into {{< product-c8y-iot >}}.
```

2023-09-19 14:03 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +consumes the MQTT messages, translates them to the {{< product-c8y-iot >}} format and stores them using [Microservice SDK](/microservice-sdk/java).
```suggestion
translates them to the {{< product-c8y-iot >}} format using mapping you provide, and then uses the [Microservice SDK](/microservice-sdk/java) to push them into {{< product-c8y-iot >}}.
```

2023-09-19 14:06 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +consumes the MQTT messages, translates them to the {{< product-c8y-iot >}} format and stores them using [Microservice SDK](/microservice-sdk/java).
These 2 suggestions are part of one 2 line suggestion. I thought the original sentence made it sound like the MQTT client SDK would do the mapping/formatting for them, so wanted to make it clear that they have to provide that

2023-09-19 14:07 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +Same solution can be also applied when trying to communicate with device. Knowing the MQTT client id and the topic,
```suggestion
The same solution can be also applied when trying to communicate with device. Knowing the MQTT client id and the topic,
```

2023-09-19 14:08 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +microservice can push any MQTT message to the device via [Java Client](/device-integration/mqtt-connect#java-client).
```suggestion
a microservice can push any MQTT message to a device via [Java Client](/device-integration/mqtt-connect#java-client).
```

2023-09-19 14:10 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +microservice can push any MQTT message to the device via [Java Client](/device-integration/mqtt-connect#java-client).
suggestion: Should the description of sending and receiving be next to the diagram for each?
Either receive-text, receive-diagram, sent-text, send-diagram, or alternatively receive-diagram, receive-text, send-diagram, sent-text.

2023-09-19 14:12 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +This section lists the implementation details for the MQTT Connect. The MQTT Connect implementation supports MQTT Version 3.1.1, support for 5.0 will be added soon.
```suggestion
This section lists the implementation details for MQTT Connect. The MQTT Connect implementation supports MQTT Version 3.1.1, support for 5.0 will be added soon.
```

2023-09-19 14:22 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +Port 9883 is enabled by default and it supports one-way SSL using username and password for client authorization.
thought: I had to look up one-way SSL as I wasn't sure what it was (server auth only, no client auth). I would have suggested making it a link to wikipedia or similar, but couldn't find a suitable (non-commercial) resource to link it to. I guess customer will have to Google it themselves!

2023-09-19 14:43 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +
suggestion: rewrite of the following paragraph (rather then a suggestion per line)

MQTT Connect topics are mapped 1:1 to Messaging Service subscriptions of the same name. The Messaging Service subscriptions reliably store the topic messages for asynchronous processing. The messages stored on these subscriptions can be consumed using the [Notifications 2.0 API](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Notification-2.0-API), however it is much simpler to use the dedicated [Java Client](/device-integration/mqtt-connect#java-client), which just requires a token to consume messages .

2023-09-19 14:46 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +MQTT Connect does not impose any topic structure. There is just a few topic names which are reserved for the future use, namely all [SmartREST 2.0](/smartrest/smartrest-two) related topics.
```suggestion
MQTT Connect does not impose any topic structure. There are just a few topic names which are reserved for historic purposes the future use, such as all the [SmartREST 2.0](/smartrest/smartrest-two) related topics.
```

2023-09-19 14:52 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +
suggestion: we can simplify the following paragraph I think

'MQTT Connect messages are packed, together with additional metadata, into [Apache AVRO](https://avro.apache.org/) binary format messages, before being sent sent to the Messaging Service.
Assuming Java types, the packed message structure looks as follows:'

2023-09-19 14:54 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +| clientId               | String  | MQTT client id                               |
```suggestion
| clientId               | String  | Uniquely identifies the MQTT client                                |
```

2023-09-19 14:55 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +| dupFlag                | boolean | MQTT duplicate flag                          |
```suggestion
| dupFlag                | boolean | Indicates this message is a resend                           |
```

2023-09-19 15:00 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +Luckily there is a [Java Client](/device-integration/mqtt-connect#java-client) which already contains classes
```suggestion
The [Java Client](/device-integration/mqtt-connect#java-client) contains classes 
```

No 'luck' involved - your's and Rohit's hard work!

2023-09-19 15:01 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +representing the above model, it also deals with AVRO binary format decoding.
```suggestion
representing the above model, and provides AVRO binary format decoding.
```

2023-09-19 15:04 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +*   Username and password. The MQTT username needs to include the tenant ID and username in the format &lt;tenantID/username>.
```suggestion
*   Username and password. The MQTT username needs to include the tenant ID and username in the format &lt;tenantID&gt;/&lt;username>.
```
suggesting both open and close angle-braces for tenantID and username as they are separate placeholders

2023-09-19 15:05 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +*   Device certificates - not yet supported, will be added in the future.
```suggestion
*   Device certificates - not yet supported. This will be added in a future release.
```

2023-09-19 15:08 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +The MQTT ClientId is a field to uniquely identify each connected client. ClientId may consist up to 128 alphanumeric characters.
```suggestion
The MQTT ClientId field uniquely identifies the connected client. ClientId may consist up to 128 alphanumeric characters.
```

2023-09-19 15:10 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +The MQTT ClientId is a field to uniquely identify each connected client. ClientId may consist up to 128 alphanumeric characters.
```suggestion
The MQTT ClientId field identifies the connected client. ClientId may consist up to 128 alphanumeric characters.
```
We say elaborate that his must be unique more strongly (better) on the next line.

2023-09-19 15:14 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +    - Possible re-send actions comes with no guarantee that the message was received and processed by the server only once.
Not sure if the 'Possible re-send ...' line reads clearly or makes sense (to me). Is there a 'not' missing ('... message was not received and processed ...'). Maybe I'm miss-reading this totally. I'm not sure what were trying to say here.

2023-09-19 15:17 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +Last will is fully supported by MQTT Connect and like with any other publish messages you can use all allowed topic and any payload.
```suggestion
Last will is fully supported by MQTT Connect and like with any other publish messages you can use any unreserved topic and any payload.
```

2023-09-19 15:24 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +
suggestion: a few changes through the following paragraph


MQTT Connect follows the MQTT specification for server responses. For example, if invalid credentials are sent in the `CONNECT` message, the server response `CONNACK` message will contain the `0x05` return code.
The return code can be treated similarly to REST API HTTP codes, such as 401.

2023-09-19 15:27 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +Below table presents basic comparison between already existing {{< product-c8y-iot >}} MQTT and the new MQTT Connect.
```suggestion
The table blow presents a basic comparison between the standard {{< product-c8y-iot >}} MQTT functionality and that of MQTT Connect.
```

2023-09-19 15:29 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +| Extensibility     | Limited by SmartREST 2.0 custom templates | Unlimited thanks to Messaging Service utilization and custom microservice implementation |
```suggestion
| Extensibility     | Limited by SmartREST 2.0 custom templates | Unlimited due to Messaging Service utilization and custom microservice implementation |
```

2023-09-19 15:37 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/faq.md
> +to bootstrap the device and obtain device credentials. Having device credentials, please also make sure that they have `Mqtt connect` `ADMIN` permission.
```suggestion
to bootstrap the device and obtain device credentials. Once the device credentials are obtained, ensure that they have `Mqtt connect` `ADMIN` permission.
```

2023-09-19 15:39 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/faq.md
> +You can easily achieve this by assigning permission to the `devices` global role.
```suggestion
You can achieve this for all devices this by granting this permission to the `devices` global role.
```

2023-09-19 15:39 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/faq.md
> +You can easily achieve this by assigning permission to the `devices` global role.
```suggestion
You can achieve this for all devices by granting this permission to the `devices` global role.
```

2023-09-19 15:41 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/java-client.md
> +MQTT Connect Java Client library provides the classes necessary to interact with the MQTT Connect.
```suggestion
MQTT Connect Java Client library provides the classes necessary to interact with MQTT Connect.
```

2023-09-19 15:41 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/java-client.md
> +Following operations are supported by the client:
```suggestion
The following operations are supported by the client:
```

2023-09-19 15:43 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/java-client.md
> +To include MQTT Connect Java Client into your project just add additional dependency inside the `<dependencies>` node.
```suggestion
To include MQTT Connect Java Client into your project just add the following additional dependency inside the `<dependencies>` node.
```

2023-09-19 15:47 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/java-client.md
> +// Build MqttPublisher and publish MqttMessage. Close the resource either with usage as below or by calling publisher.close()
```suggestion
// Build MqttPublisher and publish MqttMessage. Close the resource either by using a [try-with-resources block](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html as below or by calling publisher.close() explicitly
```

2023-09-19 15:49 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/java-client.md
> +// Build MqttPublisher and publish MqttMessage. Close the resource either with usage as below or by calling publisher.close()
```suggestion
// Build MqttPublisher and publish MqttMessage. Close the resource either by using a [try-with-resources block](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) as below or by calling publisher.close() explicitly
```

2023-09-19 15:49 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/java-client.md
> +Example usage for subscribing to messages from the MQTT Connect via WebSocket:
```suggestion
Example of subscribing to messages from the MQTT Connect via WebSocket:
```

2023-09-19 15:51 UTC, gapa-c8y requested changes
Lots of small bits, a few re-word suggestions, etc. Please argue against my suggestions as I might be wrong about them. And please re-request review when ready

2023-09-19 16:02 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +* Cooperates with Messaging Service allowing to map any MQTT binary format into {{< product-c8y-iot >}} compatible one.
Having gone though the rest of the PR now, maybe the messaging-service is a very apparent detail. However this line isn't right. The messaging-service helps provide some flexibility and reliability to MQTT Connect, but it does not provide the mapping capability. 

Maybe we want to say '_The message-service provides flexible topic based message routing, allowing addition and removal of custom message processors at at time_' (even for transitory purposes). And that it provides reliable MQTT ingress/egress.

The mapping comes into play from that flexibility, but maybe that should be on another bullet point.

2023-10-04 09:09 UTC, rohitjoshi-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +title: Overview
I would rephrase it like so:

**Replace first two points:**
- Supports publishing and subscribing arbitrary payloads on any MQTT topic. The existing topics that are defined by Cumulocity IoT are restricted. 

- Support for subscribing to the data stream from MQTT Connect and mapping them to Cumulocity IoT compatible one or routing them to a service of your choice.

-------------

Clarifications:

1> Multi-tenancy support - I would not mention this. It's assumed our platform does it.
2> Minimum traffic overhead - what does that mean?

2023-10-04 09:16 UTC, rohitjoshi-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +MQTT Connect is currently in private preview stage with very limited access, please reach out [product support](/additional-resources/contacting-support/) if you want to give it a try.
```suggestion
MQTT Connect is in final stages of development now and will be available as a private preview in 10.18. Please reach out [product support](/additional-resources/contacting-support/) if interested.
```

2023-10-04 09:26 UTC, rohitjoshi-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +utilize [Notifications 2.0 API](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Notification-2.0-API)
For now, don't mention Notification 2.0 API here. We have a Java client in place to abstract these things. How we would explain support for other language clients in TBD. If anything, they will just need to use Token API - not the entire Notifications 2.0 feature.

2023-10-04 11:48 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +| clientId               | String  | MQTT client id                               |
Changed please check now

2023-10-04 11:48 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +| messageId              | int     | MQTT message id                              |
Changes, please check it now

2023-10-04 11:48 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +| dupFlag                | boolean | MQTT duplicate flag                          |
Make sense, changed

2023-10-04 11:48 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +* Minimum traffic overhead.
This is rather about MQTT protocol in general which was designed to consume as little traffic as possible.

2023-10-04 11:48 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +*   Username and password. The MQTT username needs to include the tenant ID and username in the format &lt;tenantID/username>.
Changed.

2023-10-04 12:04 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +MQTT Connect is currently in private preview stage with very limited access, please reach out [product support](/additional-resources/contacting-support/) if you want to give it a try.
Let's not mention version as we are not 100% sure :)
Changed a little bit to remove this version info.

2023-10-04 13:02 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +title: Overview
1> Multi-tenancy support - I would not mention this. It's assumed our platform does it.
This is just a C&P from old MQTT doc, I guess it doesn't really hurt us if we leave it here.
2> Minimum traffic overhead - what does that mean?
This is rather about MQTT protocol in general which was designed to consume as little traffic as possible.

Other points changed according to the suggestion.

2023-10-04 13:08 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +MQTT Connect is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
Agree, but not really sure how to address this. In the `Requirements` chapter we already have "MQTT Connect is in final stages of development now, available as a private preview only." so your suggestion will be a duplicate of this.

Just change the "new" to "substitute"/"alternative"?

2023-10-04 14:04 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +### Architecture {#mqtt-connect-architecture}
Yeah, but this is a more general one, on my diagrams I would like to show how the message flows for different topics. I will try to reuse the arrow approach but anyway it won't be so simple ;)

2023-10-05 17:01 UTC, sagscmi requested changes
Praise: Overall this is a great first draft, and it was definitely useful & appreciated for the Hackathon (by those who bothered to read it...)

I made some specific suggestions, and proposed a few larger topics that I think should be handled in separate tickets/PRs.

Also I'm thinking we should ask Jane to review this - maybe point to the preview site and collect comments my mail/chat or in a meeting if she doesn't want to deal with the PR directly.

2023-10-09 14:38 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +microservice can push any MQTT message to the device via [Java Client](/device-integration/mqtt-connect#java-client).
The suggestion was to interleave the text descriptions between the diagrams, so each bit of text is next to the diagram(s) it relates to.

Something like:
Sending diagram
Sending text
Receiving diagram
Receiving text

We currently have: 
Sending diagram
Receiving diagram
Sending text
Receiving text

2023-10-09 14:39 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +| clientId               | String  | MQTT client id                               |
Thanks - change is good

2023-10-09 15:43 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +Knowing the topic and payload structure custom microservice can we used as a consumer which with the help of [Java Client](/device-integration/mqtt-connect#java-client),
```suggestion
A custom microservice that understands the topic and payload structure can, with the help of [Java Client](/device-integration/mqtt-connect#java-client),  
```

2023-10-09 15:43 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +consumes the MQTT messages, translates them to the {{< product-c8y-iot >}} format, and then uses the [Microservice SDK](/microservice-sdk/java) to push them into {{< product-c8y-iot >}}.
```suggestion
consume the MQTT messages, translate them to the {{< product-c8y-iot >}} format, and then use the [Microservice SDK](/microservice-sdk/java) to push them into {{< product-c8y-iot >}}.
```

2023-10-09 15:44 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +Knowing the topic and payload structure custom microservice can we used as a consumer which with the help of [Java Client](/device-integration/mqtt-connect#java-client),
Don't like the use of the word 'Knowing' here

2023-10-09 15:46 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +MQTT Connect is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
Not sure what is best either. Hopefully others might chip in with better suggestions!

2023-10-09 15:49 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +* Cooperates with Messaging Service allowing to map any MQTT binary format into {{< product-c8y-iot >}} compatible one.
This is totally outdated by subsequent changes - resolving

2023-10-09 15:55 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +* Minimum traffic overhead.
I don't think we should mention it at all. It's like saying our 'new' MQTT implementation works over TCP. There's nothing new or specific to remark on as this a quality of MQTT in general.

2023-10-09 16:02 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +* Supports publishing and subscribing arbitrary payloads on any MQTT topic. The existing topics that are defined by {{< product-c8y-iot >}} are restricted.
```suggestion
* Supports publishing and subscribing arbitrary payloads on any MQTT topic. The topics that are used by the exisging {{< product-c8y-iot >}} MQTT implementation are not permitted for use with MQTT Connect.
```

2023-10-09 16:03 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +* Supports publishing and subscribing arbitrary payloads on any MQTT topic. The existing topics that are defined by {{< product-c8y-iot >}} are restricted.
```suggestion
* Supports publishing and subscribing arbitrary payloads on any MQTT topic. The topics that are used by the existing {{< product-c8y-iot >}} MQTT implementation are not permitted for use with MQTT Connect.
```

2023-10-09 16:05 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +* Supports publishing and subscribing arbitrary payloads on any MQTT topic. The existing topics that are defined by {{< product-c8y-iot >}} are restricted.
I just wanted to clarify that they are only restricted in MQTT Connect (not restricted to existing clients and endpoints)

2023-10-09 16:34 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +MQTT Connect works together with the Messaging Service to provide as generic a solution as possible.
I was almost tempted to say things link 'any and many' and even 'hot deployment' - that's what the subscriber based message processors offer.

2023-10-09 16:37 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +The same solution can be also applied when trying to communicate with device. Knowing the MQTT client id and the topic,
```suggestion
The same solution can be also applied when trying to communicate with device. Given the MQTT client id and the topic,
```

2023-10-09 16:42 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +The table below presents a basic comparison between the standard {{< product-c8y-iot >}} MQTT functionality and that of MQTT Connect.
Can (and should) we add that MQTT Connect allows 
 - multiple processors for a topic
 - potentially hot-deployment of new processors (or upgrade of existing), for example, by adding it updating a microservice 
 
This a big (architectural) differences between MQTT Connect and existing MQTT (I'm not sure we've picked up on this in team yet)

2023-10-10 15:02 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +Knowing the topic and payload structure custom microservice can we used as a consumer which with the help of [Java Client](/device-integration/mqtt-connect#java-client),
Changes applied.

2023-10-10 15:02 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +consumes the MQTT messages, translates them to the {{< product-c8y-iot >}} format, and then uses the [Microservice SDK](/microservice-sdk/java) to push them into {{< product-c8y-iot >}}.
Done

2023-10-11 07:26 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +title: Implementation
Changed to `MQTT protocol implementation`

2023-10-11 08:33 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +MQTT Connect does not impose any topic structure. There are just a few topic names which are reserved for historic purposes and future use, such as all the [SmartREST 2.0](/smartrest/smartrest-two) r
Listing them would be cumbersome, all SmartREST related topics - `s/up`, `t/up`, `q/ul`, `s/ul`, `t/ul`, `q/ud`, `q/uc`, `t/ud`, `s/uc`, `s/ud`, `q/uat`, `t/uc`, `s/ucr`, `t/udp`, `c/ddp`, `q/dcr`, `t/dat`, `c/uat`, `t/ucr`, `q/e`, `c/dcr`, `c/dt`, `c/ds`, `t/e`, `c/dp`, `s/ddp`, `c/dl`, `q/dp`, `q/dt`, `q/ds`, `t/dt`, `s/ds`, `s/dt`, `c/dd`, `c/dc`, `t/ds`, `q/udp`, `s/dp`, `t/dp`, `q/dl`, `s/uat`, `s/dl`, `t/dl`, `q/dd`, `q/dc`, `t/dd`, `s/dd`, `s/dc`, `t/dc`, `q/dat`, `s/dcr`, `t/ddp`, `c/udp`, `s/e`, `q/ucr`, `t/uat`, `c/dat`, `t/dcr`, `c/e`, `c/ucr`, `c/ut`, `c/us`, `c/up`, `s/udp`, `c/ul`, `q/up`, `q/ut`, `q/us`, `t/ut`, `q/ddp`, `c/uc`, `c/ud`, `s/dat`, `s/ut`, `s/us`, `t/us`

I just reorganized it into a bullet list with two additional topics that I missed originally.

2023-10-11 08:35 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +The table below presents a basic comparison between the standard {{< product-c8y-iot >}} MQTT functionality and that of MQTT Connect.
Added one row with `Message processors/consumers` as this is also partially covered by `Extensibility`

2023-10-12 16:20 UTC, sagscmi approved these changes
Nice work @slc-softwareag, I'm happy to approve this.  It would be appreciated if you could create a ticket for the follow-up work that I suggested in the one comment from me that isn't resolved yet.

2023-10-13 06:58 UTC, slc-softwareag commented
> > Nice work @slc-softwareag, I'm happy to approve this. It would be appreciated if you could create a ticket for the follow-up work that I suggested in the one comment from me that isn't resolved yet.
> 
> BTW, since we can't merge this to develop yet (it needs to stay on some other branch until the Private Preview becomes a Public Preview) should we perhaps re-target this PR to a new branch (maybe something like `private-preview/mqtt-connect` or similar?), merge it there, and keep that as the target for future doc updates while we're in Private Preview mode? The link to that branch build on `surge.sh` would be shared with customers.

Good idea, target branch changed.

2023-10-13 06:58 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +MQTT Connect is in final stages of development now, available as a private preview only. Please reach out to [product support](/additional-resources/contacting-support/) if interested.
Follow up ticket: https://cumulocity.atlassian.net/browse/MTM-56141

2023-10-13 09:53 UTC, rssag requested changes

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +* Supports publishing and subscribing arbitrary payloads on any MQTT topic. The topics that are used by the existing {{< product-c8y-iot >}} MQTT implementation are not permitted for use with MQTT Co
```suggestion
* Support for publishing and subscribing arbitrary payloads on any MQTT topic. The topics that are used by the existing {{< product-c8y-iot >}} MQTT implementation are not permitted for use with MQTT Connect.
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +you to consult one of the numerous introductions in the Internet. Some references can be found on the [MQTT website](https://mqtt.org/mqtt-specification/).
```suggestion
you to consult one of the numerous introductions on the internet. Some references can be found on the [MQTT website](https://mqtt.org/mqtt-specification/).
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +### Requirements {#mqtt-connect-requirements}
```suggestion
### Requirements {#requirements}
```
should work, and makes this easier to use, as it matches the default ID

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +### Architecture {#mqtt-connect-architecture}
```suggestion
### Architecture {#architecture}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +![MQTT Connect Send](/images/mqtt-connect/mqtt-connect-send.svg)
```suggestion
![MQTT Connect send](/images/mqtt-connect/mqtt-connect-send.svg)
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +All MQTT messages coming to the MQTT Connect are forwarded to the Messaging Service, where they are persisted and waiting to be consumed.
```suggestion
All MQTT messages coming to MQTT Connect are forwarded to the Messaging Service, where they are persisted and waiting to be consumed.
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +![MQTT Connect Push](/images/mqtt-connect/mqtt-connect-push.svg)
```suggestion
![MQTT Connect push](/images/mqtt-connect/mqtt-connect-push.svg)
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +Like with the message coming from the device same solution can be also applied when trying to communicate with the device.
```suggestion
Like with the message coming from the device the same solution can be also applied when trying to communicate with the device.
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +Given the MQTT client id and the topic, a microservice can push any MQTT message to a device via [Java Client](/device-integration/mqtt-connect#java-client).
```suggestion
Given the MQTT client ID and the topic, a microservice can push any MQTT message to a device via [Java Client](/device-integration/mqtt-connect#java-client).
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +### MQTT Connect vs {{< product-c8y-iot >}} MQTT {#mqtt-vs-mqtt-connect}
```suggestion
### MQTT Connect vs {{< product-c8y-iot >}} MQTT {#mqtt-connect-vs-cumulocity-iot-mqtt}
```
@BeateRixen i'm not sure i remember the details of shortcodes within headings correctly, at least what we last came up with when we updated the IDs. is this correct?

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +| Clean session                | Start with clean session is recommended                 | Start with clean session is recommended                                           |
```suggestion
| Clean session                | Starting with clean session is recommended                 | Starting with clean session is recommended                                           |
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +### Connecting via MQTT {#mqtt-connect-connection}
```suggestion
### Connecting via MQTT {#connecting-via-mqtt}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +Client is authenticated by the server with the usage of standard username and password credentials.
```suggestion
The client is authenticated by the server with the usage of standard username and password credentials.
```
"with the usage of" could this be shortened to "via"?

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +### Topic {#mqtt-connect-topic}
```suggestion
### Topic {#topic}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +The messages stored on these subscriptions can be consumed using dedicated [Java Client](/device-integration/mqtt-connect#java-client).
```suggestion
The messages stored on these subscriptions can be consumed using a dedicated [Java Client](/device-integration/mqtt-connect#java-client).
```
not sure if "a" or "the" is better here

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +#### Topic restrictions {#mqtt-connect-topic-restrictions}
```suggestion
#### Topic restrictions {#topic-restrictions}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +Beside of that you are free to use any topic name which is compatible with [MQTT specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718106).
```suggestion
Other than that you are free to use any topic name which is compatible with the [MQTT specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718106).
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +### Payload {#mqtt-connect-payload}
```suggestion
### Payload {#payload}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +Original MQTT message is re-packed into MQTT Connect message format which beside of original payload contains additional metadata fields.
```suggestion
Original MQTT messages are re-packed into MQTT Connect message format which beside of the original payload contains additional metadata fields.
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +| payload    | byte[]       | MQTT Payload               |
```suggestion
| payload    | byte[]       | MQTT payload               |
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +| metadata   | MqttMetadata | Metadata from MQTT message |
```suggestion
| metadata   | MqttMetadata | Metadata from the MQTT message |
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +| messageId              | int     | Unique MQTT message id per client, available only with QoS 1 and 2    |
```suggestion
| messageId              | int     | Unique MQTT message ID per client, available only with QoS 1 and 2    |
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +#### Payload restrictions {#mqtt-connect-payload-restrictions}
```suggestion
#### Payload restrictions {#payload-restrictions}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +MQTT Connect doesn`t force you to use any specific payload format.
```suggestion
MQTT Connect doesn't force you to use any specific payload format. 
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +### Features {#mqtt-connect-features}
```suggestion
### Features {#features}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +#### Authentication {#mqtt-connect-authentication}
```suggestion
#### Authentication {#authentication}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +*   Username and password. The MQTT username needs to include the tenant ID and username in the format &lt;tenantID&gt;/&lt;username&gt;.
```suggestion
*   Username and password. The MQTT username must include the tenant ID and username in the format `<tenantID>/<username>`.
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +#### ClientId {#mqtt-connect-client-id}
```suggestion
#### ClientId {#client-id}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +The MQTT ClientId field identifies the connected client. ClientId may consist up to 128 alphanumeric characters.
```suggestion
The MQTT ClientId field identifies the connected client. ClientId may consist of up to 128 alphanumeric characters.
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +Each client connecting to the MQTT Connect must have a unique client identifier, connecting a second client with the same identifier will result in the previous client`s disconnection.
```suggestion
Each client connecting to MQTT Connect must have a unique client identifier, connecting a second client with the same identifier will result in the previous client's disconnection.
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +#### Quality of Service (QoS) {#mqtt-connect-qos}
```suggestion
#### Quality of Service (QoS) {#quality-of-service-qos}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +The {{< product-c8y-iot >}} implementation supports 2 levels of MQTT QoS:
```suggestion
The {{< product-c8y-iot >}} implementation supports two levels of MQTT QoS:
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +    - The client should re-send the message if there was no ack from the server.
```suggestion
    - The client should re-send the message if there was no acknowledgement from the server.
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +    - Guaranteed that subscribers will receive a message that was acknowledged by the server.
```suggestion
    - It is guaranteed that subscribers will receive a message that was acknowledged by the server.
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +For subscriptions, we will deliver all messages in the QoS that the client defined when subscribing to the topic.
who is "we"?
Cumulocity IoT? MQTT Connect?

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +#### Clean session {#mqtt-connect-clean-session}
```suggestion
#### Clean session {#clean-session}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +#### Retained flag {#mqtt-connect-retained-flag}
```suggestion
#### Retained flag {#retained-flag}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +the server response `CONNACK` message will contain the `0x05` return code.
```suggestion
the server response `CONNACK` message contains the `0x05` return code.
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/java-client.md
> +To include MQTT Connect Java Client into your project just add the following additional dependency inside the `<dependencies>` node.
```suggestion
To include MQTT Connect Java Client into your project, add the following dependency inside the `<dependencies>` node:
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/java-client.md
> +#### Example {#mqtt-connect-client-java-example}
```suggestion
#### Example {#example}
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/faq.md
> +A: MQTT Connect doesn't support device bootstrap process yet. Please follow [Integration life cycle](/device-integration/mqtt/#integration-life-cycle)
```suggestion
A: MQTT Connect doesn't support a device bootstrap process yet. Instead, follow [Integration life cycle](/device-integration/mqtt/#integration-life-cycle)
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/faq.md
> +Q: Does the MQTT Connect support SmartREST 2.0 protocol?<br/>
```suggestion
Q: Does MQTT Connect support the SmartREST 2.0 protocol?<br/>
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/faq.md
> +Q: Why MQTT Connect doesn't use standard MQTT ports 1883 and 8883?<br/>
```suggestion
Q: Why doesn't MQTT Connect use standard MQTT ports 1883 and 8883?<br/>
```

2023-10-13 09:53 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/faq.md
> +A: Those ports are already used by {{< product-c8y-iot >}} MQTT, as both endpoints are working together MQTT Connect must use different ports.
```suggestion
A: Those ports are already used by {{< product-c8y-iot >}} MQTT. Because, both endpoints are working together MQTT Connect must use different ports.
```

2023-10-13 10:22 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +Client is authenticated by the server with the usage of standard username and password credentials.
Yes, we can change this. I will do this directly in the suggestion.

2023-10-13 10:22 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +The messages stored on these subscriptions can be consumed using dedicated [Java Client](/device-integration/mqtt-connect#java-client).
Not sure either, but "a" sounds better to me ;)

2023-10-13 10:22 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +For subscriptions, we will deliver all messages in the QoS that the client defined when subscribing to the topic.
```suggestion
For subscriptions, MQTT Connect will deliver all messages in the QoS that the client defined when subscribing to the topic.
```

2023-10-13 10:22 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +For subscriptions, we will deliver all messages in the QoS that the client defined when subscribing to the topic.
we == MQTT Connect
Replaced.

2023-10-13 10:22 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +### Requirements {#mqtt-connect-requirements}
Thanks, I wasn't really sure if has to be global unique.

2023-10-13 12:01 UTC, rssag approved these changes

2023-10-16 09:35 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +
```suggestion

{{< c8y-admon-preview >}}
The feature is in preview mode, that is, it is not enabled by default and may be subject to change.
{{< /c8y-admon-preview >}}

```

2023-10-17 11:09 UTC, slc-softwareag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +
@rssag we have the follow-up story for this https://cumulocity.atlassian.net/browse/MTM-56141
I would like to close this PR and do this in scope of MTM-56141

2023-10-17 12:41 UTC, rssag commented on content/device-integration/mqtt-connect-bundle/overview.md
> +
oh, sure!

2023-10-17 13:30 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +you to consult one of the numerous introductions in the Internet. Some references can be found on the [MQTT website](https://mqtt.org/mqtt-specification/).
... just Googled this. Apparently attitudes have changed. There are no longer (many) internets - they're intranets. 

https://en.wikipedia.org/wiki/Capitalization_of_Internet

2023-10-17 13:52 UTC, gapa-c8y approved these changes
Some further minor changes that are suggestions only - one formatting error (please fix that at least)

2023-10-17 13:52 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +All MQTT messages coming to MQTT Connect are forwarded to the Messaging Service, where they are persisted and waiting to be consumed.
```suggestion
All MQTT messages coming to MQTT Connect are forwarded to the Messaging Service, where they are persisted, waiting to be consumed.
```

2023-10-17 13:52 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +All MQTT messages coming to MQTT Connect are forwarded to the Messaging Service, where they are persisted and waiting to be consumed.
suggestion: I'd prefer _either_ the above suggestion, '...persisted, waiting to be consumed' or '... persisted and wait to be consumed'.

2023-10-17 13:52 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/overview.md
> +A custom microservice that understands the topic and payload structure can, with the help of [Java Client](/device-integration/mqtt-connect#java-client),
There are about 4 blank spaces after JavaClient link. This (anymore than one blank space) causes a newline that is out of place here.
```suggestion
A custom microservice that understands the topic and payload structure can, with the help of [Java Client](/device-integration/mqtt-connect#java-client), 
```

2023-10-17 13:52 UTC, gapa-c8y commented on content/device-integration/mqtt-connect-bundle/implementation.md
> +Original MQTT messages are re-packed into MQTT Connect message format which beside of the original payload contains additional metadata fields.
```suggestion
The original MQTT messages are re-packed into MQTT Connect message format which includes the original payload and additional metadata fields.
```

2023-10-18 07:06 UTC, merged