DM-2528 - LWM2M X.509 documentation
SoftwareAG/c8y-docs pull request #1420
Opened 2023-09-12 15:06 UTC by jakubsobolewskisag

Documentation for X.509 LWM2M changes

2023-09-13 13:22 UTC, Oezge-Akin approved these changes

2023-09-14 11:12 UTC, rssag requested changes

2023-09-14 11:12 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align:left">Determines the type of connection used by the LWM2M device when it connects to {{< product-c8y-iot >}} LWM2M server. Possible values are: "NO_SEC", "PSK" and "X509".</td>
```suggestion
<td style="text-align:left">Determines the type of connection used by the LWM2M device when it connects to the {{< product-c8y-iot >}} LWM2M server. Possible values are: "NO_SEC", "PSK" and "X509".</td>
```

2023-09-14 11:12 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align:left">Determines the type of connection used by the LWM2M device when it connects to {{< product-c8y-iot >}} LWM2M bootstrap server. Possible values are: "NO_SEC", "PSK", "PSK_G
```suggestion
<td style="text-align:left">Determines the type of connection used by the LWM2M device when it connects to the {{< product-c8y-iot >}} LWM2M bootstrap server. Possible values are: "NO_SEC", "PSK", "PSK_GENERATED" and "X509".</td>
```

2023-09-14 11:12 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align: left">X.509 device certificate (in PEM format) written to device during bootstrap phase. Empty value means that it won't be written at all.</td>
```suggestion
<td style="text-align: left">X.509 device certificate (in PEM format) written to the device during bootstrap phase. An empty value means that it isn't written at all.</td>
```

2023-09-14 11:12 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align: left">X.509 device private key (in PEM format) written to device during bootstrap phase. Empty value means that it won't be written at all.</td>
```suggestion
<td style="text-align: left">X.509 device private key (in PEM format) written to the device during bootstrap phase. An empty value means that it isn't written at all.</td>
```

2023-09-14 11:12 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align: left">LWM2M Certificate Usage written to device during bootstrap phase. Empty value means that it won't be written at all. One of: <ul><li>CA_CONSTRAINT</li> <li>SERVICE_CERTIF
```suggestion
<td style="text-align: left">LWM2M Certificate usage written to the device during bootstrap phase. An empty value means that it isn't written at all. One of: <ul><li>CA_CONSTRAINT</li> <li>SERVICE_CERTIFICATE_CONSTRAINT</li> <li>TRUST_ANCHOR_ASSERTION</li> <li>DOMAIN_ISSUER_CERTIFICATE</li></ul></td>
```

2023-09-14 11:12 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align: left">Name of the server certificate to write to device during bootstrap phase. Server certificates are preconfigured in "management" tenant. Empty value means that it won't be
```suggestion
<td style="text-align: left">Name of the server certificate written to the device during bootstrap phase. Server certificates are preconfigured in the {{< management-tenant >}}. An empty value means that it isn't written at all.</td>
```

2023-09-14 11:38 UTC, Oezge-Akin commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +#### Advanced settings {#lwm2m-device-registration-advanced}
In advanced settings table, these ones needs to be updated:

- "Use common timestamp resources 5518 and 6050 or object specific timestamp for object 6 reported by the device if available" -> Use source timestamp
- "Device protocol serialization format" -> Serialization format

2023-09-14 11:55 UTC, jakubsobolewskisag commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +#### Device settings {#lwm2m-device-registration-device}
"device-settings" seems too generic. I was afraid that it may be used in other parts of documentation. I'm not sure how the links/hooks are generated so I went with something safe/unique.

2023-09-14 12:01 UTC, jakubsobolewskisag commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +#### Advanced settings {#lwm2m-device-registration-advanced}
done

2023-09-15 09:01 UTC, rssag reviewed
we discussed the IDs team-internally - while it's not wrong to use IDs that differ from the actual headings, it doesn't create a problem here and using the exact ID that matches the heading makes it a bit easier to maintain the documentation in the long run (the link ID can be inferred from the heading text).

i hope i got all the references to the headings in my suggestions :)

2023-09-18 16:05 UTC, Oezge-Akin approved these changes

2023-09-19 07:54 UTC, rssag approved these changes

2023-09-19 07:55 UTC, rssag commented
what are the target versions?

2023-09-20 09:38 UTC, bggov approved these changes

2023-10-12 08:59 UTC, merged

2023-10-12 13:05 UTC, rssag commented
reverted this PR, and created a new PR here, so we can merge when the feature is actually ready:
https://github.com/SoftwareAG/c8y-docs/pull/1481