COE-513: OEE release notes
SoftwareAG/c8y-docs pull request #144
Opened 2021-12-20 18:23 UTC by mvoigt-sag

2022-01-19 09:58 UTC, BeateRixen commented
@mvoigt-sag @thomaswinkler I did the language review and edits directly in the source file. Please note that these release notes might not be sufficient for some customers. We usually provide much more infos for each entry, at least always describing the context, the change and the impact for the user. Compare also https://docs.google.com/document/d/1SnU3xMFhBbAebr7r6oxtLjx9NY9WFCoytyESV2xyQw8/edit

2022-01-19 09:59 UTC, BeateRixen approved these changes

2022-01-19 10:28 UTC, haraldmeyer commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Only 1 measurement with 20 fragments per calculation interval will be stored now instead of 20 measurements. This reduces the number of MEAs created by the OEE app signifi
OEE app -> Cumulocity IOT OEE App

2022-01-19 10:29 UTC, haraldmeyer commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Deactivated the CSV handler.</td>
Do we need  to mention this here? It was not accessible anyway.

2022-01-19 10:30 UTC, haraldmeyer requested changes
Two minor comments.

2022-01-20 06:30 UTC, thomaswinkler commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Deactivated the CSV handler.</td>
Agree. Will remove it.

2022-01-26 10:37 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Only 1 measurement with 20 fragments per calculation interval will be stored now instead of 20 measurements. This reduces the number of MEAs created by the OEE app signifi
Implemented the fix

2022-01-31 11:52 UTC, thomaswinkler commented
@BeateRixen @MWindel @mvoigt-sag @haraldmeyer 

Pushed a new changed going over the release notes again to provide more information as requested.

2022-01-31 11:53 UTC, thomaswinkler commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Deactivated the CSV handler.</td>
Removed.

2022-02-02 13:23 UTC, haraldmeyer commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">The Availability is now always calculated at the end of each interval without relying on status change events, such as machine up or down events. Depending on the status c
@thomaswinkler This is not strictly correct. The trigger is still an MEA from the formula that arrives after the interval has ended to trigger a recalculation.

2022-02-02 13:25 UTC, haraldmeyer commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +</td>
@thomaswinkler Will old data that is spread across multiple measurements still be shown in the OEE App? I think we should mention this.

2022-02-02 13:27 UTC, haraldmeyer commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">The accuracy and rounding of Quality calculation has been fixed. Even for an expected Quality of 100.0, the calculated Quality value might have slighlty deviated. The Qual
Spelling error in "slightly". Also to make more clear: "In the past, the calculated Quality value might have slightly deviated from the expected value causing a Quality value in excess of 100.0. and an OEECalculationAlarm"

2022-02-02 13:28 UTC, haraldmeyer requested changes
See detailed comments.

2022-02-03 07:36 UTC, mvoigt-sag commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +</td>
@thomaswinkler I think the compatibility with old data (i.e. 20 measurements) is the reason why we didnt optimize the UI code (yet) - as we discussed yesterday. If we'd change the REST requests in oee-ui, you wouldnt see the OEE measurements that were created before the fix. I think this change in oee-ui should be handled in Fix4 or later.

2022-02-03 10:00 UTC, mvoigt-sag commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Enabled custom tenant UI branding. OEE App now automatically uses the tenants Branding configuration to enable customization of colors, fonts, logos etc. For more informat
Maybe the link to the doc is missing here to replace the trailing three dots?

2022-02-03 10:02 UTC, mvoigt-sag commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">When creating a new OEE calculation profile, a list of existing calculation profiles is presented to optionally choose copy an existing configuration into the new calculat
```suggestion
<td style="text-align:left">When creating a new OEE calculation profile, a list of existing calculation profiles is presented to optionally choose to copy an existing configuration into the new calculation profile. An issue has been fixed causing the list of existing calculation profiles to not show in some situations.</td>
```

2022-02-03 10:05 UTC, mvoigt-sag commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">The accuracy and rounding of Quality calculation has been fixed. Even for an expected Quality of 100.0, the calculated Quality value might have slighlty deviated. The Qual
```suggestion
<td style="text-align:left">The accuracy and rounding of Quality calculation has been fixed. Even for an expected Quality of 100.0, the calculated Quality value might have slighlty deviated. The Quality calculation has been fixed and no more Quality accuracy related OEECalculationAlarms will be triggered for the calculated interval.
```

2022-02-03 10:06 UTC, mvoigt-sag commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Improved and optimized logging of HttpErrors logged by the GeneralErrorHandler in logs of oee-apama microservice.</td>
```suggestion
<td style="text-align:left">Improved and optimized logging of HttpErrors logged by the GeneralErrorHandler in logs of apama-oeeapp microservice.</td>
```

2022-02-09 15:59 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">The accuracy and rounding of Quality calculation has been fixed. Even for an expected Quality of 100.0, the calculated Quality value might have slighlty deviated. The Qual
I implemented the changes

2022-02-09 16:12 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Enabled custom tenant UI branding. OEE App now automatically uses the tenants Branding configuration to enable customization of colors, fonts, logos etc. For more informat
Done

2022-02-11 07:45 UTC, haraldmeyer commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">The Availability is now always calculated at the end of each interval without relying on status change events, such as machine up or down events. Depending on the status c
@MWindel "The availability is now always calculated upon the arrival of the next MEA after the end of each interval without relying on a status change, such as machine goes down, happening. Depending on the status changes detected for machines, it was possible to not see any OEE being calculated for long periods of time."

2022-02-11 07:48 UTC, haraldmeyer commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +</td>
@MWindel I suggest to add one sentence at the end: "The updated OEE App is backwards-compatible and will also show data stored in separate measurements as it was stored before the change."

2022-02-11 09:45 UTC, thomaswinkler commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">The Availability is now always calculated at the end of each interval without relying on status change events, such as machine up or down events. Depending on the status c
Did push changes trying to address @haraldmeyer comment.

2022-02-11 09:45 UTC, thomaswinkler commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +</td>
Did push changes trying to address comments.

2022-02-11 10:17 UTC, mvoigt-sag commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +</td>
@thomaswinkler sounds good to me!

2022-02-11 15:45 UTC, MWindel commented
@haraldmeyer For this PR to be merged, you need to remove your "request for changes". If the content is good, please approve, so this PR can be merged.

2022-02-11 16:31 UTC, thomaswinkler approved these changes

2022-02-14 09:29 UTC, BeateRixen commented
@thomaswinkler @haraldmeyer I assume that this can finally be merged?

2022-02-14 16:23 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Enabled custom tenant UI branding. OEE App now automatically uses the tenants Branding configuration to enable customization of colors, fonts, logos etc. For more informat
the tenants Branding configuration  > the tenant´s branding configuration 
remove one instance of "for more information"

2022-02-14 16:23 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<a href="/users-guide/enterprise-tenant/#branding">Enterprise tenant > Customizing your platform > Branding</a> in the <i>User guide </i> for more information.
<i>User guide </i> > <i>User guide</i>

2022-02-14 16:24 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">In Safari browsers, the gauge charts in OEE status of machine dashboards and Andon boards have been fixed to render correctly.</td>
in OEE status > in the OEE status

2022-02-14 16:24 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Gauge charts in OEE status of machine dashboards and Andon boards have been fixed to render correctly for values greater than 100.</td>
in OEE status > in the OEE status

2022-02-14 16:25 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">The OEE targets in the overview do show trend arrows next to the OEE value indicating if the OEE trend is going up or down. An issue has been fixed breaking the correct ca
do show > show

2022-02-14 16:29 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">The accuracy and rounding of Quality calculation has been fixed. Even for an expected Quality of 100.0, the calculated Quality value might have slightly deviated. In the p
Quality calculation > the Quality calculation 
@MWindel I can´t remember if we decided to have lowercase with "Quality"?
add full stop at the end

2022-02-14 16:30 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Improved and optimized logging of HttpErrors logged by the GeneralErrorHandler in logs of apama-oeeapp microservice.</td>
in logs of apama-oeeapp microservice > in logs of the apama-oeeapp microservice

2022-02-14 16:31 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Improve and fixed REST API documentation for oee-bundle microservice. Documentation is now available as OpenAPI at <a href="https://cumulocity.com/oee/api/10.10.0/">https:
Improve > Improved
REST API documentation for oee-bundle microservice > the REST API documentation for the oee-bundle microservice

2022-02-14 16:32 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Fix and improve performance and scalability of microservices. Main fixes are related to the oee-bundle microservice.</td>
Fix and improve performance> Fixed and improved the performance
Main fixes > The main fixes

2022-02-14 16:35 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">OEE App is sending OEERestartInformation alarms when the calculation is started or stopped. An issue has been fixed sending OEERestartInformation alarms also when creating
OEE App > The OEE App

2022-02-14 16:37 UTC, BeateRixen commented
@MWindel I added a number of language related comments, please check.

2022-02-16 11:28 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +This release of Cumulocity IoT OEE App fixes important calculation issues and brings a set of UI improvements and enhancements for icons, dashboards, charts and profile editor.
Done

2022-02-16 11:29 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +Important, all OEE values and parameters calculated per calculation interval are now stored as fragments in 1 single measurement instead of 20 measurements. With this change, the number of measuremen
I formatted it as an **Important** note.

2022-02-16 11:30 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Enabled custom tenant UI branding. OEE App now automatically uses the tenants Branding configuration to enable customization of colors, fonts, logos etc. For more informat
Done

2022-02-16 11:31 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<a href="/users-guide/enterprise-tenant/#branding">Enterprise tenant > Customizing your platform > Branding</a> in the <i>User guide </i> for more information.
@BeateRixen What does this comment refer to exactly?

2022-02-16 11:31 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">OEE App is sending OEERestartInformation alarms when the calculation is started or stopped. An issue has been fixed sending OEERestartInformation alarms also when creating
Done

2022-02-16 11:32 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">In Safari browsers, the gauge charts in OEE status of machine dashboards and Andon boards have been fixed to render correctly.</td>
Done

2022-02-16 11:33 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Gauge charts in OEE status of machine dashboards and Andon boards have been fixed to render correctly for values greater than 100.</td>
Done

2022-02-16 11:34 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">The OEE targets in the overview do show trend arrows next to the OEE value indicating if the OEE trend is going up or down. An issue has been fixed breaking the correct ca
Done

2022-02-16 11:39 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Improved and optimized logging of HttpErrors logged by the GeneralErrorHandler in logs of apama-oeeapp microservice.</td>
Done

2022-02-16 11:40 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Improve and fixed REST API documentation for oee-bundle microservice. Documentation is now available as OpenAPI at <a href="https://cumulocity.com/oee/api/10.10.0/">https:
Done

2022-02-16 11:41 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Fix REST API error handling and error messages. Error responses might have contained not required information or could have used different formats.
Done

2022-02-16 13:10 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<a href="/users-guide/enterprise-tenant/#branding">Enterprise tenant > Customizing your platform > Branding</a> in the <i>User guide </i> for more information.
There is an empty space before the bracket, sorry, didn´t relaize that this gets reformatted in the comment:
"User guide </" > "User guide<"

2022-02-16 13:10 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<a href="/users-guide/enterprise-tenant/#branding">Enterprise tenant > Customizing your platform > Branding</a> in the <i>User guide </i> for more information.
There is an empty space before the bracket, sorry, didn´t relaize that this gets reformatted in the comment:
"User guide </" > "User guide<"

2022-02-16 13:50 UTC, rssag commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Store only 1 measurement with <code>type="OEEMeasurements"</code> including all calculated OEE values and parameters as separate fragments for each calculation interval. T
i'd say "1" is fine in this case

2022-02-16 14:21 UTC, BeateRixen commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Store only 1 measurement with <code>type="OEEMeasurements"</code> including all calculated OEE values and parameters as separate fragments for each calculation interval. T
Ok, then let´s leave it as is.

2022-02-16 14:24 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<a href="/users-guide/enterprise-tenant/#branding">Enterprise tenant > Customizing your platform > Branding</a> in the <i>User guide </i> for more information.
Done

2022-02-16 14:28 UTC, MWindel commented on content/release-10-10-0/oee-10-10-0-bundle/10_10_0_1.md
> +<td style="text-align:left">Fix and improve performance and scalability of microservices. Main fixes are related to the oee-bundle microservice.</td>
Done

2022-02-16 15:21 UTC, merged