[DTM] Asset location
SoftwareAG/c8y-docs pull request #1450
Opened 2023-09-25 04:46 UTC by Vagdevi1998

Document asset location feature details and also bulk import failure changes.

2023-09-25 07:53 UTC, lra-sag requested changes

2023-09-25 07:53 UTC, lra-sag commented on content/dtm/default-properties.md
> +
Add a brief summary of use of this property
```suggestion
Location property enables you to assign location (latitude and longitude) to an asset.

You can set the default values of latitude and longitude by entering corresponding values or alternatively using the map view.
```

2023-09-25 07:53 UTC, lra-sag commented on content/dtm/default-properties.md
> +The marker is positioned at D&uuml;sseldorf, Germany by default. Click or drag the marker to the preferred position to select the default value for latitude and longitude. The marker on the map is po
```suggestion
The marker is positioned at D&uuml;sseldorf, Germany by default. Click or drag the marker to the preferred position to select the default value for latitude and longitude. To close the map view, click **Close** above the map.

Note that the marker on the map is positioned at an approximated location when either latitude or longitude value is missing.
```

2023-09-27 04:52 UTC, Vagdevi1998 commented on content/dtm/default-properties.md
Added it as a separate section in asset properties

2023-09-27 04:53 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/creating-assets-bulk-import.md
> +In case of bulk operation failure, the entire operation is rolled back and user will be navigated to main assets page to cleanup the entities created and try the operation again.
Moved this to creating-assets-UI file

2023-09-27 04:53 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +For an asset with a location property click **Choose on Map** in the section to set the values for latitude and longitude using map view. Click the full screen icon at the top right corner of the map
Modified

2023-09-27 04:53 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The marker is positioned at the default value set in the location property. If no defualt value is set,the marker is positioned at D&uuml;sseldorf, Germany. Click or drag the marker to the preferred
Modified

2023-09-27 04:54 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +Default properties are available once you login into the tenant. See [Default properties](/dtm/default-properties/#characteristics-of-default-properties) to know the list of properties that are avail
Modified

2023-09-27 04:54 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +Default properties are not listed under Export asset properties. See [Default properties](/dtm/default-properties/#characteristics-of-default-properties) to know the list of properties that are avail
Modified

2023-09-27 04:54 UTC, Vagdevi1998 commented on content/dtm/default-properties.md
> +### Characteristics of default properties {#characteristics-of-default-properties}
Modified

2023-09-27 04:54 UTC, Vagdevi1998 commented on content/dtm/default-properties.md
> +Default properties cannot be deleted. All the fields are not accessible for default properties, and this accessibility may vary depending on the specific property.
Modified

2023-09-27 04:54 UTC, Vagdevi1998 commented on content/dtm/default-properties.md
> +
Added

2023-09-27 04:54 UTC, Vagdevi1998 commented on content/dtm/default-properties.md
> +The marker is positioned at D&uuml;sseldorf, Germany by default. Click or drag the marker to the preferred position to select the default value for latitude and longitude. The marker on the map is po
Modified

2023-09-29 09:27 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The marker is positioned at the default value set in the location property. If no default value is set, the marker is positioned at D&uuml;sseldorf, Germany. Click or drag the marker to the preferred
```suggestion
The marker is positioned at the default value set in the **Location** property. If no default value is set, the marker is positioned at Duesseldorf, Germany. Click or drag the marker to the preferred position to set the value for both latitude and longitude. The marker on the map is positioned at an approximated location when either the latitude or the longitude value is missing.
```

2023-09-29 09:27 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +For an asset with a location property, click **Choose on Map** in the section to set the values for latitude and longitude using map view. Click the full screen icon at the top right corner of the ma
```suggestion
For an asset with a **Location** property, click **Choose on Map** in the section to set the values for the latitude and longitude using map view. Click the full screen icon at the top right corner of the map to view it in full screen.
```

2023-09-29 09:27 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The values of latitude and longitude are automatically updated whenever a new location is selected on the map and vice-versa. The Altitude value is not represented on the map.<br>
```suggestion
The values of latitude and longitude are automatically updated whenever a new location is selected on the map and vice-versa. The altitude value is not represented on the map.<br>
```

2023-09-29 09:27 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/viewing-assets.md
> +For an asset with a location, Click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the m
```suggestion
For an asset with a location, click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the map to enter full screen mode.```

2023-09-29 09:27 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-properties.md
> +Location property enables you to assign location (latitude and longitude) to an asset. You can set the default values of latitude and longitude by entering corresponding values or alternatively using
```suggestion
The **Location** property enables you to assign location (latitude and longitude) to an asset. You can set the default values of the latitude and longitude by entering the corresponding values or alternatively using the map view.
```

2023-09-29 09:27 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-properties.md
> +To set the default values for latitude and longitude using map view, click **Choose on Map** at the end of the section. Click the full screen icon at the top right corner of the map to view it in ful
```suggestion
To set the default values for the latitude and longitude using the map view, click **Choose on Map** at the end of the section. Click the full screen icon at the top right corner of the map to view it in full screen. The marker is positioned at Duesseldorf, Germany by default. Click or drag the marker to the preferred position to select the default value for latitude and longitude.
```

2023-09-29 09:27 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-properties.md
> +The valid range for Latitude is -90 to +90 and valid range for Longitude is -180 to +180. <br>
```suggestion
The valid range for the latitude is -90 to +90 and valid range for the longitude is -180 to +180. <br>
```

2023-09-29 09:27 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-properties.md
> +The marker on the map is positioned at an approximated location when either latitude or longitude value is missing.<br>
```suggestion
The marker on the map is positioned at an approximated location when either the latitude or longitude value is missing.<br>
```

2023-09-29 09:27 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-properties.md
> +The default values of latitude and longitude are automatically updated whenever a new location is selected on the map and vice-versa. The Altitude value is not represented on the map.
```suggestion
The default values of both latitude and longitude are automatically updated whenever a new location is selected on the map and vice-versa. The Altitude value is not represented on the map.
```

2023-10-12 04:35 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +The default values of latitude and longitude are automatically updated whenever a new location is selected on the map and vice-versa. The Altitude value is not represented on the map.
Modified

2023-10-12 04:35 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +The marker on the map is positioned at an approximated location when either latitude or longitude value is missing.<br>
Modified

2023-10-12 04:35 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +The valid range for Latitude is -90 to +90 and valid range for Longitude is -180 to +180. <br>
Modified

2023-10-12 04:36 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +To set the default values for latitude and longitude using map view, click **Choose on Map** at the end of the section. Click the full screen icon at the top right corner of the map to view it in ful
@MWindel is it not necessary to add Umlaut for Duesseldorf?

2023-10-12 04:36 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +Location property enables you to assign location (latitude and longitude) to an asset. You can set the default values of latitude and longitude by entering corresponding values or alternatively using
Modified

2023-10-12 04:36 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +5. Alternatively, Click **Back** to go to previous step. Hover over the file name and click the **Delete** icon to remove the current file and upload a different one.
Modified

2023-10-12 04:37 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +Default properties are not listed under Export asset properties. See [Default properties](/dtm/default-properties/#characteristics-of-default-properties) to view the list of properties available.
Formatted Export asset properties button to bold

2023-10-12 04:37 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/viewing-assets.md
> +For an asset with a location, Click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the m
Modified

2023-10-12 04:37 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +In case of bulk operation failure, the entire operation is rolled back and user will be navigated to main assets page to cleanup the entities created and try the operation again.
Modified

2023-10-12 04:37 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The values of latitude and longitude are automatically updated whenever a new location is selected on the map and vice-versa. The Altitude value is not represented on the map.<br>
Modified

2023-10-12 04:37 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +For an asset with a location property, click **Choose on Map** in the section to set the values for latitude and longitude using map view. Click the full screen icon at the top right corner of the ma
Modified

2023-10-12 04:37 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The marker is positioned at the default value set in the location property. If no default value is set, the marker is positioned at D&uuml;sseldorf, Germany. Click or drag the marker to the preferred
@MWindel  is it necessary to add Umlaut for Duesseldorf?

2023-10-12 08:48 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-properties.md
> +The valid range for the latitude is -90 to +90 and valid range for the longitude is -180 to +180. <br>
```suggestion
The valid range for the latitude is -90° to +90° and valid range for the longitude is -180° to +180°. <br>
```

2023-10-12 08:48 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-models.md
> +5. Alternatively, click **Back** to go to previous step. Hover over the file name and click the **Delete** icon to remove the current file and upload a different one.
@Vagdevi1998 could you provide a screenshot of this step?

2023-10-12 08:48 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/viewing-assets.md
> +For an asset with a location, click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the m
```suggestion
For an asset with a location, click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the map to enter full screen mode.
```

2023-10-17 11:15 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The marker is positioned at the default value set in the location property. If no default value is set, the marker is positioned at D&uuml;sseldorf, Germany. Click or drag the marker to the preferred
@Vagdevi1998 If you spell it "ue" is it fine.

2023-10-18 06:37 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +The valid range for the latitude is -90 to +90 and valid range for the longitude is -180 to +180. <br>
Latitude and Longitude are fields which accepts both negative and position numbers within that range. 
@MWindel Should I still modify that

2023-10-18 09:10 UTC, lra-sag approved these changes

2023-10-18 09:48 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-models.md
> +5. Alternatively, click **Back** to go to previous step. Hover over the file name and click the **Delete** icon to remove the current file and upload a different one.
It is already there.

2023-10-25 12:56 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-models.md
> +5. Alternatively, click **Back** to go to previous step. Hover over the file name and click the **Delete** icon to remove the current file and upload a different one.
```suggestion
5. Alternatively, click **Back** to go to previous step. Hover over the file name and click the remove icon to remove the current file and upload a different one.
```

2023-10-26 09:17 UTC, MWindel approved these changes

2023-11-02 06:01 UTC, merged