[MTM-55237] Export time ranges - LAST_24H, LAST_7DAYS, LAST_30DAYS
SoftwareAG/c8y-docs pull request #1456
Opened 2023-09-29 14:56 UTC by pawelkowalczyksag

Its a bit extensive, maybe would be better to have just examples.

2023-10-02 07:57 UTC, Airdroplet commented on content/cockpit/managing-exports.md
> +  - Example: from 2020-12-02 12:34:56 to 2021-01-01 12:34:56 (when export done at 2021-01-01 12:34:56)
Maybe would be good to move description of  those options with numbers in names above all other options?

Like in order: 
24
7
30
week
month
year
custom

2023-10-02 14:18 UTC, Airdroplet approved these changes

2023-10-03 07:28 UTC, rssag requested changes

2023-10-03 07:28 UTC, rssag commented on content/cockpit/managing-exports.md
> +  - From: exactly 24 hours before the time of Export
"export" should be lowercase. multiple occurrences

2023-10-03 07:28 UTC, rssag commented on content/cockpit/managing-exports.md
> +  - Example: from 2020-12-31 12:34:56 to 2021-01-01 12:34:56 (when export done at 2021-01-01 12:34:56)
```suggestion
  - Example: from 2020-12-31 12:34:56 to 2021-01-01 12:34:56 (when the export is done at 2021-01-01 12:34:56)
```
also multiple occurrences

2023-10-03 07:28 UTC, rssag commented on content/cockpit/managing-exports.md
> +  - From: date and time user specified
```suggestion
  - From: date and time specified by the user
```
also below

2023-10-03 08:03 UTC, pawelkowalczyksag commented on content/cockpit/managing-exports.md
> +  - From: exactly 24 hours before the time of Export
Honestly I thought "Export" as a name of the feature should be uppercase. But sure

2023-10-03 08:08 UTC, pawelkowalczyksag commented
@rssag hope its okay now

2023-10-03 08:49 UTC, rssag approved these changes

2023-10-03 08:49 UTC, rssag commented
what are the target versions?

2023-10-03 09:15 UTC, pawelkowalczyksag commented
> what are the target versions?

I do not know yet know but probably only newest. I was asked by customer to backport but they requested outdated version so... :D

2023-10-03 13:14 UTC, pawel-rynarzewski-sag approved these changes

2023-10-03 14:41 UTC, kaczynskid-sag approved these changes

2023-10-03 20:35 UTC, jkot-softwareag approved these changes

2023-10-12 09:00 UTC, merged