MTM-53267 improve microservice scope documentation
SoftwareAG/c8y-docs pull request #1509
Opened 2023-10-26 17:30 UTC by AleksanderFiszSoftwareag

2023-10-27 08:54 UTC, BeateRixen commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +By default autowiring will use tenant scoped beans:
```suggestion
By default, auto-wiring uses tenant-scoped beans:
```

2023-10-27 08:54 UTC, BeateRixen commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +We can inject `@UserScope` version of this Api using `@Qualifier("userEventApi")` each Api bean has name composing of `user` and name of the api in this case `EventApi` in code it will be:
```suggestion
We can inject the `@UserScope` version of this API using `@Qualifier("userEventApi")`. The name for each API bean is composed of `user` and the name of the API, in this case `EventApi`. In the code it will look like the following:
```

2023-10-27 08:54 UTC, BeateRixen commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +Scope of the bean can be overridden by using ContextService for user `ContextService<UserCredentials>` and for tenant `ContextService<MicroserviceCredentials`. By using those ContextServices we can u
```suggestion
The scope of the bean can be overridden by using `ContextService<UserCredentials>` for the user and `ContextService<MicroserviceCredentials` for the tenant. By using these ContextServices we can use the service user credentials like in the `@TenantScope` bean with user credentials or use the service user credentials in `@UserScope`, for example:
```

2023-10-27 08:54 UTC, BeateRixen commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +In the next example we have two methods. First one will use user credentials to call `EventApi`. Second uses service user credentials.
```suggestion
The next example shows two methods. The first one uses user credentials to call `EventApi`. The second one uses service user credentials.
```

2023-10-27 08:57 UTC, BeateRixen commented
@AleksanderFiszSoftwareag You cannot backlog from develop into the release branches. You must create a second PR branched from the 10.18 release branch and backport from there, as the documentation structure has entirely changed in develop. Please wait until this PR is approved.

2023-10-27 09:02 UTC, rssag commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +This function will get events using current user credentials.
```suggestion
This function retrieves events using the current user credentials.
```

2023-10-29 10:00 UTC, kaczynskid-sag requested changes
Unfortunately this is nowhere near of a proper description of Microservice SDK features mentioned at this page. There are still multiple errors on this page that are very misleading, confusing ant out right just wrong. This whole page needs re-thinking and a re-write of at least few sub-sections. We should also do it together with Microservice Hosting team to improve their understanding of those concepts, as they recently took over responsibility for it and documentation in it's current state only makes it harder to understand.

2023-10-30 10:17 UTC, BeateRixen commented
> Unfortunately this is nowhere near of a proper description of Microservice SDK features mentioned at this page. There are still multiple errors on this page that are very misleading, confusing ant out right just wrong. This whole page needs re-thinking and a re-write of at least few sub-sections. We should also do it together with Microservice Hosting team to improve their understanding of those concepts, as they recently took over responsibility for it and documentation in it's current state only makes it harder to understand.

@kaczynskid-sag I agree, the entire Mircoservice SDK documentation is in a quite poor state as it has been lacking clear responsibility in the past. It could definitely need some re-writing. We have a ticket with a collection of bugs/comments already in place here: https://cumulocity.atlassian.net/browse/MTM-51289. Also note that we have removed the C# Microservice SDK documentation starting with release 10.18 as the SDK was no longer available/maintained.

2023-11-15 14:31 UTC, kaczynskid-sag commented
Implemented in https://github.com/SoftwareAG/c8y-docs/pull/1534 instead.

2023-11-15 14:31 UTC, closed without merging