Add shared and volatile
SoftwareAG/c8y-docs pull request #156
Opened 2022-01-04 10:49 UTC by andrekramer1

2022-01-04 10:52 UTC, andrekramer1 commented
Can't be checked in until we merge Core PR into develop.

2022-01-04 18:50 UTC, manasesjesus commented
Should the OpenAPI be also updated or are these changes only for WebSockets? @andrekramer1

2022-01-05 09:11 UTC, andrekramer1 commented
@manasesjesus yes. We will need to document the new boolean flags.

2022-01-05 10:35 UTC, rssag commented on content/reference/notifications-bundle/consumer-protocol.md
> +There is a timeout of 5 minutes set on idle Web Socket connections after which the connection will be closed by the server side. Therefore the consumer must be prepared to handle closed connections w
@BeateRixen @MWindel not sure about the capitalization of "Web Socket" - on the internet, i find "WebSocket", but this seems to be a library or software package. otherwise i tend to "web socket" ( not capitalized). what are your thoughts?

2022-01-05 10:39 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +They all use a token for the same subscription and the same subscriber, either by using the same shared token or using the same subscription name and subscriber when generating per instance tokens (s
```suggestion
They all use a token for the same subscription and the same subscriber, either by using the same shared token or using the same subscription name and subscriber when generating per instance tokens (for example if the token can not be shared over the network).
```

2022-01-05 10:45 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +It has a non-optional query parameter `token`.
```suggestion
It has a mandatory query parameter `token`.
```

2022-01-05 10:45 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Note that there is no explicit `subscribe a subcriber` operation using a token.
```suggestion
Note that there is no explicit "subscribe a subcriber" operation using a token.
```

2022-01-05 10:46 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +The service will then unusbscribe the subscriber and close the connection.
```suggestion
The service will then unsubscribe the subscriber and close the connection.
```

2022-01-05 13:15 UTC, manasesjesus commented on content/reference/notifications-bundle/consumer-protocol.md
> +There is a timeout of 5 minutes set on idle Web Socket connections after which the connection will be closed by the server side. Therefore the consumer must be prepared to handle closed connections w
It is a protocol, one word, and written as **WebSocket**.

2022-01-05 13:17 UTC, manasesjesus commented on content/reference/notifications-bundle/overview.md
> +Note that there is no explicit `subscribe a subcriber` operation using a token.
subcriber --> subscriber

2022-01-05 13:21 UTC, manasesjesus requested changes

2022-01-05 13:21 UTC, manasesjesus commented on content/reference/notifications-bundle/overview.md
> +A separate REST endpoint is available for this: <kbd>/notification2/unsubscibe</kbd>.
pay attention to the endpoints as they are misspelt

2022-01-05 13:21 UTC, manasesjesus commented on content/reference/notifications-bundle/overview.md
> +The messaging service will keep volatile notifications in memory but will drop notifications if more than a configurable limit is reached per subriber/consumer (default is 1000).
subscribe, subscriber, unsubscribe... these words are misspelt several times.

```suggestion
The messaging service will keep volatile notifications in memory but will drop notifications if more than a configurable limit is reached per subscriber/consumer (default is 1000).
```

2022-01-05 13:25 UTC, manasesjesus commented
> @manasesjesus yes. We will need to document the new boolean flags.

@andrekramer1 @sagscmi @rohitjoshi-softwareag is there a ticket already for this OpenAPI task?

2022-01-10 09:52 UTC, rssag approved these changes

2022-01-11 15:40 UTC, manasesjesus approved these changes

2022-01-31 08:47 UTC, BeateRixen commented
@andrekramer1 What is the status of this PR? Shouldn´t it be review by any other developer, member of your team?

2022-01-31 09:11 UTC, sagscmi commented
Hi @BeateRixen This is for a 10.14 feature and definitely not ready to be merged yet.  I hope to be able to pick it back up again soon but nobody is actively working on it right now.  Unfortunately it looks like you get automatically added to every c8y-docs PR when it is opened.

2022-01-31 09:21 UTC, BeateRixen commented
Ok, thanks for the update. Yes, I´m always added as default reviewer in this repo, and from time to time I check through the open PRs 🙂. No problem, now that I know it is still under construction.
________________________________
From: Scott Mitchell ***@***.***>
Sent: 31 January 2022 10:11
To: SoftwareAG/c8y-docs ***@***.***>
Cc: Rixen, Beate ***@***.***>; Mention ***@***.***>
Subject: Re: [SoftwareAG/c8y-docs] Add shared and volatile doc sections MTM-42808 (PR #156)


Hi @BeateRixen<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBeateRixen&data=04%7C01%7Cbeate.rixen%40softwareag.com%7Cc6b52553dec94dd3cb5608d9e499a711%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C637792170847558464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8T4dEvlXN1QJZPG%2FKwvIPW8QzUXbdz%2FLJNHbdRE8ihE%3D&reserved=0> This is for a 10.14 feature and definitely not ready to be merged yet. I hope to be able to pick it back up again soon but nobody is actively working on it right now. Unfortunately it looks like you get automatically added to every c8y-docs PR when it is opened.

—
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSoftwareAG%2Fc8y-docs%2Fpull%2F156%23issuecomment-1025521531&data=04%7C01%7Cbeate.rixen%40softwareag.com%7Cc6b52553dec94dd3cb5608d9e499a711%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C637792170847558464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mLtcoHXCaX3XxjXZXB19Q%2FNmDeEw4z23Gi%2BVNxBn8KU%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVSBLNC7HZT67OA2OBCY7GLUYZG3VANCNFSM5LHEYEMA&data=04%7C01%7Cbeate.rixen%40softwareag.com%7Cc6b52553dec94dd3cb5608d9e499a711%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C637792170847558464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Lysc8rXCubPuWcMrqNT%2BP6qabOIZVHyuXozPxF9FWQc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbeate.rixen%40softwareag.com%7Cc6b52553dec94dd3cb5608d9e499a711%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C637792170847558464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=70bzjUP6uFJskWocLsiiIkOatiThyW0fFSxjTie5slU%3D&reserved=0> or Android<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbeate.rixen%40softwareag.com%7Cc6b52553dec94dd3cb5608d9e499a711%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C637792170847558464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YyROErwdMkel93dIEESBRWR4NT21TSZW7MTLivgYJSk%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-08-03 11:53 UTC, manasesjesus reviewed
Do (any of) these updates need to go to the OpenAPI docs?

2022-08-03 11:53 UTC, manasesjesus commented on content/reference/notifications-bundle/overview.md
> +For example, instance 1 of the subscriber microservice could pass in `notification2/consumer?token=xyz&consumer=instance1` while instance 2 could use `notification2/consumer?token=XYZ&consumer=instan
this example, does it refer to "the same token" or to "one that was generated in a similar way"?

2022-08-03 11:53 UTC, manasesjesus commented on content/reference/notifications-bundle/overview.md
> +### NonPersistent subscriptions
```suggestion
### Non-persistent subscriptions
```

2022-08-09 08:23 UTC, andrekramer1 commented on content/reference/notifications-bundle/overview.md
> +For example, instance 1 of the subscriber microservice could pass in `notification2/consumer?token=xyz&consumer=instance1` while instance 2 could use `notification2/consumer?token=XYZ&consumer=instan
Can be either.

2022-08-10 09:37 UTC, BeateRixen commented on content/reference/notifications-bundle/overview.md
> +The subscription name defines the topic messages are published on, while the subscriber identifies the backend (north side) application that's usually used.
It seems that something is missing in the first part of the sentence?

2022-08-12 07:48 UTC, BeateRixen approved these changes

2022-08-12 10:00 UTC, merged