[DTM] - Asset Location, Ordering of complex properties documentation
SoftwareAG/c8y-docs pull request #1566
Opened 2023-12-05 04:48 UTC by Vagdevi1998

The changes includes the documentation for ordering of complex properties and asset location

2023-12-05 06:35 UTC, spau6 commented on content/dtm/asset-types-bundle/asset-properties.md
> +The marker on the map is not visible when either the latitude or longitude value is missing.<br>
There are 2 scenarios:
In view mode map itself will not be visible if lat or long is is not supplied
In edit mode map will be visible but marker wont be visible if lat or long is is not supplied
Please modify the statement accordingly

2023-12-05 07:08 UTC, spau6 commented on content/dtm/asset-hierarchy-bundle/viewing-assets.md
> +For an asset with a location, click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the m
```suggestion
For an asset with a location, click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the map to enter full screen mode. If latitude or longitude value is not provided, the marker is not shown on the map.
```

2023-12-05 07:14 UTC, spau6 commented on content/dtm/asset-types-bundle/asset-properties.md
> +If you have not mentioned any specific order in **Order** field, it is automatically prefilled with the order in which the key value pairs are added.
```suggestion
If specific order is not mentioned in **Order** field then it is automatically prefilled with the order in which the key value pairs are added.
```

2023-12-05 12:11 UTC, lra-sag commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The marker is positioned at the default value set in the **Location** property. By default, the marker on the map is not displayed. To make the marker visible, you need to click on the map. Click or
@Vagdevi1998, will the marker be hidden even if the default value is set in the Location property?

2023-12-05 12:36 UTC, lra-sag commented on content/dtm/asset-hierarchy-bundle/viewing-assets.md
> +For an asset with a location, click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the m
```suggestion
For an asset with a location, click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the map to enter full screen mode. If the latitude or longitude value is not present, the marker is not shown on the map.
```

2023-12-05 12:36 UTC, lra-sag commented on content/dtm/asset-types-bundle/asset-properties.md
> +<td style="text-align:left">Used to display the complex properties in a specific order.</td>
```suggestion
<td style="text-align:left">Used to define the order in which the keys of a complex property must be shown.</td>
```

2023-12-05 12:45 UTC, lra-sag commented on content/dtm/asset-types-bundle/asset-properties.md
> +If you have not mentioned any specific order in **Order** field, it is automatically prefilled with the order in which the key value pairs are added.
```suggestion
If the **Order** field is left empty, the order is determined by the sequence in which the key value pairs are added and the field will be automatically filled on saving the asset property.
```

2023-12-05 12:52 UTC, lra-sag commented on content/dtm/asset-types-bundle/asset-properties.md
> +To set the default values for the latitude and longitude using the map view, click **Choose on Map** at the end of the section. Click the full screen icon at the top right corner of the map to view i
@Vagdevi1998 , please ensure the description below is as per the current implementation before using the suggestion as is.
```suggestion
To set the default values for the latitude and longitude using the map view, click **Choose on Map** at the end of the section. Click the full screen icon at the top right corner of the map to view it in full screen. Initially, if the default latitude and longitude values are not present, the marker is not shown. To see the marker, click anywhere on the map. Click or drag the marker to the preferred position to select the default value for latitude and longitude.
```

2023-12-05 12:54 UTC, lra-sag commented on content/dtm/asset-types-bundle/asset-properties.md
> +The marker on the map is not visible when either the latitude or longitude value is missing.<br>
```suggestion
The marker on the map is not shown when either the latitude or longitude value is missing.<br>
```

2023-12-05 12:55 UTC, lra-sag commented on static/images/dtm/custom-property/dtm-property-library-complex-property.png
highlight color looks different. I think it is #ff9300

2023-12-06 03:58 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The marker is positioned at the default value set in the **Location** property. By default, the marker on the map is not displayed. To make the marker visible, you need to click on the map. Click or
No it will be visible if the value is set in location property.

2023-12-06 10:31 UTC, Vagdevi1998 commented on static/images/dtm/custom-property/dtm-property-library-complex-property.png
Modified.

2023-12-06 15:19 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The marker is positioned at the default value set in the **Location** property. By default, the marker on the map is not displayed. To make the marker visible, you need to click on the map. Click or
Modified the statement accordingly

2023-12-07 06:07 UTC, lra-sag requested changes

2023-12-07 07:22 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +To set the default values for the latitude and longitude using the map view, click **Choose on Map** at the end of the section. Click the full screen icon at the top right corner of the map to view i
As discussed, I am keeping it same.

2023-12-08 05:36 UTC, lra-sag approved these changes

2023-12-08 14:09 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The marker is positioned at the default value set in the **Location** property. Click or drag the marker to the preferred position to set the value for both latitude and longitude. If the latitude or
```suggestion
The marker is positioned at the default value set in the **Location** property. Click or drag the marker to the preferred position to set the value for both latitude and longitude. If the latitude or longitude value is not provided, the marker is not shown on the map.
```

2023-12-08 14:09 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The marker is positioned at the default value set in the **Location** property. Click or drag the marker to the preferred position to set the value for both latitude and longitude. If the latitude or
@Vagdevi1998 What do you mean by "click or drag"?

2023-12-08 14:11 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/viewing-assets.md
> +If the asset has a location, it is shown on the map under the properties section below its values.  Click the full screen icon at the top right corner of the map to view it in full screen. If the val
@Vagdevi1998 Why did you change the user focus here?

2023-12-08 14:14 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/viewing-assets.md
> +For an asset with a location, click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the m
```suggestion
For an asset with a location, click or drag the marker to the preferred position to select the value for latitude and longitude on the map. Click the full screen icon at the top right corner of the map to enter full screen mode. To see the map, provide a value for latitude and longitude.
```

2023-12-08 14:17 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-properties.md
> +To set the default values for the latitude and longitude using the map view, click **Choose on Map** at the end of the section. Click the full screen icon at the top right corner of the map to view i
```suggestion
To set the default values for the latitude and longitude using the map view, click **Choose on Map** at the end of the section. Click the full screen icon at the top right corner of the map to view it in full screen. Without values for latitude and longitude, the marker is hidden. To see the marker, click anywhere on the map. Click or drag the marker to the preferred position to select the default value for latitude and longitude.
```

2023-12-08 14:19 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-properties.md
> +The marker on the map is not shown when either the latitude or longitude value is missing.<br>
```suggestion
The marker on the map is only visible when both values for latitude and longitude are provided.<br>
```

2023-12-11 04:22 UTC, Vagdevi1998 commented on content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
> +The marker is positioned at the default value set in the **Location** property. Click or drag the marker to the preferred position to set the value for both latitude and longitude. If the latitude or
@MWindel Either user can click on the map or drag the marker to the respective position.

2023-12-12 14:28 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-properties.md
> +If the **Order** field is left empty, the order is determined by the sequence in which the key value pairs are added and the field will be automatically filled on saving the asset property.
```suggestion
If you do not fill out the **Order** field, the order is determined by the sequence in which the key value pairs are added and the field will be automatically filled on saving the asset property.
```

2023-12-12 14:28 UTC, MWindel approved these changes

2023-12-14 09:58 UTC, merged