Fixes platform services
SoftwareAG/c8y-docs pull request #1611
Opened 2024-01-11 16:27 UTC by dianaolives

2024-01-15 10:03 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_changing-data-in-the-access-mapping-section.md
> +title: Changing data in the access mapping section
```suggestion
title: Fixed issue with Save button in Access mapping section
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_fixed-issue-from-invalid-pagesize-or-currentpage-parameter.md
> +title: Fixed issue from invalid pageSize or currentPage parameter
```suggestion
title: Fixed issue with invalid parameters
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_fixed-issues-with-page-redirection.md
> +title: Fixed issues with page redirection
```suggestion
title: Fixed issues with redirection to the SSO server
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_fixed-issues-with-the-ericsson-dcp-sms-provider.md
> +    label: Administration
label should be "SMS microservice". Not sure if this is already available

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_http-code-issue-fixed.md
> +title: HTTP code issue fixed
```suggestion
title: HTTP error issue fixed
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_improved-custom-alarm-property.md
> +title: Improved custom alarm property
```suggestion
title: Fixed redundant audit log entries creation
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_improved-password-strength-indicator.md
> +title: Improved password strength indicator
```suggestion
title: Fixed issue with password strength indicator
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_improved-proof-of-possession-process.md
> +title: Improved Proof of Possession process
```suggestion
title: Fixed issues with Proof of Possession process
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_improved-unpacking-of-versioned-applications.md
> +title: Improved unpacking of versioned applications
```suggestion
title: Fixed issue with unpacking versioned applications
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_improved-unsecured-login-option.md
> +title: Improved unsecured login option
```suggestion
title: Fixed unsecured login option
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_log-files-stored-in-platform-can-now-be-downloaded.md
> +title: Log files stored in platform can now be downloaded
```suggestion
title: Log files of devices can now be downloaded
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_messaging-service-requests-time-out-quickly.md
> +title: Messaging Service requests time out quickly
```suggestion
title: Fixed issues with Messaging Service requests time out
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_no-unequal-distribution-of-notifications.md
> +title: No unequal distribution of notifications
```suggestion
title: Fixed issue with unequal distribution of notifications
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_password-reset-when-user-logs-in-with-oai-secure.md
> +title: Password reset when user logs in with OAI-Secure
```suggestion
title: Password reset on OAI-Secure login
```

2024-01-15 10:22 UTC, BeateRixen commented on content/change-logs/platform-services/2023-12-06_refreshing-session-tokens-with-two-factor-authentication.md
> +title: Refreshing session tokens with two-factor-authentication
```suggestion
title: Fixed issues with refreshing session tokens
```

2024-01-15 10:24 UTC, BeateRixen commented
@sarangovindarajan @martin-sag Please review the first bunch of fixes for the 2024 release notes. Especially please check if the titles are ok which have been added by Diana.

2024-01-16 15:40 UTC, sagscmi requested changes
Some suggested changes to title, to make it more obvious when the issue is about Notifications 2.0 vs. Realtime Notifications (both under the REST API component)

2024-01-16 15:40 UTC, sagscmi commented on content/change-logs/platform-services/cumulocity-10-18-151-0-simple-type-name-accepted-as-type-filter.md
> +title: Simple type name accepted as type filter
```suggestion
title: Simple type name accepted as type filter for Notifications 2.0 subscriptions
```

2024-01-16 15:40 UTC, sagscmi commented on content/change-logs/platform-services/cumulocity-10-18-185-0-fixed-issues-with-messaging-service-requests-time-out.md
> +title: Fixed issues with Messaging Service requests time out
```suggestion
title: Fixed issues with Messaging Service request timeouts
```

2024-01-16 15:40 UTC, sagscmi commented on content/change-logs/platform-services/cumulocity-10-18-230-0-delete-notifications-to-specific-managed-objects.md
> +title: DELETE notifications to specific managed objects
```suggestion
title: DELETE notifications for specific managed objects with Notifications 2.0
```

2024-01-18 08:37 UTC, sarangovindarajan commented on content/change-logs/platform-services/cumulocity-10-18-489-0-fixed-unsecured-login-option.md
> +title: Fixed unsecured login option
Fixed information disclosure issues with unsecured login option endpoint.

2024-01-18 08:40 UTC, sarangovindarajan commented on content/change-logs/platform-services/ui-c8y-10-18-369-0-improved-tooltip-to-copy-ssl-command.md
> +title: Improved tooltip to copy SSL command
Improved tooltip usability in Proof of possession

2024-01-18 08:42 UTC, sarangovindarajan commented on content/change-logs/platform-services/ui-c8y-10-18-497-8-redirection-to-management-tenant-removed.md
> +title: Redirection to Management tenant removed
Addressed the redirection issues for support user

2024-01-18 08:43 UTC, sarangovindarajan commented on content/change-logs/platform-services/ui-c8y-10-18-500-17-improved-sso-configuration-page.md
> +title: Improved SSO configuration page
Improved SSO configurations

2024-01-18 08:43 UTC, sarangovindarajan requested changes
Please refer to my comments..

2024-01-18 08:59 UTC, martin-sag approved these changes

2024-01-18 10:46 UTC, sagscmi approved these changes

2024-01-19 11:14 UTC, BeateRixen approved these changes

2024-01-19 11:23 UTC, merged