Rn cl cumulocity 10.18.570.0
SoftwareAG/c8y-docs pull request #1613
Opened 2024-01-16 12:48 UTC by BeateRixen

2024-01-16 12:54 UTC, BeateRixen commented
Please review and approve the entries for your team: 
@Oezge-Akin > 4 tickets
@sagscmi > 2 tickets
@martin-sag > 1 ticket
@l2p- > 1 ticket

2024-01-16 13:53 UTC, sagscmi requested changes
`MTM-56910` is actually a Realtime API ticket - it should be under Platform services / REST API.  I think the confusion was caused by having 2 components set on the ticket.

2024-01-16 13:53 UTC, sagscmi commented on content/change-logs/device-management/cumulocity-10-18-540-13-fixed-an-issue-in-the-realtime-api.md
> +    label: LWM2M
```suggestion
    label: REST API
```

2024-01-16 13:53 UTC, sagscmi commented on content/change-logs/device-management/cumulocity-10-18-540-13-fixed-an-issue-in-the-realtime-api.md
> +product_area: Device management & connectivity
```suggestion
product_area: Platform services
```

2024-01-17 09:40 UTC, MWindel approved these changes

2024-01-17 16:06 UTC, Oezge-Akin commented on content/change-logs/device-management/cumulocity-10-18-560-0-modified-object-default-handling.md
> +    label: Improvement
Feature

2024-01-17 16:06 UTC, Oezge-Akin commented on content/change-logs/device-management/cumulocity-10-18-560-0-modified-object-default-handling.md
> +The default handling of object instance actions for LWM2M objects 3, 4 and 6 can now be turned off. In addition, the default server-side firmware update state machine for object 5 can be disabled.
Could you add this sentence?: 
Device's LWM2M Configuration UI can be used to enable/disable these settings.

2024-01-18 07:43 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity-10-18-540-9-configurable-time-to-live-duration.md
> +title: Configurable Time-To-Live duration
```suggestion
title: LWM2M Time-to-Live duration for device operation realtime subscription
```

2024-01-18 07:43 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity-10-18-540-9-configurable-time-to-live-duration.md
> +The LWM2M agent realtime subscription for device operations now has a configurable Time-To-Live (TTL) duration. The default TTL duration is 3 minutes.
```suggestion
The LWM2M agent realtime subscription for device operations now has a limited Time-To-Live (TTL) duration. The default TTL duration is 3 minutes. This setting may be configured on platform level.
```

2024-01-18 07:43 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity-10-18-560-0-modified-object-default-handling.md
> +title: Modified object default handling
```suggestion
title: Option to disable LWM2M object default actions
```

2024-01-18 07:43 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity-10-18-560-0-modified-object-default-handling.md
> +    label: Improvement
```suggestion
    label: Feature
```

2024-01-18 07:43 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity-10-18-560-0-modified-object-default-handling.md
> +The default handling of object instance actions for LWM2M objects 3, 4 and 6 can now be turned off. In addition, the default server-side firmware update state machine for object 5 can be disabled.
```suggestion
The default handling of object instance actions for LWM2M objects 3, 4 and 6 can now be turned off. In addition, the default server-side firmware update state machine for object 5 can be disabled. These settings can be enabled/disabled in the device´s LWM2M  configuration in the UI. 
```

2024-01-18 07:59 UTC, Oezge-Akin approved these changes

2024-01-23 15:25 UTC, merged