Created c8y_SupportedOperations fragments table
SoftwareAG/c8y-docs pull request #164
Opened 2022-01-06 10:09 UTC by JoshuaAdemola

2022-01-06 10:47 UTC, rssag commented on content/reference/device-management-library-bundle/overview.md
> +<td>Holds information about the device’s status and its availability</td>
```suggestion
<td>Holds information about the device's status and its availability</td>
```

2022-01-06 10:48 UTC, rssag commented on content/reference/device-management-library-bundle/overview.md
> +<td>Contains information on a device’s firmware</td>
```suggestion
<td>Contains information on a device's firmware</td>
```

2022-01-06 10:49 UTC, rssag commented on content/reference/device-management-library-bundle/overview.md
> +<td>Request a device to send a log file and view the log file in the log viewer</td>
This sentence is not an ellipsis like the others so far, but an imperative.
i'd say "Requests" would work instead of "Request" (?)

2022-01-06 10:50 UTC, rssag commented on content/reference/device-management-library-bundle/overview.md
> +<td>Monitor devices for availability</td>
same here, suggestion would be "Monitors" instead of "Monitor"

2022-01-06 10:50 UTC, rssag commented on content/reference/device-management-library-bundle/overview.md
> +<td>Restart a device</td>
see above

2022-01-06 10:51 UTC, rssag commented on content/reference/device-management-library-bundle/overview.md
> +<td>Holds an array for types a log that a device supports</td>
I'm not quite sure what this sentence means

2022-01-06 11:10 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>Holds information about the device’s status and its availability</td>
Fixed

2022-01-06 11:11 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>Contains information on a device’s firmware</td>
Fixed

2022-01-06 11:12 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>Request a device to send a log file and view the log file in the log viewer</td>
Fixed

2022-01-06 11:12 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>Monitor devices for availability</td>
Fixed

2022-01-06 11:12 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>Restart a device</td>
Fixed

2022-01-06 11:14 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>Holds an array for types a log that a device supports</td>
Fixed

2022-01-06 12:08 UTC, rssag approved these changes

2022-01-06 13:05 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +#### ```c8y_SupportedOperations``` fragments
```c8y_SupportedOperations``` > c8y_SupportedOperations
code formatting looks weird in the heading

2022-01-06 13:06 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#device-info"><code>c8y_Availability</code></a></td>
I would actually not format the links as code as you do not realize them as links then. Anyway, code formatting is not necessarily required in a table (as opposed to inline text).

2022-01-06 13:07 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#device-info"><code>c8y_Availability</code></a></td>
Please change throughout the whole column.

2022-01-06 13:07 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td>An operation that permits managing binary configuration files of the device</td>
An operation that permits > Permits
To be consistent with the structure of the other entries

2022-01-06 13:07 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td>An operation that permits the download of configuration files as binaries</td>
An operation that permits > Permits
To be consistent with the structure of the other entries

2022-01-06 13:09 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td>Monitor devices for availability</td>
Monitor > Monitors

2022-01-06 13:09 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td>Restart a device</td>
Restart > Restarts

2022-01-06 13:10 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td>An operation that permits the upload of configuration files as binaries</td>
An operation that permits > Permits
To be consistent with the structure of the other entries

2022-01-06 13:12 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#device-marker"><code>c8y_IsDevice</code></a></td>
A fragment which identifies > Identifies

2022-01-06 14:06 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +#### ```c8y_SupportedOperations``` fragments
Fixed

2022-01-06 14:10 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#device-info"><code>c8y_Availability</code></a></td>
Fixed

2022-01-06 14:11 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>An operation that permits managing binary configuration files of the device</td>
Fixed

2022-01-06 14:11 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>An operation that permits the download of configuration files as binaries</td>
Fixed

2022-01-06 14:12 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>Monitor devices for availability</td>
Fixed

2022-01-06 14:12 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>Restart a device</td>
Fixed

2022-01-06 14:12 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td>An operation that permits the upload of configuration files as binaries</td>
Fixed

2022-01-06 14:12 UTC, JoshuaAdemola commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#device-marker"><code>c8y_IsDevice</code></a></td>
Fixed

2022-01-10 13:38 UTC, MWindel approved these changes

2022-01-10 15:44 UTC, dafkk requested changes

2022-01-10 15:44 UTC, dafkk commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#device-marker">c8y_IsDevice</a></td>
c8y_IsDevice is not a fragment used in the supportedOperations fragment. It is a standalone one that is added in the managed object, when it is of type device like this: "c8y_IsDevice": {}.

2022-01-10 15:44 UTC, dafkk commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#device-availability">c8y_RequiredAvailability</a></td>
Same with requiredAvailability, used as a standalone fragment: 
"c8y_RequiredAvailability": {
    "responseInterval": 60
  }

2022-01-10 15:44 UTC, dafkk commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#typed-file-based-configuration">c8y_SupportedConfiguration</a></td>
Same with supporedConfiguration and supportedLogs. Ther are not used in the supportedOperations array but as standalone fragments, holding some information.

2022-01-10 15:44 UTC, dafkk commented on content/reference/device-management-library-bundle/overview.md
> +</tr>
c8y_DeviceProfile is missed here.

2022-01-10 16:28 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +</tr>
Added

2022-01-10 16:28 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#device-marker">c8y_IsDevice</a></td>
Removed

2022-01-10 16:29 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#device-availability">c8y_RequiredAvailability</a></td>
Removed

2022-01-10 16:29 UTC, BeateRixen commented on content/reference/device-management-library-bundle/overview.md
> +<td><a href="../../reference/device-management-library/#typed-file-based-configuration">c8y_SupportedConfiguration</a></td>
Removed

2022-01-11 08:23 UTC, dafkk approved these changes

2022-01-11 12:01 UTC, merged