[DM-3035] Add a note on recommended event type for logfile events
SoftwareAG/c8y-docs pull request #1647
Opened 2024-01-30 07:26 UTC by bozhidardedov

2024-01-30 08:30 UTC, BeateRixen commented on content/device-integration/fragment-library-bundle/logs.md
> +To avoid conflicts with other events bearing binary attachments (e.g. for [typed file-based configuration](#upload-current-configuration-file))
```suggestion
To avoid conflicts with other events bearing binary attachments (for example, for [typed file-based configuration](#upload-current-configuration-file))
```

2024-01-30 08:30 UTC, BeateRixen commented on content/device-integration/fragment-library-bundle/logs.md
> +we recommend to use `c8y_Logfile` as event type.
```suggestion
we recommend you to use `c8y_Logfile` as event type.
```

2024-01-30 11:51 UTC, BeateRixen approved these changes

2024-01-31 11:33 UTC, dafkk approved these changes

2024-02-06 15:10 UTC, BeateRixen commented
@bozhidardedov Can you merge this one or do you need more approvals? If this should go to 2024, please add the backport labels.

2024-02-07 09:03 UTC, bozhidardedov commented
> @bozhidardedov Can you merge this one or do you need more approvals? If this should go to 2024, please add the backport labels.

I would like @l2p- to also take a look and would merge it then.

2024-02-07 19:36 UTC, l2p- requested changes
I'd like to see the same change also in line 86 to:

|type|string|Yes|Type of the event holding the log file should always be `c8y_Logfile`|

2024-02-12 08:58 UTC, l2p- approved these changes

2024-02-12 15:13 UTC, merged