Bug fixes.
SoftwareAG/c8y-docs pull request #1662
Opened 2024-02-05 04:49 UTC by aik24

2024-02-07 06:32 UTC, lra-sag requested changes

2024-02-07 06:32 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1019-0-0-modified-lable-for-complex-property-in-subassets-page.md
> +User can now see a label 'complex properties' instead of the previous 'property key' label  in the Subassets tab.
Use the exact case when mentioning fields or labels
```suggestion
Users can now see a label 'Complex properties' instead of the previous 'Property key' label  in the Subassets page.
```

2024-02-07 06:32 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1019-0-0-modified-success-message-on-udating-asset.md
> +title: modified success message on udating asset
Be consistent with text, use sentence case. Ensure to check for spellings.

2024-02-07 06:32 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1019-0-0-optimized-network-calls-for-assets-and-asset-models.md
> +Optimized network from the Assets property and Asset Model page.
```suggestion
Optimized calls to the backend from the Assets property and Asset Model page.
```

2024-02-07 06:32 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1019-0-0-saved-filters-for-columns-on-localization-page.md
> +title: Saved filters for columns on Localization page
This sounds more like an improvement than a fix, please describe the problem that is fixed if this is a fix, else change the change_type to Improvement

2024-02-07 06:32 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1019-0-0-updated-default-icon-to-'c8y-enterprise'.md
> +title: Updated default icon to 'c8y-enterprise'
```suggestion
title: New default icon for Assets
```

2024-02-07 06:32 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1019-0-0-updated-default-icon-to-'c8y-enterprise'.md
> +Modified default Icon from 'c8y-group' to 'c8y-enterprise' in Asset model edit page under allowed asset model.
Was this a problem only when editing an asset model? Was the default icon shown correctly in the other places? Modify the statement based on the answers to above questions.

2024-02-07 06:32 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1019-1-2-improved-map-display-for-latitude-and-longitude-values.md
> +title: Improved map display for latitude and longitude values
```suggestion
title: Corrected placement of marker when one or both the co-ordinates is set to zero
```

2024-02-07 06:32 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1019-1-2-map-marker-visibility-based-on-location-property-values.md
> +Marker on the map is not shown to the user if there are no values for latitude and longitude of loaction property in Asset properties page.
```suggestion
Users cannot see the marker on the map if there are no values for Latitude and Longitude of Location property in Asset properties page.
```
```suggestion
Users are not shown the marker on the map if there are no values for Latitude and Longitude within the Location property in Asset properties page.
```

2024-02-12 10:49 UTC, lra-sag requested changes

2024-02-12 10:49 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1019-1-1-improved-map-display-and-interaction-for-location-property.md
> +User can now view the map on the Subassets page only when both values(latitude/longitude) of location property are available; if any or both of the values are missing, the map remains hidden. Additio
```suggestion
Users can now view the map on the Subassets page only when both values(latitude/longitude) of location property are available; if any or both of the values are missing, the map remains hidden. Additionally, the marker is not shown on the map if any one of the values is missing. Clicking anywhere on the map in edit mode will update the corresponding fields automatically.
```

2024-02-12 10:49 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1019-1-1-inventory-role-permission-to-view-asset-models-in-asset-model-page.md
> +User with inventory role permission can now see all Asset models in Asset model page
```suggestion
Users with access only to specific assets via inventory roles can now view all Asset models in Asset model page 
```

2024-02-13 04:01 UTC, lra-sag approved these changes

2024-02-13 11:41 UTC, pavanshivajirao approved these changes

2024-02-14 09:52 UTC, BeateRixen commented
@aik24 @pavanshivajirao In general, many of the entries are lacking relevant information for the user. Each entry should provide a context, a description of the change (for example, the behavior before and after the change), and the impact on the user (often the same as the change behavior after the change).

2024-02-14 16:24 UTC, MWindel commented on content/change-logs/application-enablement/dtm-1019-1-2-map-marker-visibility-based-on-location-property-values.md
> +Users are not shown the marker on the map if there are no values for Latitude and Longitude within the Location property in Asset properties page.
```suggestion
Users are not shown the marker on the map if there are no values for latitude and longitude within the Location property in **Asset properties** page.
```

2024-02-14 16:24 UTC, MWindel commented on content/change-logs/application-enablement/dtm-1019-0-0-handled-display-issues for-property-values-in-subassets.md
> +Users can now view the accurate value of a boolean property as "false" instead of "undefined" on the Subassets Page. Additionally, in the absence of data, date and number properties display an undefi
```suggestion
Users can now view the accurate value of a boolean property as "false" instead of "undefined" on the **Subassets** Page. Additionally, in the absence of data, the Date and Number properties display an undefined value.
```

2024-02-16 09:01 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-1-uniform-warnings-and-errors-across-the-application.md
> +The message shown in warnings/pop up dialog windows/error messages are kept consistent across the entire application.
Are this different things? Is it "warnings" OR "pop-up dialog window" AND "error messages" or is this all the same? Then you should use just one term.

2024-02-16 09:28 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-2-map-marker-visibility-based-on-location-property-values.md
> +Users are not shown the marker on the map if there are no values for latitude and longitude within the Location property in **Asset properties** page.
```suggestion
Users are no longer shown the marker on the map if there are no values for latitude and longitude within the Location property in **Asset properties** page.
```

2024-02-16 09:29 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-2-displaying-null-for-empty-number-values-in-asset-property-page.md
> +title: Displaying null for empty Number values in Asset Property page
```suggestion
title: Displaying null for empty number values in Asset property page
```

2024-02-16 09:31 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-2-corrected-placement-of-marker-when-one-or-both-the-coordinates-is-set-to-zero.md
> +The marker is now shown at the center of the map when both or any one of the value of latitude and longitude is "0" for the Location property.
```suggestion
The marker is now shown at the center of the map when one or both of the values for latitude and longitude is "0" for the Location property.
```

2024-02-16 09:33 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-2-corrected-placement-of-marker-when-one-or-both-the-coordinates-is-set-to-zero.md
> +title: Corrected placement of marker when one or both the co-ordinates is set to zero
```suggestion
title: Corrected placement of marker if coordinate value is set to zero
```

2024-02-16 09:33 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-2-corrected-placement-of-marker-when-one-or-both-the-coordinates-is-set-to-zero.md
> +The marker is now shown at the center of the map when both or any one of the value of latitude and longitude is "0" for the Location property.
Where is that? Please provide a context.

2024-02-16 09:37 UTC, BeateRixen commented
@aik24 I finished my review. In general, please do not use upper case spelling for any terms except of explicit UI elements (such as windows and fields). In that case, the names must be spelled properly (that is exactly as in the UI) and formatted in bold. If you just refer to "numbers" or "asset models" or "asset properties" for example in general, you should not use upper case.

2024-02-19 05:58 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-0-0-Role-based-access-for-setting-default-location-for-the-location-property..md
> +Only users with edit access to Asset properties can set the default location values in the Location property through the 'Choose on map' button.
Before, there were no permissions set for the location property. Now, with permissions enabled, only users who have edit access to asset properties can set default location values using the Choose on map button in the Location property.

2024-02-19 06:11 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-0-0-default-properties-are-omitted-from-asset-property-export-list.md
> +The default asset property (Location) does not show up during the export of asset properties.
The default asset property (Location) is excluded during the export. This omission is intentional as the default properties are already present in the tenant and do not need to be exported.

2024-02-19 06:17 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-0-0-fixed-empty-grid-message-being-displayed-along-with-newly-created-assets.md
> +Fixed the issue of an empty grid message being displayed along with newly created assets.
Previously, upon creating a new asset, an empty grid message stating 'No items to display' would appear. This issue has been addressed, and the message will no longer be displayed.

2024-02-19 06:18 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-0-0-handled-UI-issues-in-import-asset-properties-preview-window.md
> +The Import asset properties preview window now displays a message when no record exists.
"Import asset properties" is the name of the window.

2024-02-19 06:21 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-1-2-corrected-placement-of-marker-when-one-or-both-the-coordinates-is-set-to-zero.md
> +The marker is now shown at the center of the map when both or any one of the value of latitude and longitude is "0" for the Location property.
The marker is now shown at the center of the map when one or both of the values for latitude and longitude is "0" for the Location property.Previously, the marker was not centrally displayed, requiring users to manually zoom in to locate it.

2024-02-19 06:22 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-1-2-corrected-placement-of-marker-when-one-or-both-the-coordinates-is-set-to-zero.md
> +The marker is now shown at the center of the map when both or any one of the value of latitude and longitude is "0" for the Location property.
The marker is now shown at the center of the map when one or both of the values for latitude and longitude is "0" for the Location property.Previously, the marker was not centrally displayed, requiring users to manually zoom in to locate it.

2024-02-19 06:42 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-0-0-dtm-version-moved-under-platform-info-section.md
> +Users can now find the label "DTM" along with the version in the user profile under the platform info section.
Layered products are still in the process of incorporating it.

2024-02-19 06:44 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-0-0-Improved-error-feedback-during-asset-instance-creation.md
> +When there are multiple asset instances, users are now navigated back to the step showing a blank value in the name field instead of navigating to the confirmation page.
When there are multiple asset instances, users are now navigated back to the step showing a blank value in the name field instead of navigating to the confirmation page. The navigation has been changed..

2024-02-19 06:45 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-0-0-added-range-validation-location-property-fields.md
> +Users can now only enter values that are within the valid range for latitude (-90 to +90) and longitude (-180 to +180) fields.
In Location property fields, updated accordingly.

2024-02-19 06:49 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-0-0-error-handling-for-cancelled-delete-operations-in-asset-models-and-properties-page.md
> +Handled the unexpected error message when a user cancels the delete operation in the **Asset models** and **Asset properties** page.
The error message that used to appear will no longer be shown when the user cancels a delete operation.

2024-02-19 06:50 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-0-0-implemented-file-size-validation-during-asset-creation-and-subassets-page..md
> +Implemented file size validation for a file type property during asset creation and in the **Subassets** page.
Modified.

2024-02-19 06:50 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-0-0-implemented-file-type-validation-in-assets-page.md
> +File type validation is handled during asset creation.
Modified.

2024-02-19 06:51 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-1-1-handled-access-denied-error-on-updating-file-property-type-in-subassets.md
> +Handled access denied error message when the users try to update the property type file in **Subassets** page.
The 'Access Denied' error message is no longer displayed to the users attempting to update the file property type.

2024-02-19 06:52 UTC, aik24 commented on content/change-logs/application-enablement/dtm-1019-1-1-uniform-warnings-and-errors-across-the-application.md
> +The message shown in warnings/pop up dialog windows/error messages are kept consistent across the entire application.
Modified

2024-02-19 07:22 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-0-0- support-for importing-complex-asset-properties.md
> +Importing a complex asset property is now supported.
```suggestion
Importing a complex asset property is now supported by the platform.
```

2024-02-19 07:25 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-0-0-fixed-empty-grid-message-being-displayed-along-with-newly-created-assets.md
> +Fixed the issue of an empty grid message being displayed along with newly created assets.
This is the kind of message I would put here.

2024-02-19 07:26 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-0-0-fixed-empty-grid-message-being-displayed-along-with-newly-created-assets.md
> +Fixed the issue of an empty grid message being displayed along with newly created assets.
```suggestion
Previously, upon creating a new asset, a message stating "No items to display" was displayed. This issue has been addressed, and the message will no longer be shown.
```

2024-02-19 07:27 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-0-0-handled-display-issues for-property-values-in-subassets.md
> +Users can now view the accurate value of a Boolean property as "false" instead of "undefined" on the **Subassets** page. Additionally, if no data is provided, the date and number properties display a
```suggestion
On the **Subassets** page, the value of a Boolean property is now accurately shown as "false" instead of "undefined" . Additionally, if no data is provided, the date and number properties display an undefined value.
```

2024-02-19 07:28 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-0-0-handled-grid-configuration-issues-in-asset-screen-page.md
> +Fixed an issue where the assets screen goes blank for one user if data is deleted by another user due to grid configuration.
```suggestion
Fixed an issue where the Assets page goes blank for one user if data is deleted by another user due to grid configuration. 
```

2024-02-19 07:28 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-0-0-handled-grid-configuration-issues-in-asset-screen-page.md
> +title: Handled grid configuration issues in asset screen page
```suggestion
title: Handled grid configuration issues in the Assets page  
```

2024-02-19 07:32 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-0-0-message-added-for-non-existing-asset-model-samples.md
> +title: Message added for non-existing asset model samples.
```suggestion
title: Message added for non-existing asset model samples
```

2024-02-19 07:32 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-1-fixed-the-error-when-value-for-latitude-or-longitude-is-zero.md
> +Fixed the error seen when the latitude or longitude value of the Location property is set to 0.
The title says "zero" while the text says "0". Better unify.

2024-02-19 07:32 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-1-handled-access-denied-error-on-updating-file-property-type.md
> +The 'Access Denied' error message is no longer displayed to the users attempting to update the file property type in the **Subassets** page.
```suggestion
The "Access denied" error message is no longer displayed on attempting to update the file property type in the **Subassets** page.
```

2024-02-19 07:32 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-1-uniform-warnings-and-errors-across-the-application.md
> +The message shown in pop up dialog windows are kept consistent across the entire application.
```suggestion
The messages shown in pop up dialog windows are kept consistent across the entire application.
```

2024-02-19 07:32 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-2-corrected-placement-of-marker-if-coordinate-value-is-set-to-zero.md
> +The marker is now shown at the center of the map when one or both of the values for latitude and longitude is "0" for the Location property.
See above: zero vs 0

2024-02-19 07:34 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1019-1-2-corrected-placement-of-marker-if-coordinate-value-is-set-to-zero.md
> +The marker is now shown at the center of the map when one or both of the values for latitude and longitude is "0" for the Location property.
```suggestion
The marker is now shown at the center of the map when one or both of the values for latitude and longitude is "0" for the Location property. Previously, the marker was not centrally displayed, requiring users to manually zoom in to locate it.
```

2024-02-20 11:58 UTC, BeateRixen approved these changes

2024-02-20 13:28 UTC, merged

2024-02-20 17:21 UTC, BeateRixen commented
@aik24 Should this PR be backported to 2024 or are these fixes only relevant for 2025?

2024-02-21 06:19 UTC, aik24 commented
Yes, this should be backported to 2024 release branch.

2024-02-21 09:37 UTC, aik24 commented
@BeateRixen Version number will be the same.

2024-02-22 09:28 UTC, BeateRixen commented
@aik24 I alreday backported the PR to 2024.

2024-02-22 10:04 UTC, aik24 commented
@BeateRixen Thank you