Create cumulocity-10-20-135-0-fixed-issue-with-sms-requests-to-bic-pr…
SoftwareAG/c8y-docs pull request #1690
Opened 2024-02-09 13:27 UTC by BeateRixen

…ovider.md

2024-02-09 13:27 UTC, BeateRixen commented
@l2p- Please especially check if the title and the change type match the ticket description.

2024-02-12 09:05 UTC, l2p- requested changes

2024-02-12 09:05 UTC, l2p- commented on content/change-logs/platform-services/cumulocity-10-20-135-0-fixed-issue-with-sms-requests-to-bic-provider.md
> +title: Fixed issue with SMS requests to Bic provider
```suggestion
title: Fixed issue with SMS requests to Bics provider
```

2024-02-13 10:47 UTC, MWindel approved these changes

2024-02-13 11:31 UTC, merged