[MTM-56083]: user guide for device's JWT token using X.509 certificates
SoftwareAG/c8y-docs pull request #1755
Opened 2024-02-28 16:21 UTC by cumulocitypans

2024-02-29 14:09 UTC, Michal-Bak requested changes

2024-02-29 14:09 UTC, Michal-Bak commented on content/device-integration/device-rest-client-bundle/rest-client-java-certificates.md
> +You do not need to set a password, user or tenant for the REST java client using certificates. {{< product-c8y-iot >}} will recognize the tenant and the user by the provided certificate.
It is a duplication? 
I think we have already description:
 how to generate token(To generate a valid certificate)  
how to upload (To copy and upload the certificate)
To change the configuration -> probably need to be explained with the same step where you describe how Create a Java application.

2024-02-29 14:12 UTC, Michal-Bak commented
And I believe you do not need to fork the repository, Since you were added toSoftwareAG organization I guess you can open PR directly

2024-03-05 06:12 UTC, cumulocitypans commented on content/device-integration/certificate-bundle/device-certificates.md
> -The user for the device will be created during the first MQTT call, if a device certificate is derived from a trusted certificate which was uploaded to the {{< product-c8y-iot >}} platform with a fla
Hi @Michal-Bak , I moved this up in certificate-bundle which is common for both REST and MQTT

2024-03-05 06:12 UTC, cumulocitypans commented on content/device-integration/device-rest-client-bundle/device-access-token.md
> +The same credentials used to access the {{< product-c8y-iot >}} Web UI can be used to execute the REST calls.
Agree, will change sentence it's not serve purpose.

2024-03-05 06:14 UTC, cumulocitypans commented on content/device-integration/device-rest-client-bundle/rest-client-java.md
> +	 */
will remove.

2024-03-05 06:40 UTC, cumulocitypans commented on content/device-integration/certificate-bundle/device-certificates.md
> +weight: 70
weight decide page sequence like lighter weight come first.

2024-03-05 06:41 UTC, cumulocitypans commented on content/device-integration/certificate-bundle/device-certificates.md
> -### Overview {#overview}
it is common for Rest and MQTT thats why I removed in one common place in certificate-bundle

2024-03-05 06:43 UTC, cumulocitypans commented on content/device-integration/certificate-bundle/overview.md
> +-   You have a valid tenant, user and password in order to access {{< product-c8y-iot >}}.
For doing admin related activity like uploading CA certificate in platform. Its perquisite

2024-03-06 07:54 UTC, cumulocitypans commented on content/device-integration/device-rest-client-bundle/rest-client-java-certificates.md
> +You do not need to set a password, user or tenant for the REST java client using certificates. {{< product-c8y-iot >}} will recognize the tenant and the user by the provided certificate.
Removed

2024-03-06 07:59 UTC, cumulocitypans commented on content/device-integration/device-rest-client.md
> +---
I did, only thing pending is creating subsection in section.

2024-03-06 15:41 UTC, cumulocitypans commented on content/device-integration/certificate-bundle/device-certificates.md
> -The user for the device will be created during the first MQTT call, if a device certificate is derived from a trusted certificate which was uploaded to the {{< product-c8y-iot >}} platform with a fla
This section moved to common place under certificate-bundle folder.

2024-03-06 16:29 UTC, cumulocitypans commented on content/device-integration/certificate-bundle/device-certificates.md
> -### JWT token retrieval {#jwt-token-retrieval}
It is moved in MQTT section under mqtt-bundle/mqtt-examples-bundle

2024-03-07 17:13 UTC, cumulocitypans commented
As per discussion with @BeateRixen and @sarangovindarajan created a new PR https://github.com/SoftwareAG/c8y-docs/pull/1795 with latest changes. Please review and provide feedback.

2024-03-07 17:13 UTC, closed without merging