Autentication features change logs
SoftwareAG/c8y-docs pull request #1763
Opened 2024-03-01 18:36 UTC by mmed-softwareag

2024-03-04 09:49 UTC, kalavathig1 commented on content/change-logs/platform-services/cumulocity-10-18-0-277-10-18-503-23-separate-roles-granting-access-to-managed-objects-and-binary-files.md
> +Security improved by splitting the Inventory role permissions into separate roles for the Managed Objects and Binary.  This enables more granular permissions to be assigned, the existing permissions
what do you mean `the existing permissions will still work.`? can you please elaborate or rewrite

2024-03-04 09:49 UTC, kalavathig1 commented on content/change-logs/platform-services/cumulocity-10-18-590-0-support-for-certificate-revocation-list.md
> +version: 10.18.590.0
based on which subtask this version is chosen ?

2024-03-04 09:49 UTC, kalavathig1 commented on content/change-logs/platform-services/cumulocity-10-18-590-0-support-for-certificate-revocation-list.md
> +Administrators can configure the Certificate Revocation List (CRL) settings (online or offline). If the revoked certificate information is maintained by the issuing Certificate Authority (CA), the on
can you make `Tenant administrators can configure... ` ?

2024-03-04 09:49 UTC, kalavathig1 commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +title: The administrator cannot change passwords for other users.
trivial: can it be `The tenant administrator cannot change password for other users.` instead pf `The administrator cannot change passwords for other users.` ?

2024-03-04 09:49 UTC, kalavathig1 commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +To improve security user administrators can no longer explicitly set passwords for other users in the tenant or other tenants' admin. This change prevents an attacker from having access to all users,
Trivial: I think it should be:
1.  `tenant administrators` and not `user administrators`.
2. `tenant's` instead of `tenants'` admin.

2024-03-04 09:49 UTC, kalavathig1 commented on content/change-logs/platform-services/cumulocity-undefined-User-administrator-can-no-longer-set-password-for-other-users.md
> +product_area: Platform services
The above title should be `Tenant administrator` and not `User administrator`

2024-03-04 10:03 UTC, sarangovindarajan commented on content/change-logs/platform-services/cumulocity-10-18-590-0-support-for-certificate-revocation-list.md
> +title: Support for Certificate Revocation List.
Title: _CRL support in Device Certificate authentication._

2024-03-04 10:13 UTC, sarangovindarajan commented on content/change-logs/platform-services/cumulocity-10-18-590-0-support-for-certificate-revocation-list.md
> +Administrators can configure the Certificate Revocation List (CRL) settings (online or offline). If the revoked certificate information is maintained by the issuing Certificate Authority (CA), the on
Rephrase: _Administrators can configure the Certificate Revocation List (CRL) settings. When a certificate is compromised, the platform is now capable of performing the the revocation check during the device authentication process. Administrators can choose an offline mode where one can manually add revoked certificate details or choose an online mode if their issuing CA maintains the revoked list of certificates._

2024-03-04 10:30 UTC, sarangovindarajan commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +Note that the administrator will still have the option to force the user to reset the password on the next login or disable the user.
this line can be removed with the above change.

2024-03-04 11:20 UTC, kalavathig1 commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +To improve security user administrators can no longer explicitly set passwords for other users in the tenant or other tenants' admin. This change prevents an attacker from having access to all users,
I think instead of `The platform has disabled the admin capability ` it can be `The platform has disabled the tenant administrator capability of changing password...`

2024-03-04 11:20 UTC, kalavathig1 commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +Note that the administrator will still have the option to force the user to reset the password on the next login or disable the user.
I think this line is fine.. it gives more info on what admin can still do

2024-03-06 15:01 UTC, BeateRixen commented
@mmed-softwareag please let me know when you have incorporated all feedback and got approval from your team. Then I will start my language review.

2024-03-06 22:46 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-10-18-0-277-10-18-503-23-separate-roles-granting-access-to-managed-objects-and-binary-files.md
> +Security improved by splitting the Inventory role permissions into separate roles for the Managed Objects and Binary.  This enables more granular permissions to be assigned, the existing permissions
done

2024-03-06 22:46 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-10-18-0-277-10-18-503-23-separate-roles-granting-access-to-managed-objects-and-binary-files.md
> +Security improved by splitting the Inventory role permissions into separate roles for the Managed Objects and Binary.  This enables more granular permissions to be assigned, the existing permissions
used Sarans idea.

2024-03-06 22:46 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-10-18-590-0-support-for-certificate-revocation-list.md
> +title: Support for Certificate Revocation List.
done

2024-03-06 22:46 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-10-18-590-0-support-for-certificate-revocation-list.md
> +version: 10.18.590.0
the last fix version of: MTM-41760 (this should contains all sub task merged)

2024-03-06 22:46 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-10-18-590-0-support-for-certificate-revocation-list.md
> +Administrators can configure the Certificate Revocation List (CRL) settings (online or offline). If the revoked certificate information is maintained by the issuing Certificate Authority (CA), the on
done

2024-03-06 22:46 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +title: The administrator cannot change passwords for other users.
for me tenant administrator is administrator of tenant (smbd with Tenant management role). This is why i'm using just Administrator. @sarangovindarajan what do you think?

2024-03-06 22:46 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +Note that the administrator will still have the option to force the user to reset the password on the next login or disable the user.
Do we have some info about it in docs? If not i will leave it - maybe let decide about it for Beate and Marlene?

2024-03-06 22:46 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-undefined-User-administrator-can-no-longer-set-password-for-other-users.md
> +product_area: Platform services
user administrator is better. Is smbd with user management role.

2024-03-06 22:46 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-undefined-User-administrator-can-no-longer-set-password-for-other-users.md
> +product_area: Platform services
user administrator is better. Is smbd with user management role.

2024-03-12 17:35 UTC, kalavathig1 approved these changes

2024-03-15 15:23 UTC, sarangovindarajan requested changes

2024-03-18 09:31 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +title: The administrator cannot change passwords for other users.
```suggestion
title: Administrators cannot change passwords for other users
```

2024-03-18 09:31 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +For security reasons, The platform has disabled the administrator capability of changing passwords of other users. The users are allowed only to change their own passwords. However, Administrators ca
```suggestion
For security reasons, administrators can no longer change passwords of other users. The users are only allowed to change their own passwords. However, administrators can still enforce the users to change their passwords on their next login in case of any anticipated breaches.
```

2024-03-18 09:31 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +Note that the administrator will still have the option to force the user to reset the password on the next login or disable the user.
```suggestion
```

2024-03-18 12:03 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +To improve security user administrators can no longer explicitly set passwords for other users in the tenant or other tenants' admin. This change prevents an attacker from having access to all users,
@kalavathig1 Tenant administrator is suggested to be someone who administers the tenant. Here, it refers to someone with user management privileges. Administrator seems the most appropriate.

2024-03-18 12:22 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-10-20-6-0-the-administrator-cannot-change-passwords-for-other-users.md
> +Note that the administrator will still have the option to force the user to reset the password on the next login or disable the user.
this is outdated: release note in this file looks: For security reasons, administrators can no longer change passwords of other users. The users are only allowed to change their own passwords. However, administrators can still enforce the users to change their passwords on their next login in case of any anticipated breaches.

2024-03-18 13:06 UTC, mmed-softwareag commented on content/change-logs/platform-services/cumulocity-10-18-590-0-support-for-certificate-revocation-list.md
> +Administrators can configure the Certificate Revocation List (CRL) settings. When a certificate is compromised, the platform is now capable of performing the revocation check during the device authen
@BeateRixen when can i find this link. The documentation was added in this PR: https://github.com/SoftwareAG/c8y-docs/pull/1704/files. Is it deployed?

2024-03-18 13:07 UTC, BeateRixen commented
@mmed-softwareag @kalavathig1 @sarangovindarajan In general, I would expect links to the user documentation in case of features.

2024-03-18 13:08 UTC, BeateRixen approved these changes

2024-03-21 08:41 UTC, merged