[MTM-56083]: User guide how to generate device access token using X509 certificate
SoftwareAG/c8y-docs pull request #1795
Opened 2024-03-07 17:11 UTC by cumulocitypans

Documentation is available on :
https://sagportal.sharepoint.com/:w:/r/sites/IoTAnalyticsRnDOps/_layouts/15/doc2.aspx?sourcedoc=%7B489B6AA8-3AFA-44DC-BD83-32DDC4B93F43%7D&file=Enable%20mTLS%20for%20REST.docx&action=default&mobileredirect=true

API documentation :
https://github.softwareag.com/IOTA/cumulocity-openapi/pull/234/

2024-03-08 12:45 UTC, Michal-Bak reviewed
Some small suggestions. My main point is to make it clear in the documentation that we do not support mTLS authentication on every REST API (as it is in MQTT), but only on one API where a token is generated and subsequent requests should use this JWT token.

2024-03-08 12:45 UTC, Michal-Bak commented on .gitignore
> +/c8y-docs.iml
This is from Idea? isn't this in the path /.idea/c8y-docs.iml ?

2024-03-08 12:45 UTC, Michal-Bak commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +Devices can authenticate against the {{< product-c8y-iot >}} platform via mTLS over REST protocol using X.509 client certificates.
Tbh I do not think we should write that c8y support authenticate via mTLS over REST. Or should we explicitly write that the device can exchange a certificate for jwt token and for the next request should use this token? Because atm it sounds like each request can be performed with a certificate and it will be accepted.

2024-03-08 12:45 UTC, Michal-Bak commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +
Did you test it? I'm not convinced this will work

2024-03-08 12:45 UTC, Michal-Bak commented on content/device-integration/device-certificates.md
> +Devices can communicate using the MQTT interface or using rest client of the platform, but MQTT over WebSocket is not supported. The {{< product-c8y-iot >}} platform expects devices to connect using
I would split it up, I would leave this sentence that it can connect via mqtt and on what port. 
And below add that it is possible to connect via REST and generate a JWT token that can be used in subsequent queries via REST.

2024-03-08 17:02 UTC, cumulocitypans commented on .gitignore
> +/c8y-docs.iml
removed unwanted change

2024-03-11 04:18 UTC, saran1239 commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +
I did check this and it works.

2024-03-11 04:20 UTC, saran1239 commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +Devices can authenticate against the {{< product-c8y-iot >}} platform via mTLS over REST protocol using X.509 client certificates.
Fair point. @cumulocitypans we should adjust the content accordingly.

2024-03-11 04:38 UTC, sarangovindarajan commented on content/device-integration/device-certificates.md
> +Devices can generate JWT token using X.509 certificates over REST using mTLS protocol, against the {{< product-c8y-iot >}} using device access token API, it can be used in subsequent requests to auth
Check this rephrased note:
_Devices can also generate JWT session token by using X.509 certificates for authentication over a defined REST endpoint - device access token API. This session token can be used in subsequent requests to authenticate to the platform._

2024-03-11 04:38 UTC, sarangovindarajan commented on content/device-integration/device-certificates.md
> +The user for the device will be created during the first API call, if a device certificate is derived from a trusted certificate which was uploaded to the {{< product-c8y-iot >}} platform with a flag
Check this rephrased sentence:
_The device_user will be created when the API is called for the first time, provided:
- the trusted certificate is uploaded to the platform
- the auto registration is enabled and
- the device certificate is derived from a trusted certificate uploaded to the {{< product-c8y-iot >}} platform_

2024-03-11 04:38 UTC, sarangovindarajan commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +Devices can authenticate against the {{< product-c8y-iot >}} platform via mTLS over REST protocol using X.509 client certificates.
Check the rephrased sentence:
_Devices can authenticate to the {{< product-c8y-iot >}} platform using X509 certificates over a defined REST endpoint protocol to procure the JWT session token._

2024-03-11 04:38 UTC, sarangovindarajan commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +### JWT token retrieval {#jwt-token-retrieval}
Let us call this JWT Session token retrieval

2024-03-11 08:15 UTC, cumulocitypans commented on content/device-integration/device-certificates.md
> +Devices can communicate using the MQTT interface or using rest client of the platform, but MQTT over WebSocket is not supported. The {{< product-c8y-iot >}} platform expects devices to connect using
Done

2024-03-11 11:00 UTC, cumulocitypans commented on content/device-integration/device-certificates.md
> +The user for the device will be created during the first API call, if a device certificate is derived from a trusted certificate which was uploaded to the {{< product-c8y-iot >}} platform with a flag
Done

2024-03-11 11:00 UTC, cumulocitypans commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +### JWT token retrieval {#jwt-token-retrieval}
Done

2024-03-11 11:00 UTC, cumulocitypans commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +Devices can authenticate against the {{< product-c8y-iot >}} platform via mTLS over REST protocol using X.509 client certificates.
Done

2024-03-11 12:14 UTC, cumulocitypans commented on content/device-integration/device-certificates.md
> +Devices can generate JWT token using X.509 certificates over REST using mTLS protocol.
Done

2024-03-11 12:14 UTC, cumulocitypans commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +Devices can authenticate against the {{< product-c8y-iot >}} platform via mTLS over REST protocol using X.509 client certificates.
Done

2024-03-12 17:31 UTC, kalavathig1 commented on content/device-integration/device-certificates.md
> -* The certificate's common name should not contain `:` characters, see [MQTT ClientId](#mqtt-clientid) for more information.
Why is this removed ?

2024-03-12 17:31 UTC, kalavathig1 commented on content/device-integration/device-certificates.md
> -### JWT token retrieval {#jwt-token-retrieval}
Why is this section removed

2024-03-13 07:14 UTC, cumulocitypans commented on content/device-integration/device-certificates.md
> -### JWT token retrieval {#jwt-token-retrieval}
This section is removed from here as here we only describing regarding device certificate (X509) and removed section is here `device-integration->Device integration using MQTT -> MQTT JWT session token retrieval.` Previously it is under name with MQTT example client, now I changed heading to `MQTT JWT session token retrieval` for more relatable.

2024-03-13 07:16 UTC, cumulocitypans commented on content/device-integration/device-certificates.md
> -* The certificate's common name should not contain `:` characters, see [MQTT ClientId](#mqtt-clientid) for more information.
I added this info under `device-integration->Device integration using MQTT -> MQTT JWT session token retrieval.` . This information is also available in section `#mqtt-clientid` also.

2024-03-18 11:25 UTC, BeateRixen commented
@cumulocitypans I have done a language review. Please check my suggestions.

2024-03-18 12:40 UTC, cumulocitypans commented
> @cumulocitypans I have done a language review. Please check my suggestions.

sorry, @BeateRixen I am not able to find out those suggestions :(

2024-03-18 12:43 UTC, BeateRixen commented
> > @cumulocitypans I have done a language review. Please check my suggestions.
> 
> sorry, @BeateRixen I am not able to find out those suggestions :(

Sorry, they should be available now. Forgot to commit.

2024-03-18 14:57 UTC, cumulocitypans commented on content/device-integration/mqtt-bundle/mqtt-connection.md
> +* KEYSTORE_NAME is the path to your keystore, which contains the private key and the chain of certificates, which the device will use to authenticate itself.
Done

2024-03-18 14:57 UTC, cumulocitypans commented on content/device-integration/rest-client-examples-bundle/hello-rest-x509.md
> +The code of the {{< product-c8y-iot >}} client implemented in Java, which connects to the platform using x.509 certificates.
Done

2024-03-19 11:06 UTC, BeateRixen commented on content/device-integration/mqtt-bundle/mqtt-connection.md
> +* KEYSTORE_NAME is the path to your keystore, which contains the private key and the chain of certificates, which the device will use to authenticate itself.
```suggestion
 KEYSTORE_NAME - The path to your keystore which contains the private key and the chain of certificates, which the device uses to authenticate itself.
```

2024-03-19 11:06 UTC, BeateRixen commented on content/device-integration/mqtt-bundle/mqtt-connection.md
> + KEYSTORE_NAME - The path to your keystore which contains the private key and the chain of certificates, which the device uses to authenticate itself.
```suggestion
* KEYSTORE_NAME - The path to your keystore which contains the private key and the chain of certificates, which the device uses to authenticate itself.
```

2024-03-19 11:07 UTC, BeateRixen commented on content/device-integration/rest-client-examples-bundle/hello-rest-x509.md
> +* KEYSTORE_PASSWORD is the password created for keystore to use its private key.
```suggestion
* KEYSTORE_PASSWORD - The password created for keystore to use its private key.
```

2024-03-19 11:08 UTC, BeateRixen commented on content/device-integration/mqtt-bundle/mqtt-connection.md
> +* KEYSTORE_PASSWORD is the password created for keystore to use its private key.
```suggestion
* KEYSTORE_PASSWORD - The password created for keystore to use its private key.
```

2024-03-19 11:09 UTC, BeateRixen commented on content/device-integration/mqtt-bundle/mqtt-connection.md
> +* TRUSTSTORE_NAME is the path to your truststore which contains the certificate of the server.
```suggestion
* TRUSTSTORE_NAME - The path to your truststore which contains the certificate of the server.
```

2024-03-19 11:09 UTC, BeateRixen commented on content/device-integration/mqtt-bundle/mqtt-connection.md
> +* TRUSTSTORE_PASSWORD is the password to access the truststore.
```suggestion
* TRUSTSTORE_PASSWORD - The password to access the truststore.
```

2024-03-19 11:09 UTC, BeateRixen commented on content/device-integration/mqtt-bundle/mqtt-connection.md
> +* TRUSTSTORE_FORMAT must be "JKS" or "PKCS12" depending on the file format. The path is provided by TRUSTSTORE.
```suggestion
* TRUSTSTORE_FORMAT - Either "JKS" or "PKCS12" depending on the file format. The path is provided by TRUSTSTORE.
```

2024-03-19 11:14 UTC, BeateRixen commented on content/device-integration/device-certificates.md
> +Devices can also authenticate to the {{< product-c8y-iot >}} using X.509 certificates over REST (port 443) using mTLS.
@cumulocitypans This sentence should probably go below the first two sentences? It is weird to start with "can also" if nothing has been described before. I would better see after row 14?

2024-03-19 11:16 UTC, BeateRixen commented
@cumulocitypans The bundle "Device integration using MQTT" doesn´t show anything. Probably an index file is missing or you changed the bundle name?

2024-03-19 11:34 UTC, cumulocitypans commented on content/device-integration/device-certificates.md
> +Devices can also authenticate to the {{< product-c8y-iot >}} using X.509 certificates over REST (port 443) using mTLS.
Moved as suggested.

2024-03-19 11:41 UTC, cumulocitypans commented
> @cumulocitypans The bundle "Device integration using MQTT" doesn´t show anything. Probably an index file is missing or you changed the bundle name?

I can see on preview button 
![Screenshot from 2024-03-19 17-10-30](https://github.com/SoftwareAG/c8y-docs/assets/160471970/1cd3b811-daa2-4e92-b3fb-0882d7775200)

2024-03-19 12:00 UTC, BeateRixen commented on content/device-integration/device-certificates.md
> +Devices can also authenticate to the {{< product-c8y-iot >}} using X.509 certificates over REST (port 443) using mTLS.
```suggestion
Devices can authenticate to {{< product-c8y-iot >}} using X.509 certificates over REST (port 443) using mTLS.
```

2024-03-19 12:00 UTC, BeateRixen commented on content/device-integration/device-certificates.md
> +Devices can also generate JWT session tokens by using X.509 certificates for authentication over a defined REST endpoint - device access token API. This session token can be used in subsequent reques
```suggestion
Devices can also generate JWT session tokens by using X.509 certificates for authentication over a defined REST endpoint - device access token API. This session token can be used in subsequent requests to authenticate to {{< product-c8y-iot >}}.
```

2024-03-20 08:36 UTC, BeateRixen approved these changes

2024-03-20 12:49 UTC, sarangovindarajan requested changes

2024-03-20 12:49 UTC, sarangovindarajan commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +title: Device access token
_Title: Device Authentication_

2024-03-20 12:49 UTC, sarangovindarajan commented on content/device-integration/device-integration-rest-bundle/x509-access-token.md
> +Devices can authenticate to the {{< product-c8y-iot >}} platform using X509 certificates over a defined REST endpoint protocol to procure the JWT session token.
Devices can authenticate to the {{< product-c8y-iot >}} platform using 
1. Device User credentials ie., Using Device username and password
2. Certificate Authentication ie., Using X509 certificates over a defined REST endpoint protocol to procure the JWT session token.

2024-03-21 04:55 UTC, sarangovindarajan approved these changes

2024-03-21 05:00 UTC, merged