Format c8y_xxx fragments as code in inline text
SoftwareAG/c8y-docs pull request #183
Opened 2022-01-11 17:15 UTC by JoshuaAdemola

2022-01-12 08:54 UTC, BeateRixen commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +For more information, see `c8y_RequiredAvailability` in [Device management library > Device availability](https://www.{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#section/Device-management-lib
`c8y_RequiredAvailability`  > This is not the name of the section; need to check in new device management library; also the link has changed in another PR

2022-01-12 08:56 UTC, BeateRixen commented on content/protocol-integration/lora-actility-bundle/create-device-protocols.md
> +The message ID should be the same for all the values. Enter the rest of the parameters according to the instructions above. Enter `c8y_Position` in the **Managed object fragment** field and create a
`c8y_Position` > since this refers to something to be entered in the UI it should have quotes (used for UI input), otherwise it is confusing

2022-01-12 08:56 UTC, BeateRixen commented on content/protocol-integration/lora-loriot-bundle/create-loriot-device-protocols.md
> +The message ID should be the same for all the values. Enter the rest of the parameters according to the instructions above. Enter `c8y_Position` in the **Managed object fragment** field and create a
see above

2022-01-12 08:56 UTC, BeateRixen commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +- Enter the type of the measurement. For example, `c8y_AccelerationMeasurement`.
see above 2x

2022-01-12 08:57 UTC, BeateRixen commented on content/protocol-integration/opcua-bundle/device-protocols.md
> +- Enter the type of the measurement, for example, `c8y_AccelerationMeasurement`.
since this refers to something to be entered in the UI it should have quotes (used for UI input), otherwise it is confusing

2022-01-12 08:58 UTC, BeateRixen commented on content/protocol-integration/sigfox-bundle/device-protocols.md
> +The message ID should be the same for all the values. Enter the rest of the parameters according to the instructions above. Enter `c8y_Position` in the **Managed object fragment** field and create a
see above

2022-01-14 08:09 UTC, JoshuaAdemola commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +For more information, see `c8y_RequiredAvailability` in [Device management library > Device availability](https://www.{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#section/Device-management-lib
Fixed

2022-01-14 08:11 UTC, JoshuaAdemola commented on content/protocol-integration/lora-actility-bundle/create-device-protocols.md
> +The message ID should be the same for all the values. Enter the rest of the parameters according to the instructions above. Enter `c8y_Position` in the **Managed object fragment** field and create a
Fixed

2022-01-14 08:11 UTC, JoshuaAdemola commented on content/protocol-integration/lora-loriot-bundle/create-loriot-device-protocols.md
> +The message ID should be the same for all the values. Enter the rest of the parameters according to the instructions above. Enter `c8y_Position` in the **Managed object fragment** field and create a
Fixed

2022-01-14 08:11 UTC, JoshuaAdemola commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +- Enter the type of the measurement. For example, `c8y_AccelerationMeasurement`.
Fixed

2022-01-14 12:20 UTC, MWindel commented on content/users-guide/device-management-bundle/device-details.md
> +The **Location** tab also shows when a device contains `c8y_Position` property. When you send a new c8y-position event, you can set the same c8y-Position fragment on the device and it will automatica
c8y-Position fragment > c8y-position fragment

2022-01-14 12:39 UTC, JoshuaAdemola commented on content/benutzerhandbuch/device-management-de-bundle/device-details.md
> +**Info**: Die Registerkarte **Tracking** wird nur angezeigt, wenn ein Gerät das Attribut `c8y_Position` enthält.
Fixed

2022-01-14 12:41 UTC, JoshuaAdemola commented on content/users-guide/device-management-bundle/device-details.md
> +The **Location** tab also shows when a device contains `c8y_Position` property. When you send a new c8y-position event, you can set the same c8y-Position fragment on the device and it will automatica
In the OpenAPI specification and Device Management Library it is spelt out as "c8y_Position".

2022-01-14 12:44 UTC, JoshuaAdemola commented on content/benutzerhandbuch/device-management-de-bundle/device-details.md
> +**Info**: Die Registerkarte **Tracking** wird nur angezeigt, wenn ein Gerät das Attribut `c8y_Position` enthält.
@BeateRixen  There are other files where this syntax error occurs. Should I fixed them in this PR?

2022-01-17 13:47 UTC, MWindel commented on content/users-guide/device-management-bundle/device-details.md
> +The **Location** tab also shows when a device contains `c8y_Position` property. When you send a new c8y-position event, you can set the same c8y-Position fragment on the device and it will automatica
Then we should unify it.

2022-01-18 11:47 UTC, BeateRixen commented on content/benutzerhandbuch/administration-de-bundle/data-retention.md
> +3. Geben Sie einen Fragmenttypen ein, wenn Sie die zu löschenden Daten genauer spezifizieren möchten. Geben Sie im Feld **Typ** ein "type"-Attribut als Filter ein. Um beispielsweise alle Alarme im Zu
@JoshuaAdemola Did you miss this one?

2022-01-18 11:47 UTC, BeateRixen commented on content/benutzerhandbuch/device-management-de-bundle/device-details.md
> +Die Registerkarte **Standort** zeigt außerdem, wenn ein Gerät das Attribut `c8y_Position` enthält. Wenn Sie ein neues c8y-position-Ereignis senden, können Sie das gleiche c8y-position-Fragment auf de
This is not correct. The name of the fragment is c8y_Position and it should be spelled this way everywhere.

2022-01-18 11:47 UTC, BeateRixen commented on content/users-guide/device-management-bundle/device-details.md
> +The **Location** tab also shows when a device contains `c8y_Position` property. When you send a new c8y-position event, you can set the same c8y-position fragment on the device and it will automatica
see above

2022-01-18 12:07 UTC, JoshuaAdemola commented on content/benutzerhandbuch/administration-de-bundle/data-retention.md
> +3. Geben Sie einen Fragmenttypen ein, wenn Sie die zu löschenden Daten genauer spezifizieren möchten. Geben Sie im Feld **Typ** ein "type"-Attribut als Filter ein. Um beispielsweise alle Alarme im Zu
Yes

2022-01-18 12:07 UTC, JoshuaAdemola commented on content/benutzerhandbuch/device-management-de-bundle/device-details.md
> +Die Registerkarte **Standort** zeigt außerdem, wenn ein Gerät das Attribut `c8y_Position` enthält. Wenn Sie ein neues c8y-position-Ereignis senden, können Sie das gleiche c8y-position-Fragment auf de
Fixed

2022-01-18 12:07 UTC, JoshuaAdemola commented on content/users-guide/device-management-bundle/device-details.md
> +The **Location** tab also shows when a device contains `c8y_Position` property. When you send a new c8y-position event, you can set the same c8y-position fragment on the device and it will automatica
Fixed

2022-01-18 12:51 UTC, JoshuaAdemola commented on content/users-guide/device-management-bundle/device-details.md
> +The **Location** tab also shows when a device contains `c8y_Position` property. When you send a new c8y-position event, you can set the same c8y-Position fragment on the device and it will automatica
Fixed

2022-01-18 12:51 UTC, JoshuaAdemola commented on content/users-guide/administration-bundle/data-retention.md
> +3. Enter a fragment type if you want to be more specific about the data to be cleaned up. To clean up all connection loss alarms with this rule, select "alarms" and enter `c8y_UnavailabilityAlarm` as
Fixed

2022-01-18 12:52 UTC, JoshuaAdemola commented on content/benutzerhandbuch/administration-de-bundle/data-retention.md
> +3. Geben Sie einen Fragmenttypen ein, wenn Sie die zu löschenden Daten genauer spezifizieren möchten. Geben Sie im Feld **Typ** ein "type"-Attribut als Filter ein. Um beispielsweise alle Alarme im Zu
Fixed

2022-01-19 10:20 UTC, BeateRixen submitted a review, later dismissed

2022-01-21 09:48 UTC, MWindel submitted a review, later dismissed

2022-01-21 09:48 UTC, rssag requested changes

2022-01-21 09:48 UTC, rssag commented on content/benutzerhandbuch/device-management-de-bundle/device-details.md
> +**Info:** Die Registerkarte **Tracking** wird nur angezeigt, wenn ein Gerät das Attribut `c8y_Position` enthält.
```suggestion
>**Info:** Die Registerkarte **Tracking** wird nur angezeigt, wenn ein Gerät das Attribut `c8y_Position` enthält.
```

2022-01-21 09:48 UTC, rssag commented on content/users-guide/device-management-bundle/device-details.md
> +**Note** that the **Tracking** tab only shows up when a device contains `c8y_Position` property.
```suggestion
>**Info: ** The **Tracking** tab only shows up when a device contains `c8y_Position` property.
```

2022-01-21 09:53 UTC, rssag approved these changes

2022-01-21 09:57 UTC, BeateRixen approved these changes

2022-01-21 09:58 UTC, MWindel approved these changes

2022-01-21 10:19 UTC, merged