Feature/r10.18.0  cdh 4491
SoftwareAG/c8y-docs pull request #1837
Opened 2024-03-20 18:24 UTC by UlrichPost

This is a first draft based on the version for 10.17 which had been reviewed by Christoph alerwady.

This new PR requires review by
- Christoph Heinz
- Tim Doernemann
- Bhaskar Reddy Byreddy

Formatting needs to be fixed (=> Christoph)
A few open questions have been marked by "???"

2024-03-21 09:43 UTC, doernemt requested changes

2024-03-21 09:43 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +When {{< product-c8y-iot >}} DataHub Edge on Kubernetes is deployed on top, the hardware requirements of the virtual machine are as follows:
When {{< product-c8y-iot >}} DataHub Edge on Kubernetes is deployed on top, the RESOURCE requirements change as follows:

2024-03-21 09:43 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| dremio-values.yaml | Configuration for deployment of Dremio |
Seems inconsistent. Column title is "Requires Adaption". First line: yes, this line: WHAT needs to be changed

2024-03-21 09:43 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| mysql-values.yaml | Configuration for deployment of MySQL database used to store DataHub configuration data |
See above

2024-03-21 09:43 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The mount path (e.g. "/datalake") then needs to be specified when configuring the initial settings in the DataHub UI,
Why do we give a choice here? Mount path IS /datalake

2024-03-21 09:43 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +However, there are installation constraints checked by the installation procedure which may not be exceeded:
licensing constraints

2024-03-21 09:43 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +After you have logged in to Cumulocity UI using the browser of your choice you should be able to navigate to the DataHub webapp as for any cloud setup.
The product behaves like the Cloud and Edge appliance version. Please refer to the general documentation.

2024-03-21 09:43 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +If that does not work, you may go through the validation stepes described below.
If the product doesn't work as intended after the installation, please go through the validation steps described below.

2024-03-21 09:43 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +kubectl get pods -n c8yedge datahub-mysql-0 --watch
Why no expected output here?

2024-03-21 09:43 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +```
Note: the exact name of the microservice instance varies, but it is always prefixed with `datahub-scope-edge-deployment-'

2024-03-21 09:43 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +When logged in to Cumulocity UI you should see the DataHub web application in
It should also be present in the usual {{< product-c8y-iot >}} Application Switcher.

2024-03-21 12:29 UTC, bbyreddy commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| mysql-values.yaml | Deployment configuration for MySQL database, which is used to store configuration data | - |
- [ ] Don't we need to adapt dremio-values.yaml and mysql-values.yaml files? In which case, the last column should have YES

2024-03-21 12:29 UTC, bbyreddy commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The distributed storage as well as the datalake storage need to be available as a volume mounted into the Dremio master pod. The mount path (e.g. "/datalake") then needs to be specified when configur
- [ ] Not clear what should the values be for "distStorage" and <DATALAKE_CONFIGURATION>
- [ ] Are these mandatory, if so, can we have some default values?

2024-03-21 12:29 UTC, bbyreddy commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +Execute the following command to prepare the required persistent volumes:
- [ ] Does ./install.sh -a just creates the required persistent volumes or even install the product?

2024-03-21 16:25 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/datahub-edge-overview.md
> +
Should be addressed now

2024-03-22 06:57 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| {{< product-c8y-iot >}} DataHub Edge on Kubernetes archive | You have downloaded the archive datahub-edgek8s.tar from the [{{< company-sag >}} {{< sag-portal >}}]({{< link-sag-portal >}}). |
Yes, it is a tar: all reasonably big files are already zipped

2024-03-22 07:06 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +When {{< product-c8y-iot >}} DataHub Edge on Kubernetes is deployed on top, the hardware requirements of the virtual machine are as follows:
@doernemt wording changed, but: these resource requirements are *on top*, correct? 
We might want to use a wording like "..., the ADDITIONAL resource requirements are" or "..., the resource requirements INCREASE BY following values:"

2024-03-22 07:07 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The hardware requirements for running a bare {{< product-c8y-iot >}} Edge instance are described in section [Requirements](/edge/installation#prerequisites).
Changed - to be verified in rendered representation.

2024-03-22 07:10 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +Execute the following command to prepare the required persistent volumes:
Left over from preceding (10.17) version of documentation - of course it triggers the documentation.

2024-03-22 07:17 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +```
replaced suffix by "XXXXXXXXXX-YYYYY"

2024-03-23 09:08 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| Kubernetes | A Linux machine with admin access using kubectl and helm to Kubernetes target environment, bash and jq command line tool must be available |
Fixed wording

2024-03-25 09:56 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +After you have logged in to Cumulocity UI using the browser of your choice you should be able to navigate to the DataHub webapp as for any cloud setup.
Changed

2024-03-25 09:57 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +When logged in to Cumulocity UI you should see the DataHub web application in
Added

2024-03-25 09:58 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/datahub-edge-overview.md
> +* An appliance running in a Linux VM deployed into a supported hypervisor; in this setup, the {{< product-c8y-iot >}} DataHub backend, the Dremio master, and the Dremio executor are running as Docker
Changed

2024-03-25 09:59 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +In this setup the application is deployed into a Kubernetes environment using an operator. The {{< product-c8y-iot >}} DataHub backend is run as a microservice within the {{< product-c8y-iot >}} plat
Changed

2024-03-25 10:00 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +TODO @UPO: Which registry and repository?
Done

2024-03-25 10:01 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/datahub-edge-overview.md
> +* An operator-based deployment into a Kubernetes environment; in this setup, the {{< product-c8y-iot >}} DataHub backend is running as a microservice within the {{< product-c8y-iot >}} platform while
Done

2024-03-25 10:02 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| Kubernetes | An environment with bash, jq, and admin access to Kubernetes via kubectl and helm command line tools. |
Fixed

2024-03-25 10:03 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| {{< product-c8y-iot >}} Edge on Kubernetes  | The corresponding version of {{< product-c8y-iot >}} Edge being set up in the Kubernetes environment; see also [Installing Cumulocity IoT Edge on Kuber
Fixed

2024-03-25 10:04 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +Subsequently, it is assumed that {{< product-c8y-iot >}} Edge on Kubernetes has been installed using the default Kubernetes namespace **c8yedge**. If another namespace has been chosen, you need to ad
Changed

2024-03-25 10:04 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +Subsequently, it is assumed that {{< product-c8y-iot >}} Edge on Kubernetes has been installed using the default Kubernetes namespace **c8yedge**. If another namespace has been chosen, you need to ad
Done

2024-03-25 10:06 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +After you have logged into the {{< product-c8y-iot >}} UI, you should be able to navigate to the {{< product-c8y-iot >}} DataHub UI by selecting the corresponding entry in the application switcher.
Wording had been changed already as suggested by Tim:
"{{< product-c8y-iot >}} DataHub Edge on Kubernetes behaves like the Cloud and Edge appliance version. Please refer to the general documentation."

2024-03-25 11:39 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| {{< product-c8y-iot >}} DataHub Edge on Kubernetes archive | You have downloaded the archive **datahub-edgek8s.tar** from the [{{< company-sag >}} {{< sag-portal >}}]({{< link-sag-portal >}}). |
```suggestion
| {{< product-c8y-iot >}} DataHub Edge on Kubernetes archive | You have downloaded the archive *datahub-edgek8s.tar* from the [{{< company-sag >}} {{< sag-portal >}}]({{< link-sag-portal >}}). |
```

2024-03-25 11:39 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| {{< product-c8y-iot >}} Edge on Kubernetes  | The corresponding version of {{< product-c8y-iot >}} Edge being set up in the Kubernetes environment; see also [Installing {{< product-c8y-iot >}} Edge
```suggestion
| {{< product-c8y-iot >}} Edge on Kubernetes  | The corresponding version of {{< product-c8y-iot >}} Edge being set up in the Kubernetes environment; see also [Installing {{< product-c8y-iot >}} Edge on Kubernetes](/guides/10.17.0/edge-k8s/installing-edge-on-k8) |
```

2024-03-25 11:39 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The resource requirements for running a bare {{< product-c8y-iot >}} Edge instance are described in section [Requirements](/edge-k8s/installing-edge-on-k8/#prerequisites).
```suggestion
The resource requirements for running a bare {{< product-c8y-iot >}} Edge instance are described in [Requirements](/edge-k8s/installing-edge-on-k8/#prerequisites). 
```

2024-03-25 11:39 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/datahub-edge-overview.md
> +* An operator-based deployment into a Kubernetes environment. In this setup, the {{< product-c8y-iot >}} DataHub backend is running as a microservice within the {{< product-c8y-iot >}} platform while
```suggestion
* An operator-based deployment into a Kubernetes environment. In this setup, the {{< product-c8y-iot >}} DataHub backend is running as a microservice within the {{< product-c8y-iot >}} platform while Dremio master and executor are deployed as a set of the Kubernetes pods
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The respective configuration in dremio-values.yaml may look as follows:
```suggestion
The respective configuration in *dremio-values.yaml* may look as follows:
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +If your Kubernetes cluster has only a single worker node, i.e. both pods are running on the same node and you can use a subfolder of /datalake mounted to a hostpath as shown above.
```suggestion
If your Kubernetes cluster has only a single worker node, that means, both pods are running on the same node and you can use a subfolder of */datalake* mounted to a hostpath as shown above.
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The **$DREMIO_USER** and **$DREMIO_PASSWORD** credentials are substituted during installation based on the values provided in datahub-config.json.
```suggestion
The ``$DREMIO_USER`` and ``$DREMIO_PASSWORD`` credentials are substituted during installation based on the values provided in *datahub-config.json*.
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +* only one executor
```suggestion
* Only one executor
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The **$MYSQL_PASSWORD** is substituted during installation based on the value provided in datahub-config.json.
```suggestion
The ``$MYSQL_PASSWORD`` is substituted during installation based on the value provided in *datahub-config.json*. 
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +In order to access Dremio, the following entry needs to be added to /etc/hosts:
```suggestion
In order to access Dremio, the following entry needs to be added to */etc/hosts*:
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +where **domain_name** is the domain name chosen during the installation of {{< product-c8y-iot >}} Edge on Kubernetes.
```suggestion
where ``domain_name`` is the domain name chosen during the installation of {{< product-c8y-iot >}} Edge on Kubernetes.
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +{{< product-c8y-iot >}} DataHub Edge on Kubernetes behaves like the Cloud and Edge appliance version. Please refer to the general documentation.
```suggestion
{{< product-c8y-iot >}} DataHub Edge on Kubernetes behaves like the Cloud and Edge appliance version.
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +In case of problems, run the following validation steps:
@UlrichPost The steps are missing, I gather this is the part that is still to be done?

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +You can monitor the startup of the MySQL pod **datahub-mysql-0** using
```suggestion
You can monitor the startup of the MySQL pod ``datahub-mysql-0`` using
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The result should be similar to:
```suggestion
The result will be similar to:
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +the output should be similar to:
```suggestion
the output will be similar to:
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The status *Running* indicates that the pods have started successfully:
```suggestion
The status "Running" indicates that the pods have started successfully:
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +You can monitor the state of the Dremio pods *zk-0*, *dremio-executor-0*, and *dremio-master-0* using
```suggestion
You can monitor the state of the Dremio pods "zk-0", "dremio-executor-0", and "dremio-master-0" using
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +the output should be similar to
```suggestion
the output will be similar to 
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +You can monitor the startup of the microservice pod *datahub-scope-edge-deployment-....* using
```suggestion
You can monitor the startup of the microservice pod "datahub-scope-edge-deployment-...." using
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +You can monitor the startup of the microservice pod *datahub-scope-edge-deployment-....* using
@UlrichPost The "..." in the pod name is to be determined or is this part of the real name?

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The status *Running* indicates that the pod has started successfully:
```suggestion
The status "Running" indicates that the pod has started successfully:
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge.md
> +title: Setting up Cumulocity IoT DataHub Edge as Appliance
```suggestion
title: Setting up Cumulocity IoT DataHub Edge as an Appliance
```

2024-03-25 13:13 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge.md
> +Before setting up {{< product-c8y-iot >}} DataHub Edge as appliance, you must check the following prerequisites:
```suggestion
Before setting up {{< product-c8y-iot >}} DataHub Edge as an appliance, you must check the following prerequisites:
```

2024-03-25 13:29 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +You can monitor the startup of the microservice pod *datahub-scope-edge-deployment-....* using
@MWindel : "..." indicates that the suffix of the name may vary for every excecution / in every environment.

2024-03-25 16:57 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +In this setup the application is deployed into a Kubernetes environment using an operator. The {{< product-c8y-iot >}} DataHub backend is run as a microservice within the {{< product-c8y-iot >}} plat
```suggestion
In this setup the application is deployed into a Kubernetes environment using an operator. The {{< product-c8y-iot >}} DataHub backend is run as a microservice within the {{< product-c8y-iot >}} platform. The Dremio master and executor are deployed as a set of the Kubernetes pods.
```

2024-03-25 16:57 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +Subsequently, it is assumed that {{< product-c8y-iot >}} Edge on Kubernetes has been installed using the default Kubernetes namespace **c8yedge**. If another namespace has been chosen, you must adapt
```suggestion
Subsequently, it is assumed that {{< product-c8y-iot >}} Edge on Kubernetes has been installed using the default Kubernetes namespace ``c8yedge``. If another namespace has been chosen, you must adapt the commands and configuration files accordingly.
```

2024-03-25 16:57 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The datalake storage needs to be available as a volume mounted into the Dremio master and executor pods. The mount path (typically "/datalake") later needs to be specified when configuring the initia
```suggestion
The datalake storage needs to be available as a volume mounted into the Dremio master and executor pods. The mount path (typically ``/datalake``) later needs to be specified when configuring the initial settings in the DataHub UI.
```

2024-03-25 16:57 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +If your Kubernetes cluster has only a single worker node, that means, both pods are running on the same node and you can use a subfolder of */datalake* mounted to a hostpath as shown above.
```suggestion
If your Kubernetes cluster has only a single worker node, that means, both pods are running on the same node and you can use a subfolder of ``/datalake`` mounted to a hostpath as shown above.
```

2024-03-25 16:57 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +In order to access Dremio, the following entry needs to be added to */etc/hosts*:
```suggestion
In order to access Dremio, the following entry needs to be added to ``/etc/hosts``:
```

2024-03-25 16:57 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +the output will be similar to:
```suggestion
The output will be similar to:
```

2024-03-25 16:57 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +When running the command
```suggestion
When running the command:
```

2024-03-25 16:57 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +When running the command
```suggestion
When running the command:
```

2024-03-25 16:57 UTC, MWindel commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +the output will be similar to
```suggestion
The output will be similar to:
```

2024-03-25 16:58 UTC, MWindel approved these changes

2024-03-26 17:54 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +If that does not work, you may go through the validation stepes described below.
Adapted wording

2024-03-26 17:57 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The distributed storage as well as the datalake storage need to be available as a volume mounted into the Dremio master pod. The mount path (e.g. "/datalake") then needs to be specified when configur
Hi @bbyreddy 
this has been simplified now. Please check modified documentation.
Also, you might go through a second installation if you are interested.

2024-03-27 09:29 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +In case of problems, run the following validation steps:
No - the section "Configuring Dremio deployment via dremio-values.yaml required updates.

2024-03-27 09:33 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The mount path (e.g. "/datalake") then needs to be specified when configuring the initial settings in the DataHub UI,
Mount path "/datalake" is now fixed, no more mentioned in documentation

2024-03-27 09:35 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +However, there are installation constraints checked by the installation procedure which may not be exceeded:
Fixed

2024-03-27 09:36 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| dremio-values.yaml | Configuration for deployment of Dremio |
Fixed

2024-03-27 09:36 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +| mysql-values.yaml | Configuration for deployment of MySQL database used to store DataHub configuration data |
Fixed

2024-03-27 10:10 UTC, doernemt approved these changes
Thanks for the updates. Looks good to me!

2024-03-27 12:53 UTC, BeateRixen commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +#### DataHub Web Application
```suggestion
#### DataHub web application
```

2024-03-27 12:53 UTC, BeateRixen commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +It should also be present in the usual {{< product-c8y-iot >}} Application Switcher.
```suggestion
It should also be present in the usual {{< product-c8y-iot >}} application switcher.
```

2024-03-27 12:53 UTC, BeateRixen commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge.md
> +title: Setting up Cumulocity IoT DataHub Edge as an Appliance
```suggestion
title: Setting up Cumulocity IoT DataHub Edge as an appliance
```

2024-03-27 12:53 UTC, BeateRixen commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge.md
> +In this setup an appliance is run within a Linux VM, which in turn is deployed into a supported hypervisor.The {{< product-c8y-iot >}} DataHub Edge backend, the Dremio master, and the Dremio executor
```suggestion
In this setup an appliance is run within a Linux VM, which in turn is deployed into a supported hypervisor. The {{< product-c8y-iot >}} DataHub Edge backend, the Dremio master, and the Dremio executor are running as Docker containers within the appliance.
```

2024-03-27 12:54 UTC, BeateRixen commented
@UlrichPost I found some minor spelling/wording stuff by scanning through the document.

2024-03-27 14:39 UTC, UlrichPost commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
> +The resource requirements for running a bare {{< product-c8y-iot >}} Edge instance are described in [Requirements](/edge-k8s/installing-edge-on-k8/#prerequisites).
No - this is a subsection of a section called "Prerequisites". 
Similarly, for old documentation of installation on Edge appliance, we have "Hardware requirements" as a subsection of "Prerequisites".
For installation on Edge on Kubernetes we have just replaced the term "Hardware" by "Resource" due to the virtual nature of the target environment.

2024-03-27 14:54 UTC, BeateRixen approved these changes

2024-03-27 14:56 UTC, merged