Feature/mtm 56466 dashboards redesign annoucement
SoftwareAG/c8y-docs pull request #1875
Opened 2024-03-28 12:46 UTC by DawidSAG

2024-03-28 13:30 UTC, janhommes approved these changes

2024-03-28 13:32 UTC, eniosultan approved these changes

2024-03-28 13:40 UTC, jdreSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +* Undo/redo functionality for flexible editing.
```suggestion
* Possibility to enable and disable dashboard template for device dashboards.
* Versioning to manage and track dashboard changes.
* Undo/redo functionality for flexible editing.
```

2024-03-28 13:43 UTC, DawidSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +* Undo/redo functionality for flexible editing.
done

2024-03-28 15:19 UTC, DawidSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +**Visual and UX Enhancements**:
```suggestion
**Visual and UX enhancements**:
```

2024-03-28 15:19 UTC, DawidSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +In a future version, we are introducing redesigned dashboards with both visual and functional enhancements, as well as new functionalities.
```suggestion
In a future version, we will introduce redesigned dashboards with both visual and functional enhancements, as well as new functionalities.
```

2024-03-28 15:19 UTC, DawidSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +**Functional Improvements**:
```suggestion
**Functional improvements**:
```

2024-03-28 15:20 UTC, DawidSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +**New Features**:
```suggestion
**New features**:
```

2024-04-02 05:37 UTC, jdreSAG approved these changes

2024-04-02 06:54 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +In a future version, we will introduce redesigned dashboards with both visual and functional enhancements, as well as new functionalities.
```suggestion
In a future version, we will introduce redesigned dashboards with both visual and functional enhancements as well as new functionalities.
```

2024-04-02 06:57 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +* We have introduced an edit mode for dashboards.
This is included in the second item, isn´t it?

2024-04-02 13:44 UTC, rahultsag requested changes

2024-04-02 13:51 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +In a future version, we will introduce redesigned dashboards with both visual and functional enhancements as well as new functionalities.
```suggestion
In the upcoming version, we will introduce redesigned dashboards with both visual and functional enhancements as well as new functionalities.
```

2024-04-02 13:53 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +* We have introduced an edit mode for dashboards.
```suggestion
```

2024-04-02 13:54 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +**New features**:
```suggestion
**New functionalities**:
```

2024-04-02 13:55 UTC, rahultsag approved these changes

2024-04-02 13:56 UTC, BeateRixen commented
@DawidSAG Could we add a link to the user documentation such as "For details refer to xxx".

2024-04-03 11:28 UTC, DawidSAG commented
> @DawidSAG Could we add a link to the user documentation such as "For details refer to xxx".

You would like to add link to: https://cumulocity.com/docs/cockpit/working-with-dashboards/ ?

2024-04-03 11:33 UTC, BeateRixen commented
> > @DawidSAG Could we add a link to the user documentation such as "For details refer to xxx".
> 
> You would like to add link to: https://cumulocity.com/docs/cockpit/working-with-dashboards/ ?

Yes, I think it makes sense to point users to the place where they can find more details.

2024-04-03 12:04 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-dashboards-redesign-and-improvements.md
> +For details refer to: [Working with dashboards](https://cumulocity.com/docs/cockpit/working-with-dashboards/).
```suggestion
For details refer to [Working with dashboards](https://cumulocity.com/docs/cockpit/working-with-dashboards/).
```

2024-04-03 12:05 UTC, merged