MTM-52611 add alarms redesign announcement
SoftwareAG/c8y-docs pull request #1877
Opened 2024-03-28 14:09 UTC by DawidSAG

2024-03-28 14:11 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-alarms-redesign-and-improvements.md
> +In a future version, we are introducing redesigned alarms with both visual and functional enhancements.
```suggestion
In a future version, we will introduce redesigned alarms with both visual and functional enhancements.
```

2024-03-28 14:14 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-alarms-redesign-and-improvements.md
> +**Visual and UX Enhancements**:
```suggestion
**Visual and UX enhancements**:
```

2024-03-28 14:14 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-alarms-redesign-and-improvements.md
> +**Functional Improvements**:
```suggestion
**Functional improvements**:
```

2024-03-28 14:14 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-alarms-redesign-and-improvements.md
> +* The "Alarms" view now shows only a single list of alarms, where filters can be applied.
```suggestion
* The "Alarms" view now only shows one single list of alarms, in which filters can be applied.
```

2024-03-28 14:14 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-alarms-redesign-and-improvements.md
> +* We have introduced a details section, which contains all information related to the alarm.
```suggestion
* A details section has been introduced which contains all information related to the alarm.
```

2024-03-28 14:14 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-alarms-redesign-and-improvements.md
> +* The Alarm list widget has been migrated to Angular.
```suggestion
* The "Alarm list" widget has been migrated to Angular.
```

2024-03-28 14:14 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-alarms-redesign-and-improvements.md
> +* Real-time functionality has been replaced with Auto refresh.
```suggestion
* The real-time functionality has been replaced with an auto-refresh functionality.
```

2024-04-02 13:44 UTC, rahultsag requested changes

2024-04-02 14:00 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-alarms-redesign-and-improvements.md
> +In the upcoming version, we will introduce redesigned alarms with both visual and functional enhancements.
```suggestion
In the upcoming version, a redesign of the alarms feature will be introduced with both visual and functional enhancements.
```

2024-04-02 14:01 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-alarms-redesign-and-improvements.md
> +* We have redesigned the way alarms are displayed in the "Alarms" view and widgets.
```suggestion
* The way alarms are displayed in the "Alarms" view and widgets has been redesigned.
```

2024-04-02 14:02 UTC, BeateRixen approved these changes

2024-04-02 14:47 UTC, rahultsag approved these changes

2024-04-03 08:07 UTC, BeateRixen commented
@DawidSAG Can be merged from my side.

2024-04-03 10:40 UTC, merged