[MTM-53448] Announcement of removal od deprecated JWT login mode from…
SoftwareAG/c8y-docs pull request #1915
Opened 2024-04-08 11:14 UTC by Michal-Bak

Announcement of removal of old deprecated JWT login mode from 10.20+

2024-04-08 12:17 UTC, pink-mongoose requested changes
This need to be re-written so that is scans more easily. I have scheduled a meeting to do this.

2024-04-22 11:35 UTC, BeateRixen commented
> This need to be re-written so that is scans more easily. I have scheduled a meeting to do this.

@pink-mongoose Any update here?

2024-04-22 11:47 UTC, Michal-Bak commented
> > This need to be re-written so that is scans more easily. I have scheduled a meeting to do this.
> 
> @pink-mongoose Any update here?

we already rephrased this release note, and I will push it, as soon as I manage to place the script in the public repository I want to reference it here

2024-04-22 13:10 UTC, pink-mongoose approved these changes

2024-04-22 13:11 UTC, pink-mongoose commented
> > > This need to be re-written so that is scans more easily. I have scheduled a meeting to do this.
> > 
> > 
> > @pink-mongoose Any update here?
> 
> @BeateRixen we already rephrased this release note, and I will push it, as soon as I manage to place the script in the public repository I want to reference it here

I have approved

2024-04-22 13:24 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +title: Removal of Deprecated JWT login mode
```suggestion
title: Removal of deprecated JWT login mode
```

2024-04-22 13:37 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +JWT authentication with Cumulocity provider which is deprecated from version 10.6 will be removed.
```suggestion
The JWT authentication with Cumulocity provider which is deprecated since version 10.6 will be removed.
```

2024-04-22 13:37 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +Not to be confused with SSO or OAI-Secure (OAuth-Internal) authentication, which are recommended and still supported.
```suggestion
This is not to be confused with SSO or OAI-Secure (OAuth-Internal) authentication, which are recommended and still supported.
```

2024-04-22 13:37 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +Deprecated authentication using JWT token with Cumulocity provider is not supported by UI applications, tokens are generated by the client and not by Cumulocity applications.
```suggestion
The deprecated authentication using JWT token with Cumulocity provider is not supported by UI applications. The tokens are generated by the client and not by the Cumulocity IoT applications.
```

2024-04-22 13:37 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +Tokens are sent to the cumulocity using the Authorization: Bearer header.
```suggestion
Tokens are sent to the the Cumulocity IoT platform using the Authorization: Bearer header.
```

2024-04-22 13:37 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +To verify that in the environment deprecated JWT is not used needs to be verified two things, this must be done by the operations team that has access to the database:
```suggestion
To verify that the deprecated JWT is not used in your environment follow the 2 steps below. This must be done by the operations team that has access to the database:
```

2024-04-22 13:37 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +1. Verify in the management database in tenants' collections any not empty authenticationProviders configuration exists.
```suggestion
1. Verify if any empty authenticationProviders configuration exists in the management database in the tenants' collections.
```

2024-04-22 13:37 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +2. Verify if any tenant has configured tenant options with the category "token.publicKey".
```suggestion
2. Verify if any tenant has configured the tenant options with the category "token.publicKey".
```

2024-04-22 13:37 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +If the “authenticationProvider” or tenant option with the "token.publicKey" category exists it may indicate that a deprecated jwt is or was used in the past.
```suggestion
If the “authenticationProvider” or tenant option with the "token.publicKey" category exists it may indicate that a deprecated JWT is or was used in the past.
```

2024-04-22 13:37 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +Please note that all usages of 'deprecated jwt' can be replaced with the currently supported authentication login method
```suggestion
Please note that all usages of the deprecated JWT can be replaced with the currently supported authentication login method
```

2024-04-22 13:37 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +using [SSO](https://cumulocity.com/guides/users-guide/administration/#configuring-single-sign-on) or [authentication with external tokens](https://cumulocity.com/guides/users-guide/administration/#co
```suggestion
using [SSO](/authentication/sso/) or [authentication with external tokens](/authentication/basic-settings/#token-generation-with-oai-secure).
```

2024-04-22 13:38 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +using [SSO](https://cumulocity.com/guides/users-guide/administration/#configuring-single-sign-on) or [authentication with external tokens](https://cumulocity.com/guides/users-guide/administration/#co
Please always refer to our latest documentation.

2024-05-06 09:18 UTC, BeateRixen commented
@Michal-Bak Can you please take a look at my comments and commit them or comment?

2024-05-07 10:19 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +The JWT authentication with Cumulocity provider which is deprecated since version 10.6 will be removed.
```suggestion
The JWT authentication with Cumulocity provider, which is deprecated since version 10.6, will be removed.
```

2024-05-07 10:20 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +Tokens are sent to the the Cumulocity IoT platform using the Authorization: Bearer header.
```suggestion
Tokens are sent to the Cumulocity IoT platform using the Authorization: Bearer header.
```

2024-05-07 10:21 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +1. Verify if any empty authenticationProviders configuration exists in the management database in the tenants' collections.
```suggestion
1. Verify if any empty `authenticationProviders` configuration exists in the management database in the tenants' collections.
```

2024-05-07 10:23 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +If the “authenticationProvider” or tenant option with the "token.publicKey" category exists it may indicate that a deprecated JWT is or was used in the past.
```suggestion
If the `authenticationProvider` configuration or a tenant option with the `token.publicKey` category exists it may indicate that a deprecated JWT is or was used in the past.
```

2024-05-07 10:23 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +2. Verify if any tenant has configured the tenant options with the category "token.publicKey".
```suggestion
2. Verify if any tenant has configured the tenant options with the category `token.publicKey`.
```

2024-05-07 10:24 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +In that case, check whether external services do not use this type of authentication.
```suggestion
In this case, check that external services do not use this type of authentication.
```

2024-05-07 10:25 UTC, BeateRixen approved these changes

2024-05-13 07:02 UTC, kalavathig1 commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +version: "10.20"
in the ticket target version is 10.17
![image](https://github.com/SoftwareAG/c8y-docs/assets/157797498/b5bb1d53-536a-47cd-87ea-7efa3a5d6dc6)
I think you need to change in ticket

2024-05-27 10:05 UTC, Michal-Bak commented
-Updated announcement after re-written with @pink-mongoose.
- Link in the announcement script for the self-hosted customer which was placed on the KB page by Jelle at https://cumulocity.atlassian.net/browse/MTM-56764. 
Please re-review.

2024-05-27 13:42 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +JWT authentication with Cumulocity, which was deprecated in version 10.6, will be removed during Q3 2024 for SaaS instance and 2025 for the annual release.
```suggestion
JWT authentication with {{< product-c8y-iot >}} is deprecated since release 10.6 and will be removed in Q3 2024 for the SaaS instances and in 2025 for the yearly releases.
```

2024-05-27 13:42 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +This authentication method should not be confused with SSO or OAI-Secure authentication, which are recommended and still supported.
```suggestion
This authentication method is not to be confused with SSO (single sign-on) or OAI-Secure authentication, which are both recommended and still supported.
```

2024-05-27 13:42 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +This change will only impact you if your organisation was an early adopter of SSO on Cumulocity.
```suggestion
This change will only impact you if your organization was an early adopter of SSO on {{< product-c8y-iot >}}.
```

2024-05-27 13:42 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +For customers on public Cloud we will have been in touch with you if you are using this type of authentication.
```suggestion
For customers on the public cloud instances we get in touch with you if you are using this type of authentication.
```

2024-05-27 13:42 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +Ask your Operations Team to run the [script](https://getsupport.softwareag.com/servicedesk/customer/kb/view/429359127). This will verify
```suggestion
Ask your Operations team to run this [script](https://getsupport.softwareag.com/servicedesk/customer/kb/view/429359127). This will verify
```

2024-05-27 13:42 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +whether any tenant collections have an authenticationProviders configuration, and
```suggestion
whether any tenant collections have an `authenticationProviders` configuration and
```

2024-05-27 13:42 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +verify if any tenant has tenant options configured with the category "token.publicKey".
```suggestion
if any tenant has the tenant options configured with the category `token.publicKey`.
```

2024-05-27 13:42 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +If either an “authenticationProvider” configuration or the tenant option "token.publicKey" category exists it will indicate that the deprecated JWT is, or was, used in the past. In this case you need
```suggestion
If either an `authenticationProvider` configuration or the tenant option `token.publicKey` category exists this indicates that the deprecated JWT is, or was, used in the past. In this case you need to check your external services for use of the JWT authentication and change it to use either SSO or OAI-Secure. These two methods provide a better and more secure approach to authentication.
```

2024-05-27 13:42 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +These two methods are documented here: using [SSO](https://cumulocity.com/docs/authentication/sso/#configuration) or [authentication with external tokens](https://cumulocity.com/docs/authentication/s
```suggestion
These methods are documented here: 
- [Single sign-on](https://cumulocity.com/docs/authentication/sso/#configuration)
- [Token generation with OAI-Secure](https://cumulocity.com/docs/authentication/sso/#configuring-access-tokens).
```

2024-05-27 13:42 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +version: "10.20"
```suggestion
version: 10.20.0
```

2024-05-27 13:58 UTC, BeateRixen approved these changes

2024-05-27 14:33 UTC, kalavathig1 commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +This change will only impact you if your organization was an early adopter of SSO on {{< product-c8y-iot >}}.
`early adopter ` is very generic. Should we mention which versions or what time frame adopter will be impacted ?

2024-05-28 08:14 UTC, Michal-Bak commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +This change will only impact you if your organization was an early adopter of SSO on {{< product-c8y-iot >}}.
TBH this was introduced in ~9.1 version and I can't say what version it was exactly

2024-05-28 08:23 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +This change will only impact you if your organization was an early adopter of SSO on {{< product-c8y-iot >}}.
then perhaps better say "used an early version of SSO"?

2024-05-28 11:01 UTC, kalavathig1 approved these changes

2024-05-28 11:53 UTC, BeateRixen commented
@pink-mongoose Can you please give a final approval?

2024-06-03 10:35 UTC, pink-mongoose commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +JWT authentication with {{< product-c8y-iot >}} is deprecated since release 10.6 and will be removed in Q3 2024 for the SaaS instances and in 2025 for the yearly releases.
```suggestion
JWT authentication with {{< product-c8y-iot >}} has been deprecated since release 10.6 and will be removed in Q3 2024 for the SaaS instances and in 2025 for the yearly releases.
```

2024-06-03 10:36 UTC, pink-mongoose commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +For customers on the public cloud instances we get in touch with you if you are using this type of authentication.
```suggestion
For customers on the public cloud instances we will get in touch with you if you are using this type of authentication.
```

2024-06-03 10:38 UTC, pink-mongoose approved these changes

2024-06-03 10:40 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10-20-removal-of-deprecated-jwt-login-mode.md
> +date: ""
```suggestion
date: 2024-06-03
```

2024-06-03 10:40 UTC, BeateRixen approved these changes

2024-06-03 10:41 UTC, merged