[DTM] - Complex property ordering
SoftwareAG/c8y-docs pull request #1958
Opened 2024-04-18 04:21 UTC by Vagdevi1998

Documents complex property ordering.

2024-04-18 05:06 UTC, lra-sag commented on content/dtm/asset-types-bundle/asset-properties.md
> +A complex asset property consists of multiple key value pairs, meaning, it contains a root object followed by one or more key value pairs. You can select the complex asset property option by switchin
```suggestion
A complex asset property consists of multiple key value pairs, meaning, it contains a root object followed by one or more key value pairs. You can select the complex asset property option by switching on the toggle. If you switch on the toggle, you must define each key value pair as well as providing a Type for each pair. You can arrange the properties in the required order by dragging and dropping them. You can expand all key value pairs at a time using **Expand all**. Alternatively, you can expand each key-value pair to see a specific property. When you add a new key value pair, it automatically expands.
```

2024-04-18 05:16 UTC, lra-sag requested changes

2024-04-18 05:16 UTC, lra-sag commented on static/images/dtm/custom-property/dtm-property-library-complex-property.png
Update screenshot to show one collapsed key and one expanded.

2024-04-18 05:16 UTC, lra-sag commented on content/dtm/asset-types-bundle/asset-properties.md
> +A complex asset property consists of multiple key value pairs, meaning, it contains a root object followed by one or more key value pairs. You can select the complex asset property option by switchin
```suggestion
A complex asset property consists of multiple key value pairs, meaning, it contains a root object followed by one or more key value pairs. You can select the complex asset property option by switching on the toggle. If you switch on the toggle, you must define each key value pair as well as providing a Type for each pair. You can arrange the properties in the required order by dragging and dropping them. Hover over the row to see the drag icon. Click and drag the drag icon for reordering. 
You can expand all key value pairs at a time using **Expand all**. Alternatively, you can expand each key-value pair to see a specific property. When you add a new key value pair, it automatically expands.
```

2024-04-18 10:56 UTC, Vagdevi1998 commented on static/images/dtm/custom-property/dtm-property-library-complex-property.png
Updated

2024-04-18 11:18 UTC, BeateRixen commented on content/dtm/asset-types-bundle/asset-properties.md
> +A complex asset property consists of multiple key value pairs, meaning, it contains a root object followed by one or more key value pairs. You can select the complex asset property option by switchin
```suggestion
A complex asset property consists of multiple key value pairs, meaning, it contains a root object followed by one or more key value pairs. You can select the complex asset property option by switching on the toggle. If you switch on the toggle, you must define each key value pair as well as providing a type for each pair. You can arrange the properties in the required order by dragging and dropping them. Hover over the row to see the drag icon. Click and drag the drag icon for reordering. 
```

2024-04-18 11:18 UTC, BeateRixen commented on content/dtm/asset-types-bundle/asset-properties.md
> +You can expand all key value pairs at a time using **Expand all**. Alternatively, you can expand each key-value pair to see a specific property. When you add a new key value pair, it automatically ex
Not sure about the spelling of "key value pair". It is spelled with and without hyphen here. Please unify. Preferred spelling definitely is "key-value pair".

2024-04-18 11:39 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +You can expand all key value pairs at a time using **Expand all**. Alternatively, you can expand each key-value pair to see a specific property. When you add a new key value pair, it automatically ex
Modified to key-value pair

2024-04-18 12:12 UTC, pavanbhosle approved these changes

2024-04-18 13:35 UTC, BeateRixen approved these changes

2024-04-29 06:43 UTC, lra-sag approved these changes

2024-04-29 06:44 UTC, merged