[DTM] - User experience improved for complex property ordering
SoftwareAG/c8y-docs pull request #1961
Opened 2024-04-18 10:48 UTC by Vagdevi1998

Improved UI for complex property ordering

2024-04-18 11:19 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1020-1-4-ui-improvement-for-ordering-of-complex-properties.md
> +Users can arrange the properties in the required order by dragging and dropping them.
Please provide a bit more context. Where exactly?

2024-04-18 16:03 UTC, Vagdevi1998 commented on content/change-logs/application-enablement/dtm-1020-1-4-ui-improvement-for-ordering-of-complex-properties.md
> +Users can arrange the properties in the required order by dragging and dropping them.
Modified

2024-04-19 05:46 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1020-1-4-ui-improvement-for-ordering-of-complex-properties.md
> +Users can now order the complex property keys by dragging and dropping them using the drag icon which appears on hover.
```suggestion
Users can now order the complex property keys by dragging and dropping them using the drag icon which appears on hovering over the row.
```

2024-04-22 10:06 UTC, BeateRixen approved these changes

2024-04-29 08:35 UTC, lra-sag requested changes

2024-04-29 08:35 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1020-1-4-ui-improvement-for-ordering-of-complex-properties.md
> +    label: Fix
For this to be visible in CD change log, please change this to Improvement

2024-04-29 08:37 UTC, Vagdevi1998 commented on content/change-logs/application-enablement/dtm-1020-1-4-ui-improvement-for-ordering-of-complex-properties.md
> +    label: Fix
Modified

2024-04-29 08:59 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1020-1-4-ui-improvement-for-ordering-of-complex-properties.md
> +  - value: change-2c7RdTdXo4
Please check if this is the right identifier for Improvement change type

2024-04-29 09:03 UTC, lra-sag approved these changes

2024-04-29 10:13 UTC, merged