Changelog: DM-3475 Device Management - Empty Software Packages since 10.18 upgrade
SoftwareAG/c8y-docs pull request #1962
Opened 2024-04-18 13:28 UTC by ashhSAG93

2024-04-18 13:45 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +title: Removal of migration from ASM v1 to ASM v2 data model
The title should state what is working now (impact of the change for the user). This title is of no value for the user.

2024-04-18 13:45 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +The issue of software packages in `c8y_InstalledSoftwareList` being emptied after ASM is resubscribed has been resolved.
```suggestion
The issue has been resolved that software packages in `c8y_InstalledSoftwareList` were emptied after ASM was resubscribed. 
```

2024-04-18 13:45 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +The mechanism of migrating the internal data model from asm-v1 to asm-v2 has been removed.
Is this the way the issue was resolved? Or is this not connected?

2024-04-18 13:45 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +title: Removal of migration from ASM v1 to ASM v2 data model
```suggestion
title: Software packages in `c8y_InstalledSoftwareList` are no longer emptied after ASM resubscribed
```

2024-04-18 13:45 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +title: Removal of migration from ASM v1 to ASM v2 data model
What is ASM?

2024-04-18 13:45 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +version: 1.2.0, 10.16.0.478, 10.18.0.398, 10.17.0.506, 10.18.540.102
This does not work. After approval, I will graft this to 2024. For the older versions please copy the approved text into the ticket and I will take care.
1.2.0 is not a valid version.

2024-04-18 13:53 UTC, l2p- commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +title: Removal of migration from ASM v1 to ASM v2 data model
ASM is Advanced software management microservice. The abbreviation isn't widely known so I wouldn't use it.

2024-04-18 13:55 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +version: 1.2.0, 10.16.0.478, 10.18.0.398, 10.17.0.506, 10.18.540.102
But the build artifact is "cumulocity". Don´t we need another build artifact here then?

2024-04-18 14:23 UTC, l2p- commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +The mechanism of migrating the internal data model from asm-v1 to asm-v2 has been removed.
We have never published anything about the different versions of the data model so referring to them here will not help users. I'd describe it like this:

An old data model migration mechanism was erroneously removing installed software information from devices when the Advanced software management microservice was resubscribed or restarted. We have removed this mechanism entirely so that existing data is no longer modified.

2024-04-18 14:24 UTC, l2p- requested changes
see inline comments

2024-04-19 12:13 UTC, ashhSAG93 commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +version: 1.2.0, 10.16.0.478, 10.18.0.398, 10.17.0.506, 10.18.540.102
@BeateRixen @l2p- do we need to do something like this:

A new build artifact called asm or advanced-software-management is created which can be used for the new component and cumulocity can be used for the older versions like 2024 and below

Then build_artifact could be like:

build_artifact:
  - value: tc-QHwMfWtBk7
    label: cumulocity
  - value: <asm component id>
     label: asm

2024-04-19 13:03 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +title: Software packages in `c8y_InstalledSoftwareList` are no longer emptied after resubscription of the Advanced Software Management microservice
```suggestion
title: Software packages in c8y_InstalledSoftwareList are no longer emptied after resubscription of the Advanced Software Management microservice  
```

2024-04-22 10:25 UTC, l2p- commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +version: 1.2.0, 10.16.0.478, 10.18.0.398, 10.17.0.506, 10.18.540.102
Yes since the change was done in the Advanced software management component after it was separated from the existing cumulocity we need to be able to reference these artifacts in docs

2024-04-22 10:33 UTC, ashhSAG93 commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +version: 1.2.0, 10.16.0.478, 10.18.0.398, 10.17.0.506, 10.18.540.102
@BeateRixen so the components that need to be created, which can be referenced in the docs PR are: advanced-software-management, device-simulator, loriot-agent, actility, cloud-remote-access, connectivity-agent-server

2024-04-22 11:12 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +version: 1.2.0, 10.16.0.478, 10.18.0.398, 10.17.0.506, 10.18.540.102
@ashhSAG93 The precise component names are  "advanced-software-mgmt", and "actility-agent" correct?

2024-04-22 11:30 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +    label: cumulocity
```suggestion
    label: advanced-software-mgmt
```

2024-04-22 11:30 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +  - value: tc-QHwMfWtBk7
```suggestion
  - value: tc-TlhlHnKTa
```

2024-04-22 11:31 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +version: 1.2.0, 10.16.0.478, 10.18.0.398, 10.17.0.506, 10.18.540.102
Added the listed components/build artifacts as spelled in the build pipeline dashboard.

2024-04-22 11:39 UTC, ashhSAG93 commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +version: 1.2.0, 10.16.0.478, 10.18.0.398, 10.17.0.506, 10.18.540.102
Will the references be updated in the Release notes process document?

2024-04-22 11:40 UTC, ashhSAG93 commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +title: Software packages in c8y_InstalledSoftwareList are no longer emptied after resubscription of the Advanced Software Management microservice
OK

2024-04-22 11:42 UTC, ashhSAG93 commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +    label: cumulocity
@BeateRixen so the component will be updated to cumulocity while backporting to older versions? Is it not possible to have multiple labels

2024-04-22 11:52 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +version: 1.2.0, 10.16.0.478, 10.18.0.398, 10.17.0.506, 10.18.540.102
Already added it there. You can also always find the IDs in the https://github.com/SoftwareAG/c8y-docs/blob/develop/data/buildartifact.json.

2024-04-22 11:54 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +    label: cumulocity
No, this is not possible. Should I leave cumulocity in oder versions? Please remove all versions except of the one for CD. And create a separate PR for 2024.

2024-04-22 11:56 UTC, ashhSAG93 commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +    label: cumulocity
I will keep it as advanced-software-mgmt for develop branch. I will create another PR for 2024 and earlier versions where the component will be cumulocity

2024-04-22 11:59 UTC, ashhSAG93 commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +version: 1.2.0
@BeateRixen version and component changes done as desired

2024-04-22 13:20 UTC, BeateRixen approved these changes

2024-04-22 18:59 UTC, l2p- requested changes

2024-04-22 18:59 UTC, l2p- commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +The issue has been resolved that software packages in `c8y_InstalledSoftwareList` were emptied after the Advanced Software Management microservice (ASM) was resubscribed.
```suggestion
```
This sentence should simply be removed the sentence below already has all the required info

2024-04-23 08:53 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-2-0-Remove-migration-mechanism.md
> +title: Software packages in c8y_InstalledSoftwareList are no longer emptied after resubscription of the ASM microservice
```suggestion
title: Installed software packages are no longer emptied after restart of the Advanced software management microservice  
```

2024-04-23 08:53 UTC, BeateRixen approved these changes

2024-04-23 12:03 UTC, l2p- approved these changes

2024-04-23 12:04 UTC, merged