Changelog 2024: DM-3475 Device Management - Empty Software Packages since 10.18 upgrade
SoftwareAG/c8y-docs pull request #1971
Opened 2024-04-22 12:15 UTC by ashhSAG93

@BeateRixen created PR for 2024. Backports to be done to 10.18, 10.17, 10.16

2024-04-22 14:06 UTC, BeateRixen approved these changes

2024-04-23 08:37 UTC, l2p- requested changes
I left a suggestion

2024-04-23 08:37 UTC, l2p- commented on content/change-logs/device-management/cumulocity-2024-Remove-migration-mechanism.md
> +title: Software packages in c8y_InstalledSoftwareList are no longer emptied after resubscription of the ASM microservice
Yes c8y_InstalledSoftwareList isn't a fragment that exists and ASM should not be used.
```suggestion
title: Installed software packages are no longer emptied after restart of the Advanced software management microservice  
```

2024-04-23 12:03 UTC, l2p- approved these changes

2024-04-23 12:04 UTC, merged