Changelog: DM-3411 Loriot-Agent output user missing Loriot Admin Role
SoftwareAG/c8y-docs pull request #1973
Opened 2024-04-23 10:11 UTC by ashhSAG93

2024-04-23 14:57 UTC, l2p- requested changes

2024-04-23 14:57 UTC, l2p- commented on content/change-logs/device-management/loriot-1-0-0-Assign-role-to-uplink-output-user.md
> +This issue has now been addressed. Existing devices as well as new devices will now be able to send uplink messages, as the output user will be assigned the role.
Users don't know what a "Loriot agent output user" is and why it would need that role. The part about devices not being able to send uplink is also misleading because they can but Loriot cannot forward them to us. We need to describe things in a way that uses terminology and functionality that is known to users.
```suggestion
Newly set up LORIOT connections did not work properly because during the setup process because the user created for LORIOT to send uplink requests from devices to the platform did not have sufficient permissions to do so. This has been addressed by adding the required permissions to existing connections and new ones.
```

2024-04-23 15:23 UTC, aaronraab commented on content/change-logs/device-management/loriot-1-0-0-Assign-role-to-uplink-output-user.md
> +This issue has now been addressed. Existing devices as well as new devices will now be able to send uplink messages, as the output user will be assigned the role.
This is really hard to read as you are using because 2 times -> 
Newly set up Loriot connections did not work properly because  the user that is being created during the setup process and used for Loriot to send uplink requests from devices to the platform did not have sufficient permissions to do so. This has been addressed by adding the required permissions to existing connections as well as new ones.

2024-04-25 05:43 UTC, ashhSAG93 commented on content/change-logs/device-management/loriot-1-0-0-Assign-role-to-uplink-output-user.md
> +This issue has now been addressed. Existing devices as well as new devices will now be able to send uplink messages, as the output user will be assigned the role.
Change has been made now

2024-04-25 05:45 UTC, ashhSAG93 commented on content/change-logs/device-management/loriot-1-0-0-Assign-role-to-uplink-output-user.md
> +Newly established LORIOT connections failed initially because the user account created for sending uplink requests from devices lacked the necessary permissions. This issue has been resolved by grant
@l2p- @aaronraab I think the sentence should now be fine. 

We could also use the below (this was a rephrase of the sentence @l2p- had suggested, by Gemini), if this isnt as per expectation:

The initial LORIOT setup malfunctioned due to insufficient permissions for the user created to transmit device data (uplink requests) to the platform. This issue has been resolved by granting the necessary permissions to both existing and new connections.

2024-05-02 10:46 UTC, l2p- approved these changes

2024-05-06 08:06 UTC, BeateRixen commented on content/change-logs/device-management/loriot-1-0-0-Assign-role-to-uplink-output-user.md
> +Newly established LORIOT connections failed initially because the user account created for sending uplink requests from devices lacked the necessary permissions. This issue has been resolved by grant
```suggestion
Newly established Loriot connections failed initially because the user account created for sending uplink requests from devices lacked the necessary permissions. This issue has been resolved by granting the required permissions to both existing and new connections.
```

2024-05-06 08:07 UTC, BeateRixen commented on content/change-logs/device-management/loriot-1-0-0-Assign-role-to-uplink-output-user.md
> +title: Assign Loriot Admin Role to the Loriot agent output user for existing and new devices.
```suggestion
title: Assign Loriot admin permissions to the Loriot agent output user for existing and new devices   
```

2024-05-06 08:09 UTC, BeateRixen commented on content/change-logs/device-management/loriot-1-0-0-Assign-role-to-uplink-output-user.md
> +Newly established LORIOT connections failed initially because the user account created for sending uplink requests from devices lacked the necessary permissions. This issue has been resolved by grant
In the title you are more precise on which permissions have been added. I would better add this information in the detailed description.

2024-05-06 11:02 UTC, BeateRixen commented on content/change-logs/device-management/loriot-1-0-0-Assign-role-to-uplink-output-user.md
> +Newly established Loriot connections failed initially because the user account created for sending uplink requests from devices lacked the necessary permissions. This issue has been resolved by grant
the required permissions > shouldn´t this be more precise? The title mentions admin permissions

2024-05-06 13:01 UTC, ashhSAG93 commented on content/change-logs/device-management/loriot-1-0-0-Assign-role-to-uplink-output-user.md
> +Newly established Loriot connections failed initially because the user account created for sending uplink requests from devices lacked the necessary permissions. This issue has been resolved by grant
I can change this to required admin permissions

2024-05-06 13:03 UTC, ashhSAG93 commented on content/change-logs/device-management/loriot-1-0-0-Assign-role-to-uplink-output-user.md
> +Newly established Loriot connections failed initially because the user account created for sending uplink requests from devices lacked the necessary permissions. This issue has been resolved by grant
Hope the changes are fine now

2024-05-07 05:32 UTC, merged