Create ui-c8y-1019-22-1-btn-default-for-sso-login-button-5488-graft-release-cd-6158.md
SoftwareAG/c8y-docs pull request #1987
Opened 2024-04-24 22:19 UTC by gen-App-Enablement

Release note created by c8y-ui-automations[bot]

Ticket: [MTM-57675](https://cumulocity.atlassian.net/browse/MTM-57675)
Original PR: [6158](https://github.softwareag.com/IOTA/cumulocity-ui/pull/6158)

2024-04-24 22:19 UTC, gen-App-Enablement reviewed
AI improvements

2024-04-24 22:19 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1019-22-1-btn-default-for-sso-login-button-5488-graft-release-cd-6158.md
> +title: btn-default for sso login button (#5488) [GRAFT][release/cd] (#6158)
The Claude AI suggested to use the following title:
```suggestion
title: Improved styling of single sign-on login button
```

2024-04-24 22:19 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1019-22-1-btn-default-for-sso-login-button-5488-graft-release-cd-6158.md
> +btn-default for sso login button (#5488) [GRAFT][release/cd] (#6158)
The Claude AI suggested to use the following body:
```suggestion
To provide a more consistent user experience, the styling of the single sign-on (SSO) login button has been updated. Previously, the SSO login button used a custom style which did not match the overall look and feel of the application. With this change, the SSO login button now uses the default button style (btn-default). This improvement in styling ensures that the SSO login button integrates seamlessly with the rest of the user interface, making it easier for users to recognize and interact with the SSO functionality.
```

2024-05-06 09:40 UTC, BeateRixen commented
@kalavathig1 @sarangovindarajan Please review and approve.

2024-05-08 12:02 UTC, mmed-softwareag approved these changes

2024-05-09 08:30 UTC, pink-mongoose requested changes
We should remove the use of the word 'style' this has no meaning to a customer.  Perhaps something like:

The user experience for the single sign-on (SSO) has been improved with an updated login button to match the overall look and feel of the application.

2024-05-10 08:21 UTC, BeateRixen approved these changes

2024-05-10 08:22 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-22-1-btn-default-for-sso-login-button-5488-graft-release-cd-6158.md
> +title: Improved styling of single sign-on login button
```suggestion
title: Improved layout of single sign-on login button
```

2024-05-10 08:23 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-22-1-btn-default-for-sso-login-button-5488-graft-release-cd-6158.md
> +The styling of the single sign-on (SSO) login button has been updated. Previously, the SSO login button used a custom style which did not match the overall look and feel of the application. With this
```suggestion
The layout of the single sign-on (SSO) login button has been updated. Previously, the SSO login button used a custom style which did not match the overall look and feel of the application. With this change, the SSO login button now uses the default button style (btn-default).
```

2024-05-10 08:25 UTC, BeateRixen commented
> We should remove the use of the word 'style' this has no meaning to a customer. Perhaps something like:
> 
> The user experience for the single sign-on (SSO) has been improved with an updated login button to match the overall look and feel of the application.

@pink-mongoose How about using the term "layout"? This is a term we often use. "User expericence" seems a bit too much when talking about a simple button change, isn´t it :-)?

2024-05-10 15:09 UTC, pink-mongoose commented on content/change-logs/platform-services/ui-c8y-1019-22-1-btn-default-for-sso-login-button-5488-graft-release-cd-6158.md
> +The styling of the single sign-on (SSO) login button has been updated. Previously, the SSO login button used a custom style which did not match the overall look and feel of the application. With this
@BeateRixen  I still do not like the fact we are using the default button style.  The last sentence can be completely removed.

2024-05-13 07:26 UTC, kalavathig1 approved these changes

2024-05-13 08:48 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-22-1-btn-default-for-sso-login-button-5488-graft-release-cd-6158.md
> +The layout of the single sign-on (SSO) login button has been updated. Previously, the SSO login button used a custom style which did not match the overall look and feel of the application. With this
```suggestion
The layout of the single sign-on (SSO) login button has been updated. Previously, the SSO login button used a custom style which did not match the overall look and feel of the application. With this change, the SSO login button now uses the default layout.
```

2024-05-13 08:49 UTC, merged