Create ui-c8y-1019-22-3-fixed-breadcrumbs-for-global-and-inventory-roles-tabs-under-accounts-roles.md
SoftwareAG/c8y-docs pull request #1992
Opened 2024-04-25 11:02 UTC by gen-App-Enablement

Release note created by pry

Ticket: [MTM-57553](https://cumulocity.atlassian.net/browse/MTM-57553)
Original PR: [6201](https://github.softwareag.com/IOTA/cumulocity-ui/pull/6201)

2024-04-25 11:02 UTC, gen-App-Enablement reviewed
AI improvements

2024-04-25 11:02 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1019-22-3-fixed-breadcrumbs-for-global-and-inventory-roles-tabs-under-accounts-roles.md
> +title: Fixed breadcrumbs for global and inventory roles tabs under Accounts > Roles [GRAFT][release/cd] (#6201)
The Claude AI suggested to use the following title:
```suggestion
title: Fixed breadcrumbs for global and inventory roles tabs under Accounts > Roles
```

2024-04-25 11:02 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1019-22-3-fixed-breadcrumbs-for-global-and-inventory-roles-tabs-under-accounts-roles.md
> +Fixed breadcrumbs for global and inventory roles tabs under Accounts > Roles [GRAFT][release/cd] (#6201)
The Claude AI suggested to use the following body:
```suggestion
In the Cumulocity IoT user interface, the breadcrumbs for the global and inventory roles tabs under the Accounts > Roles menu were previously incorrect, making navigation confusing for users. This issue has been resolved, and the breadcrumbs now accurately reflect the user's location within the application. This change improves the overall user experience by providing clear and consistent navigation across the roles management screens.
```

2024-04-26 13:38 UTC, pink-mongoose requested changes
This needs changing so it makes sense for a user.

In the Cumulocity IoT Administration App, the location information for the global and inventory roles tabs under the Accounts > Roles menu was incorrect, making navigation confusing for users. This issue has been resolved with the user's location within the application now accurately reflected.

2024-05-06 09:46 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-22-3-fixed-breadcrumbs-for-global-and-inventory-roles-tabs-under-accounts-roles.md
> +In the Administration application, the location information for the **Global roles**  and **Inventory roles** tabs under the **Accounts** > **Roles** menu was incorrect, making navigation confusing f
```suggestion
In the Administration application, the location information for the **Global roles** and **Inventory roles** tabs under the **Accounts** > **Roles** menu was incorrect, making navigation confusing for users. This issue has been resolved with the user's location within the application now accurately reflected.
```

2024-05-06 09:48 UTC, BeateRixen commented
@martin-sag @Airdroplet Please review and approve

2024-05-07 06:12 UTC, martin-sag commented
Is there a ways to find out who originally created the PR? Not sure if the corresponding developer gets all those notifications and change requests.

2024-05-07 06:54 UTC, Airdroplet approved these changes

2024-05-07 08:44 UTC, martin-sag approved these changes

2024-05-07 10:36 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-22-3-fixed-breadcrumbs-for-global-and-inventory-roles-tabs-under-accounts-roles.md
> +title: Fixed location information for Global roles and Inventory roles tabs under Accounts > Roles menu
```suggestion
title: Fixed breadcrumbs for Global roles and Inventory roles tabs
```

2024-05-07 10:37 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-22-3-fixed-breadcrumbs-for-global-and-inventory-roles-tabs-under-accounts-roles.md
> +In the Administration application, the location information for the **Global roles** and **Inventory roles** tabs under the **Accounts** > **Roles** menu was incorrect, making navigation confusing fo
```suggestion
In the Administration application, the location information for the **Global roles** and **Inventory roles** tabs under **Accounts** > **Roles** was incorrect, making navigation confusing for users. This issue has been resolved with the user's location within the application now accurately reflected.
```

2024-05-07 10:38 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-22-3-fixed-breadcrumbs-for-global-and-inventory-roles-tabs-under-accounts-roles.md
> +title: Fixed breadcrumbs for Global roles and Inventory roles tabs
```suggestion
title: Fixed location information for Global roles and Inventory roles tabs
```

2024-05-07 10:38 UTC, BeateRixen approved these changes

2024-05-07 10:39 UTC, merged

2024-05-07 10:47 UTC, BeateRixen commented
> Is there a ways to find out who originally created the PR? Not sure if the corresponding developer gets all those notifications and change requests.

@martin-sag Since these PRs are automatically created they do not include the developer. @janhommes would it be possible to automatically add the developer who merged the change?