DM-3620 - lwm2m bugfix changelog y2024
SoftwareAG/c8y-docs pull request #2004
Opened 2024-04-29 13:23 UTC by jakubsobolewskisag

y2024 changelog file

2024-04-29 14:11 UTC, aaronraab requested changes

2024-04-29 14:11 UTC, aaronraab commented on content/change-logs/device-management/cumulocity_10-18-540-115_lwm2m-agent-executes-object-mappings-multiple-times.md
> +When a LwM2M 1.1 Send request that included multiple timestamps is received, the LWM2M agent in some cases processed object resource mappings actions multiple times. This issue is now resolved to mak
-> "When a LwM2M 1.1 send request that includes multiple timestamps has been received, the object resource mapping actions have in some cases been processed multiple times by the LwM2M agent. This issue has been resolved to ensure that mapping actions get only triggerd once. " (Sorry, I currently don't have the option to directly commit suggestions

2024-04-30 12:16 UTC, Oezge-Akin approved these changes

2024-05-06 08:34 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity_10-18-540-115_lwm2m-agent-executes-object-mappings-multiple-times.md
> +title: LWM2M agent executes object mappings multiple times on LWM2M 1.1 SEND
```suggestion
title: Object mapping actions only executed once on LWM2M 1.1 send request
```

Please positively phrase in the title what works now (opposed to focusing on what was the issue).

2024-05-06 08:34 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity_10-18-540-115_lwm2m-agent-executes-object-mappings-multiple-times.md
> +When a LwM2M 1.1 send request that includes multiple timestamps has been received, the object resource mapping actions have in some cases been processed multiple times by the LwM2M agent. This issue
```suggestion
When a LWM2M 1.1 send request that includes multiple timestamps has been received, the object resource mapping actions have in some cases been processed multiple times by the LwM2M agent. This issue has been resolved to ensure that mapping actions get only triggered once.
```

2024-05-06 08:36 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity_10-18-540-115_lwm2m-agent-executes-object-mappings-multiple-times.md
> +When a LWM2M 1.1 send request that includes multiple timestamps has been received, the object resource mapping actions have in some cases been processed multiple times by the LwM2M agent. This issue
```suggestion
When a LWM2M 1.1 send request that includes multiple timestamps has been received, the object resource mapping actions have in some cases been processed multiple times by the LWM2M agent. This issue has been resolved to ensure that mapping actions get only triggered once.
```

2024-05-07 07:57 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity_10-18-540-115_lwm2m-agent-executes-object-mappings-multiple-times.md
> +title: Object mapping actions only executed once on LWM2M 1.1 send request
```suggestion
title: Object mapping actions no longer executed multiple times on LWM2M 1.1 send request
```

2024-05-07 07:57 UTC, BeateRixen approved these changes

2024-05-07 09:09 UTC, merged