Create ui-c8y-1019-23-7-fix-typo-in-iam-5661-graft-release-cd-6038.md
SoftwareAG/c8y-docs pull request #2013
Opened 2024-05-06 10:21 UTC by gen-App-Enablement

Release note created by c8y-ui-automations[bot]

Ticket: [MTM-55205](https://cumulocity.atlassian.net/browse/MTM-55205)
Original PR: [6038](https://github.softwareag.com/IOTA/cumulocity-ui/pull/6038)

2024-05-06 10:21 UTC, gen-App-Enablement reviewed
AI improvements

2024-05-06 10:21 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1019-23-7-fix-typo-in-iam-5661-graft-release-cd-6038.md
> +title: fix typo in IAM (#5661) [GRAFT][release/cd] (#6038)
The Claude AI suggested to use the following title:
```suggestion
title: Fixed typo in IAM
```

2024-05-06 10:21 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1019-23-7-fix-typo-in-iam-5661-graft-release-cd-6038.md
> +fix typo in IAM (#5661) [GRAFT][release/cd] (#6038)
The Claude AI suggested to use the following body:
```suggestion
A typo was discovered in the IAM component which could have led to confusion or incorrect behavior in certain scenarios. The typo has now been corrected, ensuring that the IAM component functions as intended. This change should not have any noticeable impact on users or their installations.
```

2024-05-08 08:37 UTC, BeateRixen commented
@mmed-softwareag Please take care of this PR.

2024-05-08 12:42 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-23-7-fix-typo-in-iam-5661-graft-release-cd-6038.md
> +title: Fixed typo in IAM (AIM -> IAM).
```suggestion
title: Fixed typo in Single sign-on page
```

2024-05-08 12:42 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-23-7-fix-typo-in-iam-5661-graft-release-cd-6038.md
> +The typo has been corrected. IAM stands for Identity and Access Management.
```suggestion
In the **Single sign-on** page, a typo  has been fixed (AIM -> IAM). IAM stands for Identity and Access Management.
```

2024-05-09 08:24 UTC, pink-mongoose approved these changes

2024-05-10 05:38 UTC, kalavathig1 requested changes

2024-05-10 05:38 UTC, kalavathig1 commented on content/change-logs/platform-services/ui-c8y-1019-23-7-fix-typo-in-iam-5661-graft-release-cd-6038.md
> +component:
isnt this ? 
component:
  - value: q3kclF6pO
    label: Authentication

2024-05-10 07:56 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-23-7-fix-typo-in-iam-5661-graft-release-cd-6038.md
> +component:
Yes, you are right, please change.

2024-05-13 06:45 UTC, kalavathig1 approved these changes

2024-05-13 07:22 UTC, merged