[MTM-42401]: Microservice SDK 10.13 upgrade
SoftwareAG/c8y-docs pull request #203
Opened 2022-01-19 07:39 UTC by c8y-kh4mell

2022-01-19 09:32 UTC, rssag requested changes

2022-01-19 09:32 UTC, rssag commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +  Sample content:
```suggestion

  Sample content:
```

2022-01-19 09:38 UTC, BeateRixen commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +Since 10.13.0 a Spring-Boot library was upgraded to 2.5.5, hence upgrading Microservice SDK to 10.13+ may require some additional development.
Please remove the part "Since 10.13.0" since it obvious from the documentation version.

2022-01-19 10:46 UTC, c8y-kh4mell commented on content/microservice-sdk/java-bundle/developing-microservice.md
> +* Spring-Boot bom does not define a version for joda-time, you may need to explicitly define version.
It's spring-boot-dependencies dependency: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies/2.5.5
Microservice SDK developer must know about it, since we also have a BOM: `microservice-dependencies`

2022-01-19 11:48 UTC, rssag approved these changes

2022-01-19 12:37 UTC, karolkaczmarski-sag approved these changes

2022-01-19 14:49 UTC, manasesjesus approved these changes

2022-01-20 12:47 UTC, rssag approved these changes

2022-01-20 12:57 UTC, manasesjesus approved these changes

2022-01-20 13:10 UTC, merged