Create ui-c8y-1019-24-1-missing-translation-in-ui-6208.md
SoftwareAG/c8y-docs pull request #2056
Opened 2024-05-15 16:26 UTC by gen-App-Enablement

Release note created by llar

Ticket: [MTM-58187](https://cumulocity.atlassian.net/browse/MTM-58187)
Original PR: [6208](https://github.softwareag.com/IOTA/cumulocity-ui/pull/6208)

2024-05-15 16:26 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1019-24-1-missing-translation-in-ui-6208.md
> +missing translation in UI (#6208)
The Claude AI suggested to use the following body:
```suggestion
Some translations were missing in the device management UI, leading to untranslated text being displayed to users. The missing translations have now been added, so that all text in the device management UI is properly translated based on the user's language settings. This change improves the user experience and usability of the device management UI for non-English speaking users.
```

2024-05-16 07:53 UTC, kalavathig1 commented on content/change-logs/platform-services/ui-c8y-1019-24-1-missing-translation-in-ui-6208.md
> +Provided translations for following global roles: "admins", "business", "devices", "readers". Also translated following inventory roles: "Manager". (#6210)
```suggestion
Global roles: "admins", "business", "devices". Inventory roles: "Manager" are now translated to Japanese.
```

2024-05-16 13:15 UTC, Airdroplet commented on content/change-logs/platform-services/ui-c8y-1019-24-1-missing-translation-in-ui-6208.md
> +title: Provided translations for default global roles (#6208)
translation being provided for all languages, so will not apply this suggestion

2024-05-16 13:15 UTC, Airdroplet commented on content/change-logs/platform-services/ui-c8y-1019-24-1-missing-translation-in-ui-6208.md
> +Provided translations for following global roles: "admins", "business", "devices", "readers". Also translated following inventory roles: "Manager". (#6210)
translation being provided for all languages, so will not apply this suggestion

2024-05-16 13:25 UTC, pink-mongoose requested changes
From the information it is unclear precisely what has been translated.

2024-05-17 08:58 UTC, Airdroplet commented
> From the information it is unclear precisely what has been translated.

Provided translations for following global roles: "admins", "business", "devices", "readers". Also translated following inventory roles: "Manager".

The respective mapping is like: 

```
admins: gettext('Admin User`role`'),
  business: gettext('Business User`role`'),
  devices: gettext('Device User`role`'),
  Manager: gettext('Asset Manager`role`'),
  readers: gettext('Reader User`role`')
```

2024-05-21 06:20 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-24-1-missing-translation-in-ui-6208.md
> +title: Provided translations for default global roles (#6208)
```suggestion
title: Provided translations for default roles 
```

2024-05-21 06:21 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-24-1-missing-translation-in-ui-6208.md
> +title: Provided translations for default global roles (#6208)
As the change also includes an inventory role

2024-05-21 06:49 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-24-1-missing-translation-in-ui-6208.md
> +The labels for the following roles are now translated. Global roles: "admins", "business", "devices". Inventory roles: "Manager".
```suggestion
The labels for the following default roles are now translated. Global roles: "admins", "business", "devices". Inventory roles: "Manager".
```

2024-05-21 06:49 UTC, BeateRixen approved these changes

2024-05-22 12:26 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1019-24-1-missing-translation-in-ui-6208.md
> +title: Provided translations for default roles
```suggestion
title: Provided translations for default roles labels
```

2024-05-22 12:27 UTC, merged