Create ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
SoftwareAG/c8y-docs pull request #2081
Opened 2024-05-23 14:04 UTC by gen-App-Enablement

Release note created by jdre

Ticket: [MTM-58509](https://cumulocity.atlassian.net/browse/MTM-58509)
Original PR: [5975](https://github.softwareag.com/IOTA/cumulocity-ui/pull/5975)

2024-05-23 14:04 UTC, gen-App-Enablement reviewed
AI improvements

2024-05-23 14:04 UTC, gen-App-Enablement commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +title: Create a type dashboard list view (#5975)
The Claude AI suggested to use the following title:
```suggestion
title: Add dashboard list view
```

2024-05-23 14:04 UTC, gen-App-Enablement commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +Create a type dashboard list view (#5975)
The Claude AI suggested to use the following body:
```suggestion
To provide users with an overview of their dashboards, a new list view has been added. The dashboard list view displays all dashboards in a tabular format, showing relevant information such as the dashboard name, description, owner, and last modification date. This change enhances the user experience by making it easier to browse, search and manage multiple dashboards in one central place.
```

2024-05-24 11:36 UTC, jdreSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +title: Create a type dashboard list view (#5975)
```suggestion
title: Add Dashboard manager feature with list of type dashboards
```

2024-05-24 11:39 UTC, jdreSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +Create a type dashboard list view (#5975)
Add Dashboard manager view. For now it contains only list of device type dashboards. It aggregates all dashboards that has device type assigned, it allows to remove these dashboards and it is also possible to view all the devices that has access to particular dashboard from list. User can edit dashboard by navigating to device view.

2024-05-24 11:40 UTC, jdreSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +Create a type dashboard list view (#5975)
```suggestion
Add Dashboard manager view. For now it contains only list of device type dashboards. It aggregates all dashboards that has device type assigned, it allows to remove these dashboards and it is also possible to view all the devices that has access to particular dashboard from list. User can edit dashboard by navigating to device view.
```

2024-05-24 11:40 UTC, jdreSAG approved these changes

2024-05-27 07:57 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +Add Dashboard manager view. For now it contains only list of device type dashboards. It aggregates all dashboards that has device type assigned, it allows to remove these dashboards and it is also po
```suggestion
A dashboard manager view has been added. This dashboard manager shows a list of device type dashboards by aggregating all dashboards that have a device type assigned. Dashboards can be removed via the list. Moreover you can view all devices that have access to a particular dashboard. Dashboards can be edited by navigating to the device view.
```

2024-05-27 07:57 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +title: Add Dashboard manager feature with list of type dashboards
```suggestion
title: New dashboard manager with list of device type dashboards
```

2024-05-27 07:58 UTC, BeateRixen commented
@rahultsag Please review and approve

2024-05-27 09:30 UTC, BeateRixen approved these changes

2024-05-27 10:00 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +title: New dashboard manager with list of device type dashboards
@janhommes  I assume that documentation will also be added shortly?

2024-05-28 08:24 UTC, rahultsag requested changes
Proposing this description : A dashboard manager view has been added to streamline the management of device type dashboards. This view aggregates and displays a list of all dashboards assigned to specific device types. From this list, dashboard templates linked to device types can be viewed ,edited by navigating to a particular instance, and templates can also be deleted if needed.

2024-05-28 08:24 UTC, rahultsag commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +A dashboard manager view has been added. This dashboard manager shows a list of device type dashboards by aggregating all dashboards that have a device type assigned. Dashboards can be removed via th
Proposing this description : A dashboard manager view has been added to streamline the management of device type dashboards. This view aggregates and displays a list of all dashboards assigned to specific device types. From this list, dashboard templates linked to device types can be viewed ,edited by navigating to a particular instance, and templates can also be deleted if needed.

2024-05-28 12:30 UTC, jdreSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +A dashboard manager view has been added. This dashboard manager shows a list of device type dashboards by aggregating all dashboards that have a device type assigned. Dashboards can be removed via th
```suggestion
A dashboard manager view has been added to streamline the management of device type dashboards. This view aggregates and displays a list of all dashboards assigned to specific device types. From this list, dashboard templates linked to device types can be viewed, edited by navigating to a particular instance and templates can also be deleted if needed.
```

2024-05-28 12:31 UTC, jdreSAG commented on content/change-logs/application-enablement/ui-c8y-1020-0-0-create-a-type-dashboard-list-view-5975.md
> +A dashboard manager view has been added. This dashboard manager shows a list of device type dashboards by aggregating all dashboards that have a device type assigned. Dashboards can be removed via th
@rahultsag  your description is commited now

2024-06-03 07:48 UTC, BeateRixen commented
@rahultsag Please approve.

2024-06-03 12:27 UTC, rahultsag approved these changes

2024-06-03 13:56 UTC, merged