[DM-3007] lwm2m OMA test fest changes changelog
SoftwareAG/c8y-docs pull request #2137
Opened 2024-06-03 12:02 UTC by jakubsobolewskisag

- composite observations
- post write

2024-06-05 12:53 UTC, jakubsobolewskisag commented on content/change-logs/device-management/lwm2m-agent_10-20-350-0_feature-composite-observations.md
> +LWM2M agent is now able to establish and cancel observations in composite mode.
done

2024-06-11 12:56 UTC, BeateRixen approved these changes

2024-06-25 07:11 UTC, Oezge-Akin approved these changes

2024-06-27 08:10 UTC, aaronraab requested changes

2024-07-01 11:24 UTC, aaronraab approved these changes

2024-09-24 12:54 UTC, Oezge-Akin commented on content/change-logs/device-management/lwm2m-agent_10-20-350-0_feature-composite-observations.md
> +date:
```suggestion
date: 2024-09-19
```

2024-09-24 12:54 UTC, Oezge-Akin commented on content/change-logs/device-management/lwm2m-agent_10-20-350-0_feature-post-write.md
> +date:
```suggestion
date: 2024-09-19
```

2024-09-24 16:02 UTC, merged