[GRAFT] [y2024] [DM-2770]
SoftwareAG/c8y-docs pull request #2170
Opened 2024-06-11 09:20 UTC by jakubsobolewskisag

lwm2m changelog

2024-06-11 09:34 UTC, BeateRixen commented on content/change-logs/device-management/lwm2m-agent-10-18-540-142-fix-generic-ui-multi-value-fragments.md
> +When device sends values from multi-instance resources (via read, composite read, observe or composite observe), the agent has to decide whether it should overwrite the previous data set or update it
@jakubsobolewskisag Please adapt to the wording in the PR to develop.

2024-06-11 11:44 UTC, aaronraab requested changes

2024-06-14 09:15 UTC, BeateRixen commented on content/change-logs/device-management/lwm2m-agent-10-18-540-142-fix-generic-ui-multi-value-fragments.md
> +When device sends values from multi-instance resources (via read, composite read, observe or composite observe), the agent has to decide whether it should overwrite the previous data set or update it
```suggestion
When a device sends values from multi-instance resources (via read, composite read, observe or composite observe), the LWM2M agent must decide whether it overwrites the previous data set or updates it (for example, by adding a new value to an existing array). Previously, in some edge cases the decision taken by the agent was not correct. This issue is now fixed and the agent always stores data from multi-instance resources correctly.  
```

2024-06-14 09:15 UTC, BeateRixen commented on content/change-logs/device-management/lwm2m-agent-10-18-540-142-fix-generic-ui-multi-value-fragments.md
> +title: LWM2M agent always stores data from multi-instance resources correctly
```suggestion
title: LWM2M agent now always stores data from multi-instance resources correctly
```

2024-06-14 09:15 UTC, BeateRixen approved these changes

2024-06-24 14:15 UTC, Oezge-Akin commented on content/change-logs/device-management/lwm2m-agent-10-18-540-142-fix-generic-ui-multi-value-fragments.md
> +    label: lwm2m-agent
```suggestion
  - value: tc-QHwMfWtBk7
    label: cumulocity
```

Because in 2024 version, lwm2m-agent is part of cumulocity component.

2024-06-24 14:15 UTC, Oezge-Akin commented on content/change-logs/device-management/lwm2m-agent-10-18-540-142-fix-generic-ui-multi-value-fragments.md
> +date:
```suggestion
date: 2024-06-14
```

As this version is GA2 approved already last week: https://github.softwareag.com/IOTA/c8y-iot-build-pipeline/pull/34948.

2024-06-24 14:15 UTC, Oezge-Akin commented on content/change-logs/device-management/lwm2m-agent-10-18-540-142-fix-generic-ui-multi-value-fragments.md
> +version: 10.18.540.142
```suggestion
version: 10.18.540.141
```
if you check the commit history https://github.softwareag.com/IOTA/cumulocity-agents/commits/release/y2024
the version is actually 10.18.540.141 and it is also being set to Jira ticket with automation

2024-06-24 14:23 UTC, jakubsobolewskisag commented on content/change-logs/device-management/lwm2m-agent-10-18-540-142-fix-generic-ui-multi-value-fragments.md
> +When device sends values from multi-instance resources (via read, composite read, observe or composite observe), the agent has to decide whether it should overwrite the previous data set or update it
done

2024-06-24 14:24 UTC, jakubsobolewskisag commented on content/change-logs/device-management/lwm2m-agent-10-18-540-142-fix-generic-ui-multi-value-fragments.md
> +When device sends values from multi-instance resources (via read, composite read, observe or composite observe), the agent has to decide whether it should overwrite the previous data set or update it
done

2024-06-24 14:24 UTC, Oezge-Akin approved these changes

2024-06-25 08:23 UTC, aaronraab approved these changes

2024-06-25 08:25 UTC, merged