MTM-58098 release notes for Date-Filtering-doesnt-work-in-Audit-Logs-…
SoftwareAG/c8y-docs pull request #2174
Opened 2024-06-12 06:48 UTC by pkepa7

…for-Alarms

2024-06-12 07:54 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10.20.419.0_Date-Filtering-doesnt-work-in-Audit-Logs-for-Alarms.md
> +date: 2024-04-26
```suggestion
date: 
```

2024-06-12 07:54 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10.20.419.0_Date-Filtering-doesnt-work-in-Audit-Logs-for-Alarms.md
> +date: 2024-04-26
The date refers to the deployment date on Zone 1 and will be added at a later time

2024-06-12 07:54 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10.20.419.0_Date-Filtering-doesnt-work-in-Audit-Logs-for-Alarms.md
> +To create an audit for a repeating alarm, the alarm creation date was used, which resulted in the audit logs having past dates.
```suggestion
To create audit log for repeating alarms, the alarm creation date was used, which resulted in audit logs having past dates. This issue has been fixed and now audit logs for repeating alarms are created with the date of the last alarm update.
```

2024-06-12 07:54 UTC, BeateRixen commented on content/change-logs/platform-services/cumulocity-10.20.419.0_Date-Filtering-doesnt-work-in-Audit-Logs-for-Alarms.md
> +title: Create an audit log with the date of the last alarm update
```suggestion
title: Audit logs for repeating alarms are created with the date of the last alarm update
```

2024-06-12 11:19 UTC, pkepa7 commented on content/change-logs/platform-services/cumulocity-10.20.419.0_Date-Filtering-doesnt-work-in-Audit-Logs-for-Alarms.md
> +To create an audit for a repeating alarm, the alarm creation date was used, which resulted in the audit logs having past dates.
Changed.

2024-06-12 11:19 UTC, pkepa7 commented on content/change-logs/platform-services/cumulocity-10.20.419.0_Date-Filtering-doesnt-work-in-Audit-Logs-for-Alarms.md
> +title: Create an audit log with the date of the last alarm update
Changed.

2024-06-12 11:19 UTC, pkepa7 commented on content/change-logs/platform-services/cumulocity-10.20.419.0_Date-Filtering-doesnt-work-in-Audit-Logs-for-Alarms.md
> +date: 2024-04-26
Changed.

2024-06-12 11:49 UTC, BeateRixen approved these changes

2024-06-13 15:43 UTC, pink-mongoose requested changes

2024-06-13 15:43 UTC, pink-mongoose commented on content/change-logs/platform-services/cumulocity-10.20.419.0_Date-Filtering-doesnt-work-in-Audit-Logs-for-Alarms.md
> +To create audit log for repeating alarms, the alarm creation date was used, which resulted in audit logs having past dates. This issue has been fixed and now audit logs for repeating alarms are creat
```suggestion
Audit logs for repeating alarms used the alarm creation date which resulted in audit logs having past dates. This issue has been fixed and now audit logs for repeating alarms are created with the date of the last alarm update.
```

2024-06-19 09:57 UTC, BeateRixen commented
@martin-sag This ones needs approval from you please.

2024-06-20 10:09 UTC, martin-sag approved these changes

2024-06-20 10:12 UTC, merged