Changelog: DM-3677 fixes Device Simulator SmartRest template collection parsing with response template
SoftwareAG/c8y-docs pull request #2190
Opened 2024-06-14 10:34 UTC by atulpandasag

2024-06-14 11:12 UTC, l2p- requested changes

2024-06-14 11:12 UTC, l2p- commented on content/change-logs/device-management/content/change-logs/device-management/device-simulator-1-8-0-SmartRest-response-template-parsing.md
> +SmartRest template collection parsing was failing with a response template. This issue has been resolved by fixing the Response template creation.
```suggestion
Device simulators configured to use a SmartREST template collection containing response templates had internal issues that prevented the creation of data. This internal has been addressed by correctly parsing response templates so that processing is no longer interrupted.
```

2024-06-14 14:06 UTC, atulpandasag commented on content/change-logs/device-management/content/change-logs/device-management/device-simulator-1-8-0-SmartRest-response-template-parsing.md
> +SmartRest template collection parsing was failing with a response template. This issue has been resolved by fixing the Response template creation.
Done

2024-06-14 14:23 UTC, l2p- approved these changes

2024-06-14 14:52 UTC, aaronraab approved these changes

2024-06-17 06:05 UTC, BeateRixen commented on content/change-logs/device-management/content/change-logs/device-management/device-simulator-1-8-0-SmartRest-response-template-parsing.md
> +title: SmartRest template collection parsing no longer fails with response template
```suggestion
title: SmartREST template collection parsing no longer fails with response template   
```

2024-06-17 06:06 UTC, BeateRixen commented on content/change-logs/device-management/content/change-logs/device-management/device-simulator-1-8-0-SmartRest-response-template-parsing.md
> +Device simulators configured to use a SmartREST template collection containing response templates had internal issues that prevented data creation. This internal has been addressed by correctly parsi
```suggestion
Device simulators configured to use a SmartREST template collection containing response templates had an internal issue that prevented data creation. This issue has been addressed by correctly parsing response templates so that processing is no longer interrupted.
```

2024-06-17 06:06 UTC, BeateRixen approved these changes

2024-06-17 06:09 UTC, merged