[DTM] - Documentation changes for CD 1020.1.10
SoftwareAG/c8y-docs pull request #2201
Opened 2024-06-19 10:33 UTC by Vagdevi1998

* User documentation for CD 1020.1.10

2024-06-19 10:49 UTC, lra-sag requested changes

2024-06-19 10:49 UTC, lra-sag commented on content/dtm/asset-types-bundle/asset-properties.md
> +A complex asset property consists of multiple key-value pairs, meaning, it contains a root object followed by one or more key-value pairs. You can select the complex asset property option by switchin
Add a line to explain how user can collapse or expand a row to hide or view the property details

2024-06-19 10:49 UTC, lra-sag commented on static/images/dtm/assets/dtm-assets-move-assets.png
Why is this screenshot updated?

2024-06-19 10:49 UTC, lra-sag commented on static/images/dtm/custom-property/dtm-property-library-import.png
Why is this screenshot updated? This and the one above are not relevant to changes in complex properties

2024-06-20 06:04 UTC, Vagdevi1998 commented on static/images/dtm/assets/dtm-assets-move-assets.png
This screenshot is updated to reflect the button name changes for Import assets -> Import in the background.

2024-06-20 06:04 UTC, Vagdevi1998 commented on static/images/dtm/custom-property/dtm-property-library-import.png
This screenshot is updated to reflect the button name change of import in the background.

2024-06-20 06:04 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/asset-properties.md
> +A complex asset property consists of multiple key-value pairs, meaning, it contains a root object followed by one or more key-value pairs. You can select the complex asset property option by switchin
Added.

2024-06-20 06:22 UTC, MWindel commented on content/dtm/asset-types-bundle/asset-properties.md
> +A complex asset property consists of multiple key-value pairs, meaning, it contains a root object followed by one or more key-value pairs. You can select the complex asset property option by switchin
```suggestion
A complex asset property consists of multiple key-value pairs, meaning, it contains a root object followed by one or more key-value pairs. You can select the complex asset property option by switching on the toggle. If you switch on the toggle, you must define each key-value pair as well as providing a type for each pair. You can arrange the properties in the required order by dragging and dropping them. Hover over the row to see the drag icon. Click and drag the drag icon for reordering. On the right side of each key-value pair, you see an expand icon <i class="dlt-c8y-icon-expand-arrow text-muted icon-20"></i>. Click the expand icon <i class="dlt-c8y-icon-expand-arrow text-muted icon-20"></i> to see a specific property. Note that when you add a new key-value pair, it automatically expands. To hide it, click the collapse icon <i class="dlt-c8y-icon-collapse-arrow text-muted icon-20"></i>.
```

2024-06-20 06:30 UTC, MWindel commented
@Vagdevi1998 This screenshot (static/images/dtm/custom-property/dtm-property-library-import.png) shows way to much empty (grey) space. Please crop the screenshot to only the dialog window.

2024-06-20 06:31 UTC, MWindel commented on static/images/dtm/custom-property/dtm-property-library-import.png
@Vagdevi1998 Please consider to reduce the number of screenshots if they are not absolutely necessary for the reader to understand the content of your documentation.

2024-06-21 05:27 UTC, Vagdevi1998 commented
> @Vagdevi1998 This screenshot (static/images/dtm/custom-property/dtm-property-library-import.png) shows way to much empty (grey) space. Please crop the screenshot to only the dialog window.

Updated the screenshot

2024-06-21 07:19 UTC, lra-sag requested changes
Go through all the screenshots for name change and add it in one go. Make sure to create a separate PR for each functionality to be documented. I believe the screenshots that show the Import button should have been updated as part of its corresponding documentation.

2024-06-21 07:19 UTC, lra-sag commented on static/images/dtm/assets/dtm-assets-move-assets.png
width of the image should be 1440px as per the standard please modify

2024-06-21 07:19 UTC, lra-sag commented on static/images/dtm/custom-property/dtm-property-library-import.png
crop the image closer to the popup such that it is at the center

2024-06-25 15:40 UTC, MWindel commented on static/images/dtm/assets/dtm-assets-move-assets.png
@Vagdevi1998 @lra-sag The image does not need to be 1440px wide, but your SCREEN dimensions (defined under settings) need to be 1440x900.

In this case, the screenshot needs to be modified, depending on what you want to showcase. If the dialog window is the important bit, then please crop the screenshot to the dialog window.

2024-06-26 07:15 UTC, Vagdevi1998 commented on static/images/dtm/custom-property/dtm-property-library-import.png
Modified

2024-06-26 09:00 UTC, lra-sag approved these changes

2024-06-26 11:18 UTC, MWindel approved these changes

2024-06-27 09:24 UTC, merged