Changelogs for Digital Twin Manager 1020.1.11
SoftwareAG/c8y-docs pull request #2217
Opened 2024-06-26 03:46 UTC by lra-sag

This PR contains the changelogs for Digital Twin Manager 1020.1.11

2024-06-26 07:02 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1020.1.11-add-default-sample-asset-models.md
> +Added Wind Turbine Model and Sample Power Plant Model as a default sample asset model in Asset model samples screen.
```suggestion
In the Asset model samples screen, the "Wind Turbine Model" and the "Sample Power Plant Model" have been added as default sample asset models.
```
What is the exact spelling of the models in the UI? Probably it should be "Wind turbine model" and "Sample power plant model" as we generally use sentence capitalization? 

Isn´t the Asset model samples screen a page? Then it must be **Asset model samples** page.

2024-06-26 07:02 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1020.1.11-update-label-capitalization.md
> +title: "Update label capitalization"
```suggestion
title: "Updated label capitalization"
```

2024-06-26 07:02 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1020.1.11-update-label-capitalization.md
> +Fixed inconsistent capitalization of labels, error messages and info messages to a uniform style throughout DTM.
```suggestion
Inconsistent capitalization of labels, error messages and info messages has been unified throughout the Digital Twin Manager application.
```

2024-06-26 07:02 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1020.1.11-add-default-sample-asset-models.md
> +      label: "Fix"
Is this really a fix? Sounds more like an improvement.

2024-06-26 12:06 UTC, pavanshivajirao approved these changes

2024-06-27 08:19 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1020.1.11-add-default-sample-asset-models.md
> +In the **Asset model samples** screen, the "Wind Turbine Model" and the "Sample Power Plant Model" have been added as default sample asset models.
```suggestion
In the **Asset model samples** page, the "Wind Turbine" model and the "Sample Power Plant" model have been added as default sample asset models.
```

2024-07-02 07:35 UTC, MWindel commented on content/change-logs/application-enablement/dtm-1020.1.11-update-label-capitalization.md
> +Inconsistent capitalization of labels, error messages and info messages has been unified throughout the Digital Twin Manager application.
```suggestion
Inconsistent capitalization of labels, error messages and info messages has been unified throughout the Digital twin manager application.
```

2024-07-02 08:15 UTC, lra-sag commented on content/change-logs/application-enablement/dtm-1020.1.11-add-default-sample-asset-models.md
> +    - value: "change-VSkj2iV9m"
```suggestion
    - value: "change-2c7RdTdXo4"
```

2024-07-02 15:34 UTC, rahultsag requested changes
i will suggest this description here: In the Asset Model Samples page, we've added two new sample models for a Wind Turbine and a Solar Power Plant. These samples serve as  an example and help you quickly get started with your own asset modeling.

2024-07-02 15:34 UTC, rahultsag commented on content/change-logs/application-enablement/dtm-1020.1.11-add-default-sample-asset-models.md
> +Added Wind Turbine Model and Sample Power Plant Model as a default sample asset model in Asset model samples screen.
i will suggest this description here: In the Asset Model Samples page, we've added two new sample models for a Wind Turbine and a Solar Power Plant. These samples serve as  an example and help you quickly get started with your own asset modeling.

2024-07-04 06:06 UTC, Vagdevi1998 commented on content/change-logs/application-enablement/dtm-1020.1.11-add-default-sample-asset-models.md
> +Added Wind Turbine Model and Sample Power Plant Model as a default sample asset model in Asset model samples screen.
Modified the description as below: 
In the **Asset model samples** page, we've added two new sample models for "Wind Turbine" and "Solar Power Plant". These samples serve as an example and help you quickly get started with your own asset modeling.

2024-07-04 06:07 UTC, Vagdevi1998 commented on content/change-logs/application-enablement/dtm-1020.1.11-add-default-sample-asset-models.md
> +      label: "Fix"
It is an improvement

2024-07-04 08:30 UTC, rahultsag approved these changes

2024-07-05 11:25 UTC, MWindel commented on content/change-logs/application-enablement/dtm-1020.1.11-add-default-sample-asset-models.md
> +title: "Added default sample asset models"
```suggestion
title: "Added default sample asset models to facilitate asset modeling"
```

2024-07-08 07:31 UTC, BeateRixen commented on content/change-logs/application-enablement/dtm-1020.1.11-add-default-sample-asset-models.md
> +date: "2024-07-04"
The date field should be left empty initially and filled in later. Or has DTM 1020.1.11 been deployed to Zone 1 on July 4th?

2024-07-08 08:35 UTC, Vagdevi1998 commented on content/change-logs/application-enablement/dtm-1020.1.11-add-default-sample-asset-models.md
> +date: "2024-07-04"
DTM 1020.1.11 has been deployed to Zone 1 on July 4th.

2024-07-08 08:59 UTC, BeateRixen approved these changes

2024-07-08 09:48 UTC, merged