MTM-56850 sso redirect to ui application documentation
SoftwareAG/c8y-docs pull request #2248
Opened 2024-07-05 08:15 UTC by mmed-softwareag

2024-07-08 04:36 UTC, kgol-c8y commented
I think if you add the screenshot with the enabled `Redirect to the user interface application` toggle button and the option to add `redirect URL` is greyed out, so that it makes sense that user need not add redirect URL

2024-07-08 04:37 UTC, kgol-c8y requested changes

2024-07-08 04:37 UTC, kgol-c8y commented on content/authentication/sso-bundle/custom-template.md
> +|Redirect to the user interface application|The redirect URL is automatically set to the application used by the user during login.
please look into my comment in the conversation

2024-08-01 08:49 UTC, mbak-c8y approved these changes

2024-08-05 05:37 UTC, kgol-c8y commented
Closing this as its duplicate of https://github.com/SoftwareAG/c8y-docs/pull/2327

2024-08-05 05:37 UTC, kgol-c8y commented
Closing this as its duplicate of https://github.com/SoftwareAG/c8y-docs/pull/2327

2024-08-05 05:37 UTC, closed without merging