Create ui-c8y-1020-7-0-split-cockpit-into-module-federation-plugins-6713.md
SoftwareAG/c8y-docs pull request #2275
Opened 2024-07-11 16:08 UTC by gen-App-Enablement

Release note created by c8y-ui-automations[bot]

Ticket: [MTM-60006](https://cumulocity.atlassian.net/browse/MTM-60006)
Original PR: [6713](https://github.softwareag.com/IOTA/cumulocity-ui/pull/6713)

2024-07-11 16:08 UTC, gen-App-Enablement reviewed
AI improvements

2024-07-11 16:08 UTC, gen-App-Enablement commented on content/change-logs/application-enablement/ui-c8y-1020-7-0-split-cockpit-into-module-federation-plugins-6713.md
> +title: split cockpit into module federation plugins (#6713)
The Claude AI suggested to use the following title:
```suggestion
title: Cockpit split into module federation plugins
```

2024-07-11 16:08 UTC, gen-App-Enablement commented on content/change-logs/application-enablement/ui-c8y-1020-7-0-split-cockpit-into-module-federation-plugins-6713.md
> +split cockpit into module federation plugins (#6713)
The Claude AI suggested to use the following body:
```suggestion
As part of the Cumulocity IoT platform, the Cockpit application provides a user interface for monitoring and controlling connected devices. To improve the modularity and maintainability of the Cockpit codebase, it has been split into separate module federation plugins. This change allows for better isolation and independent development of Cockpit features, enabling faster iteration and easier customization. Existing Cockpit functionality remains unchanged from a user perspective, ensuring a seamless transition to the new architecture.
```

2024-07-11 17:10 UTC, reey commented on content/change-logs/application-enablement/ui-c8y-1020-7-0-split-cockpit-into-module-federation-plugins-6713.md
> +split cockpit into module federation plugins (#6713)
```suggestion
The Cockpit application was splitted into further plugins. This allows admins to tailor their cockpit application to their needs without involving any coding efforts. They can remove certain plugins and therefore features which they do not want in their cockpit application. The plugins that have now been made available are: `Cockpit widgets`, `Cockpit alarms`, `Sensor phone`, `Child devices`, `Assets navigator`, `Data point library`, `Bookmarks`, `Location`, `Add location` & `Search`.
```

2024-07-11 17:12 UTC, reey commented on content/change-logs/application-enablement/ui-c8y-1020-7-0-split-cockpit-into-module-federation-plugins-6713.md
> +title: split cockpit into module federation plugins (#6713)
```suggestion
title: Pluginification of Cockpit
```

2024-07-11 17:12 UTC, reey approved these changes

2024-07-12 08:15 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-7-0-split-cockpit-into-module-federation-plugins-6713.md
> +The Cockpit application was splitted into further plugins. This allows admins to tailor their cockpit application to their needs without involving any coding efforts. They can remove certain plugins
```suggestion
The Cockpit application has been split into further plugins. This allows admins to tailor the Cockpit application to their needs without any coding effort. They can now easily remove certain plugins and thus certain features which they do not want to include in their Cockpit application. The following plugins are now available: 

* Cockpit widgets
* Cockpit alarms
* Sensor phone
* Child devices
* Assets navigator
* Data point library
* Bookmarks
* Location
* Add location
* Search
```

2024-07-12 08:15 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-7-0-split-cockpit-into-module-federation-plugins-6713.md
> +title: Pluginification of Cockpit
```suggestion
title: Cockpit application split into plugins
```

2024-07-12 08:16 UTC, BeateRixen approved these changes

2024-07-12 08:16 UTC, BeateRixen commented
@rahultsag Please approve

2024-07-16 11:47 UTC, rahultsag requested changes

2024-07-19 10:24 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-7-0-split-cockpit-into-module-federation-plugins-6713.md
> +* Search
I will merge now and add your suggestion directly in the source file.

2024-07-19 10:25 UTC, merged