Update new OAuth Internal description
SoftwareAG/c8y-docs pull request #230
Opened 2022-02-02 08:26 UTC by BeateRixen

2022-02-02 08:28 UTC, BeateRixen commented
@lukaszsoszynski The PR looks quite messy, I recommend you to review the text in the source file or in the Hugo preview.

2022-02-07 10:58 UTC, rssag requested changes

2022-02-07 10:58 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +When there is no configuration related to the session, OAuth Internal issues a JWT token with a certain lifetime. If the token expires then the user is forced to re-login because token refresh is not
think about "extremely" - do we need this kind of emphasis?

2022-02-07 10:58 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +The OAuth Internal token acts as a session identifier on the client site (web browser). Such token identifier which is stored in the cookie can have a preconfigured short lifetime. Then the {{< produ
```suggestion
The OAuth Internal token acts as a session identifier on the client site (web browser). Such a token identifier which is stored in the cookie can have a preconfigured short lifetime. Then the {{< product-c8y-iot >}} platform is responsible for renewing the session identifier without a user interaction. It is sufficient that the user's action causes the web browser to send a request to {{< product-c8y-iot >}}. Then {{< product-c8y-iot >}} can examine if the renewing of the session identifier should be executed and perform the operation if necessary. {{< product-c8y-iot >}} offers extensive configuration related to this behavior so that tenant administrators can adjust the configuration to their needs.
```

2022-02-07 10:58 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +During the session token renewal the previously provided token is revoked and a new one is provided. The parameter `Renewal token delay` defines the delay used to make this process smooth and not dis
maybe: "previously provided" -> "previous", "old and new one" -> "old and new"

2022-02-07 10:58 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +> **Info:** If external communication to the {{< management-tenant >}} has been blocked than it is only possible to access the tenant in a secure way (for example via SSH tunnel). This means that you
```suggestion
> **Info:** If external communication to the {{< management-tenant >}} has been blocked then it is only possible to access the tenant in a secure way (for example via SSH tunnel). This means that you can just as well use basic authentication. Additionally, it is not possible to use OAuth authentication since the communication from the external authorization server is also blocked. Therefore, the authentication method is automatically set to "Basic authentication" if the {{< management-tenant >}} is configured to block external communication.
```

2022-02-07 10:58 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +	- **Limit token validity for**: Lifetime of each session in minutes. When the session expires or a user logs out, the user has to enter a new verification code.
indentation not consistent with line 166 (the line below)

2022-02-07 10:58 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +	> **Info:** An SMS gateway microservice must be configured for the tenant. Naturally only users with a valid phone number associated can use this functionality.
the word "associated" seems a little lost - do we need it?

2022-02-07 16:00 UTC, MWindel commented on content/users-guide/administration-bundle/changing-settings.md
> +	- **Limit token validity for**: Lifetime of each session in minutes. When the session expires or a user logs out, the user has to enter a new verification code.
In Hugo they show up on the same indentation level.

2022-02-07 16:02 UTC, MWindel commented on content/users-guide/administration-bundle/changing-settings.md
> +   - **Limit verification code validity for**: Here you can set the lifetime of each verification code sent via SMS. When the verification code expires, in order to login the user has to request a ne
```suggestion
   - **Limit verification code validity for**: Here you can set the lifetime of each verification code sent via SMS. When the verification code expires, the user has to request a new verification code in order to login.
```

2022-02-07 16:14 UTC, MWindel commented on content/users-guide/administration-bundle/changing-settings.md
> +	> **Info:** The TOTP method is only available with the login mode "OAuth Internal".
```suggestion
> **Info:** The TOTP method is only available with the login mode "OAuth Internal".
```

2022-02-07 16:15 UTC, MWindel commented on content/users-guide/administration-bundle/changing-settings.md
> +>**Important:** Each time you change the TFA method you will be forced to log out. Users TFA settings are cleared and need to be configured again.
```suggestion
>**Important:** Each time you change the TFA method you will be forced to log out. User TFA settings are cleared and need to be configured again.
```

2022-02-08 15:10 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
> +When there is no configuration related to the session, OAuth Internal issues a JWT token with a certain lifetime. If the token expires then the user is forced to re-login because token refresh is not
Changed

2022-02-08 15:21 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
> +	> **Info:** An SMS gateway microservice must be configured for the tenant. Naturally only users with a valid phone number associated can use this functionality.
Yes; I´d say so. I mean, users will probably always have a valid phone number, the question is if it has been provided.

2022-02-15 10:01 UTC, rssag approved these changes

2022-02-15 11:17 UTC, lukaszsoszynskisag approved these changes
The documentation looks very, very good in my opinion. I added two small comments.

2022-02-15 11:17 UTC, lukaszsoszynskisag commented on content/users-guide/administration-bundle/changing-settings.md
> +> **Info:** If external communication to the {{< management-tenant >}} has been blocked, then it is only possible to access the tenant in a secure way (for example via SSH tunnel). This means that yo
I have a small suggestion. I think that "OAuth authentication" should be replaced with "SSO" here:
`Additionally, it is not possible to use SSO since the communication from the external authorization server is also blocked`

2022-02-15 14:47 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
> +>**Info:** The relation between the time parameters should be the following: renewal timeout < token timespan < absolute timeout. The recommended setting for renewal timeout is approximately half of
fixed

2022-02-15 14:49 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
> +> **Info:** If external communication to the {{< management-tenant >}} has been blocked, then it is only possible to access the tenant in a secure way (for example via SSH tunnel). This means that yo
changed

2022-02-15 20:06 UTC, Airdroplet commented on content/users-guide/administration-bundle/changing-settings.md
> +![OAI-Secure settings](/images/users-guide/Administration/admin-oaisecure-settings.png)
@lukaszsoszynskisag screenshot used here is outdated compared to description. It should show `OAI-Secure` :)

2022-02-15 20:06 UTC, Airdroplet commented on content/users-guide/administration-bundle/changing-settings.md
> +![OAI-Secure settings](/images/users-guide/Administration/admin-oaisecure-settings.png)
btw very similar screenshot is already present on this page: /images/users-guide/Administration/admin-settings-authentication.png

2022-02-15 20:16 UTC, Airdroplet commented
@lukaszsoszynskisag @BeateRixen @MWindel 
I've put small updates here: https://github.com/SoftwareAG/c8y-docs/pull/259
consider to merge 259 before you merge 230.

Please note that screenshots do not show yet very latest changes where renames were applied from "OAuth internal" to "OAI-Secure". Please consider to update all places where there was mention of oAuth internal previously :)

2022-02-16 10:35 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
> +![OAI-Secure settings](/images/users-guide/Administration/admin-oaisecure-settings.png)
I have deleted the second screenshot. After the naming change has been done in the UI, we need to replace the screenshot admin-settings-authentication.png once more.

2022-02-16 10:37 UTC, BeateRixen commented
> @lukaszsoszynskisag @BeateRixen @MWindel I've put small updates here: #259 consider to merge 259 before you merge 230.
> 
> Please note that screenshots do not show yet very latest changes where renames were applied from "OAuth internal" to "OAI-Secure". Please consider to update all places where there was mention of oAuth internal previously :)

I have already replaced all instances of OAuth Internal throughout the user documentation. For the API docs, @manasesjesus  will do the changes. I still need to check the OPS docs.

2022-02-16 10:39 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
> +>**Info:** To see the **Authentication** menu entry, you need one of the following roles: `ROLE_TENANT_ADMIN` or `ROLE_TENANT_MANAGEMENT_ADMIN`.
@lukaszsoszynskisag @Airdroplet How are these roles called from a UI perspective? I would want to change this here.

2022-02-16 11:21 UTC, MWindel approved these changes

2022-02-16 16:19 UTC, lukaszsoszynskisag commented on content/users-guide/administration-bundle/changing-settings.md
> +>**Info:** To see the **Authentication** menu entry, you need one of the following roles: `ROLE_TENANT_ADMIN` or `ROLE_TENANT_MANAGEMENT_ADMIN`.
The role ROLE_TENANT_MANAGEMENT_ADMIN in UI is actually a permission called "Tenant management" with type "ADMIN" what is visible on the following screenshot
![ROLE_TENANT_MANAGEMENT_ADMIN](https://user-images.githubusercontent.com/92983439/154308591-64cd0822-80d2-4010-82c1-e687cf5880b2.png)

But I think that role/permission `ROLE_TENANT_ADMIN` cannot be assigned or edited from the UI level. The role `ROLE_TENANT_ADMIN` is assigned to the first tenant user. The user is created together with tenant.

2022-02-16 16:53 UTC, merged