[DM-2111] lwm2m improvement - required availability
SoftwareAG/c8y-docs pull request #2305
Opened 2024-07-25 13:41 UTC by jakubsobolewskisag

* changelog
* documentation update

2024-07-25 14:05 UTC, sourajitsaha17 commented on content/change-logs/device-management/lwm2m-agent-10-20-374-0-possible-to-disable-required-availability-mgmt.md
> +LWM2M agent manages required interval of LWM2M device automatically based on LWM2M registration lifetime. It's now possible to disable this behavior globally or for specific devices.
And specify custom 'availability required interval' per device?

2024-07-25 14:19 UTC, jakubsobolewskisag commented on content/change-logs/device-management/lwm2m-agent-10-20-374-0-possible-to-disable-required-availability-mgmt.md
> +LWM2M agent manages required interval of LWM2M device automatically based on LWM2M registration lifetime. It's now possible to disable this behavior globally or for specific devices.
this was always possible - it's a C8Y standard

2024-07-25 14:22 UTC, sourajitsaha17 approved these changes

2024-07-29 07:20 UTC, BeateRixen commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align: left">Enable/Disable automatic management of availability required interval</td>
"automatic management of availability required interval": Is this really one term? This is quite long and hard to understand. Could we split it somehow? For example: Interval for automatic availability management? What is it called in the UI? I don´t think, that "required" is needed here? @Oezge-Akin can you please check the wording?

2024-07-29 07:21 UTC, BeateRixen commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align: left">When true (default), LWM2M agent will automatically set required interval to registration lifetime plus 2 minutes.</td>
```suggestion
<td style="text-align: left">When true (default), the LWM2M agent automatically sets the interval to registration lifetime plus 2 minutes.</td>
```

2024-08-05 11:23 UTC, Oezge-Akin commented on content/change-logs/device-management/lwm2m-agent-10-20-374-0-possible-to-disable-required-availability-mgmt.md
> +title: It's now possible to disable automatic management of availability required interval by LWM2M agent
```suggestion
title: Disabling automatic management of availability required interval of LWM2M agent
```

2024-08-05 11:23 UTC, Oezge-Akin commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align: left">Enable/Disable automatic management of availability required interval</td>
It is related to required interval field
https://cumulocity.com/docs/device-management-application/monitoring-and-controlling-devices/#to-monitor-the-connection-of-a-particular-device

Is this wording better "Automatic setting of required interval" to make it shorter and in tooltip we can add the details.

2024-08-05 13:32 UTC, BeateRixen commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align: left">Enable/Disable automatic management of availability required interval</td>
Yes, much clearer. Please change in the release notes title

2024-08-26 11:49 UTC, jakubsobolewskisag commented on content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
> +<td style="text-align: left">Enable/Disable automatic management of availability required interval</td>
done

2024-08-26 11:49 UTC, jakubsobolewskisag commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +  * Enable/disable automatic availability required interval management based on registration lifetime
done

2024-08-26 11:49 UTC, jakubsobolewskisag commented on content/change-logs/device-management/lwm2m-agent-10-20-374-0-possible-to-disable-required-availability-mgmt.md
> +title: It's now possible to disable automatic management of availability required interval by LWM2M agent
done

2024-08-27 07:27 UTC, Oezge-Akin approved these changes

2024-08-28 15:27 UTC, aaronraab requested changes

2024-08-28 15:27 UTC, aaronraab commented on content/change-logs/device-management/lwm2m-agent-10-20-378-0-possible-to-disable-required-availability-mgmt.md
> +title: Disabling automatic setting of required interval of LWM2M agent
```suggestion
title: Disabling the automatic configuration of the required interval
```

2024-08-28 15:27 UTC, aaronraab commented on content/change-logs/device-management/lwm2m-agent-10-20-378-0-possible-to-disable-required-availability-mgmt.md
> +The LWM2M agent automatically manages the required interval of a LWM2M device based on the LWM2M registration lifetime. It is now possible to disable this behavior globally or for specific devices.
We should also describe the other option. If I don't use the registration lifetime, how else can I define the interval? Is there a documentation entry we can reference here that describes how it works? Does it just work like for any other device like mentioned here: https://cumulocity.com/docs/device-management-application/monitoring-and-controlling-devices/#to-monitor-the-connection-of-a-particular-device?

2024-08-29 08:25 UTC, jakubsobolewskisag commented on content/change-logs/device-management/lwm2m-agent-10-20-378-0-possible-to-disable-required-availability-mgmt.md
> +title: Disabling automatic setting of required interval of LWM2M agent
done

2024-08-29 08:25 UTC, jakubsobolewskisag commented on content/change-logs/device-management/lwm2m-agent-10-20-378-0-possible-to-disable-required-availability-mgmt.md
> +The LWM2M agent automatically manages the required interval of a LWM2M device based on the LWM2M registration lifetime. It is now possible to disable this behavior globally or for specific devices.
done

2024-09-03 08:05 UTC, BeateRixen commented on content/change-logs/device-management/lwm2m-agent-10-20-378-0-possible-to-disable-required-availability-mgmt.md
> +The LWM2M agent automatically manages the required interval of a LWM2M device based on the LWM2M registration lifetime. It is now possible to disable this behavior globally or for specific devices wh
```suggestion
The LWM2M agent automatically manages the required interval of a LWM2M device based on the LWM2M registration lifetime. It is now possible to disable this behavior globally or for specific devices which results in a standard {{< product-c8y-iot >}} connection monitoring as described in [Monitoring and controlling devices](https://cumulocity.com/docs/device-management-application/monitoring-and-controlling-devices/#to-monitor-the-connection-of-a-particular-device). 
```

2024-09-03 12:28 UTC, BeateRixen approved these changes

2024-09-06 06:48 UTC, aaronraab requested changes

2024-09-06 06:48 UTC, aaronraab commented on content/change-logs/device-management/lwm2m-agent-10-20-378-0-possible-to-disable-required-availability-mgmt.md
> +The LWM2M agent automatically manages the required interval of a LWM2M device based on the LWM2M registration lifetime. It is now possible to disable this behavior globally or for specific devices wh
```suggestion
Cumulocity provides [connectivity monitoring](https://cumulocity.com/docs/device-management-application/monitoring-and-controlling-devices/#to-monitor-the-connection-of-a-particular-device) capabilities for which a required interval needs to be defined. For LwM2M device, this is automatically set by the LWM2M agent based on the registration lifetime. However, if the value is set manually, it will be overwritten by the LWM2M agent after each registration or registration update. This behavior can now be disabled both globally or for specific devices, allowing users to define the required interval independent of the registration lifetime.
```

2024-09-06 13:53 UTC, aaronraab approved these changes

2024-09-10 06:41 UTC, merged