Create ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
SoftwareAG/c8y-docs pull request #2316
Opened 2024-07-30 08:56 UTC by gen-App-Enablement

Release note created by c8y-ui-automations[bot]

Ticket: [MTM-59834](https://cumulocity.atlassian.net/browse/MTM-59834)
Original PR: [6796](https://github.softwareag.com/IOTA/cumulocity-ui/pull/6796)

2024-07-30 08:56 UTC, gen-App-Enablement reviewed
AI improvements

2024-07-30 08:56 UTC, gen-App-Enablement commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +title: Block paste dashboard action when user wants to copy device dashboard into group (#6716) [GRAFT][release/cd] (#6796)
The Claude AI suggested to use the following title:
```suggestion
title: Prevent pasting device dashboards into groups
```

2024-07-30 08:56 UTC, gen-App-Enablement commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +Block paste dashboard action when user wants to copy device dashboard into group (#6716) [GRAFT][release/cd] (#6796)
The Claude AI suggested to use the following body:
```suggestion
Previously, it was possible to copy a device dashboard and paste it into a group, which could lead to unexpected behavior and errors. With this change, the paste dashboard action is now blocked when attempting to paste a device dashboard into a group. This prevents users from accidentally copying device-specific dashboards to groups where the dashboard may not be applicable or function correctly.
```

2024-07-31 07:00 UTC, jdreSAG commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +title: Block paste dashboard action when user wants to copy device dashboard into group (#6716) [GRAFT][release/cd] (#6796)
```suggestion
title: Prevent pasting device dashboards into groups and groups dashboard into devices enhancement
```

2024-07-31 07:04 UTC, jdreSAG commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +Block paste dashboard action when user wants to copy device dashboard into group (#6716) [GRAFT][release/cd] (#6796)
```suggestion
Previously it was possible to click paste button when copying device dashboard and pasting to group (and other way too), but dashboard was not pasted and error was shown. Now paste button is disabled and title with reason for it is added.
```

2024-07-31 07:04 UTC, jdreSAG commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +Previously it was possible to click paste button when copying device dashboard and pasting to group (and other way too), but dashboard was not pasted and error was shown. Now paste button is disabled
```suggestion
Previously it was possible to click paste button when copying device dashboard and pasting to group (and opposite way too), but dashboard was not pasted and error was shown. Now paste button is disabled and title with reason for it is added.
```

2024-07-31 13:10 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +Previously it was possible to click paste button when copying device dashboard and pasting to group (and opposite way too), but dashboard was not pasted and error was shown. Now paste button is disab
```suggestion
Previously it was possible to click **Paste** when copying a device dashboard and pasting it into a group (or vice versa), which resulted in an error. Now, the paste button is disabled and information for the reason is provided.
```

2024-07-31 13:11 UTC, jdreSAG approved these changes

2024-07-31 13:11 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +title: Prevent pasting device dashboards into groups and groups dashboard into devices enhancement
```suggestion
title: Prevented pasting device dashboards into groups and group dashboards into devices
```

2024-07-31 13:12 UTC, BeateRixen approved these changes

2024-07-31 13:17 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +Previously it was possible to click **Paste** when copying a device dashboard and pasting it into a group (or vice versa), which resulted in an error. Now, the paste button is disabled and informatio
```suggestion
Previously users were able to copy a device dashboard and paste it into a group (or copy a group dashboard and paste it into a device), which resulted in an error. With this change, the paste button is now disabled and information for the reason is provided.
```

2024-07-31 13:20 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +title: Prevented pasting device dashboards into groups and group dashboards into devices
```suggestion
title: Disabled paste action when user attempts to paste device dashboards into groups or group dashboards into devices
```

2024-08-01 07:14 UTC, jdreSAG commented
@rahultsag can you have a second look, after changes?

2024-08-01 08:23 UTC, rahultsag requested changes
It seems we are restricting the paste action, not disabling the button and hence suggesting minor changes.

2024-08-01 08:23 UTC, rahultsag commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +Previously users were able to copy a device dashboard and paste it into a group (or copy a group dashboard and paste it into a device), which resulted in an error. With this change, the paste button
Previously, users were able to copy a device dashboard and paste it into a group (or copy a group dashboard and paste it into a device), which resulted in an error. To prevent this, pasting between device and group dashboards is now restricted and users will see an info message when attempting that.

2024-08-01 08:23 UTC, rahultsag commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +title: Disabled paste action when user attempts to paste device dashboards into groups or group dashboards into devices
Restricted paste action when user attempts to paste device dashboards into groups or group dashboards into

2024-08-01 08:28 UTC, BeateRixen commented on content/change-logs/application-enablement/ui-c8y-1020-13-3-block-paste-dashboard-action-when-user-wants-to-copy-device-dashboard.md
> +Previously users were able to copy a device dashboard and paste it into a group (or copy a group dashboard and paste it into a device), which resulted in an error. With this change, the paste button
```suggestion
Previously users were able to copy a device dashboard and paste it into a group (or copy a group dashboard and paste it into a device), which resulted in an error. To prevent this, pasting between device and group dashboards is now restricted and users will see an info message when attempting that.
```

2024-08-01 09:00 UTC, merged