[DM-3891] [LWM2M] Changelogs for improved snychronization for decoder events
SoftwareAG/c8y-docs pull request #2381
Opened 2024-08-22 09:57 UTC by sourajitsaha17

2024-08-22 09:58 UTC, eliasweingaertner commented on content/change-logs/device-management/cumulocity-10-18-540-190-LWM2M-improved-decoder-event-locking.md
> +Improved the synchronization mechanism to prevent duplicate external decoder events processing by the LWM2M agent.
Either "Improves" or "Has improved"

2024-08-22 09:59 UTC, eliasweingaertner approved these changes

2024-08-22 11:04 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity-10-18-540-190-LWM2M-improved-decoder-event-locking.md
> +Improves the synchronization mechanism to prevent duplicate external decoder events processing by the LWM2M agent.
```suggestion
The synchronization mechanism has been improved to prevent duplicate external decoder events processing by the LWM2M agent.
```

2024-08-23 08:08 UTC, sourajitsaha17 commented on content/change-logs/device-management/cumulocity-10-18-540-190-LWM2M-improved-decoder-event-locking.md
> +Improved the synchronization mechanism to prevent duplicate external decoder events processing by the LWM2M agent.
done

2024-08-23 13:27 UTC, aaronraab requested changes

2024-08-23 13:27 UTC, aaronraab commented on content/change-logs/device-management/cumulocity-10-18-540-190-LWM2M-improved-decoder-event-locking.md
> +The synchronization mechanism has been improved to prevent duplicate external decoder events processing by the LWM2M agent.
```suggestion
The synchronization mechanism has been improved to prevent the LwM2M Agent from processing duplicate external decoder events.
```

2024-08-27 08:49 UTC, aaronraab approved these changes

2024-08-27 08:52 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity-10-18-540-190-LWM2M-improved-decoder-event-locking.md
> +The synchronization mechanism has been improved to prevent the LwM2M Agent from processing duplicate external decoder events.
```suggestion
The synchronization mechanism has been improved to prevent the LwM2M agent from processing duplicate external decoder events.
```

2024-08-27 08:53 UTC, BeateRixen approved these changes

2024-08-27 08:53 UTC, BeateRixen commented on content/change-logs/device-management/cumulocity-10-18-540-190-LWM2M-improved-decoder-event-locking.md
> +The synchronization mechanism has been improved to prevent the LwM2M agent from processing duplicate external decoder events.
```suggestion
The synchronization mechanism has been improved to prevent the LWM2M agent from processing duplicate external decoder events.
```

2024-08-27 08:54 UTC, merged