Changelog: DM-3837 ASM OOM Killed
SoftwareAG/c8y-docs pull request #2394
Opened 2024-08-27 13:03 UTC by ashhSAG93

2024-08-27 13:19 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-8-0-fix-for-oomkill-during-software-read.md
> +The Advanced Software Management microservice used to crash due to an Out of Memory error while reading the softwares of a device. This fix optimises the process
```suggestion
The Advanced Software Management microservice used to run out of memory while reading the software items of a device. This issue has been fixed.
```

2024-08-27 13:19 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-8-0-fix-for-oomkill-during-software-read.md
> +of reading the softwares of a device without causing the microservice to crash and improves stability when we have devices with a large number of softwares.
```suggestion
The process has been optimized towards reading the software items of a device without issues and improving the stability in case of devices with a large number of software items. 
```

2024-08-27 13:19 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-8-0-fix-for-oomkill-during-software-read.md
> +title: Optimized Memory Usage while reading softwares of a device
```suggestion
title: Reading software items of a device no longer results in running out of memory
```

2024-08-27 15:23 UTC, BeateRixen approved these changes

2024-08-28 13:40 UTC, l2p- requested changes
Overall I think this changelog goes into an entirely wrong direction. We should explain customer impact of our changes. So far there was no customer impact because the reason why we implemented this was an internally discovered instability on one specific test environment. So writing a changelog about running out of memory is not really helpful.

This means that the story becomes about scalability and possibly memory efficiency. Do users really care about memory usage for a service that is provided? So my proposal is either we write a story about scalability or we write no changelog about this at all. @aaronraab which one do you prefer?

2024-08-29 08:50 UTC, aaronraab commented on content/change-logs/device-management/asm-1-8-0-fix-for-oomkill-during-software-read.md
> +The process has been optimized towards reading the software items of a device without issues and improving the stability in case of devices with a large number of software items.
I somehow can't reply to Philipp's remark. But I do fully agree. If this was only found in a test environment, this shouldn't be mentioned at all. Highlighting scalability improvements is also not helpful as scalability is expected by our customers so this actually does not actually imply an improvements but uncovers a problem in our past implementation. If no-one has seen any issues - that's good and we shouldn't highlight that we had some.

2024-08-29 09:11 UTC, ashhSAG93 commented on content/change-logs/device-management/asm-1-8-0-fix-for-oomkill-during-software-read.md
> +The process has been optimized towards reading the software items of a device without issues and improving the stability in case of devices with a large number of software items.
@l2p- shall I close the PR now? And then close the issue?

2024-09-03 08:12 UTC, BeateRixen commented on content/change-logs/device-management/asm-1-8-0-fix-for-oomkill-during-software-read.md
> +The process has been optimized towards reading the software items of a device without issues and improving the stability in case of devices with a large number of software items.
@ashhSAG93 Has this been clarified? Can we close the PR?

2024-09-03 09:23 UTC, closed without merging