[MTM-60743]: Enhance documentation of c8y-docs uploading same CA across tenant
SoftwareAG/c8y-docs pull request #2408
Opened 2024-09-02 11:46 UTC by cumulocitypans

https://cumulocity.atlassian.net/browse/MTM-60743

For Reviewers:
https://sagportal.sharepoint.com/:w:/r/sites/IoTAnalyticsRnDOps/_layouts/15/Doc.aspx?sourcedoc=%7B181C635B-97A0-4933-B0B3-4BD5F317A717%7D&file=Shared%20Trusted%20Certificates%20(Proposal).docx&action=default&mobileredirect=true

Enabling feature for allowing to upload same CA across platform.

2024-09-10 08:53 UTC, BeateRixen commented on content/device-integration/rest-client-examples-bundle/hello-rest-x509.md
> +If some other tenant uploaded a same certificate. In this case the device will always try to authorize itself with certificates but will fail in tenant identification.
```suggestion
If some other tenant uploaded a same certificate the device will always try to authorize itself with certificates but will fail in tenant identification.
```

2024-09-10 08:54 UTC, BeateRixen commented on content/device-integration/mqtt-bundle/implementation.md
> +* Probably some other tenant uploaded a same certificate. In this case the device will always try to authorize itself with certificates but will fail in tenant identification.
```suggestion
* If some other tenant uploaded a same certificate the device will always try to authorize itself with certificates but will fail in tenant identification.
```

2024-09-10 08:55 UTC, BeateRixen commented on content/device-integration/mqtt-bundle/implementation.md
> +* Probably some other tenant uploaded a same certificate. In this case the device will always try to authorize itself with certificates but will fail in tenant identification.
Isn´t this a duplicate of the following item?

2024-09-12 14:34 UTC, BeateRixen commented on content/device-integration/mqtt-bundle/implementation.md
> +* If some other tenant uploaded a same certificate the device will always try to authorize itself with certificates but will fail in tenant identification.
Not sure if you have not seen my comment, but this seems to be a duplicate of the sentence below, or is this something different?

2024-09-16 05:10 UTC, cumulocitypans commented on content/device-integration/mqtt-bundle/implementation.md
> +* If some other tenant uploaded a same certificate the device will always try to authorize itself with certificates but will fail in tenant identification.
`If all of the cases above are met and the device connection is still rejected due to certificates validation, then probably some other tenant uploaded a certificate with the same 'Common Name' as one of those sent by your device. In this case the device will always try to authorize itself with certificates.`

` If some other tenant uploaded a same certificate the device will always try to authorize itself with certificates but will fail in tenant identification.`

Above both sentence is differen as previous one is about same common name (CN) not certificate but below sentence talking about same certificate irrespective of common name (CN).

2024-09-16 07:43 UTC, BeateRixen approved these changes

2024-10-04 06:51 UTC, kgol-c8y approved these changes

2024-10-04 11:11 UTC, MWindel commented
@cumulocitypans What is the status here? Please add appropriate labels if the referencing software is not yet deployed.

2024-10-07 05:24 UTC, saran-govindarajan requested changes
@

2024-10-07 05:24 UTC, saran-govindarajan commented on content/change-logs/platform-services/cumulocity-10-20-27-1-information-about-mqtt-rest-limitation-for-shared-trusted.md
> +Support has been added for uploading same certificate on across tenant in {{< product-c8y-iot >}} via system option. When its enabled a message with warning "Shared trusted certificates are enabled o
_Devices may not able to connect over MQTT/REST using certificates_ 
This change is introduced for cumulocity instances that use only LwM2M devices. The MQTT/REST clients using certificate authentication will be affected when this system option is enabled.
@pink-mongoose Can you please confirm the release notes?

2024-10-07 05:24 UTC, saran-govindarajan commented on content/device-integration/device-certificates.md
> +Now we have capability to upload same certificate across multiple tenants in {{< product-c8y-iot >}}. It will be achieved by enabling instance level system option `system.ssl.shared-truststore.enable
We should also specify that the system property is disabled by default and can be enabled only by platform administrators and the steps are detailed in operations guide.
@pink-mongoose Can you please confirm the documentation notes.

2024-10-08 11:11 UTC, BeateRixen commented
@cumulocitypans @saran-govindarajan What is the status of this PR? PRs containing change logs should be merged in time so that they get published in time with the software update.

2024-10-15 08:32 UTC, pink-mongoose commented on content/change-logs/platform-services/cumulocity-10-20-27-1-information-about-mqtt-rest-limitation-for-shared-trusted.md
> +Support has been added for uploading same certificate on across tenant in {{< product-c8y-iot >}} via system option. When its enabled a message with warning "Shared trusted certificates are enabled o
1. We should not have a release note for this.
2. Documentations should be in the Operations Guide only

Information must include:
* For self hosted and dedicated environments only.
* No support for devices connecting over MQTT or REST - this is important, technically it is possible if the customer tracks their certificates but it makes support very difficult which is why R&D have stated NO SUPPORT. So change the _Device may not be able to connect _... to _When enabled devices must not use MQTT or REST, this is not supported when using this capability. _ or words to that effect.

2024-10-15 08:48 UTC, cumulocitypans commented on content/change-logs/platform-services/cumulocity-10-20-27-1-information-about-mqtt-rest-limitation-for-shared-trusted.md
> +Support has been added for uploading same certificate on across tenant in {{< product-c8y-iot >}} via system option. When its enabled a message with warning "Shared trusted certificates are enabled o
@pink-mongoose change in Operations Guide https://github.com/Cumulocity-IoT/c8y-docs-ops/pull/874 Please have a look is this information is sufficient? 
We can close this PR

2024-10-17 12:48 UTC, cumulocitypans commented
Closing this PR as we don't need to have change log for this.

2024-10-17 12:48 UTC, closed without merging