Create ui-c8y-1020-28-2-disable-edit-duplicate-options-for-global-smartrules-displayed-in-other-views.md
SoftwareAG/c8y-docs pull request #2456
Opened 2024-09-20 08:56 UTC by gen-App-Enablement

Release note created by llar

Ticket: [MTM-55915](https://cumulocity.atlassian.net/browse/MTM-55915)
Original PR: [7066](https://github.softwareag.com/IOTA/cumulocity-ui/pull/7066)

2024-09-20 08:56 UTC, gen-App-Enablement reviewed
AI improvements

2024-09-20 08:56 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1020-28-2-disable-edit-duplicate-options-for-global-smartrules-displayed-in-other-views.md
> +title: Disable-edit-duplicate-options-for-global-smartrules-displayed-in-other-views-than-global-smartrules-view [GRAFT][release/cd] (#7066)
The Claude AI suggested to use the following title:
```suggestion
title: disable edit and duplicate options for global smart rules displayed outside the global smart rules view
```

2024-09-20 08:56 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1020-28-2-disable-edit-duplicate-options-for-global-smartrules-displayed-in-other-views.md
> +Disable-edit-duplicate-options-for-global-smartrules-displayed-in-other-views-than-global-smartrules-view [GRAFT][release/cd] (#7066)
The Claude AI suggested to use the following body:
```suggestion
In the UI, global smart rules were shown with edit and duplicate options in other views than the dedicated global smart rules view. With this change, the edit and duplicate options for global smart rules are now disabled when they are displayed outside of the global smart rules view. This ensures that global smart rules can only be edited and duplicated in the dedicated view to avoid confusion and unintended modifications in other contexts.
```

2024-09-20 11:12 UTC, pink-mongoose requested changes
The one liner does nothing to indicate why this change has been made and does not scan with the dashes between words.  I would suggest something like:

To make the behaviour of global smart rules more deterministic, editing of global smart rules is now only allowed in the global smart rules view.

2024-09-22 22:12 UTC, Airdroplet commented
> The one liner does nothing to indicate why this change has been made and does not scan with the dashes between words. I would suggest something like:
> 
> To make the behaviour of global smart rules more deterministic, editing of global smart rules is now only allowed in the global smart rules view.

apparently it didn't pick up the message from commit automatically (ref: https://github.softwareag.com/IOTA/cumulocity-ui/pull/7066/commits/1d0d71dff62306d514800c9db2fd210e28082b38)

2024-09-23 14:11 UTC, Airdroplet approved these changes

2024-10-02 07:52 UTC, MWindel commented on content/change-logs/platform-services/ui-c8y-1020-28-2-disable-edit-duplicate-options-for-global-smartrules-displayed-in-other-views.md
> +Before it was possible to edit global smart rule from any context (device, group or application). With this change edit and duplicate action for global smart rule only available from global smart rul
```suggestion
Previously, it was possible to edit global smart rules from any context (device, group or application). With this change to edit and duplicate actions for global smart rules is only possible to do in the **Global smart rule** page.
```

2024-10-02 07:58 UTC, iiar-c8y commented on content/change-logs/platform-services/ui-c8y-1020-28-2-disable-edit-duplicate-options-for-global-smartrules-displayed-in-other-views.md
> +Before it was possible to edit global smart rule from any context (device, group or application). With this change edit and duplicate action for global smart rule only available from global smart rul
@MWindel what about small improvement on suggestion, like: 

```
Previously, it was possible to edit global smart rules from any context (device, group or application). With this change to use edit and duplicate actions for global smart rules is only possible from **Global smart rule** page.
```

2024-10-07 09:17 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1020-28-2-disable-edit-duplicate-options-for-global-smartrules-displayed-in-other-views.md
> +Previously, it was possible to edit global smart rules from any context (device, group or application). With this change to use edit and duplicate actions for global smart rules is only possible from
```suggestion
Previously, it was possible to edit global smart rules from any context (device, group or application). With this change editing or duplicating global smart rules is only possible from the **Global smart rule** page.
```

2024-10-07 09:19 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1020-28-2-disable-edit-duplicate-options-for-global-smartrules-displayed-in-other-views.md
> +title: Disable edit and duplicate options for global smart rules displayed outside the global smart rules view
```suggestion
title: Edit and duplicate options for global smart rules disabled outside the Global smart rules page
```

2024-10-07 10:45 UTC, BeateRixen approved these changes

2024-10-08 11:00 UTC, BeateRixen commented
@Airdroplet Can be merged from my side

2024-10-08 11:19 UTC, iiar-c8y commented
@BeateRixen I unable to merge, it is blocked by change request from @pink-mongoose.

2024-10-08 11:34 UTC, BeateRixen commented
@pink-mongoose I guess your comment has been resolved. Can you please approve?

2024-10-09 08:47 UTC, merged