Feature/mtm 58268/document mqtt service topic limiting
SoftwareAG/c8y-docs pull request #2464
Opened 2024-09-24 15:54 UTC by abor-c8y

Additional sections outlining changes included in MQTT Service topic limiting feature.

Details regarding receiving errors for topic limit related failures for MQTT 3 clients via error topic are absent as this is yet to be implemented: https://github.com/Cumulocity-IoT/c8y-mqtt-service/pull/153

2024-09-26 14:32 UTC, MWindel commented on content/device-integration/mqtt-service-bundle/implementation.md
> +MQTT Service has the ability to limit the total number of topics that a single tenant can create, current default is no limit.
```suggestion
MQTT Service has the ability to limit the total number of topics that a single tenant can create. The current default is no limit.
```

2024-09-26 14:32 UTC, MWindel commented on content/device-integration/mqtt-service-bundle/implementation.md
> +When creation of new topic, via implicit creation via client publishing message or subscribing to non-existent topic, would breach the topic limit
```suggestion
When the creation of a new topic, either by creating it directly via the client publishing message or subscribing to anon-existent topic, would breach the topic limit
```

2024-09-26 14:32 UTC, MWindel commented on content/device-integration/mqtt-service-bundle/implementation.md
> +In the case of MQTT 5 clients have access to reason code and reason string describing the failure when using QoS 1 via acknowledgements,
```suggestion
In the case of MQTT, five clients have access to the reason code and reason string describing the failure when using QoS 1 via acknowledgements,
```

2024-09-26 14:32 UTC, MWindel commented on content/device-integration/mqtt-service-bundle/implementation.md
> +reason code being QUOTA_EXCEEDED: 0x97.
```suggestion
reason code being `QUOTA_EXCEEDED: 0x97`.
```

2024-09-26 14:32 UTC, MWindel commented on content/device-integration/mqtt-service-bundle/implementation.md
> +In the case of MQTT 3.1 and 3.1.1 clients only have access to reason code describing the failure when using QoS 1 via acknowledgements and only
```suggestion
In the case of MQTT 3.1 and 3.1.1 clients only have access to the reason code describing the failure when using QoS 1 via acknowledgements and only
```

2024-09-26 14:32 UTC, MWindel commented on content/device-integration/mqtt-service-bundle/implementation.md
> +for SUBSCRIBE packets, where the reason code is 0x80.
```suggestion
for the SUBSCRIBE packets, where the reason code is `0x80`.
```

2024-09-26 14:32 UTC, MWindel commented on content/device-integration/mqtt-service-bundle/implementation.md
> +For PUBLISH packets, client will be disconnected with no further information as per the MQTT specification.
```suggestion
For PUBLISH packets, the client will be disconnected with no further information as per the MQTT specification.
```

2024-09-26 14:32 UTC, MWindel commented on content/device-integration/mqtt-service-bundle/implementation.md
> +MQTT Service will automatically remove topics which are no longer in use, topics are recognized as inactive when there are no subscriptions and
```suggestion
The MQTT service will automatically remove topics which are no longer in use, topics are recognized as inactive when there are no subscriptions and
```

2024-09-26 14:32 UTC, MWindel commented on content/device-integration/mqtt-service-bundle/implementation.md
> +internal publisher to the topic is closed. The publisher is responsible for publishing modified MQTT Service messages to the correct topic and these
```suggestion
the internal publisher to the topic is closed. The publisher is responsible for publishing the modified MQTT service messages to the correct topic. These
```

2024-09-26 14:32 UTC, MWindel commented on content/device-integration/mqtt-service-bundle/index.html
> +title: MQTT Service
```suggestion
title: MQTT service
```

2024-10-08 15:29 UTC, gapa-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +When creation of new topic, via implicit creation via client publishing message or subscribing to non-existent topic, would breach the topic limit
@abor-c8y in case you don't spot it, there's a mistake in @MWindel's suggestion ('anon-existent' should be ' a non-existent')

2024-10-08 15:32 UTC, gapa-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +In the case of MQTT 5 clients have access to reason code and reason string describing the failure when using QoS 1 via acknowledgements,
@abor-c8y, @MWindel. This should be ' ... of MQTT 5, clients have access ...'. The 5 is the MQTT protocol version, not the number of clients.

2024-10-08 15:36 UTC, gapa-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +In the case of MQTT 5 clients have access to reason code and reason string describing the failure when using QoS 1 via acknowledgements,
.. and should this be '... using QoS 1 _with_ acknowledgements ...'.

The whole sentence seems unclear and maybe assuming some context/example. It's hard to tell what it should be or what it is trying to say..

2024-10-08 15:41 UTC, gapa-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +In the case of MQTT 5 clients have access to reason code and reason string describing the failure when using QoS 1 via acknowledgements,
.. okay the context is 'topic limit'. SO I guess the missing part is that we should be saying, 'When the topic limit is reached, attempts to create  new topic will ... for MQTT 5, ....for MQTT 3.1 and 3.1.1. Maybe broken into more than one sentences or bullet points.

2024-10-08 15:44 UTC, gapa-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +MQTT Service will automatically remove topics which are no longer in use, topics are recognized as inactive when there are no subscriptions and
I'd suggest a full-stop and new sentence between '... no longer in use. and 'topics are recognized ...' rather than a comma

2024-10-08 15:54 UTC, gapa-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +MQTT Service will automatically remove topics which are no longer in use, topics are recognized as inactive when there are no subscriptions and
In fact more - user the same language across 2 sentences 
```suggestion
The MQTT service will automatically remove topics which are no longer active. Topics are recognized as inactive when there are no subscriptions and
```

2024-10-08 15:55 UTC, gapa-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +When creation of new topic, via implicit creation via client publishing message or subscribing to non-existent topic, would breach the topic limit
```suggestion
When the creation of a new topic, either by creating it directly via the client publishing message or subscribing to a non-existent topic, would breach the topic limit
```

2024-10-08 16:02 UTC, gapa-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +
```suggestion
the internal publisher to the topic is closed. The publisher is responsible for publishing the modified MQTT service messages to the correct topic. The publishers 
live within a cache with an expiry time of one hour. As a result, it can take up to an hour after removing all subscriptions from a topic
for it to be automatically deleted.

```

2024-10-08 16:05 UTC, gapa-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +internal publisher to the topic is closed. The publisher is responsible for publishing modified MQTT Service messages to the correct topic and these
Alternative that adds this below. 'These sounded like the messages as it was the only plural entity in the previous sentence, so below I've changed 'These' to 'The publishers' to be clearer. I also improved the following sentence

2024-10-08 16:08 UTC, gapa-c8y requested changes
Happy to go through these with you (it might be confusing given I've added to @MWindel's comments. Also I might need correction to my understanding.

2024-10-09 15:44 UTC, gapa-c8y approved these changes

2024-10-29 08:31 UTC, MWindel approved these changes

2024-10-29 11:23 UTC, merged