Create ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
SoftwareAG/c8y-docs pull request #2533
Opened 2024-10-16 11:48 UTC by gen-App-Enablement

Release note created by mmed-c8y

Ticket: [MTM-56510](https://cumulocity.atlassian.net/browse/MTM-56510)
Original PR: [7309](https://github.com/Cumulocity-IoT/cumulocity-ui/pull/7309)

2024-10-16 11:48 UTC, gen-App-Enablement reviewed
AI improvements

2024-10-16 11:48 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +title: cherry-pick of all feature: 31cccab4f43f2bcc51a132dcb402b1a… (#7309)
The Claude AI suggested to use the following title:
```suggestion
title: All feature cherry-picked from main branch
```

2024-10-16 11:48 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +cherry-pick of all feature: 31cccab4f43f2bcc51a132dcb402b1a… (#7309)
The Claude AI suggested to use the following body:
```suggestion
As part of ongoing development efforts, a commit containing an "all feature" was made on the main branch. To ensure this feature is also available on the current branch, the commit has been cherry-picked and merged. This change brings the current branch up-to-date with the latest "all feature" from the main branch. End-users should not experience any noticeable impact, as this is an internal development change.
```

2024-10-28 08:55 UTC, kowa-c8y requested changes

2024-10-28 08:55 UTC, kowa-c8y commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +cherry-pick of all feature: 31cccab4f43f2bcc51a132dcb402b1a… (#7309)
@mmed-c8y please verify the suggestions as current release note is to technical

2024-10-31 13:47 UTC, kowa-c8y approved these changes

2024-10-31 13:47 UTC, kowa-c8y commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator has the option to log out all users assigned to that role.
```suggestion
When deleting or modifying a global role, the administrator has the option to log out all users who are assigned to that role.
```

2024-11-01 12:17 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +title: Logging out all users when deleting/changing global roles.
```suggestion
title: Logging out all users when deleting or modifying a global role
```

2024-11-01 12:17 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator has the option to log out all users assigned to that role.
I suggest to add "now": the administrator now has the option...

2024-11-07 11:48 UTC, BeateRixen commented
@kowa-c8y @mmed-c8y @saran-govindarajan Can we get this PR merged? It already quite old and change logs should be added quickly (latest within a week) to get published in time.

2024-11-11 09:25 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator has the option to log out all users who are assigned to that role.
```suggestion
When deleting or modifying a global role, the administrator has the option to log out all users that are assigned to that role.
```

2024-11-11 09:25 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator has the option to log out all users that are assigned to that role.
```suggestion
When deleting or modifying a global role, the administrator now has the option to log out all users that are assigned to that role.
```

2024-11-11 09:30 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator now has the option to log out all users that are assigned to that role.
@saran-govindarajan @JanePorter This information is quite poor. What was the issue the user was facing and what is the advantage of this option? We need more details here to make this entry of any use to the user. This PR is now open for a couple of weeks, actually change log PR should be merged asap.

2024-11-28 08:02 UTC, kowa-c8y commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator now has the option to log out all users that are assigned to that role.
Actually, it seems that the description is complete - previously there was no option to log all users out when modifying a global role, but now there is.

2024-11-28 08:03 UTC, kowa-c8y commented
From my point of view it can be merged. I already approved it. If @BeateRixen  will confirm it it will be automatically, merged.

2024-11-28 08:23 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +title: Logging out all users when deleting or modifying a global role
```suggestion
title: Option to log out all users when deleting or modifying a global role
```

2024-11-28 13:10 UTC, JanePorter commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator now has the option to log out all users that are assigned to that role.
@kowa-c8y but why would someone want to lot out all users? Should it read something like:

When deleting or modifying a global role and administrator can now ensure the changes take immediate effect by using a new option which will log out all users assigned to that role.

2024-11-28 13:26 UTC, kowa-c8y commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator now has the option to log out all users that are assigned to that role.
Good point! The intention here is definitely worth mentioning.  :+1:

2024-11-28 13:29 UTC, kowa-c8y commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator now has the option to log out all users that are assigned to that role.
```suggestion
When deleting or modifying a global role, an administrator can now ensure that changes take immediate effect by using a new option to log out all users assigned to that role.
```

2024-11-28 13:29 UTC, kowa-c8y commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator now has the option to log out all users that are assigned to that role.
@BeateRixen please check if it's ok commit and we will merge it :+1:

2024-11-29 12:15 UTC, kowa-c8y commented on content/change-logs/platform-services/ui-c8y-1020-36-0-cherry-pick-of-all-feature-31-cccab-4-f-43-f.md
> +When deleting or modifying a global role, the administrator now has the option to log out all users that are assigned to that role.
@BeateRixen  please check last commit and if its ok please merge it

2024-12-02 11:11 UTC, BeateRixen approved these changes

2024-12-02 11:12 UTC, merged