MTM-43486 Review Data explorer
SoftwareAG/c8y-docs pull request #254
Opened 2022-02-13 20:37 UTC by Airdroplet

* improved description in some places
* updated screenshots
* removed some unclear screenshots

2022-02-13 20:41 UTC, Airdroplet commented
@BeateRixen Review of this part is quite complex. I suspect that there are some issues for UI to fix in order to make sure that Data Explorer, at least in relation to information provided within internal doc: https://docs.google.com/document/d/1rWydw6kHDJnzVk12-NClFT4JVAjfMJpTVaxBdK9w_ng/edit?usp=sharing

Therefor please review carefully changes suggested here.

2022-02-14 16:12 UTC, BeateRixen commented on content/users-guide/cockpit-bundle/data-explorer.md
> +>**Info:** Save as default is triggering save of datapoint configuration within particular source device object. In case of saving configuration as default, reference to stored data can be used by ot
@Airdroplet Where do I find this "Save as default" option?

2022-02-16 19:44 UTC, Airdroplet commented
@BeateRixen please don't rush with merging this one. I still need to talk with team in respect to some issues observed on platform in respect to this feature. Hopefully will finish with my tests before Friday.

2022-02-17 08:25 UTC, Airdroplet commented on content/users-guide/cockpit-bundle/data-explorer.md
> +Click **Save as default** if you want for each user accessing the view to be able to see data points configuration.
@BeateRixen I have changed this part to correspond to previously mentioned internal document. 

Additionally did some testing due to previous doubts and confirm that everything is fine there.

2022-02-17 08:26 UTC, Airdroplet commented
@BeateRixen I think it is fine now from content perspective. Please verify grammar and it can go in :)

2022-02-17 08:29 UTC, Airdroplet commented on content/users-guide/cockpit-bundle/data-explorer.md
> +Click **Save as default** if you want for each user accessing the view to be able to see data points configuration.
hm, still not right :)

2022-02-17 08:49 UTC, Airdroplet commented on content/users-guide/cockpit-bundle/data-explorer.md
> +Click **Save as default** if you want each user accessing the view to be able to see predefined configuration when adding datapoints to be displayed in data explorer.
@BeateRixen this has been changed

2022-02-17 08:50 UTC, Airdroplet commented on content/users-guide/cockpit-bundle/data-explorer.md
> +Click **Save as default** if you want for each user accessing the view to be able to see data points configuration.
changed once more

2022-02-17 08:50 UTC, Airdroplet commented
@BeateRixen now it should be correct :)

2022-02-17 09:49 UTC, pawel-rynarzewski-sag requested changes
General remark: please use "data point" and "smart rule" consistently with the rest of documentation.

2022-02-17 09:49 UTC, pawel-rynarzewski-sag commented on content/users-guide/cockpit-bundle/data-explorer.md
> +>**Info:** JsonPath expressions added from data points are stored in bracket notation in order to increase flexibility in fragment and series naming (for example whitespaces are supported):
The trailing `:` suggests that something will follow it, e.g. a screenshot, but now it's removed. I see the screenshot was from export UI, so not really belonging in data point explorer section. Shouldn't we move both JsonPath note and the screenshot to the right section instead?

2022-02-17 09:49 UTC, pawel-rynarzewski-sag commented on content/users-guide/cockpit-bundle/data-explorer.md
> +>**Info:** if you have existing **on measurement threshold create alarm** smartrule based on data point library entry used for current datapoint, when you click **save as default** you are effectivel
Maybe change "Info" to "Example"?

2022-02-17 09:49 UTC, pawel-rynarzewski-sag commented on content/users-guide/cockpit-bundle/data-explorer.md
> +If you want to restore data point library default settings, click **Load from library** and then click **Save as default**.
I'd move this to the main text above.

2022-02-17 09:49 UTC, pawel-rynarzewski-sag commented on content/users-guide/cockpit-bundle/data-explorer.md
> +Click **Save as default** if you want each user accessing the view to be able to see predefined configuration when adding datapoints to be displayed in data explorer.
This is only one of the effects. Maybe: `Click **Save as default** to store data point settings into device's managed object. These settings will then take precendence over the settings from data point library, e.g. when this data point is added to a data explorer by other users, or when there is a threshold smart rule processing this device and its data point. If you want to restore data point library default settings, click **Load from library** and then click **Save as default**.`?
btw, executing the last sentence, only save settings from library to device, right? There is no way to genuinely remove data point entry from device's managed object?

2022-02-17 12:52 UTC, Airdroplet commented on content/users-guide/cockpit-bundle/data-explorer.md
> +Click **Save as default** if you want each user accessing the view to be able to see predefined configuration when adding datapoints to be displayed in data explorer.
only manually via rest

2022-02-17 12:54 UTC, Airdroplet commented on content/users-guide/cockpit-bundle/data-explorer.md
>  ![Save data point to library](/images/users-guide/cockpit/cockpit-dataexplorer-savedatapoint.png)
yeah, right, will replace that one.

2022-02-17 13:00 UTC, Airdroplet commented on content/users-guide/cockpit-bundle/data-explorer.md
> +>**Info:** if you have existing **on measurement threshold create alarm** smartrule based on data point library entry used for current datapoint, when you click **save as default** you are effectivel
done

2022-02-18 11:02 UTC, Airdroplet commented on content/users-guide/cockpit-bundle/data-explorer.md
> +>**Info:** JsonPath expressions added from data points are stored in bracket notation in order to increase flexibility in fragment and series naming (for example whitespaces are supported):
removed from here

2022-02-18 11:54 UTC, pawel-rynarzewski-sag commented on content/users-guide/cockpit-bundle/data-explorer.md
> +For details on the data point library refer to [Using the datapoint library](#data-point-library).
"Data point library" - this is how it's spelled in the app

2022-02-21 05:19 UTC, Airdroplet commented on content/users-guide/cockpit-bundle/data-explorer.md
> +>**Example:** if you have existing **on measurement threshold create alarm** smartrule based on data point library entry used for current datapoint, when you click **save as default** you are effecti
Sounds good.

2022-02-21 05:20 UTC, Airdroplet commented on content/users-guide/cockpit-bundle/data-explorer.md
> +For details on the data point library refer to [Using the datapoint library](#data-point-library).
changed

2022-02-21 12:45 UTC, pawel-rynarzewski-sag approved these changes

2022-02-22 09:05 UTC, BeateRixen approved these changes

2022-02-22 09:15 UTC, merged