DM-2812: Adding change logs
SoftwareAG/c8y-docs pull request #2545
Opened 2024-10-22 12:58 UTC by shaikhahme

2024-10-22 13:16 UTC, aaronraab requested changes

2024-10-22 13:16 UTC, aaronraab commented on content/change-logs/device-management/lwm2m-agent_10-20-394-0_updating-bulk-registration-templates.md
> +When bulk registering LWM2M devices to the LWM2M service, the wizard provides default bulk registration templates.
```suggestion
The wizard for bulk registering LWM2M devices to Cumulocity provides default bulk registration templates.
```

2024-10-22 13:16 UTC, aaronraab commented on content/change-logs/device-management/lwm2m-agent_10-20-394-0_updating-bulk-registration-templates.md
> +These bulk device registration templates have been updated to reflect new properties including X.509 security
```suggestion
These templates have been updated to reflect new properties including the X.509 security
```

2024-10-23 06:55 UTC, Oezge-Akin commented on content/change-logs/device-management/lwm2m-agent_10-20-394-0_updating-bulk-registration-templates.md
> +ticket: DM-4048
```suggestion
ticket: DM-2812
```

2024-10-24 08:27 UTC, BeateRixen commented on content/change-logs/device-management/lwm2m-agent_10-20-394-0_updating-bulk-registration-templates.md
> +The wizard for bulk registering LWM2M devices to Cumulocity provides default bulk registration templates.
```suggestion
The wizard for bulk registering LWM2M devices to {{< product-c8y-iot >}} provides default bulk registration templates.
```

2024-10-24 08:27 UTC, BeateRixen approved these changes

2024-10-24 09:13 UTC, Oezge-Akin approved these changes

2024-10-24 11:58 UTC, aaronraab approved these changes

2024-10-28 09:32 UTC, merged