[MTM-61478] changed the structure titles for enhanced time series support
SoftwareAG/c8y-docs pull request #2599
Opened 2024-11-04 10:27 UTC by darlucumulo

2024-11-04 10:56 UTC, MWindel commented on content/enterprise-tenant/enhanced-time-series-migration-support-bundle/enhanced-time-series-support.md
> +title: Enhanced time series configuration
@darlucumulo Could you also fix the file name accordingly?

2024-11-04 10:57 UTC, pawel-rynarzewski-sag commented on content/enterprise-tenant/enhanced-time-series-migration-support.md
> +title: Enhanced time series migration support
This is an entry covering both configuration and migration subentries, so it needs to be more general:
```suggestion
title: Enhanced time series support
```

2024-11-04 10:57 UTC, pawel-rynarzewski-sag commented on content/enterprise-tenant/enhanced-time-series-migration-support-bundle/enhanced-time-series-support.md
>  helpcontent:
This `helpcontent` should rather be moved to the section about time series migration in `time-series-migration.md`. Note it will require an update of link in the timeseries repo, too.

2024-11-04 10:57 UTC, pawel-rynarzewski-sag commented on content/enterprise-tenant/enhanced-time-series-migration-support-bundle/enhanced-time-series-support.md
> +title: Enhanced time series configuration
Not sure we want to repeat the whole phrase "Enhanced time series" in child items if it's already in the parent?

2024-11-04 10:57 UTC, pawel-rynarzewski-sag commented on content/enterprise-tenant/enhanced-time-series-migration-support-bundle/time-series-migration.md
> +title: Enhanced time series migration
Not sure we want to repeat the whole phrase "Enhanced time series" in child items if it's already in the parent?

2024-11-04 10:57 UTC, pawel-rynarzewski-sag commented on content/enterprise-tenant/enhanced-time-series-migration-support.md
>    - html
Is the position (`weight: 11`) of the item correct? Is it more important than managing tenants and user hierarchies?

2024-11-04 12:04 UTC, darlucumulo commented on content/enterprise-tenant/enhanced-time-series-migration-support.md
>    - html
I had no idea what weight should be there so I've added the same weight as for managing tenants section; as long migration of time series measurements won't be done and it could influence users expectations and work it could be kinda a bloker for customers, so it definitely should not be the last in the hierarchy, however only `enterprise tenant` bundle has lower weight, everything else has higher. And user hierarchies is not in enterprise bundle

2024-11-04 12:04 UTC, darlucumulo commented on content/enterprise-tenant/enhanced-time-series-migration-support-bundle/time-series-migration.md
> +title: Enhanced time series migration
why not?

2024-11-04 12:04 UTC, darlucumulo commented on content/enterprise-tenant/enhanced-time-series-migration-support-bundle/enhanced-time-series-support.md
> +title: Enhanced time series configuration
why not? the view will be on the new page right?

2024-11-05 16:43 UTC, pawel-rynarzewski-sag commented on content/enterprise-tenant/enhanced-time-series-migration-support-bundle/enhanced-time-series-support.md
> +title: Enhanced time series configuration
My point was to avoid repeating 3 very similar phrases in the adjacent menu entries, shorter labels help to distinguish the entries.
I see you changed it to "General configuration" already :+1:

2024-11-05 16:44 UTC, pawel-rynarzewski-c8y commented on content/enterprise-tenant/enhanced-time-series-migration-support-bundle/time-series-migration.md
> +title: Enhanced time series migration
My point was to avoid repeating 3 very similar phrases in the adjacent menu entries, shorter labels help to distinguish the entries.
I see you changed the child entries' labels already :+1:

2024-11-05 16:45 UTC, pawel-rynarzewski-sag commented on content/enterprise-tenant/enhanced-time-series-migration-support.md
>    - html
ok, so let's keep `11` as is.

2024-11-05 17:02 UTC, pawel-rynarzewski-sag requested changes

2024-11-05 17:02 UTC, pawel-rynarzewski-c8y commented on content/enterprise-tenant/enhanced-time-series-support-bundle/migration-process-description.md
> +  - label: enhanced-time-series-support
Note that section title is used to generate `id` of the section on the website
![2024-11-05_17-56](https://github.com/user-attachments/assets/7186015d-2df8-4fbc-b814-f1d088a2f25f)
and `label` should correspond to it, because it's used in a link later on.
```suggestion
  - label: migration-process-description
```
**Remember to update hash parts of links in UI as well.**
https://github.com/search?q=repo%3ACumulocity-IoT%2Fc8y-timeseries-migration+%23enhanced-time-series-support&type=code

2024-11-06 09:44 UTC, merged