Create ui-c8y-1021-11-0-migrated-custom-properties-form-7484-graft-release-cd-7682.md
SoftwareAG/c8y-docs pull request #2688
Opened 2024-12-02 07:28 UTC by gen-App-Enablement

Release note created by pawel-rynarzewski-sag

Ticket: [MTM-60789](https://cumulocity.atlassian.net/browse/MTM-60789)
Original PR: [7682](https://github.com/Cumulocity-IoT/cumulocity-ui/pull/7682)

2024-12-02 07:28 UTC, gen-App-Enablement reviewed
AI improvements

2024-12-02 07:28 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1021-11-0-migrated-custom-properties-form-7484-graft-release-cd-7682.md
> +title: Migrated custom properties form (#7484) [GRAFT][release/cd] (#7682)
The Claude AI suggested to use the following title:
```suggestion
title: Custom properties form migrated to Angular
```

2024-12-02 07:28 UTC, gen-App-Enablement commented on content/change-logs/platform-services/ui-c8y-1021-11-0-migrated-custom-properties-form-7484-graft-release-cd-7682.md
> +Migrated custom properties form (#7484) [GRAFT][release/cd] (#7682)
The Claude AI suggested to use the following body:
```suggestion
As part of the ongoing modernization efforts, the custom properties form has been migrated from the legacy technology to Angular. This change brings the custom properties form in line with the latest web technologies used in the application. The migration improves consistency and maintainability of the codebase. For users, the functionality and user interface of the custom properties form remains largely unchanged.
```

2024-12-02 17:58 UTC, JanePorter commented on content/change-logs/platform-services/ui-c8y-1021-11-0-migrated-custom-properties-form-7484-graft-release-cd-7682.md
> +Migrated custom properties form (#7484) [GRAFT][release/cd] (#7682)
Custom properties form improvement

2024-12-02 18:01 UTC, JanePorter requested changes
See suggested changes

2024-12-05 11:26 UTC, pawel-rynarzewski-sag commented on content/change-logs/platform-services/ui-c8y-1021-11-0-migrated-custom-properties-form-7484-graft-release-cd-7682.md
> +title: Migrated custom properties form (#7484) [GRAFT][release/cd] (#7682)
```suggestion
title: '"Custom properties" tab improved'
```

2024-12-05 11:26 UTC, pawel-rynarzewski-sag commented on content/change-logs/platform-services/ui-c8y-1021-11-0-migrated-custom-properties-form-7484-graft-release-cd-7682.md
> +Migrated custom properties form (#7484) [GRAFT][release/cd] (#7682)
declined this suggestion

2024-12-05 11:27 UTC, pawel-rynarzewski-sag commented on content/change-logs/platform-services/ui-c8y-1021-11-0-migrated-custom-properties-form-7484-graft-release-cd-7682.md
> +Migrated custom properties form (#7484) [GRAFT][release/cd] (#7682)
```suggestion
The "Custom properties" tab has been improved with extraneous information moved to a new "Limits" tab providing a cleaner and more consistent interface.
```

2024-12-05 12:38 UTC, JanePorter approved these changes

2024-12-05 13:01 UTC, pawel-rynarzewski-sag approved these changes

2024-12-05 14:36 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1021-11-0-migrated-custom-properties-form-7484-graft-release-cd-7682.md
> +The "Custom properties" tab has been improved with extraneous information moved to a new "Limits" tab providing a cleaner and more consistent interface.
```suggestion
The **Custom properties** tab in the tenant details has been improved by moving extraneous information to a new **Limits** tab providing a cleaner and more consistent interface.
```

2024-12-05 14:38 UTC, BeateRixen commented on content/change-logs/platform-services/ui-c8y-1021-11-0-migrated-custom-properties-form-7484-graft-release-cd-7682.md
> +title: '"Custom properties" tab improved'
```suggestion
title: Improved Custom properties tab in the tenant details
```

2024-12-05 14:38 UTC, BeateRixen approved these changes

2024-12-05 14:39 UTC, merged