MQTT Service private preview user documentation
SoftwareAG/c8y-docs pull request #2695
Opened 2024-12-03 18:26 UTC by scmi-c8y

Integration PR for the MQTT Service private preview user documentation. All changes to this documentation should be merged into the `private-preview/mqtt-service` branch until the MQTT Service is promoted to public preview. This PR will be merged into `develop` at that time.

NOTE: This replaces the previous PR from the `private-preview/mqtt-connect` branch 1) so we can use the right name, and 2) it was the quickest way to rebase it and create a new preview.

2025-01-06 22:11 UTC, MWindel approved these changes

2025-01-13 14:53 UTC, bph-c8y commented on content/device-integration/mqtt-service.md
> +section:
Should this be `sector`? Noticed the left-hand pane was a little broken, and I think this is the reason:

![image](https://github.com/user-attachments/assets/27c7b9c3-be36-43a4-8ffc-612f2f167479)

2025-01-23 13:35 UTC, eickler commented on content/device-integration/mqtt-service-bundle/java-client.md
> +#### Example {#example}
Shouldn't the example be related to the use case? 

IMHO:
* Do the subscription first and show how a message is converted for Cumulocity. E.g. incoming text message is converted to an event with the text message on a device. I guess receiving data is the most important use case.
* Show publishing as second example. 
* Add a link to the implementation in cumulocity-examples or somewhere on Github?

2025-01-23 13:35 UTC, eickler commented on content/device-integration/mqtt-service-bundle/faq.md
> +Q: How to obtain device credential?<br/>
I was confused when reading this. What does a reference to the Cumulocity MQTT integration lifecycle help with non-Cumulocity devices? IHMO that deserves a bit more discussion. How does it go practically? Some pre-registration process?

2025-01-23 13:47 UTC, scmi-c8y commented on content/device-integration/mqtt-service.md
> +section:
@bph-c8y It is supposed to be a top-level section, i.e. not nested under "Device integration using MQTT".

2025-01-23 13:50 UTC, bph-c8y commented on content/device-integration/mqtt-service.md
> +section:
I believe the key would still be sector, like https://github.com/Cumulocity-IoT/c8y-docs/blob/e5fee622add47b7755677de97f9bc80adcbf0df7/content/device-integration/mqtt.md.

(Actually, I think looking at https://github.com/Cumulocity-IoT/c8y-docs/pull/2274, `sector` was the correct way of doing this, but isn't any more).

2025-01-23 14:43 UTC, scmi-c8y commented on content/device-integration/mqtt-service.md
> +section:
Fixed once I understood what @bph-c8y was getting at - the navigation drop-down at the top of the LH pane was broken, and using `sector` instead of `section` fixes this. Thanks Bevan!

2025-01-31 13:56 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/java-client.md
> +#### Example {#example}
You're right, the example could be improved a lot. I'll create a ticket to spend some time on that before the service becomes GA.

2025-01-31 14:14 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/faq.md
> +Q: How to obtain device credential?<br/>
Agreed, this could be clearer. The underlying issue is that MQTT Service clients are 1) not necessarily devices, and 2) don't have any required representation in the C8Y data model. The only interaction with the core is to authenticate the MQTT connection, and that just requires a user on the tenant, it doesn't have to be a "device user". We're aware that we will need a better answer here, and that probably means some out-of-band way to register/bootstrap a non-C8Y device to have an identity in the core. In the meantime though, the doc can certainly be improved. We can pick this up as part of the current feature to add client certificate support (which will need a general review/rework of the doc around onboarding clients to the MQTT Service)

2025-04-24 08:47 UTC, bbyreddy commented on content/device-integration/mqtt-service-bundle/overview.md
> +you to consult one of the numerous introductions on the internet. Some references can be found on the [MQTT website](https://mqtt.org/mqtt-specification/).
```suggestion
you to consult one of the numerous introductions on the internet. Some references can be found on the <a href="https://mqtt.org/mqtt-specification/" target="_blank">MQTT website</a>.
```
Just so this external link opens up in a new tab.

2025-04-24 08:59 UTC, bbyreddy commented on content/device-integration/mqtt-service-bundle/overview.md
> +| Message processors/consumers | Build-in message processor for each SmartREST 2.0 topic | Custom mapping microservices can support multiple processors for a topic          |
- [ ] I think we want to say "Built-in" not "Build-in".

2025-04-24 09:00 UTC, bbyreddy commented on content/device-integration/mqtt-service-bundle/overview.md
> +| Message processors/consumers | Build-in message processor for each SmartREST 2.0 topic | Custom mapping microservices can support multiple processors for a topic          |
- [ ] I think we want to say "Built-in" not "Build-in".

2025-04-24 17:48 UTC, rthrippleton requested changes

2025-04-24 17:48 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/overview.md
> +* Support for subscribing to the data stream from MQTT Service and mapping it to {{< product-c8y-iot >}} compatible one or routing them to a different service.
I don't quite understand what this means? Is this talking about custom microservices subscribing via N2.0, and then doing arbitrary things with it?

2025-04-24 17:48 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/overview.md
> +* Full horizontal scalability.
```suggestion
```
This isn't actually true right now!

2025-04-24 17:48 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +MQTT Service requires clean session to be set to "1" (true). We cannot guarantee that disabling clean session will work reliably, hence we recommend you to always enable clean session.
```suggestion
MQTT Service requires clean session to be set to "1" (true). Disabling clean session has no effect, meaning that a reconnecting client will not see any messages that it missed since the last disconnection.
```

2025-04-24 17:48 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/overview.md
> +* Support for publishing and subscribing arbitrary payloads on any MQTT topic. The topics that are used by the existing {{< product-c8y-iot >}} MQTT implementation are not permitted for use with MQTT
```suggestion
* Support for sending and receiving arbitrary payloads on any MQTT topic. The topics that are used by the existing {{< product-c8y-iot >}} MQTT implementation are not permitted for use with MQTT Service.
```

2025-04-24 17:48 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/overview.md
> +MQTT Service is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
So, I'm wondering why we're calling this "MQTT Service" instead of "The MQTT Service".

@BeateRixen - Scott thinks this _might_ have been a recommendation from you? But it was a long time ago that this doc was first written.

Or maybe just a mistake? (not all languages have a definite article)

2025-04-24 17:48 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/overview.md
> +then to the microservice where it is converted to the final {{< product-c8y-iot >}} REST request.
At the moment, this implies that there's a shrinkwrapped solution for conversion, when really we just provide the SDK to write **a** microservice. Coming to this cold as a user, I'd feel a bit mislead.
```suggestion
then to a user-provided microservice where it is converted to the final {{< product-c8y-iot >}} REST request.
```
(similar for the diagrams, where this comment should also apply)

2025-04-24 17:48 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/overview.md
> +Given the MQTT client ID and the topic, a microservice can push any MQTT message to a device via [Java Client](/device-integration/mqtt-service#java-client).
I might be wrong, but I think you don't need the MQTT client id - you push a message to a topic, and any MQTT subscriber will see it.

2025-04-28 10:21 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/overview.md
> +| Message processors/consumers | Build-in message processor for each SmartREST 2.0 topic | Custom mapping microservices can support multiple processors for a topic          |
Done

2025-04-28 11:29 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/overview.md
> +MQTT Service is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
As a n00b, when I see this in the sidebar
![image](https://github.com/user-attachments/assets/06c9f401-87d1-4a84-b595-cc4aec969637)
it makes me think that "new MQTT endpoint" should be more expressive, along the lines of "NOT TO BE CONFUSED WITH THIS OLD THING". Because it's confusing!

2025-04-28 11:36 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/overview.md
> +then to a user-provided microservice where it is converted to the final {{< product-c8y-iot >}} REST request.
"to the final REST request" somewhat buries the lede while being technically correct. It's describing how something is done, rather than the end result that the audience is interested in.

I'm leaning towards "to a Cumulocity object representation, via a REST request" (this is sub-optimal wording, but you get my gist).

Same wording is in the diagram btw.

2025-04-28 11:49 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +Port 2883 (no TLS) is disabled by default due to security risks, as traffic is unencrypted.
FYI, looks like this is open on eu-latest. Doc wrong, or deployment is wrong?

2025-04-28 13:08 UTC, rthrippleton commented on static/images/mqtt-service/mqtt-service-send.svg
"MQTT Device pushing on topic" - doesn't seem to fit with "Similarly, messages can be sent to devices, as shown in the diagram below.". The arrows don't really clear it up either.

2025-04-28 13:11 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
An end user is more likely to know the meaning of "Notifications 2.0" than "Messaging Service" - while we should keep saying that MQTT maps to topics in the messaging service, can we have a few name-drops of N2.0 throughout this doc? Or do we not want to 'reveal' that you can go from device -> external N2.0 subscriber ?

2025-04-28 13:12 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +The original MQTT messages are re-packed into MQTT Service message format which includes the original payload and additional metadata fields.
```suggestion
The original MQTT messages map bidirectionally to the MQTT Service message format which includes the original payload and additional metadata fields.
```
because you can go both ways using the Java client

2025-04-28 13:24 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/overview.md
> +* Support for subscribing to the data stream from MQTT Service and mapping it to {{< product-c8y-iot >}} compatible one or routing them to a different service.
Re-worked, hopefully clearer now?

2025-04-28 13:25 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/overview.md
> +MQTT Service is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
The more I look at this the more I want to add "the" everywhere -- my fingers automatically did it already in a few places and I haven't removed them. Very tempted to go through and change this globally unless there is a specific reason not to do that.

2025-04-28 13:25 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/overview.md
> +Given the MQTT client ID and the topic, a microservice can push any MQTT message to a device via [Java Client](/device-integration/mqtt-service#java-client).
Correct, and fixed.

2025-04-28 13:27 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/overview.md
> +MQTT Service is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
Would it work to rename the old section to "Core MQTT" (which is what we agreed to call it) and add some words explaining how it is different from the MQTT Service? I already added a bit in the MQTT Service intro explaining that from the other direction, and stating that the two endpoints will co-exist (at least for now).

2025-04-28 13:29 UTC, scmi-c8y commented on static/images/mqtt-service/mqtt-service-send.svg
My bad, the SVG files apparently contained multiple "pages" and I ended up using the same diagram for both. Should be correct now?

2025-04-28 13:34 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
I don't really want to lead users towards N2.0 here - especially as we don't (and don't plan to) document how to create that N2.0 subscriber.

2025-04-28 13:39 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +Port 2883 (no TLS) is disabled by default due to security risks, as traffic is unencrypted.
Bit of both... we opened it up during the private preview to help customers who could do unencrypted or two-way TLS, but not one-way TLS. Now that client certificate support is available that isn't necessary and we hope we won't need to  open 2889 on the higher zones. Perhaps we should clarify that unencrypted connections are an option for dedicated environments but not for our managed ones?

2025-04-28 15:48 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +Port 2883 (no TLS) is disabled by default due to security risks, as traffic is unencrypted.
I think the doc is already clear on that (line below). eu-latest is just an anomaly, so I'm happy to leave this.

2025-04-28 15:49 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
So long term the only supported way to publish data and subscribe to the service is via actual MQTT, Apama (soon) or the Java library that hides away N2.0?

2025-04-28 15:58 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/overview.md
> +MQTT Service is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
Looks good to me!

2025-04-28 15:58 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/overview.md
> +MQTT Service is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
Re-worked as I suggested above. Hopefully that makes more sense to the n00bs now?

2025-04-28 15:58 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/overview.md
> +MQTT Service is the new MQTT endpoint implementation of {{< product-c8y-iot >}} which provides the following benefits:
Yeah, that's a good idea IMO - go right ahead.

2025-04-28 16:02 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
Medium-term, yes. Long-term, we will have the "Horizon 2" protocol, whatever that turns out to be, maybe even native Pulsar. We don't want to lock people in to the current N2.0 protocol that we might ultimately want to replace.

2025-04-28 16:04 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/java-client.md
I think in a section after this, you want a reference to https://github.com/Cumulocity-IoT/cumulocity-dynamic-mapper/ . On the one hand, it's an off-the-peg solution that doesn't require developing a Java microservice, but on the other hand it's not officially supported so needs a big admonition.

2025-04-28 16:10 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
Fair enough. I might be a bit peeved if my only option for a custom service was Java locked into a specific SDK, but that's just me :-)

2025-04-28 16:19 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +There are further instructions regarding creating self-signed CA, intermediate, and device certificates certificates under [Generating and signing certificates](/device-integration/device-certificate
This link is half-broken - path is fine, anchor goes nowhere. `/device-certificate-authentication/managing-trusted-certificates/` might be what you want?

2025-04-28 17:03 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +There are further instructions regarding creating self-signed CA, intermediate, and device certificates certificates under [Generating and signing certificates](/device-integration/device-certificate
Fixed, along with a few others that didn't point to where they should have.

2025-04-28 17:03 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/java-client.md
Added it to the FAQ section... hopefully "community-supported open-source component" is enough of a disclaimer.

2025-04-28 17:05 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/overview.md
> +then to a user-provided microservice where it is converted to the final {{< product-c8y-iot >}} REST request.
Re-worked the text, will also update the diagram.

2025-04-28 18:10 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +#### Creating self-signed certificates
So, it looks like this stuff is an alias to `/device-certificate-authentication/device-certificates/`  , although the latter is more verbose . Is the procedure for creating client certs for MQTT Service devices the exact same as the procedure for client certs for devices connecting over HTTP/Core MQTT/LWM2M ? If so, it ought to live there, with just a cross-reference.

And if we do that, there's a list at the top of "Device Certificates" that needs its enumeration updating; currently mentioning HTTP, (Core) MQTT and LWM2M.

2025-04-28 19:30 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +#### Creating self-signed certificates
@rohitjoshi-c8y can explain why we duplicated some of the existing content. Agreed that the list in the other section should mention the MQTT Service.

2025-04-30 16:50 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +For more details on auto-registration, refer to [Auto-registration](/device-certificate-authentication/device-certificates#registering-devices-using-certificates) guide.
As a relative n00b, if I read that link in the context of the MQTT service, Registering devices using certificates / Auto registration    implies that connecting with MQTT for the first time creates a user, or device credentials, or a device .... ? (none of these happen in practice)

BTW, `/device-certificate-authentication/device-certificates/` is a bit stuck in the past - there's an enumeration at the top of the various ways you can SSL your way into the platform, and the only MQTT mentioned is the core MQTT.

2025-05-01 15:36 UTC, rohitjoshi-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +#### Creating self-signed certificates
Hi @rthrippleton, we decided to duplicate because the original doc is muddled with irrelevant details and does not read well. So, we decided to write it for the MQTT Service with clear instructions on creating and using client certificates.

2025-05-01 18:11 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +For more details on auto-registration, refer to [Auto-registration](/device-certificate-authentication/device-certificates#registering-devices-using-certificates) guide.
```suggestion
```
Discussed with Rohit, we agreed that these sentences were more confusing than helpful, as they implied that devices would get created by the MQTT service.

2025-05-01 18:14 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +#### Creating self-signed certificates
I can't persuade you to instead fix the original doc? It's not a great customer experience to have us create two bits of doc about the same topic and purposes; ideally we want one canonical bit of doc on this topic, and what's been written in _this_ PR is suitable for that.

2025-05-02 11:06 UTC, scmi-c8y commented on content/device-integration/mqtt-service-bundle/implementation.md
> +#### Creating self-signed certificates
I don't disagree that our doc is better :-) nor that we should only explain this stuff once. However, the risk is that if we start updating the old material we a) end up owning it and b) tread on toes and make ourselves unpopular. That's not a fight I want to have *right now* but maybe something we can look at for GA.

2025-05-02 14:59 UTC, scmi-c8y commented
@JanePorter @bbyreddy @schmiel-cumulocity @rohitjoshi-c8y @rthrippleton I have added the proposed change log entry directly to this branch so it will be available at the same time as the rest of the doc. See https://cumulocity-iot-c8y-docs-build-pr-2695.surge.sh/change-logs/#mqtt-service-0.4.35-public-preview.

2025-05-02 16:11 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +#### Creating self-signed certificates
107b936a5

2025-05-02 16:21 UTC, rthrippleton commented on content/change-logs/platform-services/mqtt-service-0.4.35-public-preview.md
> +Otherwise, please contact [Global Support](/additional-resources/contacting-support/) to request the microservice subscription for your tenant.
```suggestion
Otherwise, please contact [product support](/additional-resources/contacting-support/) to request the microservice subscription for your tenant.
```
is the terminology we use everywhere else in the doc. Global Support might be a bit of an old era term.

2025-05-02 16:23 UTC, rthrippleton commented on content/change-logs/platform-services/mqtt-service-0.4.35-public-preview.md
> +It also supports more flexible communication patterns between devices, applications, and the {{< product-c8y-iot >}} platform, controlled by user-provided microservices.
This is actually really good wording that would stop somebody who's already familiar with the old MQTT implementation from being confused. Do you think it's worth copying this into the overview doc? Not every new user of the service will come to it via a changelog entry.

2025-05-02 16:37 UTC, scmi-c8y commented on content/change-logs/platform-services/mqtt-service-0.4.35-public-preview.md
> +It also supports more flexible communication patterns between devices, applications, and the {{< product-c8y-iot >}} platform, controlled by user-provided microservices.
Included in https://github.com/Cumulocity-IoT/c8y-docs/pull/2695/commits/ab33bcb017e144eeb22191d482670d99aaf3ba5f

2025-05-02 16:38 UTC, rthrippleton approved these changes

2025-05-06 09:08 UTC, rohitjoshi-c8y commented on content/device-certificate-authentication/device-certificates.md
> +**Core MQTT**
**_question:_** I am not sure we should rename "MQTT" to "Core MQTT". I understand your intent to better distinguish between the two MQTT implementations in the platform, but renaming the existing one could be confusing. I will defer to @scmi-c8y on which way to go here.

2025-05-06 09:11 UTC, rohitjoshi-c8y commented on content/device-certificate-authentication/device-certificates.md
> +Devices can communicate using the [Core MQTT interface](/device-integration/mqtt/) of the platform, but MQTT over WebSocket is not supported. The {{< product-c8y-iot >}} platform expects devices to c
**_suggestion:_** _The {{< product-c8y-iot >}} platform expects devices to connect using SSL on port 8883_ is redundant.

```suggestion
Devices can communicate using the [Core MQTT interface](/device-integration/mqtt/) of the platform, but MQTT over WebSocket is not supported.
```

2025-05-06 09:13 UTC, rohitjoshi-c8y commented on content/device-certificate-authentication/device-certificates.md
> +Devices can communicate using the [MQTT Service](/device-integration/mqtt-service/). The {{< product-c8y-iot >}} platform expects devices to connect using SSL on port 8883.
**_suggestion:_** _The {{< product-c8y-iot >}} platform expects devices to connect using SSL on port 8883_ is redundant.

```suggestion
Devices can communicate using the [MQTT Service](/device-integration/mqtt-service/).
```

2025-05-06 09:16 UTC, rohitjoshi-c8y commented on content/device-certificate-authentication/device-certificates.md
> +Devices can communicate using the [MQTT Service](/device-integration/mqtt-service/). The {{< product-c8y-iot >}} platform expects devices to connect using SSL on port 8883.
**_suggestion:_** Similar to LWM2M, I think we should clearly state that customers are required to explicitly include the tenant ID in the connect packet.

2025-05-06 10:06 UTC, rthrippleton commented on content/device-certificate-authentication/device-certificates.md
> +**Core MQTT**
I think the rename was Scott's idea :-D

2025-05-06 10:43 UTC, rthrippleton commented on content/device-certificate-authentication/device-certificates.md
> +Devices can communicate using the [MQTT Service](/device-integration/mqtt-service/). The {{< product-c8y-iot >}} platform expects devices to connect using SSL on port 8883.
It's not redundant, it's wrong :-D (should be 9883)

I'm writing it like that, simply because Core MQTT explicitly states the port as well. Does that seem ok?

2025-05-06 10:45 UTC, rthrippleton commented on content/device-certificate-authentication/device-certificates.md
> +Devices can communicate using the [MQTT Service](/device-integration/mqtt-service/). The {{< product-c8y-iot >}} platform expects devices to connect using SSL on port 8883.
fdd4aa2fd

2025-05-06 12:54 UTC, BeateRixen commented on content/device-integration/mqtt-service-bundle/implementation.md
> +#### Creating self-signed certificates
At least we should create a ticket to have the original section updated accordingly. I completely agree with @rthrippleton that we should not duplicate text. If you like I can replace the original texts with yours and take the risk of ownership/annoying people :-).

2025-05-06 13:08 UTC, rthrippleton commented on content/device-integration/mqtt-service-bundle/implementation.md
> +#### Creating self-signed certificates
I think it would require too much technical attention to make sure it's right - it's not a one-for-one replacement, the overlap is a lot more vague than that.

2025-05-06 13:42 UTC, JanePorter approved these changes

2025-05-06 14:01 UTC, rohitjoshi-c8y commented on content/device-certificate-authentication/device-certificates.md
> +Devices can communicate using the [MQTT Service](/device-integration/mqtt-service/). The {{< product-c8y-iot >}} platform expects devices to connect using SSL on port 8883.
Well, I thought you meant Core MQTT because it said 8883 :D

2025-05-06 14:17 UTC, rthrippleton commented on content/device-certificate-authentication/device-certificates.md
> +Devices can communicate using the [MQTT Service](/device-integration/mqtt-service/). The {{< product-c8y-iot >}} platform expects devices to connect using SSL on port 8883.
Understood. Thanks for getting me to look at it again, that would have been awkward!

2025-05-06 15:43 UTC, scmi-c8y commented on content/device-certificate-authentication/device-certificates.md
> +**Core MQTT**
Yeah, blame me. We do explain the difference at the top of the guide, so hopefully it won't be too confusing. "Core MQTT" is the agreed name (it was preferred to "Legacy MQTT") and we need to start using it to distinguish which one we are talking about.

2025-05-06 15:50 UTC, scmi-c8y commented
So I think we're just waiting for @schmiel-cumulocity to check how the "default microservice" configuration actually works, and whether we need to change the instructions around checking that your tenant is allowed to use the service. Otherwise this is ready to merge.

@BeateRixen could we get a code owner approval for the main doc please? I think Jane's only applied to the change log part.

2025-05-07 08:15 UTC, BeateRixen commented on content/change-logs/platform-services/mqtt-service-0.4.35-public-preview.md
> +To determine whether the feature is available for your tenant, open the Administration application and navigate to Ecosystem → Microservices.
```suggestion
To determine whether the feature is available for your tenant, open the Administration application and navigate to **Ecosystem** > **Microservices**.
```

2025-05-07 08:17 UTC, BeateRixen commented on content/device-integration/mqtt-service-bundle/implementation.md
> +#### Error Topic {#error-topic}
```suggestion
#### Error topic {#error-topic}
```

2025-05-07 08:17 UTC, BeateRixen commented on content/device-integration/mqtt-service-bundle/java-client.md
> +#### Repositories and dependencies {#repositories-and-dependencies}
```suggestion
### Repositories and dependencies {#repositories-and-dependencies}
```

2025-05-07 08:18 UTC, BeateRixen commented on content/device-integration/mqtt-service-bundle/java-client.md
> +#### Examples {#example}
```suggestion
### Examples {#example}
```

2025-05-07 08:18 UTC, BeateRixen approved these changes

2025-05-07 08:19 UTC, BeateRixen commented
> So I think we're just waiting for @schmiel-cumulocity to check how the "default microservice" configuration actually works, and whether we need to change the instructions around checking that your tenant is allowed to use the service. Otherwise this is ready to merge.
> 
> @BeateRixen could we get a code owner approval for the main doc please? I think Jane's only applied to the change log part.

@scmi-c8y Just fixed some heading levels (and minor formatting) and approved. Looks good!

2025-05-08 16:06 UTC, merged