Updated DTM  screenshots with new branding changes
SoftwareAG/c8y-docs pull request #2705
Opened 2024-12-06 04:58 UTC by Vagdevi1998

Screenshots for DTM have been updated with the new branding changes.

2025-01-06 10:09 UTC, BeateRixen approved these changes

2025-01-07 11:54 UTC, lara-c8y requested changes

2025-01-07 11:54 UTC, lara-c8y commented on static/images/dtm/bulk-import/dtm-bulk-import-template.png
Is the screenshot with windows task bar necessary?

2025-01-08 06:48 UTC, Vagdevi1998 commented on static/images/dtm/bulk-import/dtm-bulk-import-template.png
Removed the taskbar in the screenshot

2025-01-08 06:56 UTC, lara-c8y approved these changes

2025-01-08 09:04 UTC, merged