Introduced i18n tutorial to WebSdk guide.
SoftwareAG/c8y-docs pull request #272
Opened 2022-02-22 11:50 UTC by jakub-wierzbicki

2022-03-01 09:39 UTC, rssag requested changes

2022-03-01 09:39 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +3. Restart your server and application.
this formerly said "reload", i replaced that with "restart". this might not be correct, please check @jakub-wierzbicki

2022-03-01 09:39 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +3. Restart the server and the application.
this formerly said "reload", i replaced that with "restart". this might not be correct, please check @jakub-wierzbicki

2022-03-01 09:39 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +If your language is set to italian, reloading the application will render the content as `User settings (it)`.
I left "reload" here.

2022-03-01 09:39 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +Note that the string templates must have their parentheses escaped in order to avoid compilation errors.
"parentheses" was formerly "interpolation marks" - i'm not sure if that is correct. please check @jakub-wierzbicki

2022-03-01 09:39 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +This way angular will ignore parentheses, so they can be interpreted by the translation service.
"parentheses" was formerly "interpolation marks" - i'm not sure if that is correct. please check @jakub-wierzbicki

2022-03-01 09:39 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +We recommend you to have `ngNonBindable` present while translating HTML blocks because otherwise the Angular compiler might interfere with the translation service.
this piece of information is already in line 283, is it not? We should not add it twice.

2022-03-01 09:39 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +[Missing code block?]
There was just a single ``` in this place. I assume that the code block is missing @jakub-wierzbicki

2022-03-01 09:39 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +The file `locales.pot` contains all strings that were marked with the `translate` pipe, the `translate` directive or the `gettext` method.
This looks like a paraphrase of what is in line 480. If it is, pick one.

2022-03-01 09:39 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +In this example you must use Angular's `ngNonBindable` directive in addition to the `translate` directive.
"In this example" might be "In the following example".

2022-03-02 11:29 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +Note that the string templates must have their parentheses escaped in order to avoid compilation errors.
I am not sure about that. I think that "double curly braces" would be more correct. Also, Angular documentation references to this syntax as "Interpolation marks"
https://angular.io/guide/interpolation

2022-03-02 11:34 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +We recommend you to have `ngNonBindable` present while translating HTML blocks because otherwise the Angular compiler might interfere with the translation service.
Actually these two cases are a bit different - in first example ngNonBindable is required, in order to correctly put values from parameters into templates. In this example ngNonBindable is optional, but it is good to use it, as there are some cases that can break translation, if ngNonBindable is not present.

2022-03-02 11:42 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +[Missing code block?]
I think that it was leftover from my initial review. Maybe we could put constructor snippet there.

2022-03-02 11:47 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +The file `locales.pot` contains all strings that were marked with the `translate` pipe, the `translate` directive or the `gettext` method.
line 480 describes effect of executing extraction tool, while 483 describes 'locales.pot' that contains all extracted strings from source code

2022-03-03 13:59 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +[Missing code block?]
what would be the snippet code? @jakub-wierzbicki

2022-03-03 14:05 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +Note that the string templates must have their parentheses escaped in order to avoid compilation errors.
went with "curly braces"

2022-03-03 14:06 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +This way angular will ignore parentheses, so they can be interpreted by the translation service.
went with "curly braces"

2022-03-03 17:12 UTC, pawel-rynarzewski-sag requested changes

2022-03-03 17:12 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +After using this command, the directory *./locales* will contain all available translations.
After reading this section, I've come up with this:
```md
You can use `c8ycli locale-extract` command to extract strings from:
- `node_modules/@c8y/locales` (it contains all the default strings and translations, so then it's easier to edit or add new ones)
- `.` (your custom modules, components, templates, services, etc.)

After using this command, a new directory `./locales` will be created (if not existing yet) and it will contain:
- `\*.po` files for all available languages (you can edit and copy these files to the *./translations/locales* directory, as well as add necessary imports),
- `locales.pot` containing all strings that were marked with the `translate` pipe, the `translate` directive or the `gettext` method in your own source code under `.`, i.e. it does not include any default strings from `node_modules/@c8y/locales` (you can append these values to your custom `\*.po` files and translate them).
```
Do you think it's a bit clearer?
Also, does it mean that there is no way to automatically add new extracted strings to a custom `*.po` file? From the description it sounds like user needs to figure out which ones are new and add them manually.

2022-03-03 17:28 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +>**Important:** The string templates must have the curly braces escaped in order to avoid compilation errors.
I have tested it and it worked, but i'll check it again, just to be sure

2022-03-04 11:50 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +>**Important:** The string templates must have the curly braces escaped in order to avoid compilation errors.
ok, would be great if it worked, because I saw similar use case in our own code.

2022-03-07 10:10 UTC, rssag approved these changes

2022-03-10 10:18 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> + **Version:** 1013.57.0 | **Packages:** @c8y/cli, @c8y/apps and @c8y/ngx-components
would version 1013.72.0 work then? @pawel-rynarzewski-sag @jakub-wierzbicki

2022-03-10 10:19 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +#### Configuration of a fresh environment
i went with "new platform instance" instead of "fresh environment"

2022-03-10 10:22 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +Now you can run the application. When starting, the application renders a blank page that contains the `Index`.
what would be the code that is added to `app.module.ts`?

2022-03-10 10:27 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +{{< product-c8y-iot >}} comes with a wide range of content that is already translated in multiple languages. These translations can be extended.
done

2022-03-10 10:27 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    import { TextTranslationComponent } from "./text-translation.component";
done

2022-03-10 10:28 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    <h4 class="card-title">Angular pipe example</h4>
done

2022-03-10 10:28 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +Alternatively, use the `c8yDate` pipe to return dates in `medium` format. This also works with values outside of the by ECMAScript supported range:
done

2022-03-10 10:28 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    <h4 class="card-title">Cumulocity pipe example</h4>
done

2022-03-10 10:29 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +The `c8ycli locale-extract` command automatically copies all translations from the `node_modules/@c8y/locales.` This makes it easier to edit and add new translations.
what's the suggestion here? @pawel-rynarzewski-sag

2022-03-10 13:19 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +The `c8ycli locale-extract` command automatically copies all translations from the `node_modules/@c8y/locales.` This makes it easier to edit and add new translations.
Just that the dot is not part of the folder path, so move outside.

2022-03-10 13:23 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> + **Version:** 1013.57.0 | **Packages:** @c8y/cli, @c8y/apps and @c8y/ngx-components
1013.72.0 is also not a GA version. Let's check 1013.0.x line again, I don't see a reason why it should not work there.

2022-03-10 13:28 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +#### Configuration of a fresh environment
That sounds like you needed a new platform instance to perform the steps in the tutorial, while it only shows how to create a new app with translations, regardless of what you already have in the platform, so I'd go with `#### Setting up a new application`. Do you agree @jakub-wierzbicki ?

2022-03-10 13:31 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +Now you can run the application. When starting, the application renders a blank page that contains the `Index`.
These 2 lines:
```ts
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { RouterModule as ngRouterModule } from '@angular/router';
import { CoreModule, BootstrapComponent, RouterModule } from '@c8y/ngx-components';
import { TranslationsModule } from './translations/translations.module';      // <--

@NgModule({
  imports: [
    BrowserAnimationsModule,
    RouterModule.forRoot(),
    ngRouterModule.forRoot([], { enableTracing: false, useHash: true }),
    CoreModule.forRoot(),
    TranslationsModule                                                        // <--
  ],
  bootstrap: [BootstrapComponent]
})
export class AppModule {}
```

2022-03-10 14:30 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +>**Important:** The string templates must have the curly braces escaped in order to avoid compilation errors.
Rechecked it too: it doesn't extract it neither from a custom app, nor from our source code. However, if you add an entry manually:
```po
msgid "Mr. Smith is \\{\\{ age \\}\\} years old"
msgstr "Herr Smith ist \\{\\{ age \\}\\} Jahre alt"
```
then it translates fine.
I've checked what regex is used by the extractor and it simply does not match `translate` with params, see: https://regex101.com/r/oMTMb9/1
We could try to override the regexes after `ext` creation in
https://github.softwareag.com/IOTA/cumulocity-ui/blob/579324ba79e12ce97fe99d0ae3091ddcd65d793c/packages/cli/src/utils/LocaleUtils.ts#L79-L82
to handle such cases. Original regexes are created here https://github.com/rubenv/angular-gettext-tools/blob/52f0a7c66e141e25024ae91ac10fa9ecbc935ace/lib/extract.js#L136-L144

2022-03-16 12:26 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> + variableWithText = 'Text inside variable that is translatable';
Agree. I have moved text regarding gettext under example files, as info block.

2022-03-16 12:26 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +Wrap such strings with the `gettext` function. This will enable automatic extraction of the strings to your *.po file*. This also indicates that such strings are meant to be translated, as shown in t
I think that it is not completely true, as new strings are not extracted to .po files, but appears 
```
msgid "Text inside variable that is translatable"
msgstr ""
```
inside /locales/locale.pot

2022-03-16 12:26 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +See [Extracting translations using the locale extract tool](#extracting-translations-using-locale-extract-tool) for information about translation extraction.
Done

2022-03-16 12:26 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +    Translating content using the `instant` method, requires you to keep track of language changes. Make sure that if a user changes the language, the text is translated again. See the example below
I have altered it to: 
```
Translating content using the `instant` method, has a flaw that given translation will not be updated upon language change.
In order to achieve this, it is required to keep track of language changes.
Make sure that if a user changes the language, the text is translated again. See the example below for reference:
```
Do You think that would be ok?

2022-03-16 12:26 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +#### Extracting translations using the locale-extract tool
Done

2022-03-16 12:26 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +In order to display dates with correct localization rules., use the Angular `date` pipe, as shown in the example below:
Done

2022-03-16 12:27 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +#### Configuration of a fresh environment
Agree

2022-03-16 12:27 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +Now you can run the application. When starting, the application renders a blank page that contains the `Index`.
Done

2022-03-16 12:32 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +In this example you must use Angular's `ngNonBindable` directive in addition to the `translate` directive.
Done

2022-03-16 12:40 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +[Missing code block?]
Done

2022-03-16 18:03 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +>**Info:** If the application is set to German, the user settings menu will show **User settings (de)** instead of the default **Benutzereinstellungen**.
:+1:

2022-03-16 18:25 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +>**Important:** The string templates must have the curly braces escaped in order to avoid compilation errors.
Yeah, it does work indeed, but you need to remember to add the entry manually, because it won't be extracted in the regular workflow. Therefore I was wondering if we could improve the extraction script somehow. If you think so, or want to add a study, let's have a separate task, and for the tutorial, let's use what we know works fine end-to-end, i.e. suggest translation in *.ts in this case.

2022-03-16 18:26 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> + variableWithText = 'Text inside variable that is translatable';
:+1:

2022-03-23 12:25 UTC, BeateRixen commented on content/web/tutorials-bundle/internationalization.md
> +{{< product-c8y-iot >}} provides integrated tools that allow you to translate your content. It is based on the `ngx-translate` library. The `CoreModule` exports a preconfigured instance of this tool,
@jakub-wierzbicki Where does "it" refer to in " It is based on the `ngx-translate` library. The tools mentioned in the previous sentence? Then it should be "They"? Or the translation feature? Not really clear.

2022-03-23 12:26 UTC, BeateRixen commented
@jakub-wierzbicki @pawel-rynarzewski-sag What is the status of this PR? From a language perspective it is more or less complete. Note that I just added one more comment.

2022-03-23 12:27 UTC, BeateRixen approved these changes

2022-03-24 11:10 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +{{< product-c8y-iot >}} provides integrated tools that allow you to translate your content. It is based on the `ngx-translate` library. The `CoreModule` exports a preconfigured instance of this tool,
It reefers to general Internationalization ecosystem. Do You think that we should change "It" to something else?

2022-03-24 11:11 UTC, jakub-wierzbicki commented
> @jakub-wierzbicki @pawel-rynarzewski-sag What is the status of this PR? From a language perspective it is more or less complete. Note that I just added one more comment.

All post-review changes are applied. This PR should be ready to merge after final verification.

2022-03-24 11:12 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +<div>{{ "Mr. Smith is \{\{ age \}\} years old" | translate:{age: 40} }}</div>
Done

2022-03-24 11:21 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +>**Important:** The string templates must have the curly braces escaped in order to avoid compilation errors.
I have added another info box, that explains this behavior.

2022-03-24 13:15 UTC, BeateRixen commented on content/web/tutorials-bundle/internationalization.md
> +{{< product-c8y-iot >}} provides integrated tools that allow you to translate your content. It is based on the `ngx-translate` library. The `CoreModule` exports a preconfigured instance of this tool,
Yes, this would make it clearer. Is it one or several tools? You say "integrated tools" at the top and then later on "this tool". Suggestion:

{{< product-c8y-iot >}} provides an integrated tool which allows you to translate your content. This tool is based on the `ngx-translate` library. The `CoreModule` exports a preconfigured instance of this tool, with {{< product-c8y-iot >}} already being integrated.

2022-03-25 11:48 UTC, MWindel approved these changes

2022-03-28 08:36 UTC, BeateRixen commented
@pawel-rynarzewski-sag Could you please approve?

2022-03-28 10:12 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +{{< product-c8y-iot >}} provides integrated tools that allow you to translate your content. It is based on the `ngx-translate` library. The `CoreModule` exports a preconfigured instance of this tool,
Thank You!

2022-03-28 21:49 UTC, pawel-rynarzewski-sag requested changes
Found a few missing steps and code rendering/formatting issues.

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    <div>{{ "Mr. Smith is \{\{ age \}\} years old" | translate:{age: 40} }}</div>
Didn't we discuss moving this to component's class to avoid the issue with this string not being extracted by `npm run locale-extract`? Maybe:
```ts
template = gettext('Mr. Smith is {{ age }} years old');
```
```html
<div>{{ template | translate:{ age: 40 } }}</div>
```
I see the important notes below, but I think that tutorial should not show the unrecommended way of doing things, so you should rather follow your own advice, I think. Would you agree? Instead, you could add an Info box for the ts/html example that we do not put the text in the html template because the extraction tool does not support such syntax.

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +Similarly to the example with the translate pipe, the content of the `span` will be translated to `User settings (it)`.
```
Similarly to the example with the `translate` pipe, the content of the `span` will be translated to **User settings (it)**.
```

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    ```html
Fix rendering.

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    ```po
I guess you need to remove `po`:
![2022-03-28_23-20](https://user-images.githubusercontent.com/92171763/160489179-f80c7060-992b-4f4d-bbb5-86aad153d3ba.png)

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    msgid "Read about your current language in <a href="#guide">our guide</a>"
I see it works fine anyway, but shouldn't the internal `"` be escaped as `\"` to be valid gettext?

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +     variableWithText = gettext('Text inside variable that is translatable');
Maybe also include a snippet adding this string to `de.po` or `it.po`, like in the previous example?

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    ```
Let's split these into points for ts and html, like in other examples, and fix rendering:
![2022-03-28_23-32](https://user-images.githubusercontent.com/92171763/160491032-295f46ac-26de-4752-b0ef-85021368233e.png)

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    ```ts
Fix rendering too.

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +      this.textStream = this.translateService.stream(this.variableWithText)
Maybe with `constructor` to have a mental link to the main example above and not confuse the user:
```
constructor(private translateService: TranslateService) {
  this.textStream = this.translateService.stream(this.variableWithText);
}
```

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    ```ts
Fix rendering and split into points.

2022-03-28 21:49 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    ```html
Fix rendering.

2022-03-29 10:47 UTC, jakub-wierzbicki commented on content/web/tutorials-bundle/internationalization.md
> +    c8ycli new my-app-i18n -a @c8y/apps@1013.0.63
Looks like new version of c8ycli finally hit the table :D

2022-03-30 07:48 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    c8ycli new my-app-i18n -a @c8y/apps@1013.0.63
so, " -a @c8y/apps@1013.0.63" should be removed? done.

2022-03-30 07:48 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +Start with creating a new application.
done, but i added a sentence rather than a list with two items.

2022-03-30 07:49 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    ```
yes, this is an indentation error. fixed.

2022-03-30 07:51 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +3. Restart the server and the application.
added the sentence, but i think the screenshot is not necessary.

2022-03-30 07:52 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +>**Info:** You can find <i>*.po</i> files with default translations under *./my-app-i18n/node_modules/@c8y/ngx-components/locales*. To edit these files copy them to your *locales* directory.
done

2022-03-30 07:53 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    "Language: de\n"
done

2022-03-30 07:55 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    ```
done

2022-03-30 07:58 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +There are multiple ways to translate content. The most common is the "translate" pipe and directive, which is explained in the following section.
fixed multiple occurrences.

2022-03-30 07:59 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +If your language is set to Italian, reloading the application will render the content as `User settings (it)`.
done

2022-03-30 07:59 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +The translate pipe allows to set different parameters, as shown in the example for `translations/locales/it.po:
fixed

2022-03-30 09:29 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    <div>{{ "Mr. Smith is \{\{ age \}\} years old" | translate:{age: 40} }}</div>
what is there to do here then? @pawel-rynarzewski-sag

2022-03-30 09:31 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    ```html
done

2022-03-30 09:32 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    ```po
done

2022-03-30 09:32 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    msgid "Read about your current language in <a href="#guide">our guide</a>"
added

2022-03-30 09:32 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +     variableWithText = gettext('Text inside variable that is translatable');
@jakub-wierzbicki

2022-03-30 09:34 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    ```
done

2022-03-30 09:34 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    ```ts
done

2022-03-30 09:35 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +      this.textStream = this.translateService.stream(this.variableWithText)
done

2022-03-30 09:35 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    ```ts
done

2022-03-30 09:36 UTC, rssag commented on content/web/tutorials-bundle/internationalization.md
> +    ```html
done

2022-05-11 09:05 UTC, BeateRixen commented
@jakub-wierzbicki @pawel-rynarzewski-sag Is there anything missing from your side or could this PR finally be approved and merged?

2022-05-12 08:08 UTC, pawel-rynarzewski-sag commented
@BeateRixen, yes, there is an issue in the main package which breaks some of the steps in the tutorial, we need to wait for it to be fixed first (MTM-44941).

2023-02-21 12:28 UTC, BeateRixen commented
@jakub-wierzbicki @pawel-rynarzewski-sag What is the status of this PR? It is actually one year old now :-).

2023-02-27 15:55 UTC, pawel-rynarzewski-sag commented
@BeateRixen, a bit over a year indeed :disappointed: I see that the corresponding task got dropped from our taskboard before it got unblocked by another team and was never resumed. @jakub-wierzbicki @Airdroplet, anything against putting it back on our taskboard and finalizing it?

2023-08-02 15:09 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +currentDate = new Date();
I know it's obvious for us where to put it, but the tutorial is for other people with different experience. Consider adding info to which file each snippet goes, like in the first sections of this tutorial.

2023-08-02 15:09 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    msgstr "Mr. Smith is  {{ age }} years old (it)"
Maybe remove this one from here and indicate in the certain step when to add it? You already do this for a few more strings that need to be added when following the tutorial.

2023-08-02 15:11 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    Translating content using the `instant` method, requires you to keep track of language changes. Make sure that if a user changes the language, the text is translated again. See the example below
This suggestion has been implemented.

2023-08-02 15:13 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    c8ycli new my-app-i18n -a @c8y/apps@1013.0.63
yes, the command is correct now

2023-08-02 15:14 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +
`it` part has been fixed. import still missing from the steps list.

2023-08-02 15:17 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    <div>{{ "Mr. Smith is \{\{ age \}\} years old" | translate:{age: 40} }}</div>
@jakub-wierzbicki the comment is still valid, let's present the recommended way of doing it which works well with string extraction.

2023-08-02 15:21 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    msgid "Read about your current language in <a href="#guide">our guide</a>"
Same should be done for the translation:
```
msgid "Read about your current language in <a href=\"#guide\">our guide</a>"
msgstr "Read about your Italian language in <a href=\"#italian-guide\">our Italian guide</a>"
```

2023-08-02 15:21 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +     variableWithText = gettext('Text inside variable that is translatable');
@jakub-wierzbicki still valid comment

2023-08-03 13:17 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +
Added import step.

2023-08-03 13:18 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +    msgid "Read about your current language in <a href="#guide">our guide</a>"
done

2023-08-03 13:26 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +     variableWithText = gettext('Text inside variable that is translatable');
done

2023-08-03 13:46 UTC, pawel-rynarzewski-sag commented on content/web/tutorials-bundle/internationalization.md
> +msgstr "Sig. Smith ha {{ age }} anni"
Removed the entry from the initial content.

2023-08-04 10:12 UTC, Airdroplet approved these changes

2023-08-04 10:13 UTC, merged