DM-4225 change-log-prevent-resource-instance-level-operation-for-LWM2M-1-0-device
SoftwareAG/c8y-docs pull request #2756
Opened 2024-12-30 14:11 UTC by Oezge-Akin

2025-01-02 13:05 UTC, aaronraab requested changes

2025-01-02 13:05 UTC, aaronraab commented on content/change-logs/device-management/lwm2m-agent-2-1-0-blocking-resource-instance-operation-for-lwm2m-1-0-devices.md
> +title: Preventing resource instance level operation execution for LWM2M 1.0 devices
```suggestion
title: Preventing execution of operations on resource instance level for LWM2M 1.0 devices
```

2025-01-02 13:05 UTC, aaronraab commented on content/change-logs/device-management/lwm2m-agent-2-1-0-blocking-resource-instance-operation-for-lwm2m-1-0-devices.md
> +The LwM2M resource instance level operations are introduced in LwM2M 1.1 and are not supported for LwM2M 1.0 devices.
```suggestion
The LwM2M resource instance level operations have been introduced in LwM2M 1.1 but are not supported by LwM2M 1.0 devices.
```

2025-01-02 13:05 UTC, aaronraab commented on content/change-logs/device-management/lwm2m-agent-2-1-0-blocking-resource-instance-operation-for-lwm2m-1-0-devices.md
> +When the LwM2M resource instance level operations are created in the {{< product-c8y-iot >}} platform such as read /5/0/8/0 against a LwM2M 1.0 device, the operation will be directly failed by the LW
```suggestion
When the LwM2M resource instance level operations are created in the {{< product-c8y-iot >}} platform such as read /5/0/8/0 against a LwM2M 1.0 device, the operation will be directly failed by the LWM2M service and not be sent to the device.
```

2025-01-06 08:56 UTC, eliasweingaertner commented on content/change-logs/device-management/lwm2m-agent-2-1-0-blocking-resource-instance-operation-for-lwm2m-1-0-devices.md
> +This is now incorporated in {{< product-c8y-iot >}} platform operations.
I'd leave the sentence in line 19 out and write in line 20 "the operation will now directly fail and not be sent to the device".

2025-01-06 09:07 UTC, Oezge-Akin commented on content/change-logs/device-management/lwm2m-agent-2-1-0-blocking-resource-instance-operation-for-lwm2m-1-0-devices.md
> +This is now incorporated in {{< product-c8y-iot >}} platform operations.
I'll remove line 19. In line 20 I have additionally the example, I would like to keep that to make it more understandable for customers.

2025-01-06 09:42 UTC, eliasweingaertner commented on content/change-logs/device-management/lwm2m-agent-2-1-0-blocking-resource-instance-operation-for-lwm2m-1-0-devices.md
> +This is now incorporated in {{< product-c8y-iot >}} platform operations.
My comment was a little brief. I'd do it like this:

```suggestion
When the LwM2M resource instance level operations are created in the {{< product-c8y-iot >}} platform such as read /5/0/8/0 against a LwM2M 1.0 device, the operation will now directly fail and not be sent to the device.
```

2025-01-06 09:44 UTC, eliasweingaertner commented on content/change-logs/device-management/lwm2m-agent-2-1-0-blocking-resource-instance-operation-for-lwm2m-1-0-devices.md
> +When the LwM2M resource instance level operations are created in the {{< product-c8y-iot >}} platform such as read /5/0/8/0 against a LwM2M 1.0 device, the operation will be directly failed by the LW
```suggestion
```

2025-01-06 09:45 UTC, Oezge-Akin commented on content/change-logs/device-management/lwm2m-agent-2-1-0-blocking-resource-instance-operation-for-lwm2m-1-0-devices.md
> +version: 2.1.0
```suggestion
version: 1021.0.0
```

2025-01-06 10:10 UTC, eliasweingaertner approved these changes

2025-01-06 12:06 UTC, aaronraab approved these changes

2025-01-06 14:01 UTC, BeateRixen commented on content/change-logs/device-management/lwm2m-agent-2-1-0-blocking-resource-instance-operation-for-lwm2m-1-0-devices.md
> +The LwM2M resource instance level operations have been introduced in LwM2M 1.1 but are not supported by LwM2M 1.0 devices.
```suggestion
The LWM2M resource instance level operations have been introduced in LWM2M 1.1 but are not supported by LWM2M 1.0 devices.
```

2025-01-06 14:02 UTC, BeateRixen commented on content/change-logs/device-management/lwm2m-agent-2-1-0-blocking-resource-instance-operation-for-lwm2m-1-0-devices.md
> +When LwM2M resource instance level operations (Example: `read /5/0/8/0`) against a LwM2M 1.0 device are created, the operation will now directly fail and not be sent to the device.
```suggestion
When LWM2M resource instance level operations (Example: `read /5/0/8/0`) against a LWM2M 1.0 device are created, the operation will now directly fail and not be sent to the device.
```

2025-01-06 14:02 UTC, BeateRixen approved these changes

2025-01-06 14:14 UTC, merged