MTM-40015: MQTT return codes documentation
SoftwareAG/c8y-docs pull request #350
Opened 2022-03-31 12:47 UTC by pawelkowalczyksag

2022-03-31 17:41 UTC, jkot-softwareag commented on content/device-sdk/mqtt-bundle/implementation.md
> +It is a way to signal a closing connection, as most clients treat `CONNACK` with a code other than `0` like the connection needs to be closed.
_as most *mqtt* clients_
or 
_as most *mqtt client applications*_

2022-04-01 08:34 UTC, BeateRixen commented
@pawelkowalczyksag Hi Pawel, unfortunately your force-push has overwritten all language changes done by Richard and Marlene yesterday. If you had conflicts they should actually be resolved instead of overwriting our work. Since there were many changes this might have been difficult, but force push is also not the best solution :-). So one of you has to start from scratch again now :-). @rssag and @MWindel when doing language changes directly in the source files, better tell the PR owner that you are working on the files. @MWindel would you mind doing your changes again?

2022-04-01 09:37 UTC, pawelkowalczyksag commented
Everything should be now back, sorry was not expecting changes.

2022-04-04 11:54 UTC, AleksanderFiszSoftwareag approved these changes

2022-04-04 12:04 UTC, MWindel approved these changes

2022-04-05 06:22 UTC, micst96 requested changes

2022-04-05 06:22 UTC, micst96 commented on content/device-sdk/mqtt-bundle/implementation.md
> +Due to inconsistencies in the {{< product-c8y-iot >}} implementation of MQTT return codes, there are special cases:
I would not point to inconsistencies in c8y implementation in public doc (that to some extent is also true), becasue the main problem was that MQTT in 3.1.x version doesn't support all necessary codes - it is solved in MQTT 5.0 version. @karolkaczmarski-sag what do you think?

2022-04-05 10:33 UTC, jkot-softwareag commented on content/device-sdk/mqtt-bundle/implementation.md
> +When initiating an MQTT connection, you can be exposed to several errors.
an -> a ?

2022-04-05 22:06 UTC, jkot-softwareag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|4|Connection refused, bad user name or password | Incorrect credentials (wrong username and/or password, but not on empty password. See special cases below). This error is never returned when authen
why we have in same line `user name` and `username`? Can it be standarized?

2022-04-05 22:11 UTC, jkot-softwareag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|5|Connection refused, not authorized | Device side related problem, used when the device doesn't have permissions or is doing something forbidden. For example, if the client sends malformed messages
`For example, device managed object problems, or the sudden removal of permissions.`

What do we mean by `device managed object problems`? Malformed json, missing externalID or agent fragment for operations or something else?

2022-04-11 08:48 UTC, pawelkowalczyksag commented on content/device-sdk/mqtt-bundle/implementation.md
> +When initiating an MQTT connection, you can be exposed to several errors.
@MWindel ? I actually don't the rules, but I never saw "A MQTT" always "AN MQTT"

2022-04-11 08:48 UTC, pawelkowalczyksag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|5|Connection refused, not authorized | Device side related problem, used when the device doesn't have permissions or is doing something forbidden. For example, if the client sends malformed messages
We talked about this on chat, its not really clear what can cause a problem. But this more about giving user a clue - go check managed object, maybe there's a problem

2022-04-11 10:24 UTC, rssag commented on content/device-sdk/mqtt-bundle/implementation.md
> +When initiating an MQTT connection, you can be exposed to several errors.
it's "an"

2022-04-13 22:59 UTC, karolkaczmarski-sag requested changes

2022-04-13 22:59 UTC, karolkaczmarski-sag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|3|Connection refused, Server unavailable | General platform side error, used on internal errors and unknown authorization problems. <br>Can be received on network issues. <br>Error should be tempora
Please write description for codes 3,4,5 as if tenant options are always false (we don't want to document such workarounds)
Compare with https://docs.google.com/document/d/1QZS7vEk_r0ta2TskfwpjclEy8qW0xvjF6EPjLEJ6LzA/edit#

2022-04-14 06:27 UTC, pawelkowalczyksag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|2|Connection refused, identifier rejected | ClientId is not accepted by the platform.|
If ClientId is empty, You won't get this error I think

2022-04-19 12:54 UTC, karolkaczmarski-sag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|2|Connection refused, identifier rejected | ClientId is not accepted by the platform.|
Maybe clientid will be rejected earlier, so this "return" would not execute - please check :)

2022-04-29 12:54 UTC, pawelkowalczyksag commented on content/device-sdk/mqtt-bundle/implementation.md
> +The platform can also use `CONNACK` to signal a sudden error, such as a network issue.
Remove sudden error, it is just a way of signaling errors by platform

2022-05-05 15:55 UTC, rssag requested changes

2022-05-05 15:55 UTC, rssag commented on content/device-sdk/mqtt-bundle/implementation.md
> +When there is an MQTT error, platform responds with a CONNACK message with non-zero return code.
```suggestion
When there is an MQTT error, the platform responds with a `CONNACK` message with a non-zero return code.
```

2022-05-05 15:55 UTC, rssag commented on content/device-sdk/mqtt-bundle/implementation.md
> +`CONNACK` is not only a response to `CONNECT` message, but also a way to signal errors by platform.
```suggestion
`CONNACK` is not only a response to a `CONNECT` message, but also a way to signal errors that occurred in the platform.
```

2022-05-05 15:55 UTC, rssag commented on content/device-sdk/mqtt-bundle/implementation.md
> +It is a way to signal a closing connection, as most MQTT clients treat `CONNACK` with a code other than `0` like the connection needs to be closed.
```suggestion
It is also a way to signal a closing connection, as most MQTT clients treat `CONNACK` with a code other than `0` like the connection needs to be closed.
```

2022-05-05 15:55 UTC, rssag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|1|Connection refused, unacceptable protocol version | Unsupported version of MQTT protocol used. Currently, {{< product-c8y-iot >}} only allows 3.1 and 3.1.1.|
```suggestion
|1|Connection refused, unacceptable protocol version | Unsupported version of the MQTT protocol. Currently, {{< product-c8y-iot >}} only allows 3.1 and 3.1.1.|
```

2022-05-05 15:55 UTC, rssag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|3|Connection refused, Server unavailable | General platform side error, used on internal errors and unknown authorization problems. <br>Can be received on network issues. <br>Error should be tempora
```suggestion
|3|Connection refused, Server unavailable | General platform side error, used on internal errors and unknown authorization problems. <br>Can be received on network issues. <br>The error should be temporary and independent of device state, therefore the usual solution to this is to try again later.|
```

2022-05-05 15:55 UTC, rssag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|5|Connection refused, not authorized | Device side related problem, used when the device doesn't have permissions or is doing something forbidden. For example, if the client sends malformed messages
```suggestion
|5|Connection refused, not authorized | Device side related problem, used when the device doesn't have permissions or is doing something forbidden. For example, if the client sends malformed messages or tries to execute an operation without authenticating first, such as publishing a message.<br>Thrown on any issue with certificate authentication (for example, wrong common name, failed auto registration). <br>Also thrown on general issues with receiving device data or some other authorization problem related to the device state on the platform. For example, device managed object problems, or the sudden removal of permissions. In this situation it may be required to take action on the platform to investigate and apply a fix.<br> Lastly, it can also be thrown on unexpected exceptions like performance issues, especially during connection. Therefore it is a good approach to repeat the connection a few times to overcome temporary performance issues.|
```

2022-05-05 15:55 UTC, rssag commented on content/device-sdk/mqtt-bundle/implementation.md
> +Refer to the [MQTT Version 3.1.1 > 3.2 CONNACK - Acknowledge connection request](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718033) for details on the official MQTT con
```suggestion
Refer to [MQTT Version 3.1.1 > 3.2 CONNACK - Acknowledge connection request](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718033) for details on the official MQTT connection return codes.
```

2022-05-05 15:56 UTC, rssag approved these changes

2022-05-06 07:18 UTC, micst96 approved these changes

2022-05-06 07:18 UTC, micst96 commented on content/device-sdk/mqtt-bundle/implementation.md
> +|2|Connection refused, identifier rejected | ClientId is not accepted by the platform.|
minor: code 2 is returned when the identifier is empty or null, but actually when the client use mqtt in version 3.1 and the client id is longer than 23 characters we still use code 5 due to some generic error handling. I am not sure if we want to add this info to doc or if we need some task to change it, but just wanted to mention it. FYI @karolkaczmarski-sag

2022-05-06 07:45 UTC, pawelkowalczyksag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|2|Connection refused, identifier rejected | ClientId is not accepted by the platform.|
I missed that, I think we should include it here

2022-05-06 14:36 UTC, karolkaczmarski-sag requested changes

2022-05-06 14:36 UTC, karolkaczmarski-sag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|2|Connection refused, identifier rejected | ClientId is not accepted by the platform.|
Good catch @micst96, @pawelkowalczyksag please add this

2022-05-06 14:36 UTC, karolkaczmarski-sag commented on content/device-sdk/mqtt-bundle/implementation.md
> +|5|Connection refused, not authorized | Device side related problem, used when the device doesn't have permissions or is doing something forbidden. For example, if the client sends malformed messages
Not only "device side" e.g. failures (for whatever reason) during processing the message.

2022-05-11 10:09 UTC, pawelkowalczyksag commented
@BeateRixen I think this is done and ready to merge

2022-05-11 10:27 UTC, BeateRixen commented
> @BeateRixen I think this is done and ready to merge

@pawelkowalczyksag Should that go into the 10.14 branch as well?

2022-05-11 11:38 UTC, pawelkowalczyksag commented
@BeateRixen it should just go to the newest 10.15 branch.

2022-05-11 11:45 UTC, merged

2022-05-11 11:46 UTC, BeateRixen commented
Merged to develop and grafted to 10.14.