Changed need to to must
SoftwareAG/c8y-docs pull request #360
Opened 2022-04-12 09:43 UTC by JoshuaAdemola

2022-04-13 13:36 UTC, MWindel commented on content/protocol-integration/snmp-bundle/agent.md
> +>**Info:** If you are using one of the {{< company-sag >}} public cloud instances, you musr ensure that your tenant is subscribed to the Mibparser microservice.
```suggestion
>**Info:** If you are using one of the {{< company-sag >}} public cloud instances, you must ensure that your tenant is subscribed to the Mibparser microservice.
```

2022-04-13 13:38 UTC, rssag requested changes
one small typo

2022-04-13 13:38 UTC, rssag commented on content/device-sdk/cpp-bundle/use.md
> +As shown in [Integrating to {{< product-c8y-iot >}}](#integrating-to-cumulocity-iot), first we must add a new SmartREST template for CPU measurement and also increase the template version number. The
in this file, there's "you must" first, then "we must", and later again "you must". we should unify that as well and only use "you" instead of "we"

also more occurrences in other files.

on second thought, we should handle "you" vs "we" separately so we don't mix up too many things at once. let's not fix it in this PR.

2022-04-13 13:38 UTC, rssag commented on content/protocol-integration/snmp-bundle/agent.md
> +>**Info:** If you are using one of the {{< company-sag >}} public cloud instances, you musr ensure that your tenant is subscribed to the Mibparser microservice.
```suggestion
>**Info:** If you are using one of the {{< company-sag >}} public cloud instances, you must ensure that your tenant is subscribed to the Mibparser microservice.
```
typo.

2022-04-14 12:10 UTC, JoshuaAdemola commented on content/protocol-integration/snmp-bundle/agent.md
> +>**Info:** If you are using one of the {{< company-sag >}} public cloud instances, you musr ensure that your tenant is subscribed to the Mibparser microservice.
Fixed

2022-04-14 12:13 UTC, JoshuaAdemola commented on content/protocol-integration/snmp-bundle/agent.md
> +>**Info:** If you are using one of the {{< company-sag >}} public cloud instances, you musr ensure that your tenant is subscribed to the Mibparser microservice.
Fixed

2022-04-20 09:40 UTC, BeateRixen commented on content/concepts/introduction-bundle/api.md
> +In contrast to many other IoT platforms, {{< product-c8y-iot >}} uses the same APIs and the same interface technology for all use cases. As a consequence, you have a wider range of choices in putting
That does not really work here. Please change:
You must use only > Moreover, you only need to use

2022-04-20 09:43 UTC, BeateRixen commented on content/device-sdk/linux-agent-developer-guide-bundle/buffer.md
> +The {{< product-c8y-iot >}} C++ SDK offers two message buffering methods in case of connection lost. To switch it, you must change the arguments to be parsed to `SrReporter()`. The {{< product-c8y-io
I would leave this here as is. The "just" should stay and that sounds weird with "must".

2022-04-20 09:44 UTC, BeateRixen commented on content/device-sdk/linux-agent-developer-guide-bundle/buffer.md
> +You must add two new arguments when constructing the `SrRepoter` object:
see above

2022-04-20 09:46 UTC, BeateRixen commented on content/device-sdk/mqtt-examples-bundle/hello-mqtt-cs.md
> +To develop a very simple "Hello world" MQTT client for {{< product-c8y-iot >}}, you must:
@rssag This list shows a different format (colon and capitalization). I would make it consistent with the other lists.

2022-04-20 09:47 UTC, BeateRixen commented on content/device-tutorials/tinkerforge.md
> +For the software connection between the devices, you must install  Tinkerforge's Brick Daemon and Brick Viewer on the RaspPi. The installation instructions are provided on the Tinkerforge web page fo
remove extra space after "install"

2022-04-20 09:49 UTC, BeateRixen commented on content/event-language/advanced-cel-bundle/advanced-trigger.md
> +If you must take all measurements into account because, for example, you want to calculate the sum of your measurements and you do not want to update it for every new measurement.
@JoshuaAdemola In the future, you can ignore the event-language bundle in case of such quality improvement tasks. This documentation is deprecated and we do no longer need to improve it.

2022-04-20 10:51 UTC, JoshuaAdemola commented on content/concepts/introduction-bundle/api.md
> +In contrast to many other IoT platforms, {{< product-c8y-iot >}} uses the same APIs and the same interface technology for all use cases. As a consequence, you have a wider range of choices in putting
Fixed

2022-04-20 10:53 UTC, JoshuaAdemola commented on content/device-sdk/linux-agent-developer-guide-bundle/buffer.md
> +The {{< product-c8y-iot >}} C++ SDK offers two message buffering methods in case of connection lost. To switch it, you must change the arguments to be parsed to `SrReporter()`. The {{< product-c8y-io
Fixed

2022-04-20 10:53 UTC, JoshuaAdemola commented on content/device-sdk/linux-agent-developer-guide-bundle/buffer.md
> +You must add two new arguments when constructing the `SrRepoter` object:
Fixed

2022-04-20 10:58 UTC, JoshuaAdemola commented on content/device-tutorials/tinkerforge.md
> +For the software connection between the devices, you must install  Tinkerforge's Brick Daemon and Brick Viewer on the RaspPi. The installation instructions are provided on the Tinkerforge web page fo
Fixed

2022-04-20 10:58 UTC, JoshuaAdemola commented on content/event-language/advanced-cel-bundle/advanced-trigger.md
> +If you must take all measurements into account because, for example, you want to calculate the sum of your measurements and you do not want to update it for every new measurement.
Got it

2022-04-21 07:50 UTC, BeateRixen commented on content/device-sdk/mqtt-examples-bundle/hello-mqtt-cs.md
> +To develop a very simple "Hello world" MQTT client for {{< product-c8y-iot >}}, you must:
Fixed it.

2022-04-21 07:51 UTC, BeateRixen approved these changes

2022-04-22 07:31 UTC, merged