DM-761: add device heartbeat info
SoftwareAG/c8y-docs pull request #371
Opened 2022-04-26 07:36 UTC by georgi-huklev

2022-04-26 10:10 UTC, BeateRixen approved these changes

2022-04-28 08:55 UTC, l2p- requested changes

2022-04-28 08:55 UTC, l2p- commented on content/reference/device-management-library-bundle/device-availability.md
> +The platform considers the creation of measurements, events, alarms as well as empty managed object updates as the device's heartbeat. These requests will mark the device as available.
Please add info about the X-Cumulocity-Application-Key header for updates except empty MO updates. If you are looking for a reference about this behavior in the sources, look into `AvailabilityServiceImpl::onHeartBeat`

2022-05-02 08:36 UTC, BeateRixen approved these changes

2022-05-02 08:40 UTC, rssag commented on content/reference/device-management-library-bundle/device-availability.md
> +The following requests are considered as device's heartbeat and will mark the device as available:
```suggestion
The following requests are considered a device's heartbeat and will mark the device as available:
```

2022-05-02 08:40 UTC, rssag approved these changes

2022-05-04 15:12 UTC, l2p- approved these changes

2022-05-04 15:14 UTC, merged