feature/MTM-37550/MTM-42349-Update-documentation-related-to-Mass-Devi…
SoftwareAG/c8y-docs pull request #423
Opened 2022-05-19 23:28 UTC by Airdroplet

Initial version of public documentation for registration with security token

2022-05-23 10:49 UTC, jkot-softwareag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Configuration can be performed by setting following tenant options with one of above values:
case sensitive or insensitive? It seems insensitive

2022-05-23 10:58 UTC, jkot-softwareag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +In case of providing incorrect token error message will be displayed. After certain amount of attempts registration for device will reach blocked state and should be manually removed and started over
`In case of providing incorrect token, the error message will be displayed`. @BeateRixen I mean "error message" is separate from "token".
I am not sure about `should be manually removed and started over`. Maybe platform operator should first check what is happening. If he is under attack, then he should not restart procedure to give attacker more chances

2022-05-23 10:58 UTC, jkot-softwareag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Entering correct token for device which requires will lead to successful registration.
which requires **it**
(as below)

2022-05-23 11:20 UTC, jkot-softwareag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +For any device which uses security token, **accept all** feature is not available and will display a warning message.
`is not available`, which means this device will be skipped in process of accepting or something else will happen?

2022-05-23 11:23 UTC, jkot-softwareag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Any device connected to platform which is not using security token will be blocked and there is no possibility in this mode to complete registration for such devices.
`Any device trying to register in platform...`. 

`Connected` may be understand inproperly, and clients may ask about general mqtt connections. As far as I understand, after device is registered everything works as previously, and devices registered in the past will work regardless of how they were registered.

2022-05-23 14:19 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Configuration can be performed by setting following tenant options with one of above values:
it seems to be insensitive based on tests I have performed. I checked with upper case values tho XD

2022-05-23 14:25 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Any device connected to platform which is not using security token will be blocked and there is no possibility in this mode to complete registration for such devices.
yes, this security improvement affects only new devices added after introduce of this feature.

2022-05-24 08:42 UTC, Airdroplet reviewed
Due to layout update those images should be replaced

Replace images:

* [x] static/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security-accept-all.png
* [x] static/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security-blocked-state.png
* [ ] static/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security-enter-token.png
* [ ] static/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security.png

2022-05-27 09:41 UTC, pawel-rynarzewski-sag reviewed
A few suggestions from me.

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +> **Info:** In order to restart device registration process (for example due to the **Blocked** status) respective device registration item should be removed and process should be started from beginn
```suggestion
> **Info:** If a device registration is blocked, you will need to delete it first and then create it again.
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +> **Info:** "Pending acceptance" screen might differ depending on [security policy setting](#security-token-policy).
I'd keep it in sync with the target title.
```suggestion
> **Info:** "Pending acceptance" screen might differ depending on [security token policy](#security-token-policy).
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Platform supports following values for security token policy:
```suggestion
Platform supports the following values for security token policy:
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +  "value": "ignored"
I'd keep it upper case, for consistency with values listed above.
```suggestion
  "value": "IGNORED"
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +To mitigate possibility of random guess on not yet registered device serial number which might lead to situation when device is taken over by third tenant, security token policy should be configured.
```suggestion
Security token policy should be configured to reduce the risk of taking over not yet registered devices by threat actors (for example, by guessing their serial numbers).
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +* **OPTIONAL** - If device will require secure registration, platform will honor that by requesting additional security token from user.
```suggestion
* **OPTIONAL** - If a device requires secure registration, the platform will request an additional security token from user.
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +* **IGNORED** - Even if device requires secure registration, platform will ignore that requirement.
```suggestion
* **IGNORED** - Even if a device requires secure registration, the platform will ignore that requirement.
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +* **REQUIRED** - All devices connected to platform must use security token during registration.
```suggestion
* **REQUIRED** - All devices connected to the platform must use security token during registration.
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Configuration can be performed by setting following tenant options with one of above values:
```suggestion
The policy can be configured by setting the following tenant option with one of the values listed above, for example:
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +In this mode device connected to platform can be accepted without token validation.
```suggestion
In this mode a device connected to the platform can be accepted without any token validation.
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +List of device registration is presented on image below. As can be noticed, input to provide token is available for all devices in this mode.
```suggestion
The list of device registrations is presented in the image below. Note that the input for security token is displayed for all devices.
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +When device connected to platform doesn't use security token, device registration is proceeding without requirement to provide any value for security token input by user.
```suggestion
When a device connected to the platform doesn't use a security token, the registration can proceed without providing any value in the security token input.
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +If token is being provided by user for device which connected unsecurely, it will be accepted and token will be ignored.
```suggestion
If a security token is provided for a device which is connected unsecurely, it will be accepted and the token will be ignored.
```

2022-05-27 09:41 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Any following attemp will result in error:
```suggestion
Any following attempt will result in error:
```

2022-05-30 08:22 UTC, AleksanderFiszSoftwareag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Configuration can be performed by setting following tenant options with one of above values:
com.cumulocity.model.device.DeviceSecurityTokenPolicy#fromString it should be insensitive

2022-05-30 08:26 UTC, AleksanderFiszSoftwareag approved these changes

2022-05-30 09:23 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +  "value": "ignored"
ok, did it intentionally initially to show that value is case insensitive. But this trick is not necessary.

2022-05-31 12:48 UTC, jkot-softwareag approved these changes

2022-06-02 11:09 UTC, pawel-rynarzewski-sag reviewed
A few comments for the remaining part.

2022-06-02 11:09 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +On image below one device being registered by providing correct security token and two other devices were blocked without ever reaching **PENDING ACCEPTANCE** state.
```suggestion
In the screenshot below the first device has been accepted by providing the correct security token, the two other ones have been blocked without ever reaching **Pending acceptance** state.
```

2022-06-02 11:09 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Summary of warning message provides details on devices which could not be accepted automatically
```suggestion
The details of the warning message provide the list of devices which could not be accepted automatically.
```

2022-06-02 11:09 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Such devices should be accepted manually by providing correct **security token** value and clicking **Accept** button.
```suggestion
Such devices should be accepted manually by providing correct **Security token** value and clicking **Accept** button.
```

2022-06-02 11:09 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +###### Registration in optional security policy without using security token
"optional security policy" could be skipped as we're in the section dedicated to it already.

2022-06-03 08:00 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +###### Registration in optional security policy using security token
regarding header, we probably need to ask UIX team to take a look. Maybe they are familiar with styling for our docs.

FYI @carlosceia @catarino-sag

2022-06-03 08:02 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +###### Registration in optional security policy using security token
Regarding consolidating content maybe we can talk, because I don't really get the point from the image?

2022-06-03 08:09 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +The procedure of accepting devices is same as described by [registration in optional security policy using security token](#registration-in-optional-security-policy-using-security-token)
Note sure about that, will check if it actually can be joined. But currently would rather prefer to refer to behavior description if it is pretty much same.

2022-06-03 10:16 UTC, catarino-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +###### Registration in optional security policy using security token
> regarding header, we probably need to ask UIX team to take a look. Maybe they are familiar with styling for our docs.

@Airdroplet you're using ###### to format a subsection header, instead follow this:

### Section header

#### Subsection header

2022-06-03 10:31 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +###### Registration in optional security policy using security token
##### Sub-subssction header

`##### Sub-subssction header`

2022-06-03 10:35 UTC, catarino-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +###### Registration in optional security policy using security token
Just noticed that the markdown was rendered (as it should, actually) :)

So:

`### Section header` 

`#### Subsection header` 

and yes:

`##### Sub-subsection header`

2022-06-06 09:17 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +###### Registration in optional security policy using security token
I have chenaged the approach a little here by getting avay from usa of header tittles (Noticed that we use something like that on different pages). 
Additionally I have reordered content, it should be better now.

2022-06-06 13:56 UTC, karolkaczmarski-sag approved these changes

2022-06-09 20:44 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +The procedure of accepting devices is same as described by [registration in optional security policy using security token](#registration-in-optional-security-policy-using-security-token)
Didn't figure out how to join it and keep options described in understandable manner. Let's leave it like is.

2022-06-27 12:30 UTC, karolkaczmarski-sag approved these changes

2022-06-27 20:09 UTC, pawel-rynarzewski-sag approved these changes
Just 2 suggestions more, otherwise looks good to me.

2022-06-27 20:09 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +<img src="/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-required-security-blocked-unsecure-devices.png" alt="Pending acceptance devices in optional security token
`alt` description is not updated

2022-06-30 07:53 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +> **Info** Feature requires user to have **READ** permission to **option management**. In case if permission is not granted, security token policy used by default is **OPTIONAL**.
done

2022-06-30 07:53 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +<img src="/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-required-security-blocked-unsecure-devices.png" alt="Pending acceptance devices in optional security token
updated all `alt` descriptions. Hope it is better now :)

2022-07-05 13:07 UTC, rssag requested changes

2022-07-05 13:07 UTC, rssag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +![Error displayed on accepting device registration request by providing an incorrect token](/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security-wrong-
i think it might suffice to mention the error messages here. we try to avoid too many screenshots as they have to be maintained. what do you think @BeateRixen ?

2022-07-05 13:07 UTC, rssag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +![Blocking device registration request as a result of continuous errors in providing a token](/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security-reac
the error message in this screenshot contains errors i think (missing closing parentheses). and as stated above, i think we might be able to avoid them alltogether.

2022-07-05 13:42 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +* **IGNORED** - Even if a device requires secure registration, {{< product-c8y-iot >}} will ignore that requirement.
```suggestion
* IGNORED - Even if a device requires secure registration, {{< product-c8y-iot >}} will ignore that requirement.
```

2022-07-05 13:42 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +* **REQUIRED** - All devices connected to {{< product-c8y-iot >}} must use a security token during registration.
```suggestion
* REQUIRED - All devices connected to {{< product-c8y-iot >}} must use a security token during registration.
```

2022-07-05 13:44 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +With a value of **IGNORED** for the security token policy, a device connected to {{< product-c8y-iot >}} can be accepted without any token validation:
```suggestion
With a value of IGNORED for the security token policy, a device connected to {{< product-c8y-iot >}} can be accepted without any token validation:
```

2022-07-05 13:46 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +![Error displayed on accepting device registration request by providing an incorrect token](/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security-wrong-
Agreed. @Airdroplet Please remove all screenshots that are of no additional value for the user as he sees the screens/messages etc. in the product anyway.

2022-07-05 13:49 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Depending on the security token policy, the "Pending acceptance" screen will be different.
```suggestion
{{< c8y-admon-info >}}
The **Pending acceptance** screen might differ depending on the [security token policy](#security-token-policy-for-device-registration).
{{< /c8y-admon-info >}}
```

2022-07-07 09:30 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +* **OPTIONAL** - If a device requires secure registration, {{< product-c8y-iot >}} will request an additional security token from the user.
Is it left in bold intentionally?

2022-07-07 09:54 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +* **OPTIONAL** - If a device requires secure registration, {{< product-c8y-iot >}} will request an additional security token from the user.
```suggestion
* OPTIONAL - If a device requires secure registration, {{< product-c8y-iot >}} will request an additional security token from the user.
```

2022-07-07 09:55 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +* **OPTIONAL** - If a device requires secure registration, {{< product-c8y-iot >}} will request an additional security token from the user.
No, fixed

2022-07-13 10:46 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +![Error displayed on accepting device registration request by providing an incorrect token](/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security-wrong-
removed some of the screenshots.

2022-07-13 10:46 UTC, Airdroplet commented on content/users-guide/device-management-bundle/connecting-devices.md
> +![Blocking device registration request as a result of continuous errors in providing a token](/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security-reac
removed some of those screenshots

2022-07-13 10:52 UTC, Airdroplet commented
@BeateRixen @rssag 

As for remaining screenshots, in my opinion those are necessary to provide correct overview of the feature.

2022-07-13 12:08 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +The feature requires the user to have READ permission for "Option management". In the case of missing permission, the security token policy defaults to OPTIONAL.
```suggestion
The feature requires you to have READ permission for "Option management". In the case of missing permission, the security token policy defaults to OPTIONAL.
```

2022-07-13 12:11 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +In this mode any device connected to {{< product-c8y-iot >}} is required to use a security token on establishing the connection and a user is required to enter the same token when accepting the devic
```suggestion
In this mode any device connected to {{< product-c8y-iot >}} must use a security token on establishing the connection and the user must enter the same token when accepting the device.
```

2022-07-13 12:12 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +Such devices must be accepted manually by providing the correct **Security token** value and clicking the **Accept** button.
```suggestion
Such devices must be accepted manually by providing the correct **Security token** value and clicking **Accept**.
```

2022-07-13 12:13 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +In the case of providing an incorrect token, an error message will be displayed informing about mismatch between value used by device and value provided via user interface.
```suggestion
In the case of providing an incorrect token, an error message will be displayed informing about a mismatch between the value used by the device and the value provided via the user interface.
```

2022-07-13 12:16 UTC, BeateRixen commented on content/users-guide/device-management-bundle/connecting-devices.md
> +After a certain amount of failed attempts, the registration will reach the blocked state. Reaching blocked is followed by an error message informing about it.
```suggestion
After a certain amount of failed attempts, the registration will reach the blocked state, indicated by a corresponding error message.
```

2022-07-19 14:20 UTC, pawel-rynarzewski-sag commented on content/users-guide/device-management-bundle/connecting-devices.md
> +```json
Not sure, for new tenants this policy can be set via tenant policies UI, but for existing ones there is no UI and it needs to be set via REST API - then a JSON body for the request might be useful.

2022-07-20 08:40 UTC, BeateRixen approved these changes

2022-07-20 09:57 UTC, MWindel approved these changes

2022-07-20 10:04 UTC, merged