DM-814: document c8y_Agent fragment and related SmartREST templates
SoftwareAG/c8y-docs pull request #437
Opened 2022-06-01 07:57 UTC by georgi-huklev

2022-06-01 16:44 UTC, l2p- requested changes

2022-06-03 07:37 UTC, rssag approved these changes

2022-06-03 07:51 UTC, georgi-huklev commented on content/reference/device-management-library-bundle/device-info.md
> +All devices must provide information about the agent they are running, that is the software that integrates them with {{< product-c8y-iot >}}.
@rssag this is an optional fragment, should or can has to be used.
```suggestion
All devices should provide information about the agent they are running, that is the software that integrates them with {{< product-c8y-iot >}}.
```

2022-06-03 08:50 UTC, rssag approved these changes

2022-06-08 09:07 UTC, merged