Converted info, important and warning admonitions from the old format…
SoftwareAG/c8y-docs pull request #438
Opened 2022-06-01 11:48 UTC by JoshuaAdemola

… to the new shortcode way

2022-06-03 09:52 UTC, rssag requested changes

2022-06-03 09:52 UTC, rssag commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +{{< c8y-admon-info >}}You should try to ensure that the data you feed into the measurements base collection is consistent. If measurements of the same type vary in the fragment structures, the result
```suggestion
{{< c8y-admon-info >}}
You should try to ensure that the data you feed into the measurements base collection is consistent. If measurements of the same type vary in the fragment structures, the resulting target table might not be as concise as intended. A common problem, for example, are varying data types of the values like one value being 2.079 and another one NaN. In such a case the resulting column in the target table would have a mixed type of number and string, which complicates further processing in follow-up applications.
```

2022-06-03 09:52 UTC, rssag commented on content/edge/configuration-bundle/configuring-the-network.md
> +	 {{< /c8y-admon-info >}}
indentation looks off here, but it's probably only source code cosmetic.

2022-06-03 09:52 UTC, rssag commented on content/edge/installation-bundle/installing-edge-using-gui.md
> +  {{< /c8y-admon-important >}}
indentation

2022-06-03 09:52 UTC, rssag commented on content/edge/migration-bundle/restoring-the-data-on-edge-109.md
> +    {{< /c8y-admon-important >}}
indentation

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/api-reference-bundle/jobs.md
>  <br>1. For *periodic* frequency, `cronExpression`, `dataFromPreviousNSeconds` and `timeZone` fields are mandatory.
```suggestion
1. For *periodic* frequency, `cronExpression`, `dataFromPreviousNSeconds` and `timeZone` fields are mandatory.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/api-reference-bundle/jobs.md
>  <br>2. For *once* frequency, `scheduleAt`, `dataFrom` and `dataTo` fields are mandatory and should adhere to the ISO-8601 date-time format
```suggestion
2. For *once* frequency, `scheduleAt`, `dataFrom` and `dataTo` fields are mandatory and should adhere to the ISO-8601 date-time format, that is "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", for instance "2019-12-30T22:59:50.235+05:30".
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/api-reference-bundle/jobs.md
>  <br> &emsp; i.e. "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", for instance "2019-12-30T22:59:50.235+05:30".
```suggestion
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/api-reference-bundle/jobs.md
>  <br> &emsp; The difference between `dataFrom` and `dateTo` must not exceed 24 hours.
```suggestion
<br>The difference between `dataFrom` and `dateTo` must not exceed 24 hours.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/api-reference-bundle/resources.md
>  <br>1. For PMML, the resources are typically JAR files or excel sheets containing custom functions and look up tables respectively.
```suggestion
1. For PMML, the resources are typically JAR files or excel sheets containing custom functions and look up tables respectively.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/api-reference-bundle/resources.md
>  <br>2. For ONNX, the resources are typically python files containing some pre-processing or post-processing logic which can be embedded into a pipeline.
```suggestion
2. For ONNX, the resources are typically python files containing some pre-processing or post-processing logic which can be embedded into a pipeline.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/web-app-bundle/managing-models.md
>  <br>For uploading PMML models, use the **Apply PMML Cleanser** toggle in the top menu bar to enable/disable the PMML cleanser.
```suggestion
For uploading PMML models, use the **Apply PMML Cleanser** toggle in the top menu bar to enable/disable the PMML cleanser.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/web-app-bundle/managing-models.md
>  <br>By default, the toggle is enabled.<br>
```suggestion
<br>By default, the toggle is enabled.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/web-app-bundle/managing-models.md
>  <br>During a PMML upload if the **Apply PMML Cleanser** toggle is enabled, comprehensive semantic checks and corrections will be performed on the provided PMML file.  Disabling it will improve upload
```suggestion

During a PMML upload if the **Apply PMML Cleanser** toggle is enabled, comprehensive semantic checks and corrections will be performed on the provided PMML file.  Disabling it will improve upload time, but this is not recommended. If the PMML file is large, such as Random Forest model, we recommend you to compress the file with ZIP/GZIP before uploading. This will reduce the upload time drastically.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/web-app-bundle/managing-pipelines.md
>  <br>1. The pre-processing/post-processing scripts must contain a python function named **process** which takes in just one argument. The processing logic should be contained in this function. Any inp
```suggestion
1. The pre-processing/post-processing scripts must contain a python function named **process** which takes in just one argument. The processing logic should be contained in this function. Any inputs to these scripts can be accessed using the argument of the **process** function.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/web-app-bundle/managing-pipelines.md
> +<br>2. The **process** function of any pre-processing script must return a *Dictionary* with the keys containing the input field names of the model and its corresponding values containing the pre-pro
```suggestion
2. The **process** function of any pre-processing script must return a *Dictionary* with the keys containing the input field names of the model and its corresponding values containing the pre-processed data.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/web-app-bundle/managing-pipelines.md
>  <br>3. If there is a post-processing script, the outputs of the ONNX model will be the input to the **process** function of the post-processing script which may or may not return an output depending
```suggestion
3. If there is a post-processing script, the outputs of the ONNX model will be the input to the **process** function of the post-processing script which may or may not return an output depending on the use case.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/web-app-bundle/processing-data.md
>  <br>1. For a periodic frequency, a CRON expression is generated and used by the scheduler.
```suggestion
1. For a periodic frequency, a CRON expression is generated and used by the scheduler.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/web-app-bundle/processing-data.md
>  <br>2. The data range selected for the schedule must not exceed 24 hours.
```suggestion
2. The data range selected for the schedule must not exceed 24 hours.
```

2022-06-03 09:52 UTC, rssag commented on content/machine-learning/web-app-bundle/processing-data.md
>  <br>3. For a one-time job, you need to select the date when the job should run. You also need to specify the data range to be used for processing when the job is executed.
```suggestion
3. For a one-time job, you need to select the date when the job should run. You also need to specify the data range to be used for processing when the job is executed.
```

2022-06-03 11:49 UTC, JoshuaAdemola commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +{{< c8y-admon-info >}}You should try to ensure that the data you feed into the measurements base collection is consistent. If measurements of the same type vary in the fragment structures, the result
Fixed

2022-06-03 11:51 UTC, JoshuaAdemola commented on content/edge/configuration-bundle/configuring-the-network.md
> +	 {{< /c8y-admon-info >}}
Fixed

2022-06-03 11:52 UTC, JoshuaAdemola commented on content/edge/installation-bundle/installing-edge-using-gui.md
> +  {{< /c8y-admon-important >}}
Fixed

2022-06-03 11:53 UTC, JoshuaAdemola commented on content/edge/migration-bundle/restoring-the-data-on-edge-109.md
> +    {{< /c8y-admon-important >}}
Fixed

2022-06-03 11:59 UTC, JoshuaAdemola commented on content/machine-learning/api-reference-bundle/jobs.md
>  <br> &emsp; The difference between `dataFrom` and `dateTo` must not exceed 24 hours.
Fixed

2022-06-03 11:59 UTC, JoshuaAdemola commented on content/machine-learning/api-reference-bundle/jobs.md
>  <br> &emsp; i.e. "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", for instance "2019-12-30T22:59:50.235+05:30".
Fixed

2022-06-03 11:59 UTC, JoshuaAdemola commented on content/machine-learning/api-reference-bundle/jobs.md
>  <br>2. For *once* frequency, `scheduleAt`, `dataFrom` and `dataTo` fields are mandatory and should adhere to the ISO-8601 date-time format
Fixed

2022-06-03 11:59 UTC, JoshuaAdemola commented on content/machine-learning/api-reference-bundle/jobs.md
>  <br>1. For *periodic* frequency, `cronExpression`, `dataFromPreviousNSeconds` and `timeZone` fields are mandatory.
Fixed

2022-06-03 12:01 UTC, JoshuaAdemola commented on content/machine-learning/api-reference-bundle/resources.md
>  <br>1. For PMML, the resources are typically JAR files or excel sheets containing custom functions and look up tables respectively.
Fixed

2022-06-03 12:01 UTC, JoshuaAdemola commented on content/machine-learning/api-reference-bundle/resources.md
>  <br>2. For ONNX, the resources are typically python files containing some pre-processing or post-processing logic which can be embedded into a pipeline.
Fixed

2022-06-03 12:03 UTC, JoshuaAdemola commented on content/machine-learning/web-app-bundle/managing-models.md
>  <br>For uploading PMML models, use the **Apply PMML Cleanser** toggle in the top menu bar to enable/disable the PMML cleanser.
Fixed

2022-06-03 12:03 UTC, JoshuaAdemola commented on content/machine-learning/web-app-bundle/managing-models.md
>  <br>By default, the toggle is enabled.<br>
Fixed

2022-06-03 12:03 UTC, JoshuaAdemola commented on content/machine-learning/web-app-bundle/managing-models.md
>  <br>During a PMML upload if the **Apply PMML Cleanser** toggle is enabled, comprehensive semantic checks and corrections will be performed on the provided PMML file.  Disabling it will improve upload
Fixed

2022-06-03 12:04 UTC, JoshuaAdemola commented on content/machine-learning/web-app-bundle/managing-pipelines.md
>  <br>1. The pre-processing/post-processing scripts must contain a python function named **process** which takes in just one argument. The processing logic should be contained in this function. Any inp
Fixed

2022-06-03 12:04 UTC, JoshuaAdemola commented on content/machine-learning/web-app-bundle/managing-pipelines.md
>  <br>3. If there is a post-processing script, the outputs of the ONNX model will be the input to the **process** function of the post-processing script which may or may not return an output depending
Fixed

2022-06-03 12:05 UTC, JoshuaAdemola commented on content/machine-learning/web-app-bundle/processing-data.md
>  <br>3. For a one-time job, you need to select the date when the job should run. You also need to specify the data range to be used for processing when the job is executed.
Fixed

2022-06-07 12:15 UTC, MWindel commented on content/apama/overview-analytics-bundle/migrate-from-esper.md
> +    {{< c8y-admon-important >}}
Enter line break before the box

2022-06-07 12:15 UTC, MWindel commented on content/apama/overview-analytics-bundle/migrate-from-esper.md
> +    {{< c8y-admon-important >}}
Enter line break before the box

2022-06-07 12:15 UTC, MWindel commented on content/apama/troubleshooting-bundle/monitoring-rest.md
> +    {{< c8y-admon-info >}}
Add line break before box

2022-06-07 12:15 UTC, MWindel commented on content/apama/troubleshooting-bundle/monitoring-rest.md
> +    {{< c8y-admon-info >}}
Add line break before box

2022-06-07 12:28 UTC, MWindel approved these changes

2022-06-10 11:31 UTC, JoshuaAdemola commented on content/apama/overview-analytics-bundle/migrate-from-esper.md
> +    {{< c8y-admon-important >}}
Fixed

2022-06-10 11:32 UTC, JoshuaAdemola commented on content/apama/overview-analytics-bundle/migrate-from-esper.md
> +    {{< c8y-admon-important >}}
Fixed

2022-06-10 11:32 UTC, JoshuaAdemola commented on content/apama/troubleshooting-bundle/monitoring-rest.md
> +    {{< c8y-admon-info >}}
Fixed

2022-06-10 11:32 UTC, JoshuaAdemola commented on content/apama/troubleshooting-bundle/monitoring-rest.md
> +    {{< c8y-admon-info >}}
Fixed

2022-06-14 08:08 UTC, JoshuaAdemola commented on content/apama/troubleshooting.md
> +{{< c8y-admon-info >}}
@rssag Can you fix this?

2022-06-14 08:18 UTC, rssag commented on content/apama/troubleshooting.md
> +{{< c8y-admon-info >}}
this is one of the occurrences of admonition blocks before the first h3. we agreed on such admonition blocks to be moved so it doesn't happen (since this is arguably consistent behavior with how existing CSS rules are applied).
@MWindel where should the block be moved?

2022-06-14 09:56 UTC, MWindel commented on content/apama/troubleshooting.md
> +{{< c8y-admon-info >}}
@rssag Yes, moving them would be best.

2022-06-14 09:57 UTC, MWindel commented on content/datahub/working-with-datahub.md
> +{{< c8y-admon-info >}}
@rssag could you move this?

2022-06-14 10:23 UTC, rssag commented on content/datahub/working-with-datahub.md
> +{{< c8y-admon-info >}}
removed the admonition block, and made it regular text.

2022-06-14 10:23 UTC, rssag approved these changes

2022-06-14 11:07 UTC, merged