[DM-1005] Document LwM2M 1.1 features
SoftwareAG/c8y-docs pull request #453
Opened 2022-06-14 09:23 UTC by bggov

2022-06-14 11:58 UTC, bggov commented on content/protocol-integration/lwm2m-bundle/overview.md
> +{{< product-c8y-iot >}} LWM2M 1.1 introduces a new client's side "send" operation. If a sensor or number of sensors want to send measurements to the server, they can use the "send" operation to send
From customer's side it's good to know that we're already supporting this in a much simple way. I agree that I'm getting in too many technical details, so I can remove some of them. I can leave only the first part, where it says we support 'send', but remove the rest of the details.

2022-06-14 13:04 UTC, sag-eweingaertner approved these changes

2022-06-14 13:04 UTC, sag-eweingaertner commented on content/protocol-integration/lwm2m-bundle/register-device.md
> +Note, that since {{< product-c8y-iot >}} LWM2M 1.1, &ldquo;Q&rdquo; (queue) mode is not supported, and the default mode will be &ldquo;U&rdquo; (unqueued). Although {{< product-c8y-iot >}} will alway
I'd rephrase this a little: {{< product-c8y-iot >}} will always queue operations regardless if the device is connected or not, hence this setting has virtually zero effect on the behavior of {{< product-c8y-iot >}}.

2022-06-14 13:25 UTC, rssag approved these changes
language review as commit + approval

2022-06-15 09:15 UTC, sag-eweingaertner requested changes

2022-06-15 09:15 UTC, sag-eweingaertner commented on content/protocol-integration/lwm2m-bundle/overview.md
> +You can connect any device supporting LWM2M 1.1 or LWM2M 1.0 to {{< product-c8y-iot >}} without programming. {{< product-c8y-iot >}} expects the device and its capabilities (such as firmware update)
I missed this before. Please do not mention TCP or any other binding mode at all. Please simply write above (see second marker) only that we support CoAP-UDP.

2022-06-15 09:15 UTC, sag-eweingaertner commented on content/protocol-integration/lwm2m-bundle/overview.md
> +{{< product-c8y-iot >}} currently supports LWM2M 1.1.
-> {{< product-c8y-iot >}} currently supports LWM2M 1.1 over CoAP and UDP.

2022-06-27 09:19 UTC, Oezge-Akin approved these changes

2022-07-05 08:38 UTC, sag-eweingaertner approved these changes

2022-07-05 11:46 UTC, BeateRixen commented on content/protocol-integration/lwm2m-bundle/shell-commands.md
> +<td align="left">Composite writes of one or more values to a resources on the device. The data will be written to the listed resource paths in a single request</td>
```suggestion
<td align="left">Composite writes of one or more values to a resource on the device. The data will be written to the listed resource paths in a single request</td>
```

2022-07-05 11:47 UTC, BeateRixen approved these changes

2022-07-06 11:31 UTC, BeateRixen commented
@bggov Can this be merged, and is this for 10.15 only?

2022-07-07 08:38 UTC, merged