Fixed table, ordered widgets and device details
SoftwareAG/c8y-docs pull request #486
Opened 2022-07-01 09:37 UTC by JoshuaAdemola

2022-07-04 14:19 UTC, rssag requested changes

2022-07-04 14:19 UTC, rssag commented on content/benutzerhandbuch/cockpit-de-bundle/widgets-collection.md
> +<td align="left">Zeigt die Zustände eines Geräts im Form einer Ampel.</td>
```suggestion
<td align="left">Zeigt die Zustände eines Geräts in Form einer Ampel.</td>
```

2022-07-04 14:19 UTC, rssag commented on content/benutzerhandbuch/cockpit-de-bundle/widgets-collection.md
> +Das "Ampel"-Widget visualisiert den Status eines Geräts im Form einer Ampel.
```suggestion
Das "Ampel"-Widget visualisiert den Status eines Geräts in Form einer Ampel.
```

2022-07-04 14:19 UTC, rssag commented on content/benutzerhandbuch/cockpit-de-bundle/widgets-collection.md
> +Sie können einen Datenpunkt für das Tacho auswählen sowie mehrere Datenpunkte, die als Beschriftung auf der linken Seite angezeigt werden.
```suggestion
Sie können einen Datenpunkt für den Tacho auswählen sowie mehrere Datenpunkte, die als Beschriftung auf der linken Seite angezeigt werden.
```

2022-07-05 10:57 UTC, BeateRixen commented on content/benutzerhandbuch/cockpit-de-bundle/widgets-collection.md
> +Das "Ampel"-Widget visualisiert den Status eines Geräts im Form einer Ampel.
Any change to the German translation must be communicated to the translators via @MWindel otherwise it will not find its way into their database and will be wrong again next time.

2022-07-05 15:32 UTC, MWindel approved these changes

2022-07-06 09:24 UTC, merged