MTM-46693 - Update SSO doc
SoftwareAG/c8y-docs pull request #488
Opened 2022-07-04 11:50 UTC by chbakar

update SSO screenshots

2022-07-05 14:44 UTC, BeateRixen approved these changes

2022-07-05 14:46 UTC, BeateRixen commented
@chbakar Can you please also check the German screenshots and provide new ones if required? Since the User guide is also provided in German we need to have all screenshots with the German UI as well. You can find them in the folder images/benutzerhandbuch (with the same names as the respective English ones).

2022-07-05 14:47 UTC, chbakar commented
> @chbakar Can you please also check the German screenshots and provide new ones if required? Since the User guide is also provided in German we need to have all screenshots with the German UI as well. You can find them in the folder images/benutzerhandbuch (with the same names as the respective English ones).

2022-07-05 14:48 UTC, chbakar commented
No problem @BeateRixen. I'll update those as well

2022-07-06 11:23 UTC, BeateRixen commented on content/benutzerhandbuch/administration-de-bundle/changing-settings.md
> +Die Benutzer-ID kann auf ein beliebiges Feld des an die Plattform gesendeten Autorisierungs-Tokens gesetzt werden. Wir empfehlen Ihnen, das Autorisierungs-Token in den Audit-Logs zu überprüfen, um si
```suggestion
Die Benutzer-ID kann in ein beliebiges Feld des an die Plattform gesendeten Autorisierungs-Tokens gesetzt werden. Wir empfehlen Ihnen, das Autorisierungs-Token in den Audit-Logs zu überprüfen, um sicherzustellen, dass das richtige Feld verwendet wird (siehe [Troubleshooting](#troubleshooting)).
```

2022-07-06 11:24 UTC, BeateRixen commented on content/benutzerhandbuch/administration-de-bundle/changing-settings.md
> +4. Durch Spezifizieren der JWKS (JSON Web Key Set)-Adresse. JWKS ist ein Satz kryptografischer Schlüssel, die öffentliche Schlüssel enthalten, die zum Verifizieren von Autorisierungs-Token verwendet
```suggestion
4. Durch Spezifizieren der JWKS (JSON Web Key Set)-Adresse. JWKS ist ein Satz kryptografischer Schlüssel, die öffentliche Schlüssel enthalten, die zum Verifizieren von Autorisierungs-Tokens verwendet werden, die vom Autorisierungsserver ausgestellt wurden.
```

2022-07-06 11:24 UTC, BeateRixen approved these changes

2022-07-06 11:25 UTC, BeateRixen commented on content/benutzerhandbuch/administration-de-bundle/changing-settings.md
> +Die Benutzer-ID kann in ein beliebiges Feld des an die Plattform gesendeten Autorisierungs-Tokens gesetzt werden. Wir empfehlen Ihnen, das Autorisierungs-Token in den Audit-Logs zu überprüfen, um sic
@MWindel FYI. This is the German file which will contain new text.

2022-07-11 11:10 UTC, micst96 requested changes

2022-07-11 11:10 UTC, micst96 commented on content/users-guide/administration-bundle/changing-settings.md
> +4. By specifying the JWKS (JSON Web Key Set) address. JWKS is a set of cryptographic keys containing public keys used to verify tokens issued by the authorization server.
```suggestion
4. By specifying the JWKS (JSON Web Key Set) URI. JWKS is a set of JWK objects containing a public key used to verify tokens issued by the authorization server.
```

2022-07-11 11:14 UTC, chbakar commented on content/users-guide/administration-bundle/changing-settings.md
> +The user ID can be set to any field of the authorization token sent to the platform. We recommend you to inspect the authorization token in the audit logs to make sure the correct field is used (see
The top-level fields is definitely more detailed

2022-07-11 12:19 UTC, micst96 approved these changes

2022-07-11 12:33 UTC, merged