OPC UA chapter for troubleshooting enhanced, by adding JMX
SoftwareAG/c8y-docs pull request #497
Opened 2022-07-06 11:38 UTC by PestusAtSAG

https://cumulocity.atlassian.net/browse/DM-428 [B] As Nordex, I want to have the total number of retries and total number of outgoing http request for custom actions

2022-07-06 14:24 UTC, BeateRixen commented
@PestusAtSAG Please be aware that you need one approval from a developer as subject matter expert as well.

2022-07-07 11:45 UTC, PestusAtSAG commented
ok, thanks for info, i am asking R&D Team for reviewer

2022-07-07 11:49 UTC, sag-eweingaertner commented on content/protocol-integration/opcua-bundle/troubleshooting.md
> +### Prometheus
We do not document what we don't have :) Should be removed.

2022-07-07 11:52 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/troubleshooting.md
> +### Prometheus
Do you mean the complete Prometheus part?

2022-07-07 13:00 UTC, rssag commented
what's up with this PR targeting a forked version of c8y-docs? it says "SoftwareAG:develop", and i cannot checkout PestusAtSAG:DM-428-custom-action-jmx-bean locally for c8y-docs

2022-07-07 13:11 UTC, rssag requested changes

2022-07-07 13:11 UTC, rssag commented on content/protocol-integration/opcua-bundle/troubleshooting.md
> +Via jconsole the MBeans can be selected and following attributes can be accessed:
```suggestion
Via jconsole the MBeans can be selected and the following attributes can be accessed:
```

2022-07-07 13:11 UTC, rssag commented on content/protocol-integration/opcua-bundle/troubleshooting.md
> +Particular for custom actions it is usefull to get some statistics. This attributes can be retrieved from CustomActionMBean:
```suggestion
It can be is useful to get some statistics for custom actions in particular. These attributes can be retrieved from the CustomActionMBean:
```

2022-07-07 13:11 UTC, rssag commented on content/protocol-integration/opcua-bundle/troubleshooting.md
> +1. Table of all called URLs seperated by http return code and retry count.
```suggestion
1. Table of all called URLs seperated by HTTP return code and retry count.
```

2022-07-07 13:11 UTC, rssag commented on content/protocol-integration/opcua-bundle/troubleshooting.md
> +The key entry of the table contains of
```suggestion
The key entry of the table consists of:
```

2022-07-07 13:11 UTC, rssag commented on content/protocol-integration/opcua-bundle/troubleshooting.md
> +
```suggestion
```

2022-07-07 13:11 UTC, rssag commented on content/protocol-integration/opcua-bundle/troubleshooting.md
> +![jconsole MBeans](/images/device-protocols/opcua/opcua-jmx-mbeans.png)
the image files use ".PNG" file extension. this should be lower case. the image links should also then use lower case (it's correct here, but there are two more occurrences where it's upper case).

2022-07-07 13:11 UTC, rssag commented on content/protocol-integration/opcua-bundle/troubleshooting.md
> +![jconsole MBeans CustomActionMBean CounterTable](/images/device-protocols/opcua/opcua-jmx-customActionMBean-CounterTable.PNG)
since we're in an enumeration here, i'm not sure about the indentation. i can't check the PR out to have a look at it locally, also see my question about the fork.

2022-07-07 13:22 UTC, PestusAtSAG commented
I have no rights to create a feature branch on this repository. However, i am contributing to opc ua gateway and also have to contribute to c8y-docs. For that reason i created a fork and did my changes there and created a PR on this fork for merging to head repository.

2022-07-07 13:26 UTC, rssag commented
> @rssag I have no rights to create a feature branch on this repository. However, i am contributing to opc ua gateway and also have to contribute to c8y-docs. For that reason i created a fork and did my changes there and created a PR on this fork for merging to head repository.

oh. alright, i granted you write permission just now

2022-07-08 11:38 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/troubleshooting.md
> +![jconsole MBeans](/images/device-protocols/opcua/opcua-jmx-mbeans.png)
i changed the other to lower case

2022-08-03 15:37 UTC, rssag commented
i ported this to a regular PR to develop here: https://github.com/SoftwareAG/c8y-docs/pull/545
closing this PR.

2022-08-03 15:37 UTC, closed without merging