Administration related topics
SoftwareAG/c8y-docs pull request #538
Opened 2022-07-26 13:38 UTC by BeateRixen

2022-07-26 13:39 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
> +- Custom alarm and event properties can be used as custom fields which can be added to your reports and will be available in the **Exports** page in the Cockpit application.
```suggestion
- Custom alarm and event properties can be used as custom fields which can be added to your reports and will be available in the **Export** page in the Cockpit application.
```

2022-07-28 20:43 UTC, manasesjesus requested changes
fixing links to the OpenAPI

2022-07-28 20:43 UTC, manasesjesus commented on content/users-guide/administration-bundle/changing-settings.md
> +- [Authentication](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Authentication) in the {{< openapi >}} for details on managing authentication via REST.
```suggestion
- [Authentication](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#section/Authentication) in the {{< openapi >}} for details on managing authentication via REST.
```

2022-07-28 20:43 UTC, manasesjesus commented on content/users-guide/administration-bundle/data-retention.md
> +- [Retention](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Retention) in the {{< openapi >}} for details on managing retention rules via REST.
```suggestion
- [Retention rules](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Retention-rules) in the {{< openapi >}} for details on managing retention rules via REST.
```

2022-07-28 20:43 UTC, manasesjesus commented on content/users-guide/administration-bundle/tfa.md
> +- [Authentication](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Authentication) in the {{< openapi >}} for details on managing authentication via REST.
```suggestion
- [Authentication](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#section/Authentication) in the {{< openapi >}} for details on managing authentication via REST.
```

2022-08-01 10:29 UTC, manasesjesus approved these changes
links to the OpenAPI are looking good

2022-08-09 14:30 UTC, MWindel approved these changes

2022-08-09 14:32 UTC, rssag approved these changes

2023-03-08 08:51 UTC, BeateRixen commented
@Airdroplet Hi Jarek, we would like to add some "related topics" at the top of each chapter to guide the users to other places of interest in the documentation. I have already added what I found useful but perhaps you have some more/better ideas? Could you please review and comment if you think we should add links? Thanks!

2023-03-08 09:54 UTC, BeateRixen commented
> @Airdroplet Hi Jarek, we would like to add some "related topics" at the top of each chapter to guide the users to other places of interest in the documentation. I have already added what I found useful but perhaps you have some more/better ideas? Could you please review and comment if you think we should add links? Thanks!

https://cumulocity.atlassian.net/browse/MTM-44131 This is the ticket, which is assigned to me. Let me know if I should create a subtask for you or someone else from your team?

2023-03-15 08:38 UTC, Airdroplet approved these changes

2023-03-15 12:46 UTC, BeateRixen commented on content/users-guide/administration-bundle/business-rules.md
> +- [Alarms](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Alarms) in the {{< openapi >}} for details on managing alarms via REST.
```suggestion
- [Alarms](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Alarms) in the {{< openapi >}} for details on managing alarms via REST.
```

2023-03-15 12:46 UTC, BeateRixen commented on content/users-guide/administration-bundle/changing-settings.md
> +- [Authentication](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#section/Authentication) in the {{< openapi >}} for details on managing authentication via REST.
```suggestion
- [Authentication](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#section/Authentication) in the {{< openapi >}} for details on managing authentication via REST.
```

2023-03-15 12:46 UTC, BeateRixen commented on content/users-guide/administration-bundle/data-retention.md
> +- [Retention rules](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Retention-rules) in the {{< openapi >}} for details on managing retention rules via REST.
```suggestion
- [Retention rules](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Retention-rules) in the {{< openapi >}} for details on managing retention rules via REST.
```

2023-03-15 12:46 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-applications.md
> +- [Applications](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Applications) in the {{< openapi >}} for managing applications via REST.
```suggestion
- [Applications](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Applications) in the {{< openapi >}} for managing applications via REST.
```

2023-03-15 12:46 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-microservices.md
> +- [Applications](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Applications) in the {{< openapi >}} for managing applications via REST.
```suggestion
- [Applications](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Applications) in the {{< openapi >}} for managing applications via REST.
```

2023-03-15 12:46 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-permissions.md
> +- [Roles](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Roles) and [Inventory Roles](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Inventory-Roles) in the {{< open
```suggestion
- [Roles](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Roles) and [Inventory Roles](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Inventory-Roles) in the {{< openapi >}} for managing permissions via REST.
```

2023-03-15 12:46 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-users.md
> +- [Users](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#tag/Users) in the {{< openapi >}} for managing users via REST.
```suggestion
- [Users](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#tag/Users) in the {{< openapi >}} for managing users via REST.
```

2023-03-15 12:46 UTC, BeateRixen commented on content/users-guide/administration-bundle/tfa.md
> +- [Authentication](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#section/Authentication) in the {{< openapi >}} for details on managing authentication via REST.
```suggestion
- [Authentication](https://{{< domain-c8y >}}/api/core/{{< c8y-current-version >}}/#section/Authentication) in the {{< openapi >}} for details on managing authentication via REST.
```

2023-03-15 14:36 UTC, rssag approved these changes

2023-03-15 14:38 UTC, MWindel approved these changes

2023-03-22 10:44 UTC, merged