MTM-46186: Clarify messaging release support
SoftwareAG/c8y-docs pull request #553
Opened 2022-08-08 14:42 UTC by sagscmi

Clarify in which releases the Messaging Service and features built on it are available.  Will unfortunately need to be grafted back as far as 10.11.

2022-08-08 15:45 UTC, BeateRixen commented on content/users-guide/enterprise-tenant-bundle/ms-data-broker.md
> +For the shared public cloud instances of the {{< product-c8y-iot >}} platform, the Messaging Service is enabled by default on release 10.13 and above, and the microservice-based data broker can be en
```suggestion
For the shared public cloud instances of the {{< product-c8y-iot >}} platform, the Messaging Service is enabled by default on release 10.13 and above, and the microservice-based data broker can be enabled on reqeust for individual tenants that already have access to the original data broker.
```

2022-08-08 16:09 UTC, gapa-c8y requested changes

2022-08-08 16:09 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +To receive notifications over the Notifications 2.0 protocol, an application or microservice must subscribe to notifications, either for notifications about a particular managed object or in a wider
```suggestion
To receive notifications over the Notifications 2.0 protocol, an application or microservice must subscribe to notifications, either for notifications about a particular managed object or in a wider context that is scoped to a tenant. Subscriptions are persistent, long lived, and allow notifications to be stored reliably until consumed and acknowledged by a consuming microservice or application.
```

2022-08-09 07:45 UTC, BeateRixen commented on content/reference/notifications-bundle/overview.md
> +{{< c8y-admon-info >}}
@sagscmi Would it make sense to use the "requirements" admonition here {{< c8y-admon-req >}} and further below? As this is what it is about, isn´t it?
{{< c8y-admon-req >}}

2022-08-09 08:38 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +{{< c8y-admon-info >}}
@BeateRixen Yes that makes sense, I will make the change in both files.  I actually didn't know that tag existed, and I didn't want to use the `important` admonition, which seemed a bit too aggressive.

2022-08-09 08:50 UTC, BeateRixen approved these changes

2022-08-09 11:38 UTC, gapa-c8y approved these changes

2022-08-09 12:17 UTC, merged