first draft of Proof of Possession's documentation
SoftwareAG/c8y-docs pull request #569
Opened 2022-08-19 11:59 UTC by vfo-softwareag

2022-08-19 13:53 UTC, rssag requested changes

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +### Perform Proof Of Possession
```suggestion
### Perform a proof of possession
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +Why and for what do I need Proof Of Possession?
```suggestion
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +The Cumulocity Platform uses X.509 certificates to authenticate end devices. The certificates used there work with a so-called chain of trust, which means, that one can create further trustworthy sub
```suggestion
The Cumulocity IoT platform uses X.509 certificates to authenticate end devices.
The certificates work with a chain of trust: you can create trustworthy subcertificates with a trusted certificate.
Each certificate consists of a public and a private part.
Also see asymmetric encryption.
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +The Cumulocity Platform receives the public part of each certificate that is to be used for device authentication. The assignment of the device to a tenant is also done by the certificate, since each
```suggestion
The Cumulocity IoT platform receives the public part of each certificate that is to be used for device authentication.
The assignment of the device to a tenant is also done by the certificate, since each certificate must be uniquely assigned.
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +However, since the public part of a certificate (and the sub certificates) is not secret, potentially every Internet user worldwide has access to it. This makes it possible for a potential attacker t
```suggestion
However, since the public part of a certificate (and the subcertificates) is not secret, anyone on the internet theoretically has access to it.
A potential attacker could upload the public part of a certificate to the Cumulocity IoT platform even if he does not have access to the private part of the certificate (thus not being the owner of the certificate).
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +To ensure a verification of ownership by the uploader, a Proof Of Possession is required by the platform.
```suggestion
To ensure verification of ownership by the uploader, a proof of possession is required by the platform.
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +The sub-steps for this are as follows:
```suggestion
The steps for the proof of possession are as follows:
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +- Upload of the certificate to the platform
```suggestion
- Upload of the certificate to the platform,
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +- Download of the Unsigned Key
```suggestion
- Download of the unsigned key,
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +- Encryption of the Unsigned Key by the certificate owner (which thereby becomes a Signed Key)
```suggestion
- Encryption of the unsigned key by the certificate owner, which makes the key a signed key,
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +- Proof of Possession is confirmed if the uploaded signed key matches the signed key expected by the platform.
```suggestion
- The proof of possession is confirmed if the uploaded signed key matches the signed key expected by the platform.
```

2022-08-19 13:53 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +- Upload of the signed key to the platform
```suggestion
- Upload of the signed key to the platform,
```

2022-08-19 13:54 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +Also see asymmetric encryption.
This looks like it's supposed to link somewhere. Where?

2022-08-25 09:30 UTC, vfo-softwareag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +Also see asymmetric encryption.
Hi Richard. What I want to say is: "Google the internet for asymmetric encryption."
(I know that we can't write it like that)
How did you solve something like that in the past? We cannot link e.g. Wikipedia in our documentation, but the user need at least a basic knowledge about ass asymmetric encryption to understand what is goin' on.

2022-08-25 09:33 UTC, vfo-softwareag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +Also see asymmetric encryption.
B.t.w.: UI-Screenshots are also missing right now, due to the not finished implementation of it.

2022-08-30 10:41 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +Also see asymmetric encryption.
is there some other source of information we can recommend besides wikipedia?

2022-10-06 09:49 UTC, Michal-Bak commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +The Cumulocity IoT platform uses X.509 certificates to authenticate end devices.
The Cumulocity IoT - > {{< product-c8y-iot >}}

2022-10-06 09:49 UTC, Michal-Bak commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +The Cumulocity IoT platform receives the public part of each certificate that is to be used for device authentication.
The Cumulocity IoT - > {{< product-c8y-iot >}}

2022-10-06 09:49 UTC, Michal-Bak commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +- Upload of the certificate to the platform,
Not sure if it is a step for the proof of possession? 
Maybe:
The steps for performing proof of possession for the uploaded certificate are as follows:
- Download...

2022-10-06 11:05 UTC, vfo-softwareag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +The Cumulocity IoT platform uses X.509 certificates to authenticate end devices.
fixed

2022-10-06 11:05 UTC, vfo-softwareag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +The Cumulocity IoT platform receives the public part of each certificate that is to be used for device authentication.
fixed

2022-10-20 11:52 UTC, rssag commented
is this still on hold? as there has been recent activity @vfo-softwareag

2022-10-27 07:22 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +If the maximum chain length for your dedicated installation is changed, we strongly recommend using the proof of possession feature to protect your service from DOS attacks.
```suggestion
If you change the maximum chain length for your dedicated installation, we strongly recommend you to use the proof of possession feature to protect your service from DOS attacks.
```

2022-10-27 07:22 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
>  However, this behaviour can be changed for dedicated installations by changing a platform wide configuration setting and increasing the allowed maximum length of the chain of certificates to more tha
```suggestion
However, you can change this behavior for dedicated installations by changing a platform wide configuration setting and increasing the allowed maximum length of the chain of certificates to more than 2.
```

2022-10-27 07:22 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +Also see asymmetric encryption.
what would work best is a site that has some form of reputation in the field. i'm not even against wikipedia that much, since it's widely accepted nowadays and has pretty good (well, arguably good) quality assurance. we should definitely include some pointer where the reader can find more information if we don't provide it here.

2022-10-27 08:42 UTC, vfo-softwareag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +Also see asymmetric encryption.
ok. I will add a link to Wikipedia. (at least for now)

2022-10-27 15:12 UTC, rssag commented on content/device-sdk/mqtt-bundle/device-certificates.md
> +Also see asymmetric encryption: https://en.wikipedia.org/wiki/Public-key_cryptography
```suggestion
Also see [asymmetric encryption](https://en.wikipedia.org/wiki/Public-key_cryptography).
```

2022-10-27 15:13 UTC, rssag approved these changes
one suggestion for the link + approval

2022-10-27 16:16 UTC, vfo-softwareag commented
> this is also for 10.16.0, right?

Afaik it is for 10.16.0 only

2022-10-27 16:37 UTC, rssag commented
> > this is also for 10.16.0, right?
> 
> Afaik it is for 10.16.0 only

oh. because in august we apparently added 10.13.0 to 10.15.0 labels. and the "on hold" label. can i remove those?

2022-10-27 16:40 UTC, vfo-softwareag commented
> > > this is also for 10.16.0, right?
> > 
> > 
> > Afaik it is for 10.16.0 only
> 
> oh. because in august we apparently added 10.13.0 to 10.15.0 labels. and the "on hold" label. can i remove those?
I think so. But let me double check it with the team

2022-10-28 17:08 UTC, vfo-softwareag commented
> > > > this is also for 10.16.0, right?
> > > 
> > > 
> > > Afaik it is for 10.16.0 only
> > 
> > 
> > oh. because in august we apparently added 10.13.0 to 10.15.0 labels. and the "on hold" label. can i remove those?
> 
> I think so. But let me double check it with the team

The remaining versions should be 10.15 and 10.16.

2022-11-21 15:25 UTC, rssag approved these changes

2022-12-02 09:50 UTC, sarangovindarajan approved these changes

2022-12-02 09:52 UTC, vfo-softwareag commented
Documentation for Proof Of Possession added.

2022-12-02 09:53 UTC, merged