MTM-47846: doc: first cut of pulsar and databroker install guide
SoftwareAG/c8y-docs pull request #603
Opened 2022-09-01 15:25 UTC by ianfairman-sg

Pulsar and data broker install guide for Edge. The first paragraph (the overview) is lifted direct from Gary's group overview document.

Outstanding issues:

- Need to sort out putting bundle on Empower server.
- Need consistent naming of databroker (or "data broker", "DataBroker", etc.)

2022-09-02 10:05 UTC, sagscmi commented on content/edge/databroker.md
> +title: Installing Pulsar & Databroker on Edge
One very general initial comment that applies in a lot of places - we should talk about the "Messaging Service" (rather than "Pulsar") and the  "Microservice-based Data broker" (vs. the legacy one that still exists) at least in the chapter titles and when introducing the concepts.  We don't hide the fact that the Messaging Service is mostly Pulsar but we should use the "marketing" name for the capability wherever possible.

2022-09-02 10:18 UTC, sagscmi requested changes
First round review.

2022-09-02 10:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +sudo kubectl get pods -A
Should show some expected sample output here.

2022-09-02 10:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +The key pods that should be running are the pulsar bookie, pulsar broker, pulsar zookeeper and databroker agent server. It may take a few minutes for the kubernetes pods to settle into a Running stat
As a "for more information" point we should reference the Messaging operations guide which has a reasonably comprehensive troubleshooting section.  Unfortunately you can't link to it directly but you can name the guide and the section within it.

2022-09-02 10:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +Using SCP, copy the bundle to the /tmp directory on the Edge server - you will need to enter the password for the Edge Linux admin account (management tenant) when prompted.
Can we give an example command line, probably with placeholders like the one below?

2022-09-02 10:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +Data broker is an optional component of {{< product-c8y-iot >}} Edge. The data broker is a {{< product-c8y-iot >}} feature that allows a {{< product-c8y-iot >}} Tenant to send data in motion (live me
Good intro, should probably also include a reference to the microservice-based data broker documentation in the user guide.

2022-09-02 10:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +Data broker is an optional component of {{< product-c8y-iot >}} Edge. The data broker is a {{< product-c8y-iot >}} feature that allows a {{< product-c8y-iot >}} Tenant to send data in motion (live me
The doc team will know for sure but I don't know if "Tenant" should always be capitalised like that?

2022-09-02 10:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +ssh <ADMIN_USERNAME>@<DNS_NAME_OF_SERVER> -t "/bin/bash -c 'cd /tmp && sudo /opt/c8y/utilities/install_signed_package.sh/tmp/<BUNDLE_NAME>"
```suggestion
ssh <ADMIN_USERNAME>@<DNS_NAME_OF_SERVER> -t "/bin/bash -c 'cd /tmp && sudo /opt/c8y/utilities/install_signed_package.sh /tmp/<BUNDLE_NAME>"
```

2022-09-02 10:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +The key pods that should be running are the pulsar bookie, pulsar broker, pulsar zookeeper and databroker agent server. It may take a few minutes for the kubernetes pods to settle into a Running stat
Are there any common/likely failure cases of our script that we should cover here?

2022-09-07 11:20 UTC, gapa-c8y commented on content/edge/databroker-bundle/databroker-edge.md
> +Data broker is an optional component of {{< product-c8y-iot >}} Edge. The data broker is a {{< product-c8y-iot >}} feature that allows a {{< product-c8y-iot >}} Tenant to send data in motion (live me
A little bit uncomfortable with saying 'The other, second Tenant can be within the same Cumulocity IoT instance or ...' as on the Edge there should only be one (non-management) tenant. I know I write that, but it was for the general case.

Maybe we can simply remove that sentence - seems to read just as well without it

2022-09-07 11:23 UTC, gapa-c8y commented on content/edge/databroker-bundle/databroker-edge.md
> +Using SCP, copy the bundle to the /tmp directory on the Edge server - you will need to enter the password for the Edge Linux admin account (management tenant) when prompted.
The linux admin account password is not same as the management tenant password (it may have the same value for us and many others to reduce password overload).

I might be wrong (I might be confused by the password overload), but if not, we should remove '(management tenant)' from the sentence.

2022-09-07 11:30 UTC, gapa-c8y commented on content/edge/databroker-bundle/databroker-edge.md
> +Using SCP, copy the bundle to the /tmp directory on the Edge server - you will need to enter the password for the Edge Linux admin account (management tenant) when prompted.
.. maybe referring to it as the 'Edge Linux admin account' doesn't help separate these user concepts; 'admin' is the usual username of the Cumulocity 'empowered user' for a tenant, so using that term when referring to the empowered linux user muddies things.
 Not sure what alternative to suggest, maybe 'Edge Linux login account' or 'Edge Linux host administrative login account'. Maybe they're a bit convoluted

2022-09-08 10:16 UTC, gapa-c8y commented on content/edge/databroker-bundle/databroker-edge.md
> +substituting the relevant values of `<ADMIN_USERNAME>`, `<DNS_NAME_OF_SERVER>` and `<BUNDLE_NAME>`. You will need to enter the Edge Linux admin account password again followed by the Cumulocity admin
If we do change the term 'Linux admin credentials' then we have two more case here; one here and one below on the line starting 'To confirm Pulsar ...'

2022-09-08 10:18 UTC, gapa-c8y requested changes
I think we must NOT say the tenant can be in the same Cumulocity IoT instance as that is not the case for Edge.
Other comments I am open to disagreement and/or better suggestions

2022-09-09 12:09 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +The key pods that should be running are the pulsar bookie, pulsar broker, pulsar zookeeper and databroker agent server. It may take a few minutes for the kubernetes pods to settle into a Running stat
I can't find this - do you have a link.

2022-09-09 12:12 UTC, ianfairman-sg commented on content/edge/databroker.md
> +title: Installing Pulsar & Databroker on Edge
I've made these changes.

2022-09-09 12:14 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +Data broker is an optional component of {{< product-c8y-iot >}} Edge. The data broker is a {{< product-c8y-iot >}} feature that allows a {{< product-c8y-iot >}} Tenant to send data in motion (live me
I know what you mean - it doesn't seem to be quite right.

2022-09-09 12:18 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +ssh <ADMIN_USERNAME>@<DNS_NAME_OF_SERVER> -t "/bin/bash -c 'cd /tmp && sudo /opt/c8y/utilities/install_signed_package.sh/tmp/<BUNDLE_NAME>"
Good spot!

2022-09-09 12:23 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +The key pods that should be running are the pulsar bookie, pulsar broker, pulsar zookeeper and databroker agent server. It may take a few minutes for the kubernetes pods to settle into a Running stat
I can't think of much. Because of the file sizes involved, it's not difficult to run out of disk space, although that's more of a problem for the host VM rather than the child VM.

2022-09-09 12:37 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +Using SCP, copy the bundle to the /tmp directory on the Edge server - you will need to enter the password for the Edge Linux admin account (management tenant) when prompted.
I often have to think about which account I am using. I've made some changes that will hopefully make this clearer.

2022-09-09 12:43 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +substituting the relevant values of `<ADMIN_USERNAME>`, `<DNS_NAME_OF_SERVER>` and `<BUNDLE_NAME>`. You will need to enter the Edge Linux admin account password again followed by the Cumulocity admin
I've re-ordered some of these paragraphs to address an earlier issue and also made some changes to the text to address this.

2022-09-09 14:35 UTC, gapa-c8y commented on content/edge/databroker-bundle/databroker-edge.md
> +Using SCP, copy the bundle to the /tmp directory on the Edge server - you will need to enter the password for the Edge Linux admin account (management tenant) when prompted.
Great (I get confused too - and no matter what we do, it's a easy place to get confused as there are too many users in play in Edge).

I'll take a re-read ...

2022-09-09 14:39 UTC, gapa-c8y commented on content/edge/databroker-bundle/databroker-edge.md
> +Data broker is an optional component of {{< product-c8y-iot >}} Edge. The data broker is a {{< product-c8y-iot >}} feature that allows a {{< product-c8y-iot >}} Tenant to send data in motion (live me
Sorry, I resolved this comment too soon (you haven't pushed) - I'll leave this until I've seen the change (hence unresolved)

2022-09-09 15:27 UTC, gapa-c8y commented on content/edge/databroker-bundle/databroker-edge.md
> +Using SCP, copy the bundle to the /tmp directory on the Edge server - you will need to enter the password for the Edge Linux admin account (management tenant) when prompted.
'Edge Linux administrative/login account' is much clear, but maybe one (I suggest) the simpler one below is nicer, i.e.; 'Edge Linux admin account'. 

It just seems neater, but is clearly the Linux login

2022-09-09 15:28 UTC, gapa-c8y commented on content/edge/databroker-bundle/databroker-edge.md
> +substituting the relevant values of `<ADMIN_USERNAME>`, `<DNS_NAME_OF_SERVER>` and `<BUNDLE_NAME>`. You will need to enter the Edge Linux admin account password again followed by the Cumulocity admin
Thanks. I prefer the term you updated to here to the one above (as in comment above)

2022-09-12 18:32 UTC, sag-tjegorow commented on content/edge/databroker-bundle/databroker-edge.md
> +[THIS NEEDS UPDATING WHEN THE DATA BROKER STARTS INSTALLING AGAIN]
From my Edge VM with working databroker:
```
[root@iot-edge-server admin]# kubectl get pods -A
NAMESPACE                NAME                                                             READY   STATUS      RESTARTS   AGE
c8y-messaging-service    pulsar-bookie-0                                                  1/1     Running     0          11h
c8y-messaging-service    pulsar-bookie-init-zptcn                                         0/1     Completed   0          11h
c8y-messaging-service    pulsar-broker-0                                                  1/1     Running     0          11h
c8y-messaging-service    pulsar-pulsar-init-7fg9v                                         0/1     Completed   0          11h
c8y-messaging-service    pulsar-zookeeper-0                                               1/1     Running     0          11h
calico-system            calico-kube-controllers-5ddcc6fc8f-wh246                         1/1     Running     0          11h
calico-system            calico-node-gwwjh                                                1/1     Running     0          11h
calico-system            calico-typha-59d77bd956-4dtwn                                    1/1     Running     0          11h
cumulocity-single-node   databroker-agent-server-scope-edge-deployment-6b58b84c6f-rrsln   0/1     Running     3          11h
cumulocity-single-node   device-simulator-scope-management-deployment-8bf49bff7-cwxjq     1/1     Running     0          11h
cumulocity-single-node   kube-registry-persistent-secure-69fbcb8b6d-tqf92                 1/1     Running     0          11h
kube-system              coredns-74ff55c5b-7lnkt                                          1/1     Running     0          11h
kube-system              etcd-localhost                                                   1/1     Running     0          11h
kube-system              kube-apiserver-localhost                                         1/1     Running     0          11h
kube-system              kube-controller-manager-localhost                                1/1     Running     0          11h
kube-system              kube-proxy-zbvnd                                                 1/1     Running     0          11h
kube-system              kube-scheduler-localhost                                         1/1     Running     0          11h
kube-system              metrics-server-5b78d5f9c6-7zcx9                                  1/1     Running     1          11h
tigera-operator          tigera-operator-76bbbcbc85-4wvcf                                 1/1     Running     1          11h
```

2022-09-23 15:59 UTC, sagscmi commented
@bbyreddy Bhaskar, please add whoever from the Edge team should review these doc changes.

2022-09-23 16:12 UTC, gapa-c8y approved these changes

2022-09-23 16:18 UTC, sagscmi requested changes
Lots of suggested changes.  Made the naming of the data broker consistent with the user guide and added some "further information" links.  Also see the suggestion to highlight the resource requirements in a "Requirements" block - the extra RAM need is too easy to miss otherwise.

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +For more information see the [Messaging Reference Guide](https://cumulocity.com/guides/reference/notifications/).
```suggestion
For more information on installing and troubleshooting the Messaging Service see the "Messaging Service Installation & operations guide", part of the Cumulocity IoT Platform documentation set available from https://documentation.softwareag.com/ (Software AG Empower login required).
For more information on configuring and using the microservice-based data broker, see the [Microservice-based data broker](https://cumulocity.com/guides/users-guide/enterprise-tenant/#ms-data-broker) section of the Cumulocity user guide.
```

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +The key pods that should be running are the pulsar bookie, pulsar broker, pulsar zookeeper and databroker agent server. It may take a few minutes for the kubernetes pods to settle into a Running stat
See suggested change below...

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +The key pods that should be running are the pulsar bookie, pulsar broker, pulsar zookeeper and databroker agent server. It may take a few minutes for the kubernetes pods to settle into a Running stat
See comment above about the system requirements.

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +You need to ensure that microservices are enabled for Edge as both the Messaging Service and Data broker run as Kubernetes pods. Running microservices on a basic Edge install requires the number of C
Maybe worth highlighting this in a `{{< c8y-admon-req >}}` Requirements block?  See https://github.com/SoftwareAG/c8y-docs/pull/553/files for an example of the syntax.

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/index.html
> +title: Installing the Messaging Service & the Microservices-Based Databroker
```suggestion
title: Installing the Messaging Service & the microservice-based data broker
```

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker.md
> +title: Installing the Messaging Service & the Microservices-Based Databroker on Edge
```suggestion
title: Installing the Messaging Service & the microservice-based data broker on Edge
```

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +title: Installing the Messaging Service and the Microservice-based Data broker on Edge
```suggestion
title: Installing the Messaging Service and the microservice-based data broker on Edge
```

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +The Microservice-based Data broker is an optional component of {{< product-c8y-iot >}} Edge. The data broker is a {{< product-c8y-iot >}} feature that allows a {{< product-c8y-iot >}} tenant to send
```suggestion
The microservice-based data broker is an optional component of {{< product-c8y-iot >}} Edge. The data broker is a {{< product-c8y-iot >}} feature that allows a {{< product-c8y-iot >}} tenant to send data in motion (live measurements, events and alarms), using the standard {{< product-c8y-iot >}} REST API requests, to another tenant as that data arrives in the first tenant. It is often used to 'ship' data from remote Edge {{< product-c8y-iot >}} instances in the field to a central {{< product-c8y-iot >}} instance, where all data from all remote 'field' locations can be seen and handled together. Another use case may be where devices are leased; the devices are managed by the leasing company in its tenant, and the devices' measurements, etc. are sent, via a data broker connection, onto the leasing tenant for application data processing.
```

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +The bundle for installing the Messaging Service and the Microservice-based Data broker comes as a .tgz file which contains the Messaging Service and Data broker files, an install script and a digital
```suggestion
The bundle for installing the Messaging Service and the microservice-based data broker comes as a `.tgz` file which contains the Messaging Service and data broker files, an install script and a digital signature. This bundle is unpacked, the signature verified and the install script executed by another script that is part of the standard Edge install. The bundle can be downloaded from the [Software AG Empower server](https://empower.softwareag.com/). The bundle is named "Cumulocity IoT Data Broker Edge".
```

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +You need to ensure that microservices are enabled for Edge as both the Messaging Service and Data broker run as Kubernetes pods. Running microservices on a basic Edge install requires the number of C
```suggestion
You need to ensure that microservices are enabled for Edge as both the Messaging Service and data broker run as Kubernetes pods. Running microservices on a basic Edge install requires the number of CPU cores to be increased from 2 to 4 and the RAM to be increased from 6GB to 8GB. Running the Messaging Service and data broker requires an extra 4GB of RAM on top of this.
```

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +To confirm the Messaging Service and Data broker are now running, log into the Edge VM using ssh with the connection details used previously and run:
```suggestion
To confirm the Messaging Service and data broker are now running, log into the Edge VM using ssh with the connection details used previously and run:
```

2022-09-23 16:18 UTC, sagscmi commented on content/edge/databroker-bundle/databroker-edge.md
> +The key pods that should be running are the pulsar bookie, pulsar broker, pulsar zookeeper and databroker agent server. It may take a few minutes for the kubernetes pods to settle into a Running stat
```suggestion
The key pods that should be running are the `pulsar-bookie-0`, `pulsar-broker-0`, `pulsar-zookeeper-0` and `databroker-agent-server` (with an installation-specific suffix on the pod name). It may take a few minutes for the Kubernetes pods to settle into a Running state after the install has been done.
```

2022-09-28 10:01 UTC, sagscmi approved these changes
All good from my side but I still want approval from @bbyreddy and the Edge team before we merge this.

2022-10-04 15:53 UTC, bbyreddy reviewed
Hi @ianfairman-sg,
I added some minor suggestions, please check.

Thanks!

2022-10-04 15:53 UTC, bbyreddy commented on content/edge/databroker-bundle/databroker-edge.md
> +scp C:\Temp\<BUNDLE_NAME> "<LOGIN_USERNAME>@<DNS_NAME_OF_SERVER>:/tmp/<BUNDLE_NAME>"
- [ ] I suggest we replace the BUNDLE_NAME with the exact name of the tar file. Like databroker-edge.tar. 
- [ ] And also not refer to C:\Temp.
- [ ] The destination of scp need not point to a specific file, as omitting the filename from the destination location copies the file with the original name.

2022-10-04 15:53 UTC, bbyreddy commented on content/edge/databroker-bundle/databroker-edge.md
> +You need to ensure that microservices are enabled for Edge as both the Messaging Service and data broker run as Kubernetes pods. Running microservices on a basic Edge install requires the number of C
- [ ] Edge refers to enabling microservices as "enabling microservice hosting feature"
- [ ] Provide a link to the corresponding section of the documentation https://cumulocity.com/guides/edge/configuration/#configuring-microservices

2022-10-04 15:53 UTC, bbyreddy commented on content/edge/databroker-bundle/databroker-edge.md
> +ssh <LOGIN_USERNAME>@<DNS_NAME_OF_SERVER> -t "/bin/bash -c 'cd /tmp && sudo /opt/c8y/utilities/install_signed_package.sh /tmp/<BUNDLE_NAME>"
- [ ] Would it be simpler if we split this into two steps?
       1. SSH into edge `ssh <LOGIN_USERNAME>@<DNS_NAME_OF_SERVER>`
       2. run the script `sudo /opt/c8y/utilities/install_signed_package.sh /tmp/<BUNDLE_NAME>`

2022-10-04 15:53 UTC, bbyreddy commented on content/edge/databroker-bundle/databroker-edge.md
> +tigera-operator          tigera-operator-76bbbcbc85-6clrf                                 1/1     Running     0          82m```
- [ ] Extra ``` characters at the end of the line.

2022-10-05 08:29 UTC, rssag requested changes

2022-10-05 08:29 UTC, rssag commented on content/edge/databroker-bundle/databroker-edge.md
> +You will need to enter the Edge Linux admin account password again followed by the Cumulocity admin account password.
```suggestion
Enter the Edge Linux admin account password, again followed by the {{< product-c8y-iot >}} admin account password.
```

2022-10-05 08:29 UTC, rssag commented on content/edge/databroker-bundle/databroker-edge.md
> +To confirm the Messaging Service and data broker are now running, log into the Edge VM using ssh with the connection details used previously and run:
```suggestion
To confirm the Messaging Service and data broker are now running, log into the Edge VM using SSH with the connection details used previously and run:
```

2022-10-05 08:29 UTC, rssag commented on content/edge/databroker-bundle/databroker-edge.md
> +Which should return something like this:
```suggestion
The command returns something like this:
```

2022-10-05 08:29 UTC, rssag commented on content/edge/databroker.md
> +title: Installing the Messaging Service & the Microservices-Based Databroker on Edge
```suggestion
title: Installing the Messaging Service and the microservices-based data broker on Edge
```

2022-10-05 08:29 UTC, rssag commented on content/edge/databroker-bundle/index.html
> +title: Installing the Messaging Service & the Microservices-Based Databroker
```suggestion
title: Installing the Messaging Service and the microservices-based data broker on Edge
```

2022-10-05 08:29 UTC, rssag commented on content/edge/databroker-bundle/databroker-edge.md
> +The key pods that should be running are the `pulsar-bookie-0`, `pulsar-broker-0`, `pulsar-zookeeper-0` and `databroker-agent-server` (with an installation-specific suffix on the pod name). It may tak
```suggestion
The key pods that should be running are `pulsar-bookie-0`, `pulsar-broker-0`, `pulsar-zookeeper-0` and `databroker-agent-server`, with a suffix for the pod name specific to the installation. It may take a few minutes for the Kubernetes pods to settle into a running state after the installation has finished.
```

2022-10-05 08:29 UTC, rssag commented on content/edge/databroker-bundle/databroker-edge.md
> +For more information on installing and troubleshooting the Messaging Service see the "Messaging Service Installation & operations guide", part of the Cumulocity IoT Platform documentation set availab
```suggestion
For more information on installing and troubleshooting the Messaging Service see the *Messaging Service Installation & operations guide*.
```

2022-10-05 08:29 UTC, rssag commented on content/edge/databroker-bundle/databroker-edge.md
> +For more information on configuring and using the microservice-based data broker, see the [Microservice-based data broker](https://cumulocity.com/guides/users-guide/enterprise-tenant/#ms-data-broker)
```suggestion
For more information on configuring and using the microservice-based data broker, see [Enterprise tenant > Microservice-based data broker](/users-guide/enterprise-tenant/#ms-data-broker) in the *User guide*.
```

2022-10-05 11:02 UTC, sagscmi approved these changes

2022-10-05 11:02 UTC, sagscmi commented on content/edge/databroker-bundle/index.html
> +title: Installing the Messaging Service & the Microservices-Based Databroker
Should also be "microservice-based" not "microservices-based" (there is only one microservice involved)

2022-10-05 11:02 UTC, sagscmi commented on content/edge/databroker.md
> +title: Installing the Messaging Service & the Microservices-Based Databroker on Edge
Should also be "microservice-based" not "microservices-based" (there is only one microservice involved)

2022-10-05 11:20 UTC, rssag commented on content/edge/databroker.md
> +title: Installing the Messaging Service & the Microservices-Based Databroker on Edge
updated the suggestion

2022-10-05 11:20 UTC, rssag commented on content/edge/databroker-bundle/index.html
> +title: Installing the Messaging Service & the Microservices-Based Databroker
updated the suggestion

2022-10-05 15:30 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +ssh <LOGIN_USERNAME>@<DNS_NAME_OF_SERVER> -t "/bin/bash -c 'cd /tmp && sudo /opt/c8y/utilities/install_signed_package.sh /tmp/<BUNDLE_NAME>"
I decided not to change this as this command has been tested a lot. If you really don't like it I will change it.

2022-10-05 15:31 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +The microservice-based data broker is an optional component of {{< product-c8y-iot >}} Edge. The data broker is a {{< product-c8y-iot >}} feature that allows a {{< product-c8y-iot >}} tenant to send
Changed.

2022-10-05 15:31 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +You need to ensure that microservices are enabled for Edge as both the Messaging Service and data broker run as Kubernetes pods. Running microservices on a basic Edge install requires the number of C
Changed.

2022-10-05 15:33 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +Using SCP, copy the bundle to the /tmp directory on the Edge server - you will need to enter the password for the Edge Linux administrative/login account when prompted. For Example:
Changed.

2022-10-05 15:42 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +For more information on configuring and using the microservice-based data broker, see the [Microservice-based data broker](https://cumulocity.com/guides/users-guide/enterprise-tenant/#ms-data-broker)
Changed.

2022-10-05 16:02 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +You will need to enter the Edge Linux admin account password again followed by the Cumulocity admin account password.
Chnaged.

2022-10-05 16:03 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +To confirm the Messaging Service and data broker are now running, log into the Edge VM using ssh with the connection details used previously and run:
Changed.

2022-10-05 16:04 UTC, ianfairman-sg commented on content/edge/databroker.md
> +title: Installing the Messaging Service & the Microservices-Based Databroker on Edge
Changed.

2022-10-05 16:05 UTC, ianfairman-sg commented on content/edge/databroker-bundle/databroker-edge.md
> +The key pods that should be running are the `pulsar-bookie-0`, `pulsar-broker-0`, `pulsar-zookeeper-0` and `databroker-agent-server` (with an installation-specific suffix on the pod name). It may tak
Changed.

2022-10-06 07:56 UTC, bbyreddy approved these changes

2022-10-06 07:56 UTC, bbyreddy commented on content/edge/databroker-bundle/databroker-edge.md
> +ssh <LOGIN_USERNAME>@<DNS_NAME_OF_SERVER> -t "/bin/bash -c 'cd /tmp && sudo /opt/c8y/utilities/install_signed_package.sh /tmp/<BUNDLE_NAME>"
No problem. Thanks!

2022-10-07 16:16 UTC, sagscmi approved these changes
One more instance of "microservices-based" changed to "microservice-based".

2022-10-07 16:16 UTC, sagscmi commented on content/edge/databroker.md
> +title: Installing the Messaging Service and the microservices-based data broker on Edge
```suggestion
title: Installing the Messaging Service and the microservice-based data broker on Edge
```

2022-10-07 16:34 UTC, sagscmi commented
@rssag I think all your comments have been addressed - I've just gone through and resolved 12+ conversations :-)  If you're OK with the changes I think we're just waiting for your approval to get this merged - thanks!

2022-10-10 10:25 UTC, rssag approved these changes

2022-10-10 12:37 UTC, merged