DM-818 Documentation for Loriot Downlink Support
SoftwareAG/c8y-docs pull request #616
Opened 2022-09-19 14:20 UTC by ashhSAG93

2022-09-19 16:47 UTC, rssag requested changes

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/loriot-overview.md
> +* Configure the Loriot agent endpoint in LORIOT Network Server using {{< product-c8y-iot >}} data forwarder or create a Loriot LNS Connection and register the device in Cumulocity.
```suggestion
* Configure the Loriot agent endpoint in LORIOT Network Server using {{< product-c8y-iot >}} data forwarder or create a Loriot LNS connection and register the device in {{< product-c8y-iot >}}. 
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +title: Configure the Loriot agent endpoint credentials and register the devices via Cumulocity
this title is three lines in the navigation. can it be shortened?

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +If you select **Connectivity** for the first time, you are asked to create a connection. Click **Add Connection**.
```suggestion
When you select **Connectivity** for the first time, you are asked to create a connection. Click **Add Connection**.
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +- **Base URL**: The URL associated with the Loriot Provider account.
```suggestion
- **Base URL**: The URL associated with the Loriot provider account.
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +Click **Save**. If you have entered the correct information, you see the message "Connection created".
```suggestion
Click **Save**. If the information you have entered is correct, the message "Connection created" appears.
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +Note: Always keep the **Gateway Information** option enabled because the Loriot agent only processes "gw" (gateway information) messages.
```suggestion
{{< c8y-admon-info >}}
Always keep the **Gateway Information** option enabled because the Loriot agent only processes "gw" (gateway information) messages.
{{< /c8y-admon-info >}}
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +If there are devices associated with the connection, an error message will appear, stating "Can not update the LNS Connection with `<name of LNS Connection>` as it's associated with `<number of devic
```suggestion
If there are devices associated with the connection, an error message appears, stating "Can not update the LNS Connection with `<name of LNS Connection>` as it's associated with `<number of devices>`. Click the link to download the file with the details of the associated devices: `/service/<agent-context-path>/lns-connection/<lns-connection-name>/device`".
```
there's a mistake in the error message, but i guess we cannot fix it here? (Can not -> Cannot)

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +If there are devices associated with the connection, an error message will appear, stating "Can not delete the LNS Connection with `<name of LNS Connection>` as it's associated with `<number of devic
```suggestion
If there are devices associated with the connection, an error message appears, stating "Can not delete the LNS Connection with `<name of LNS Connection>` as it's associated with `<number of devices>`. Click the link to download the file with the details of the associated devices: `/service/<agent-context-path>/lns-connection/<lns-connection-name>/device`".
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +POST {{url}}/service/loriot/newDeviceRequest
```suggestion
POST <kbd>{{url}}/service/loriot/newDeviceRequest</kbd>
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +The body of the POST Request is as shown below:
```suggestion
The body of the POST request:
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +title: Configure the Loriot agent endpoint credentials via the Loriot Network Server and register devices on receiving uplink messages
this title is four lines long in the navigation. can it be shortened?

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +### <a name="map-loriot-endpoint-with-credentials">Configuring the Loriot endpoint using Basic authentication</a>
```suggestion
<a name="map-loriot-endpoint-with-credentials">
### Configuring the Loriot endpoint using basic authentication</a>
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +## <a name="loriot-device-registration">Loriot device registration via API</a>
```suggestion
<a name="loriot-device-registration">
### Loriot device registration via API</a>
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +## <a name="cumulocity-loriot-connection-configuration">Creation of Loriot LNS Connection in Cumulocity</a>
```suggestion
<a name="cumulocity-loriot-connection-configuration">
### Creation of Loriot LNS Connection in Cumulocity</a>
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +### To add a new connection
```suggestion
#### To add a new connection
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +### To update a connection
```suggestion
#### To update a connection
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +### To delete a connection
```suggestion
#### To delete a connection
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +Use {{< product-c8y-iot >}} data forwarder for configuring the Loriot endpoint using Basic authentication.
```suggestion
Use {{< product-c8y-iot >}} data forwarder for configuring the Loriot endpoint using basic authentication.
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +The Loriot devices can now be registered in Cumulocity when uplink messages are received.
```suggestion
The Loriot devices can now be registered in {{< product-c8y-iot >}} when uplink messages are received. 
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +## <a name="uplink-message-device-creation">Device Creation via Loriot Uplink Message</a>
```suggestion
<a name="uplink-message-device-creation">
### Device creation via Loriot uplink message</a>
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +While processing the Loriot LoRa device request, the Loriot agent automatically creates the device in the {{< product-c8y-iot >}} platform, if it does not yet exist. This means that the user does not
```suggestion
While processing the Loriot LoRa device request, the Loriot agent automatically creates the device in the {{< product-c8y-iot >}} platform, if it does not yet exist.
This means that you do not need to register the Loriot LoRa device explicitly.
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +all gateway information.
```suggestion
The Loriot LoRa agent only processes "gw" messages to avoid duplicate measurements or events in {{< product-c8y-iot >}}, because most of the information matches with "gw" message whereas "gw" message also carries all gateway information.
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +In the below Loriot LoRa device message `gws` represents a list of gateways involved in the network.
```suggestion
In the Loriot LoRa device message below, `gws` represents a list of gateways involved in the network:
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +The Loriot LoRa agent maps the `rssi` value to the standard {{< product-c8y-iot >}}  SignalStrength object and updates the device managed object with the `lat` and `lon` values.
```suggestion
The Loriot LoRa agent maps the `rssi` value to the standard {{< product-c8y-iot >}} `SignalStrength` object and updates the device managed object with the `lat` and `lon` values.
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +The device registered with the EUI above, must be re-registered via the provided Cumulocity API (see [Configure the Loriot agent endpoint credentials and register the devices via Cumulocity](#configu
```suggestion
The device registered with the EUI above, must be re-registered via the provided {{< product-c8y-iot >}} API (see [Configure the Loriot agent endpoint credentials and register the devices via Cumulocity](#configure-loriot-credentials-cumulocity)), to be associated with an LNS Connection and a particular device type, in order to be able to send downlink messages
```

is "EUI" meant to be "UI"?

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/operations-loriot.md
> +If a Loriot device supports receiving hexadecimal commands, you can send them using shell operations. Notice that these commands are not serial monitor commands.
```suggestion
If a Loriot device supports hexadecimal commands, you can send them using shell operations. Notice that these commands are not serial monitor commands.
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/operations-loriot.md
> +In the following screenshot you can find some examples of a device protocol's predefined commands and their format.
```suggestion
In the following screenshot you can find some examples of a device protocol's predefined commands and their format:
```

2022-09-19 16:47 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/operations-loriot.md
> +Click **Execute**. The operation will be sent to the device. The timing depends on Loriot Platform.
```suggestion
Click **Execute**. The operation will be sent to the device. The timing depends on Loriot platform.
```

2022-09-20 02:10 UTC, ashhSAG93 commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +The device registered with the EUI above, must be re-registered via the provided Cumulocity API (see [Configure the Loriot agent endpoint credentials and register the devices via Cumulocity](#configu
No it is meant to be EUI.

2022-09-20 02:12 UTC, ashhSAG93 commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +title: Configure the Loriot agent endpoint credentials and register the devices via Cumulocity
Will try to shorten it

2022-09-20 02:16 UTC, ashhSAG93 commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +title: Configure the Loriot agent endpoint credentials via the Loriot Network Server and register devices on receiving uplink messages
Yes will try to shorten it

2022-09-20 10:03 UTC, ashhSAG93 commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +title: Configure the Loriot agent endpoint credentials and register the devices via Cumulocity
Shortened now

2022-09-20 10:09 UTC, miryalarahul commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +title: Endpoint configuration and device registration via uplink message
Endpoint configuration and device registration-->Device registration via uplink message

2022-09-20 10:11 UTC, ashhSAG93 commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +title: Endpoint configuration and device registration via uplink message
Have made the changes

2022-09-20 10:16 UTC, miryalarahul commented on content/protocol-integration/lora-loriot-bundle/loriot-overview.md
> +* Configure the Loriot agent endpoint in LORIOT Network Server using {{< product-c8y-iot >}} data forwarder or create a Loriot LNS connection and register the device in {{< product-c8y-iot >}}.
We can register a device directly from Cumulocity which allows the user to perform the downlink. The agent also support automatic registers which doesn't have an option to of downlink.   Modify it to mention two way its possible and one has the limitation

2022-09-20 10:16 UTC, miryalarahul commented on content/protocol-integration/lora-loriot-bundle/operations-loriot.md
> +title: Sending operations
Keep this title in synch with other agents

2022-09-20 10:21 UTC, ashhSAG93 commented on content/protocol-integration/lora-loriot-bundle/operations-loriot.md
> +title: Sending operations
Its in sync with the other agents

2022-09-20 13:49 UTC, rssag requested changes

2022-09-20 13:49 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +title: Device registration via Cumulocity
```suggestion
title: Device registration via Cumulocity IoT
```

2022-09-20 13:49 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +title: Device Registration via uplink message
```suggestion
title: Device registration via uplink message
```

2022-09-20 13:49 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-register-network-server.md
> +In order to be able to send downlink operations, the devices registered via uplink message must be re-registered using Cumulocity (see [Device registration via Cumulocity](#configure-loriot-credentia
```suggestion
In order to be able to send downlink operations, the devices registered via uplink message must be re-registered using {{< product-c8y-iot >}} (see [Device registration via Cumulocity IoT](#configure-loriot-credentials-cumulocity)), to be associated with a connection and a device type.
```

2022-09-20 13:49 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/loriot-overview.md
> +  - Configure the Loriot Agent Endpoint via Loriot Network Server and register the device via uplink message. In order to be able to send downlink messages, the devices created using this method need
```suggestion
* Register the device in two ways:
  - Create a Loriot LNS connection and register the device using {{< product-c8y-iot >}}.
  - Configure the Loriot Agent endpoint via Loriot Network Server and register the device via uplink message. In order to be able to send downlink messages, the devices created using this method need to be re-registered via {{< product-c8y-iot >}} to be associated with a connection and device type.  
```

2022-09-21 06:45 UTC, miryalarahul approved these changes

2022-09-21 07:02 UTC, rssag commented
which releases does this apply to?

2022-09-21 07:02 UTC, rssag approved these changes

2022-09-21 10:06 UTC, ashhSAG93 commented
> which releases does this apply to?

Only 10.16

2022-09-21 10:07 UTC, merged