[DM-1424]: Changed user guide configuration docs for getting setting config on a device + screenshots.
SoftwareAG/c8y-docs pull request #625
Opened 2022-10-04 15:42 UTC by dafkk

https://user-images.githubusercontent.com/92030501/193864310-c4a485ea-c0c9-4b9e-82fd-86646243bb25.mov

2022-10-05 09:24 UTC, dafkk commented on content/users-guide/device-management-bundle/managing-device-data.md
> +Typed file-based configurations are the recomended way of hadnling configurations on a device. Here devices can manage multiple configurations at the same time. For different types different configur
What I mean is that the typed file-based config handles the files through events that are responsible for the clean up later if device is deleted by themselves and the legacy one uses binary upload. But maybe I need to put it more clear I will think of another way to put it.

2022-10-05 10:46 UTC, rssag requested changes

2022-10-05 10:46 UTC, rssag commented on content/users-guide/device-management-bundle/managing-device-data.md
> +The managing of configurations from and to a device can be done in multiple ways. Depending on user permissions and settings of the device user may be able to work with text based, typed file-based a
```suggestion
Managing configurations from and to a device can be done in multiple ways. Depending on user permissions and device settings, you can work with text based, typed file-based or legacy file-based configuration. Refer to [Device management library > Configuration](/reference/device-management-library/#configuration) in the *Reference guide* for more detailed and technical information.
```

additional question: what does "configurations from and to a device" mean exactly?

2022-10-05 10:46 UTC, rssag commented on content/users-guide/device-management-bundle/managing-device-data.md
> +#### To retrieve and apply a configuration snapshot to a device which supports typed file-based configurations
```suggestion
#### To retrieve and apply a configuration snapshot to a device which supports typed file-based configuration
```

2022-10-05 10:46 UTC, rssag commented on content/users-guide/device-management-bundle/managing-device-data.md
> +Typed file-based configurations are the recomended way of hadnling configurations on a device. Here devices can manage multiple configurations at the same time. For different types different configur
```suggestion
We recommend you to use typed file-based configuration. With typed file-based configuration, devices can manage multiple configurations at the same time. You can upload or retrieve different configurations for different types. The file communication is also updated with this approach and handled in a more efficient way.
```

2022-10-05 10:46 UTC, rssag commented on content/users-guide/device-management-bundle/managing-device-data.md
> +#### To retrieve and apply a configuration snapshot to a device which supports legacy file-based configurations
```suggestion
#### To retrieve and apply a configuration snapshot to a device which supports legacy file-based configuration
```

2022-10-05 10:46 UTC, rssag commented on content/users-guide/device-management-bundle/managing-device-data.md
> +Devices that want to manage configuration as files can achieve a basic form using legacy file-based configuration. This way only allows one configuration to be set per a device.
```suggestion
Devices managing configuration as files can do so in a basic form using legacy file-based configuration. Legacy file-based configuration only allows a single configuration to be set per a device.
```

2022-10-05 14:00 UTC, dafkk commented on content/users-guide/device-management-bundle/managing-device-data.md
> +The managing of configurations from and to a device can be done in multiple ways. Depending on user permissions and settings of the device user may be able to work with text based, typed file-based a
Means sending a configuration to a device and requesting a configuration from a device. Basically managing configurations on devices.

2022-10-05 14:29 UTC, rssag commented on content/users-guide/device-management-bundle/managing-device-data.md
> +The managing of configurations from and to a device can be done in multiple ways. Depending on user permissions and settings of the device user may be able to work with text based, typed file-based a
ok, i added that to the suggestion

2022-10-05 14:35 UTC, rssag commented on content/users-guide/device-management-bundle/managing-device-data.md
> +We recommend you to use typed file-based configuration. With typed file-based configuration, devices can manage multiple configurations at the same time. You can upload or retrieve different configur
```suggestion
We recommend you to use typed file-based configuration. With typed file-based configuration, devices can manage multiple configurations at the same time. You can upload or retrieve different configurations for different types. Using this approach is more versatile because the configurations are handled as events rather than as files, which is more efficient.

2022-10-10 07:54 UTC, bozhidardedov approved these changes

2022-10-10 11:53 UTC, rssag approved these changes

2022-10-11 15:31 UTC, rssag commented
to which releases does this apply?

2022-10-12 15:09 UTC, dafkk commented
> to which releases does this apply?

Amm I guess when new configuration types were introduced so that would make it 10.7

2022-10-13 07:31 UTC, merged

2022-10-13 13:05 UTC, dafkk commented
> hm... since we're not even at 10.16.0 yet - i think it was merged too early (since we usually create the next release version from develop, which would be 10.16.0). i'll double-check with @BeateRixen on monday. We can take care of the revert and the new PR, that we can park until 10.17.0 then. Just a heads-up for now :)

Not 10.17, the changes were missing from 10.7 release up till now.

2022-10-17 16:25 UTC, rssag commented
compromise - i cherry-picked it to 10.15.0 and 10.14.0, below that i ran into conflicts. so i'd say we settle for these versions