MTM-45799 add generic information about inventory roles improvements
SoftwareAG/c8y-docs pull request #628
Opened 2022-10-07 11:08 UTC by jkot-softwareag

I will create separate PRs to previous releases after this one will be reviewed and language adjusted. 

The reasoning is that part of changes were introduced in 10.13 (MEA), 10.14 (Inventory), and now in 10.16 (Operations, default algorithm changed to new one).

2022-10-07 12:26 UTC, karolkaczmarski-sag commented on content/users-guide/administration-bundle/managing-permissions.md
> +### Performance improvements
This is great improvement, but I'm not convinced that user documentation is right place to announce that since X.Y version something works better - this should be announced via other channels (release notes, demo, tech forum, trainings etc).
From UI point of view nothing has changed and after few more c8y versions this information will become meaningless.

2022-10-07 16:29 UTC, jkot-softwareag commented on content/users-guide/administration-bundle/managing-permissions.md
> +### Performance improvements
We have discussed this with Elena and @jaro-herod and idea was to have "something" in public docs accessible for all users, and more precise article with details and limitation on tech-forum.

I think it may be important from UI point of view that response time changes from 10-60s to 50-100ms for particular screens. We can have clients starting to use inventory roles after this change, and tech-forum article may be not obvious to find

2022-10-10 15:22 UTC, rssag requested changes

2022-10-10 15:22 UTC, rssag commented on content/users-guide/administration-bundle/managing-permissions.md
> +* All screens with aggregated alarm views from many devices, if number of alarms in the system is not big. Example screens: Cockpit > Home, Cockpit > Alarms, Device Management > Home
```suggestion
* Pages with aggregated alarm views from multiple devices, if the number of alarms in the system is low, for example [Cockpit > Home dashboard](/users-guide/cockpit/#home-dashboard), Cockpit > Alarms and Device Management > Home.
```

2022-10-10 15:22 UTC, rssag commented on content/users-guide/administration-bundle/managing-permissions.md
> +* Similar for screens with aggregated events and operations from many devices. Example screens: Device Management > Overviews > Events, Device Management > Overviews > Device control
```suggestion
* Pages with aggregated events and operations from multiple devices, for example Device Management > Overviews > Events and Device Management > Overviews > Device control.
```

2022-10-11 07:45 UTC, jkot-softwareag commented
Applied all suggestions from Richard

2022-10-11 08:55 UTC, rssag commented on content/users-guide/administration-bundle/managing-permissions.md
> +The following UI pages have an improved performance after updating to version 10.16:
here it says 10.16 now, but 10.13 above
is this intended?

2022-10-11 09:51 UTC, jkot-softwareag commented on content/users-guide/administration-bundle/managing-permissions.md
> +The following UI pages have an improved performance after updating to version 10.16:
Yes. The situation looks like this: 
* improvements have started in 10.13, and it was covering MEA Apis
* in 10.14 there were added improvements for Inventory ("All devices" page)
in both versions this was behind the feature flag (by default OFF)
* in 10.16 there were added improvements for Operations (merged), and changing feature flag to ON (approved)

So I want to prepare different PRs for each version respectively, after this one is approved. 

Maybe we can change 10.16 to _"after updating to current version"_ or _"have an improved performance in current version"_

2022-10-11 11:34 UTC, jkot-softwareag commented on content/users-guide/administration-bundle/managing-permissions.md
> +The following UI pages have an improved performance after updating to version 10.16:
yes, `.0` is not a problem. We can even add 0 to `10.13.0` to have it standard/similar in both places.

2022-10-11 12:56 UTC, pawel-rynarzewski-sag commented on content/users-guide/administration-bundle/managing-permissions.md
> +The following UI pages have an improved performance after updating to version 10.16:
Maybe it's just me, but as this is for docs and you already emphasized when the improvements started and what was the most recent one, maybe it would make sense to list what was introduced in the versions over time (like you did in the comment above).
When preparing PRs for earlier versions, you can just skip paragraphs/points about the newer ones.

2022-10-11 13:43 UTC, jkot-softwareag commented on content/users-guide/administration-bundle/managing-permissions.md
> +The following UI pages have an improved performance after updating to version 10.16:
does it work properly, or is hardcoded to 10.11.0 now?
I changed locally text to `after updating to version {{< c8y-current-version >}}` and I see on hugo preview `10.11.0`

2022-10-11 15:42 UTC, rssag commented on content/users-guide/administration-bundle/managing-permissions.md
> +The following UI pages have an improved performance after updating to version 10.16:
it is maintained in every release branch (but apparently not in develop :D)

2022-10-12 08:34 UTC, jkot-softwareag commented on content/users-guide/administration-bundle/managing-permissions.md
> +The following UI pages have an improved performance after updating to version 10.16:
We can decide what is better for this public docs. The more detailed description will be pushed to tech-forum based on the document I shared for review.
I was thinking to start with the note that improvements started in 10.13, and then for each release write not the delta from previous but sum of all improvements which are accessible in "current" version (MEA in 10.13; MEA+Inventory in 10.14&10.15, all in 10.16)

But if you guys think that it is better to mention all changes with versions in which those were introduced - we can do it this way.

2022-10-13 11:03 UTC, jkot-softwareag commented on content/users-guide/administration-bundle/managing-permissions.md
> +The following UI pages have an improved performance after updating to version 10.16:
we have agreed in team PlaMa to only put current version, and have cumulative information what has been improved. 
Each PR will have slightly changed text.

2022-10-13 12:41 UTC, pawel-rynarzewski-sag approved these changes

2022-10-13 15:20 UTC, rssag commented on content/users-guide/administration-bundle/managing-permissions.md
> +* Pages with aggregated events and operations from multiple devices, for example, Device Management > Overviews > Events and Device Management > Overviews > Device control.
those links would be:

```suggestion
* Pages with aggregated events and operations from multiple devices, for example, [Device Management > Monitoring and controlling devices > Troubleshooting devices > To view events](/users-guide/device-management/#to-view-events) and [Device Management > Monitoring and controlling devices > Working with operations](/users-guide/device-management/#working-with-operations).
```

2022-10-14 08:47 UTC, jkot-softwareag commented on content/users-guide/administration-bundle/managing-permissions.md
> +* Pages with aggregated events and operations from multiple devices, for example, Device Management > Overviews > Events and Device Management > Overviews > Device control.
Thanks for links Paweł, we will use them :).
Richard - Is it better to use documentation names like "Monitoring and controlling device" or UI names like "Overviews" ?
I prefer to see UI screens, but maybe in documentation there is a rule to always use doc pages titles/chapters

2022-10-14 09:14 UTC, Airdroplet approved these changes

2022-10-14 09:21 UTC, rssag commented on content/users-guide/administration-bundle/managing-permissions.md
> +* Pages with aggregated events and operations from multiple devices, for example, Device Management > Overviews > Events and Device Management > Overviews > Device control.
if we use doc links, we have a standard way of expressing paths to the section we link to.
if we are referring to UI views directly, i'd advise against using links if we don't have the exact view as a screenshot somewhere in the documentation.

your call, i'm fine with either. i think pawel suggested some places where aggregated events/operations also occur, but where we have infact a screenshot of the UI view.

2022-10-14 13:31 UTC, jkot-softwareag commented
Applied suggestions and links. Currently it looks following (10.11 will be resolved to 10.16.0 after releasing branch):
![image](https://user-images.githubusercontent.com/92089923/195859231-79c303c6-663a-4fe0-8c35-77d848fa3fd1.png)

2022-10-17 10:12 UTC, rssag approved these changes

2022-10-20 15:20 UTC, jkot-softwareag commented
I have changed order of paragraphs. UI preview now looks like in the screenshot below. Link to openApi for 10.16 is not working (yet). Probably text needs a bit of polishing

![image](https://user-images.githubusercontent.com/92089923/196989935-2a8b9c47-341b-437f-b0b7-921914d2ab02.png)

2022-10-21 07:05 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-permissions.md
> +The {{< product-c8y-iot >}} platform now has optimized UI performance for users with inventory roles access. In particular, requests for tenants with large inventory hierarchies are faster.
```suggestion
The {{< product-c8y-iot >}} platform provides optimized UI performance for users with inventory roles access. In particular, requests for tenants with large inventory hierarchies are faster.
```

2022-10-21 07:06 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-permissions.md
> +As an administrator, you can switch back to the previous solution and this improved performance feature will be disabled:
```suggestion
As an administrator, you can disable the performance feature:
```

2022-10-21 07:07 UTC, BeateRixen approved these changes

2022-10-21 07:32 UTC, merged