CIE-4177. Added topic for security hardening.
SoftwareAG/c8y-docs pull request #630
Opened 2022-10-07 16:22 UTC by sharath-jk

2022-10-10 11:50 UTC, rssag commented on content/edge/installation-bundle/edge-security-hardening.md
> +The Edge appliance is security hardened, by default. Furthermore, there are certain security configuration that you can apply to enhance the security of the Edge appliance. To apply the security conf
```suggestion

The Edge appliance is security hardened by default.
Furthermore, there are certain security configuration that you can apply to enhance the security of the Edge appliance. To apply the security configuration, see [Security configuration](/edge/configuration/#configuring-security). 
```

2022-10-10 11:51 UTC, rssag approved these changes

2022-10-10 16:50 UTC, rssag approved these changes

2022-10-10 17:28 UTC, sharath-jk commented on content/edge/installation-bundle/edge-security-hardening.md
> +Furthermore, there are certain security configurations that you can apply to enhance the security of the Edge appliance. To apply the security configuration, see [Security configuration](/edge/config
Done.

2022-10-10 18:00 UTC, bbyreddy approved these changes

2022-10-10 18:15 UTC, sharath-jk commented
@bbyreddy - I'll keep this PR open until we have the security hardening guide updated by Saran.

2022-10-10 18:16 UTC, rssag requested changes

2022-10-10 18:16 UTC, rssag commented on content/edge/configuration-bundle/configuring-security.md
> +    In the enforcing mode, you cannot access the Edge appliance remotely through VNC.<br>{{< /c8y-admon-important >}}<br>Default value: permissive
```suggestion
In the enforcing mode, you cannot access the Edge appliance remotely through VNC.
    {{< /c8y-admon-important >}}<br>Default value: permissive
```
indentation inside admonition blocks is rendered, unfortunately.

2022-10-10 18:16 UTC, rssag commented on content/edge/configuration-bundle/configuring-security.md
> +    Once enabled, you cannot disable the audit logging configuration.
```suggestion
Once enabled, you cannot disable the audit logging configuration.
```

2022-10-10 18:18 UTC, rssag commented on content/edge/configuration-bundle/configuring-security.md
> +{{< c8y-admon-important >}}For information about Deployment seurity best practices and Tenant administration security configuration guidelines, see <a href="/files/edge/10-13-0_Security_Hardening_Gui
```suggestion
{{< c8y-admon-important >}}
For information about deployment security best practices and tenant administration security configuration guidelines, see <a href="/files/edge/10-13-0_Security_Hardening_Guidelines_guide.pdf" target="_blank">Security Hardening Guidelines</a>.
{{< /c8y-admon-important >}}
```

2022-10-10 18:22 UTC, rssag approved these changes

2022-10-11 09:41 UTC, MWindel commented on content/edge/configuration-bundle/configuring-security.md
> +Furthermore, there are certain security configurations that you can apply to enhance the security of the Edge appliance.
```suggestion
Furthermore, you can apply specific security configurations to enhance the security of you Edge appliance.
```

2022-10-11 11:35 UTC, merged