[MTM-47904] New SSO access mapping configuration enabled
SoftwareAG/c8y-docs pull request #634
Opened 2022-10-13 08:05 UTC by Michal-Bak

Documentation for 10.16

2022-10-13 08:57 UTC, chbakar commented on content/users-guide/administration-bundle/changing-settings.md
The third option is not described

2022-10-13 10:02 UTC, chbakar approved these changes

2022-10-13 13:12 UTC, rssag requested changes

2022-10-13 13:12 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +By default, configuration for dynamic access mapping is selected: **Roles selected in the rules above will be reassigned to a user on each log in and other ones will be cleared** This means, that dyn
```suggestion
By default, the configuration for dynamic access mapping is selected: **Roles selected in the rules above will be reassigned to a user on each log in and other ones will be cleared**.
This means that dynamic access mapping assigns user roles, based on the access token, on every user login.
It is not possible to change the user roles inside {{< product-c8y-iot >}} as they would be overwritten on the next user login.
```

2022-10-13 13:12 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +  * When selected, dynamic access mapping will be used on every login, but the roles not listed in the access mapping configuration will not be updated. Only the roles that are listed in the defined
```suggestion

* **Use dynamic access mapping only on user creation**

  When selected, dynamic access mapping will be used only when a new user logs in to fill in the initial roles. When a user already exists in {{< product-c8y-iot >}}, the roles will not be overwritten nor updated.
  
* **Roles selected in the rules above will be reassigned to a user on each log in and other ones will be unchanged**

  When selected, dynamic access mapping will be used on every login, but the roles not listed in the access mapping configuration will not be updated. Only the roles that are listed in the defined access mapping rules will be overwritten.
```

(blank lines and indentation are needed for the correct line breaks)

2022-10-13 13:12 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +Selecting one of the two options mentioned above will also enable admins to edit roles of SSO users in the user management. For details, refer to  [Administration > Managing permissions](/users-guide
```suggestion
Selecting one of the two options mentioned above will also enable admins to edit roles of SSO users in the user management. For details, refer to [Administration > Managing permissions](/users-guide/administration/#attach-global) in the *User guide*.
```

2022-10-18 08:47 UTC, Michal-Bak commented
@rssag  Can you re-review?

2022-10-18 12:06 UTC, rssag approved these changes

2022-10-18 12:17 UTC, merged