MTM-48465 - documenation for tenant sso configuration access
SoftwareAG/c8y-docs pull request #635
Opened 2022-10-13 11:06 UTC by chbakar

documented tenant SSO configuration access

2022-10-13 12:42 UTC, rssag requested changes

2022-10-13 12:42 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +Users of such tenants will be unable to update the configuration. This removes the risk of an incorrectly configured SSO, which can prevent other users from login via SSO.
```suggestion
Users of such tenants are unable to update the configuration. This removes the risk of an incorrectly configured SSO, which can prevent other users from logging in via SSO.
```

2022-10-13 12:42 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +Click the **Single sign-on** tab (this tab is only shown for tenants which have access to the SSO configuration) in the **Authentication** page.
```suggestion
Click the **Single sign-on** tab in the **Authentication** page.
Note that the tab is only visible for tenants which have access to the SSO configuration. 
```

2022-10-13 13:22 UTC, rssag approved these changes

2022-10-13 13:22 UTC, rssag commented
which releases does this apply to?

2022-10-13 13:26 UTC, chbakar commented
> which releases does this apply to?

10.16

2022-10-14 09:29 UTC, Michal-Bak approved these changes

2022-10-17 15:34 UTC, BeateRixen approved these changes

2022-10-20 08:53 UTC, Michal-Bak approved these changes

2022-10-20 08:55 UTC, rssag commented on content/users-guide/administration-bundle/changing-settings.md
> +The {{< management-tenant >}} can grant or restrict access to SSO configurations for specific tenants. For more information about configuration access, please refer to the [Login options API](https:/
```suggestion
The {{< management-tenant >}} can grant or restrict access to SSO configurations for specific tenants. For more information about configuration access, refer to the [Login options API](https://{{< domain-c8y >}}/api/{{< c8y-current-version >}}/#operation/putAccessLoginOptionResource) in the {{< openapi >}}.
```

2022-10-20 08:55 UTC, rssag approved these changes

2022-10-20 08:59 UTC, merged