MTM-45799 add generic information about inventory roles improvements for 10.14
SoftwareAG/c8y-docs pull request #637
Opened 2022-10-14 17:07 UTC by jkot-softwareag

PR based on https://github.com/SoftwareAG/c8y-docs/pull/628, but with scope of information what is done till 10.14 (and 10.15 since there were no changes between those)

Preview from local hugo:

![image](https://user-images.githubusercontent.com/92089923/195903005-154fcdae-ec20-42c2-a82a-e0d513221e66.png)

2022-10-17 06:09 UTC, pawelkowalczyksag approved these changes

2022-10-17 10:23 UTC, rssag commented
when this is merged, should it be cherry-picked to release/r10.15.0 as well?

2022-10-17 10:23 UTC, rssag approved these changes

2022-10-17 10:40 UTC, rssag requested changes

2022-10-17 10:40 UTC, rssag commented on content/users-guide/administration-bundle/managing-permissions.md
> +New approach is disabled by default and needs to be switched on the tenant level using tenant option (see the Release notes for details).
```suggestion
The improvements are disabled by default in version {{< c8y-current-version >}}. Activate them on the tenant level by using the tenant option. See the relevant [release notes entry]() for details.
```
suggestion is incomplete. Also, I think we should add the explanation here as well then, since it's rather the other way around - release notes will link to the detailed explanation, not vice versa.

2022-10-17 10:57 UTC, jkot-softwareag commented on content/users-guide/administration-bundle/managing-permissions.md
> +New approach is disabled by default and needs to be switched on the tenant level using tenant option (see the Release notes for details).
But this switch via tenant option is same as in 10.13, and we can only link to previous Release Notes, since 10.14 RN will not mention it. https://cumulocity.com/releasenotes/release-10-13-0/whatsnew-10-13-0/ this is mentioned in the other PR, for 10.13:
https://github.com/SoftwareAG/c8y-docs/pull/636. 
I think we should not mention tenant option here in the documentation, since this part is on the different level of abstracion.

2022-10-17 11:01 UTC, rssag commented on content/users-guide/administration-bundle/managing-permissions.md
> +New approach is disabled by default and needs to be switched on the tenant level using tenant option (see the Release notes for details).
alright then. updated the suggestion with an anchor for the subsection

2022-10-17 11:08 UTC, jkot-softwareag commented on content/users-guide/administration-bundle/managing-permissions.md
> +New approach is disabled by default and needs to be switched on the tenant level using tenant option (see the Release notes for details).
commited :+1:

2022-10-17 12:26 UTC, pawel-rynarzewski-sag approved these changes

2022-10-17 12:26 UTC, rssag approved these changes

2022-10-17 13:36 UTC, rssag reviewed
@BeateRixen

2022-10-18 08:30 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-permissions.md
> +### Performance improvements
@jkot-softwareag Same here. I don´t think that is makes sense to add this section to the documentation. Stating performance improvements in the release notes is the right place. It is of no value for users here.

2022-10-19 14:36 UTC, jkot-softwareag commented on content/users-guide/administration-bundle/managing-permissions.md
> +### Performance improvements
I will push here changes similar to https://github.com/SoftwareAG/c8y-docs/pull/636 in single commit.

2022-10-19 14:39 UTC, jkot-softwareag commented
Screenshot from current version is below. The only thing which may need correction is link to OpenAPI which points to version 10.13. The main difference from 10.13 is that also some pages related to inventory (devices) are now also optimized.

![image](https://user-images.githubusercontent.com/92089923/196722460-3faac549-349d-41ff-a9a8-c47619a364e9.png)

2022-10-20 09:54 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-permissions.md
> +The option looks like the following in the REST API (see also the [{{< openapi >}}](https://cumulocity.com/api/10.13.0/#operation/postOptionCollectionResource)):
```suggestion
The option looks like the following in the REST API (see also the [{{< openapi >}}](https://cumulocity.com/api/10.14.0/#operation/postOptionCollectionResource)):
```

2022-10-20 09:54 UTC, BeateRixen approved these changes

2022-10-20 09:54 UTC, BeateRixen commented
@jkot-softwareag I have changed the OpenAPi version. Would you want to add anything about the additional improvements?

2022-10-20 09:58 UTC, jkot-softwareag commented
> @jkot-softwareag I have changed the OpenAPi version. Would you want to add anything about the additional improvements?

Thanks @BeateRixen :+1: , nothing to add, in my opinion this is ready to merge.

2022-10-20 09:59 UTC, merged