Loriot Device Registration - Modify documentation to include UI changes
SoftwareAG/c8y-docs pull request #640
Opened 2022-10-21 01:57 UTC by ashhSAG93

2022-10-21 05:06 UTC, miryalarahul approved these changes

2022-10-21 08:43 UTC, rssag requested changes

2022-10-21 08:43 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +- **Title** Title of the device to be registered
```suggestion
- **Title** Title of the device to be registered.
```

2022-10-21 08:43 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +- **Device EUI** This is the unique identifier for the device. It is a 16 character (8 byte) long hexadecimal number. You can find it on the device itself.
is this always the case? (the EUI being on the device)

2022-10-21 08:43 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +- **Connection** Lists all configured Loriot connections in the tenant. The following Application name option is populated based on the selected Loriot connection
```suggestion
- **Connection** Lists all configured Loriot connections in the tenant. The **Application name** option (see below) is populated based on the selected Loriot connection.
```

2022-10-21 08:43 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +- **Application name** Select the appropriate application name under which the device needs to be registered in the Loriot provider
```suggestion
- **Application name** Select the appropriate application name under which the device must be registered in the Loriot provider.
```

2022-10-21 08:43 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +You can verify that the device is really connected by checking that events are actually coming in. You can do so by clicking on a device and opening its **Events** tab. All events related to this dev
```suggestion
You can verify that the device is connected by incoming events. Click on a device and open its **Events** tab. All events related to this device are listed.
```

2022-10-21 08:43 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +For more information on viewing and managing your connected devices, also refer to [Device Management](/users-guide/device-management/).
```suggestion
For more information on viewing and managing your connected devices, also refer to [Device Management](/users-guide/device-management/) in the *User guide*.
```

2022-10-21 08:43 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +In order to migrate the device from one LNS connection to another, the device needs to be re-registered.
```suggestion
In order to migrate the device from one LNS connection to another, the device must be re-registered:
```

2022-10-21 08:43 UTC, rssag commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +The user is directed to the device registration page where he can perform the re-registration following the steps above and selecting the desired LNS connection.
```suggestion

1. Navigate to the **LPWAN** tab of the Device.
2. Click the **Provider connection** dropdown.
3. A prompt will appear stating that in order to migrate the device from one LNS connection to another, you must re-register the device. Click the **Re-Register** button.
4. You are directed to the device registration page where you can perform the re-registration following the steps above and selecting the desired LNS connection. 
```

2022-10-21 09:08 UTC, ashhSAG93 commented on content/protocol-integration/lora-loriot-bundle/configure-loriot-credentials-cumulocity.md
> +- **Device EUI** This is the unique identifier for the device. It is a 16 character (8 byte) long hexadecimal number. You can find it on the device itself.
Yes

2022-10-26 08:49 UTC, rssag approved these changes

2022-10-26 08:49 UTC, rssag commented
to which releases does this apply? @ashhSAG93

2022-10-26 08:55 UTC, ashhSAG93 commented
> to which releases does this apply? @ashhSAG93

10.16

2022-10-26 08:55 UTC, merged