DM-1271 Updated Software section in Device Management Library chapter in Reference guide after changes to Advanced Software Management
SoftwareAG/c8y-docs pull request #661
Opened 2022-11-06 20:57 UTC by MaciekSoftwareAG

… in Reference guide after changes to Advanced Software Management

2022-11-07 08:15 UTC, rssag requested changes

2022-11-07 08:15 UTC, rssag commented on content/reference/device-management-library-bundle/software.md
> +In this approach the `c8y_SoftwareList` fragment is placed in the single child addition of type`c8y_InstalledSoftwareList`.
```suggestion
Using the "advanced" approach, the `c8y_SoftwareList` fragment is placed in the single child addition of type `c8y_InstalledSoftwareList`.
```

2022-11-07 08:15 UTC, rssag commented on content/reference/device-management-library-bundle/software.md
> +[microservice](https://cumulocity.com/guides/concepts/applications/#microservices) was introduced.
```suggestion
To facilitate the management of listed software packages, the Advanced Software Management default [microservice](https://cumulocity.com/guides/concepts/applications/#microservices) was introduced.
```

2022-11-07 08:15 UTC, rssag commented on content/reference/device-management-library-bundle/software.md
>  Devices may indicate their support for Advanced Software Management by including the ```c8y_SoftwareUpdate``` operation
```suggestion
Devices support Advanced Software Management when they include the `c8y_SoftwareUpdate` operation
```

2022-11-07 08:15 UTC, rssag commented on content/reference/device-management-library-bundle/software.md
>  the ```c8y_SupportedSoftwareTypes``` fragment.
```suggestion
in their `c8y_SupportedOperations` fragment and list their supported software types in the `c8y_SupportedSoftwareTypes` fragment.
```

2022-11-07 09:58 UTC, MaciekSoftwareAG commented on content/reference/device-management-library-bundle/software.md
> +and the second *advanced*.
I named it "legacy", but I don't thing there is strong encouraging to use "advanced" approach.

2022-11-07 14:59 UTC, rssag commented
to which releases does this apply?

2022-11-07 14:59 UTC, rssag approved these changes

2022-11-09 16:18 UTC, l2p- requested changes

2022-11-09 16:18 UTC, l2p- commented on content/reference/device-management-library-bundle/software.md
> +To facilitate the management of listed software packages, the Advanced Software Management default [microservice](https://cumulocity.com/guides/concepts/applications/#microservices) was introduced.
We should not be pointing users to the data model on the inventory API. I'd describe it like this:
```suggestion
Using the "advanced" approach, the `c8y_SoftwareList` fragment is is no longer present in the device managed object. The data is separated from the device managed object which keeps the size of the device managed object low even for very large lists of installed software. All installed software for a device can be read and managed through the Advanced Software Management default [microservice](https://cumulocity.com/guides/concepts/applications/#microservices).
```

2022-11-14 17:51 UTC, MaciekSoftwareAG commented on content/reference/device-management-library-bundle/software.md
> +To facilitate the management of listed software packages, the Advanced Software Management default [microservice](https://cumulocity.com/guides/concepts/applications/#microservices) was introduced.
Isn't the whole chapter pointing users to data model on the inventory API?

2022-11-30 09:16 UTC, l2p- commented on content/reference/device-management-library-bundle/software.md
> +To facilitate the management of listed software packages, the Advanced Software Management default [microservice](https://cumulocity.com/guides/concepts/applications/#microservices) was introduced.
The point of this documentation is to describe how device integrators can manage their installed software with the platform. In advanced software management this should always happen through the ASM microservice endpoints and never through the standard platform APIs. If there are other places in this chapter that point to inventory API the those need to be changed too.

2023-01-19 11:46 UTC, rssag commented
@MaciekSoftwareAG 
this is still missing a review by the team.
also which releases does it apply to?

2023-01-19 13:53 UTC, MaciekSoftwareAG commented
Yes, waiting for Philipp, he will be back next week. And he will know the release.

2023-01-26 13:58 UTC, l2p- approved these changes

2023-01-31 18:00 UTC, merged