Documentation changes for 10.16
SoftwareAG/c8y-docs pull request #665
Opened 2022-11-09 12:40 UTC by Vagdevi1998

2022-11-09 16:39 UTC, MWindel commented
Delete the screenshot. It does not contribute anything more to the documentation than is already described in the context.

2022-11-09 16:39 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/viewing-assets.md
> +You see a warning message if one or more properties assocaited with the asset is not present.
```suggestion
You see a warning message if one or more properties associated with the asset are not present.
```

2022-11-09 16:39 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/viewing-assets.md
> +![Asset Type Modification Warning](/images/dtm/assets/asset-type-modification-warning.png)
Remove the screenshot

2022-11-14 09:33 UTC, MWindel commented on content/dtm/asset-types-bundle/property-library.md
> +If selected, enter the allowed file types separated by a comma in the **Allowed file types** field. Provide the maximum file size for uploads **Max file size (MB)** field. When you create an asset wi
```suggestion
If selected, enter the allowed file types separated by a comma in the **Allowed file types** field. Provide the maximum file size for uploads in the **Max file size (MB)** field. When you create an asset with this custom property, you can only upload files of the allowed file types with a file size not exceeding the file size limit.
```

2022-11-14 12:38 UTC, MWindel commented on content/dtm/asset-types-bundle/property-library.md
> +2. In the resulting confirmation dialogue, click **Confirm** to continue the deletion or **Cancel** to cancel the deletion.
```suggestion
2. In the resulting confirmation dialogue, click **Confirm** to continue.

2022-11-16 09:15 UTC, MWindel approved these changes

2022-11-16 10:45 UTC, spau6 commented on content/dtm/asset-types-bundle/property-library.md
> +If selected, enter the allowed file types separated by a comma in the **Allowed file types** field. Provide the maximum file size for uploads in the **Max file size (MB)** field. When you create an a
We will display either "Max file size in MB" or "Max file size in MB ( Size limit on tenant: 1000 MB)"
Here 1000 MB is a dynamic value (file size for that tenant)
Please consider this change as part of the documentation

2022-11-18 03:53 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/property-library.md
> +If selected, enter the allowed file types separated by a comma in the **Allowed file types** field. Provide the maximum file size for uploads in the **Max file size (MB)** field. When you create an a
Modified the field name as per the implementation

2022-11-18 08:37 UTC, spau6 approved these changes

2022-11-18 15:13 UTC, MWindel commented on content/dtm/asset-types-bundle/property-library.md
> +If there is a file size limit set on the tenat, you see the limit in the label. For example: If the max file size set on tenant is 1 GB,the label looks like Max file size in MB ( Size limit on tenant
```suggestion
If there is a file size limit set for the tenat, you see the limit in the label. 
So if the maximum file size set for the tenant is 1 GB, the label states the maximum file size in MB, for example, 1024 MB.<br>
```

2022-11-21 07:13 UTC, MWindel commented
@Vagdevi1998 please incorporate the requested changes before merging.

2022-11-22 03:08 UTC, Vagdevi1998 commented on content/dtm/asset-types-bundle/property-library.md
> +If there is a file size limit set on the tenat, you see the limit in the label. For example: If the max file size set on tenant is 1 GB,the label looks like Max file size in MB ( Size limit on tenant
The field name will change as per the tenant options. Here Max file size in MB (size limit on tenant: 1024 MB) is the name of the field.

2022-11-22 09:37 UTC, lra-sag requested changes

2022-11-22 09:37 UTC, lra-sag commented on content/dtm/asset-types-bundle/asset-types.md
> +4. If this asset type is used by any asset, select **Confirm** in the resulting confirmation dialogue to continue saving your changes.
Please change the spelling of dialog

2022-11-22 09:37 UTC, lra-sag commented on content/dtm/asset-types-bundle/property-library.md
> +4. If this property is used by any asset type, in the resulting confirmation dialogue, select **Confirm** to continue to save your changes.
confirmation <s>dialogue</s> dialog

2022-11-22 09:37 UTC, lra-sag commented on content/dtm/asset-types-bundle/property-library.md
> +In the resulting confirmation dialogue, click **Confirm** to continue.
confirmation <s>dialogue</s> dialog

2022-11-22 09:37 UTC, lra-sag commented on content/dtm/asset-types-bundle/property-library.md
> +If the custom property you want to delete, is part of an existing asset, you see a error notification and the custom property is not deleted.
```suggestion
If the custom property you want to delete is part of an existing asset, you see a error notification and the custom property is not deleted.
```

2022-11-22 09:54 UTC, lra-sag approved these changes

2022-11-22 13:23 UTC, MWindel commented on content/dtm/asset-hierarchy-bundle/viewing-assets.md
> +2. In the resulting confirmation dialog, click **Confirm** to continue or **Cancel** to cancel the deletion.
```suggestion
In the following dialog box, click **Confirm** to continue.
```

2022-11-22 13:25 UTC, MWindel approved these changes

2022-11-23 10:03 UTC, merged