PAB-3484: Replace application_queue_full alarm with 3 new ones
SoftwareAG/c8y-docs pull request #681
Opened 2022-11-21 08:18 UTC by kailol-sag

2022-11-21 10:50 UTC, shrutidogra-23 commented on content/apama/troubleshooting-bundle/alarms.md
> +See the description for [The correlator input queue is full](#input_queue_full) for more details.
Should we also link the output_queue_full alarm here?

2022-11-21 11:28 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
> +See the description for [The correlator input queue is full](#input_queue_full) for more details.
No, I would not do this. The reason I added this link is that the user can also read all of the details that are only given for the first of these alarms on that page.

2022-11-21 15:03 UTC, shrutidogra-23 commented on content/apama/troubleshooting-bundle/alarms.md
> +See the description for [The correlator input queue is full](#input_queue_full) for more details.
ok

2022-11-21 15:04 UTC, shrutidogra-23 approved these changes

2022-11-21 16:17 UTC, rthrippleton requested changes
Wording currently being discussed on the code change PR - let's hold off merging this until that's settled.

2022-11-23 16:41 UTC, MWindel approved these changes

2022-11-23 18:57 UTC, rthrippleton requested changes

2022-11-23 18:57 UTC, rthrippleton commented on content/apama/troubleshooting-bundle/alarms.md
> +<a name="input_queue_full"></a>
Precise wording aside, because we potentially/eventually see all of these alarms at the same time, I'd like to tie them together a bit better, rather than treating them as four totally disjoint alarms (four includes the 'CEP' alarm).

For example, a single section covering the symptom as a whole. "Performance alarms" might make sense, which then includes mention of these alarms. Otherwise this is more of an encyclopedia than troubleshooting.

2022-11-24 10:09 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
> +<a name="input_queue_full"></a>
An additional heading would require one more indentation for the different alarms (heading from #### to #####). And if I'm to add this new "Performance alarms" heading (at ####), then we would also need one or more headings for the other alarms above them. So how would you group them and with which headings?

2022-11-24 11:55 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
> +<a name="input_queue_full"></a>
Shruti just explained this to me a bit more. So you want to have a single heading in the same way as done for https://cumulocity.com/guides/apama/troubleshooting/#apama_ctrl_fatalcritwarn - with no further subheadings. And you want to "smuggle" in the CEP alarm, also without a subheading. Is this what you want? Yeah, that's easy then.

2022-11-24 12:02 UTC, shrutidogra-23 commented on content/apama/troubleshooting-bundle/alarms.md
>  The correlator's input and output queues are periodically monitored to check for building up of events. If the pending queue size grows above the normal threshold (20,000 for the input queue and 10,0
We should remove the threshold values from the doc as they are arbitrary values

2022-11-24 12:59 UTC, rthrippleton commented on content/apama/troubleshooting-bundle/alarms.md
> +<a name="input_queue_full"></a>
Yeah, no subheadings really necessary. Just in general I'm keen for this but of the doc to be helpfully structured, rather than a pure rendering of what one sees in the alarm - the most important audience for this is somebody who's already seen the alarm, and needs a bit more comfort/advice.

2022-11-24 13:08 UTC, rthrippleton requested changes

2022-11-24 13:08 UTC, rthrippleton commented on content/apama/troubleshooting-bundle/alarms.md
> +  cannot process the requests at the rate at which they are arriving.
So this alarm contains a lot of technical details (and in fact, the other two do as well). While it may not be helpful for many users, if they do want to know more, a link to https://docbuilder1.eur.ad.sag/jenkins/job/pam/job/trunk-webhelp_en/lastSuccessfulBuild/artifact/out/webhelp/index.html#page/pam-webhelp%2Fre-DepAndManApaApp_list_of_correlator_status_statistics.html would serve well, as there's no way such text can be self-explanatory enough.

2022-11-24 13:26 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
>  The correlator's input and output queues are periodically monitored to check for building up of events. If the pending queue size grows above the normal threshold (20,000 for the input queue and 10,0
Ok, I'll remove this: " (20,000 for the input queue and 10,000 for the output queue)".

But I do not know either what exactly "pending" is to mean here. @rthrippleton , please let me know what to do about this. Maybe just remove this word?

2022-11-24 13:34 UTC, rthrippleton commented on content/apama/troubleshooting-bundle/alarms.md
>  The correlator's input and output queues are periodically monitored to check for building up of events. If the pending queue size grows above the normal threshold (20,000 for the input queue and 10,0
That's where https://github.com/SoftwareAG/c8y-docs/pull/681#discussion_r1031492375 comes in - this part of the text is genuinely deep technical details, that may or may not be interesting to the user, and we're using the exact display names that the correlator uses so that looking it up is easier/consistent.

2022-11-24 15:21 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
>  The correlator's input and output queues are periodically monitored to check for building up of events. If the pending queue size grows above the normal threshold (20,000 for the input queue and 10,0
I removed some of that text, and also moved some text to a different position.

2022-11-24 15:22 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
> +  cannot process the requests at the rate at which they are arriving.
I've added the link to the Apama doc.

2022-11-24 16:19 UTC, rthrippleton requested changes

2022-11-24 16:19 UTC, rthrippleton commented on content/apama/troubleshooting-bundle/alarms.md
> +Full input or output queues can cause a serious performance degradation.
'Full' isn't really correct, we raise this when queues are backing/building up, suggesting that things are being produced faster than they can be processed.

Also, it's less mysterious to to invert the cause / effect in this line - instead, backing up queues are a ***symptom** of performance issues in your app or c8y. That's a good start in answering the readers question of "Why would queues back up?" ... though the detail comes later.

2022-11-24 16:19 UTC, rthrippleton commented on content/apama/troubleshooting-bundle/alarms.md
> +The correlator queue sizes are based on the number of events, not raw bytes.
This line is probably not useful here, as that's deep technical detail that's in the linked docs. However, it does no harm, so I'm easy if you want to remove this or keep it.

2022-11-24 16:19 UTC, rthrippleton commented on content/apama/troubleshooting-bundle/alarms.md
> +To diagnose the cause, you can try the following. It may be that the Apama-ctrl microservice is running slow because of time-consuming rules in the script, or the microservice is deprived of resource
``` time-consuming rules in the script```
This seems not to make sense ... 'script'? Just ```time-consuming rules``` would be better, or maybe ```smartrules/models/EPL apps```

2022-11-25 07:55 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
> +The correlator queue sizes are based on the number of events, not raw bytes.
I've removed it.

2022-11-25 07:56 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
> +To diagnose the cause, you can try the following. It may be that the Apama-ctrl microservice is running slow because of time-consuming rules in the script, or the microservice is deprived of resource
ok, updated.

2022-11-25 07:57 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
> +Full input or output queues can cause a serious performance degradation.
I've changed this. Better now?

2022-11-25 12:17 UTC, rthrippleton requested changes

2022-11-25 12:17 UTC, rthrippleton commented on content/apama/troubleshooting-bundle/alarms.md
> +suggesting that events are being produced faster than they can be processed.
Bidirectional, to deal with both the input/output case. This is not ideal wording, but this is what I'm thinking:
```suggestion
suggesting that events/requests are being produced by Apama/C8Y  faster than they can be processed by Apama/C8Y
```

2022-11-25 13:10 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
> +suggesting that events are being produced faster than they can be processed.
Is it Apama or the Apama-ctrl microservice?

2022-11-25 13:18 UTC, rthrippleton commented on content/apama/troubleshooting-bundle/alarms.md
> +suggesting that events are being produced faster than they can be processed.
_Technically_ `Apama` is more correct, because this is a sort of correlator-specific property we're talking about but it doesn't matter so much - in counterpoint, we hardly mention `Apama` on this page, and mention `Apama-ctrl` far more often. Your call - technical correctness vs. scanning better on the page!

2022-11-25 13:22 UTC, kailol-sag commented on content/apama/troubleshooting-bundle/alarms.md
> +suggesting that events are being produced faster than they can be processed.
I'll go for technical correctness then :-) Thanks. The doc has been updated.

2022-11-28 08:50 UTC, shrutidogra-23 approved these changes

2022-11-28 10:29 UTC, merged