Release notes/10.11.+
SoftwareAG/c8y-docs pull request #70
Opened 2021-11-09 15:09 UTC by BeateRixen

2021-11-09 15:14 UTC, MWindel commented on content/release-10-11-0/announcements-10-11-0.md
> +For reference, we disable all HTTP-encoded and control characters (like \u0000). The full list of HTTP-encoded characters equals the one here: https://secure.n-able.com/webhelp/NC_9-1-0_SO_en/Content
```suggestion
For reference, we disable all HTTP-encoded and control characters (like \u0000). The full list of HTTP-encoded characters equals the one here: https://secure.n-able.com/webhelp/NC_9-1-0_SO_en/Content/SA_docs/API_Level_Integration/API_Integration_URLEncoding.html.
```

2021-11-09 15:21 UTC, rssag commented on content/release-10-11-0/announcements-10-11-0.md
> +With the 10.12 release, the O-Auth Internal authentication will be enabled by default for all tenants. With the 10.13 release the Basic Authentication option will be removed for browser-based applica
```suggestion
With the 10.12 release, the O-Auth Internal authentication will be enabled by default for all tenants. With the 10.13 release the Basic Authentication option will be removed for browser-based applications and all applications will be forced to use the token-based authentication mechanism O-Auth Internal. Note that Basic Authentication will still be available for devices connecting to the Cumulocity IoT platform.
```

2021-11-09 16:25 UTC, rssag requested changes

2021-11-09 16:25 UTC, rssag commented on content/release-10-11-0/platform-10-11-0-bundle/10-11-0-4.md
> +<td > Cumulocity IoT will now provide the issuer name to distinguish between different  instances, tenants and other OTC stored in authenticator applications like Google Authenticator or Microsoft Au
```suggestion
<td > Cumulocity IoT will now provide the issuer name to distinguish between different instances, tenants and other OTC stored in authenticator applications like Google Authenticator or Microsoft Authenticator. </td>
```

2021-11-09 16:25 UTC, rssag commented on content/release-10-11-0/platform-10-11-0-bundle/10-11-0-4.md
> +<td> Fixed a bug that was preventing administrators, logged in using SSO, to change local users email addresses.</td>
i'd rather add a "when they were logged in using SSO" at the end

2021-11-09 16:25 UTC, rssag commented on content/release-10-11-0/platform-10-11-0-bundle/10-11-0-4.md
> +<td > The tracker-agent now uses microservice subscription. The registration  of tenants tracker-agent-{tenantId} is no longer required. A subscription is now required for new tenants using the track
```suggestion
<td > The tracker-agent now uses microservice subscription. The registration of tenants tracker-agent-{tenantId} is no longer required. A subscription is now required for new tenants using the tracker-agent. Tenants that have already been using tracker-agent will be subscribed automatically.</td>
```

2021-11-09 16:25 UTC, rssag commented on content/release-10-11-0/whatsnew-10-11-0.md
> +For details on the capabilities and usage of Notifications 2.0, see [Notifications 2.0](https://cumulocity.com/guides/reference/notifications/) in the *Reference guide* and the Cumulocity IoT [API do
https://cumulocity.com/api/10.11.0/#tag/Notification-2.0-API
there's this already in 10.11.0 (which is not visible via landing page yet)

2021-11-09 16:25 UTC, rssag commented on content/release-10-11-0/whatsnew-10-11-0.md
> +Existing queries do not need to be changed, they will behave in exactly the same manner as prior to release 10.10.  For date and time bounded queries the new parameters available are:
```suggestion
Existing queries do not need to be changed, they will behave in exactly the same manner as prior to release 10.10. For date and time bounded queries the new parameters available are:
```

2021-11-09 17:00 UTC, BeateRixen commented on content/release-10-11-0/announcements-10-11-0.md
> +##### Removal of cep microservice
Yes, this is the name of the microservice.

2021-11-09 17:08 UTC, BeateRixen commented on content/release-10-11-0/devices-10-11-0-bundle/10-11-0-4.md
> +<td> The processing mode set in the OPC UA device protocol is now also applied for the mappings created due to historic read operations with TAG tag type.</td>
Done

2021-11-09 17:09 UTC, BeateRixen commented on content/release-10-11-0/machine-learning-10-11-0-bundle/10_11_0.md
> +  - JSON parser now throws a consistent `400 - Bad Request` when an incorrect JSON is passed by the user. Earlier it was throwing `500 - Internal Server Error` in some cases.
Done

2021-11-09 17:17 UTC, BeateRixen commented on content/release-10-11-0/platform-10-11-0-bundle/10-11-0-4.md
> +<td> Fixed a bug that was preventing administrators, logged in using SSO, to change local users email addresses.</td>
Done

2021-11-10 09:30 UTC, rssag approved these changes

2021-11-10 09:47 UTC, MWindel approved these changes

2021-11-10 09:48 UTC, merged