MTM-49965: reference-notifications: rework of non-persistent subscriptions and tokens
SoftwareAG/c8y-docs pull request #720
Opened 2022-12-09 12:23 UTC by gapa-c8y

DRAFT for now of quick feedback while still in progress.

Note: I can't find Yeswanth in reviewers list - please add if you know it (will ask on Teams chat also)

Changed to natural order of dealing with subscription stuff first.
non-persistent rewritten and now includes it's own token paragraph leaning on distinction of non-persistent/persistent identity.

First sentences of share written, but will be continuing on ...

2022-12-09 14:28 UTC, sagscmi reviewed
Looks good so far Gary.  A few suggested changes that you can feel free to ignore as they are mostly personal preference, plus a couple of proposed clarifications/simplifications.

2022-12-09 14:28 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +When creating a subscription, an optional Boolean `nonPersistent` field can be added to the request body,
Is "field" the right name for this entity?  According to https://swagger.io/docs/specification/2-0/describing-request-body/ "body parameter" might be more correct, although not sure what term we use elsewhere in the documentation.

2022-12-09 14:28 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +They use replicated secondary storage to maintain large backlogs (within the constraints of any maximum backlog sizes)
Personal wording preference, feel free to ignore.
```suggestion
They use replicated secondary storage to maintain large backlogs (within the constraints of any configured backlog limits)
```

2022-12-09 14:28 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +upon reconnection they will continue to receive notifications from position they were at before the outage
```suggestion
upon reconnection they will continue to receive notifications from the position they were at before the outage 
```

2022-12-09 14:28 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +Non-persistent subscriptions are only buffered in memory and their consumers' positions are not persisted (not durable).
```suggestion
Non-persistent subscriptions are only buffered in memory and their consumers' positions are not persisted across disconnections of the consumer.
```

2022-12-09 14:28 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +When both a persistent and a non-persistent subscriptions are created with the same name (`subscription` field value in the request body)
Possibly too many commas here now but the parentheses didn't quite feel right...
```suggestion
When both a persistent and a non-persistent subscription are created with the same name, that is, with the same `subscription` field value in the request body, 
```

2022-12-09 14:28 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +may be surprising to others, so it may not be wise to do this unless they are otherwise the same.
Agree with @slc-softwareag's comment elsewhere that this could be stated more concisely/clearly.

2022-12-09 14:28 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +Setting this field to `true` in the token creation request targets the non-persistent one.
I think this could be said more simply and firmly.  Maybe something like this: "To create a token for a non-persistent subscription, it is *required* to include a `non-persistent` body parameter in the request, with its value set to `true`.  Otherwise, the request will be taken to refer to a persistent subscription with the same name."

2022-12-09 14:28 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +Shared tokens allow parallelization of the consumer workload.
Not sure about this one but it felt like it needed a little more.
```suggestion
Shared tokens allow parallelization of the consumer workload for a notification subscription. 
```

2022-12-09 14:28 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +It has no impact on the rate of notification throughput through, and thus their egress from, Cumulocity.
```suggestion
It has no impact on the rate of notification throughput through, and thus their egress from, the Cumulocity core.
```

2022-12-09 15:26 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +When creating a subscription, an optional Boolean `nonPersistent` field can be added to the request body,
I'll remove 'body' form after request on this change (otherwise 2 bodies). So will be '... body parameter can be added to the request, ...'

2022-12-09 15:27 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +When creating a subscription, an optional Boolean `nonPersistent` field can be added to the request body,
.. probably same for shared so will amend that and anywhere else I've changed also

2022-12-09 15:46 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +may be surprising to others, so it may not be wise to do this unless they are otherwise the same.
Reworked (push shortly) and also the next paragraph, which was written in the context of subscriptions with the same name/subscription-field, but has been updated to apply to all subscriptions (you have to use right non-persistent toekn value to target a notification whether there is name commonality or not)

2022-12-09 15:48 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +Setting this field to `true` in the token creation request targets the non-persistent one.
Ah, may have just done so (following on from comment above). Please review again - your alternative might be preferable

2022-12-09 16:03 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +When creating a subscription, an optional Boolean `nonPersistent` field can be added to the request body,
done

2022-12-09 16:03 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +may be surprising to others, so it may not be wise to do this unless they are otherwise the same.
pushed

2022-12-09 16:04 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +Setting this field to `true` in the token creation request targets the non-persistent one.
done - but please recriticise as I had already taken initiative on this

2022-12-09 16:08 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +Shared tokens allow parallelization of the consumer workload.
Done

2022-12-09 16:09 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +It has no impact on the rate of notification throughput through, and thus their egress from, Cumulocity.
Done and have also already change 'throughput through' to 'throughput within' but not quite sure that is the best option (it's better).

2022-12-11 14:27 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +The notification load is divided into shares dictated by a hash of the id of the source that generated the notification (typically a device id).
Not sure I would mention hashing in user documentation
```suggestion
The notification load is spread across the shared consumers according to the id of the source that generated the notification, typically a device id.
All notifications for a given id will be delivered to the same consumer, and each consumer may be receiving notifications for many different ids.
```

2022-12-11 14:31 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +Note that, as the shares are divided by a hash of the ids, it can result in an asymmetric balance of notification load across the shares if there are few source ids involved. This should even out for
Again I just don't want to say "hash" here.  Not certain that "algorithm" is any better although people probably have a sense of what that means even if they couldn't define it.
```suggestion
Note that the load spreading algorithm may result in an asymmetric balance of notification load across the shares when there are few source ids in the subscription.
Load should generally become more evenly distributed as the number of sources increases.
```

2022-12-11 14:33 UTC, sagscmi commented on content/reference/notifications-bundle/overview.md
> +In order to help keep the messages from a given set of source ids sticky to consumer client shares in the face of consumer client connection interruptions, the consumer clients can provide an
```suggestion
In order to help keep the messages from a given set of source ids "sticky" to shared consumers in the face of connection interruptions, the consumer clients can provide an 
```

2022-12-12 08:30 UTC, slc-softwareag commented on content/reference/notifications-bundle/overview.md
> +The notification load is divided into shares dictated by a hash of the id of the source that generated the notification (typically a device id).
Agree, writing about hash may just bring us more questions from customers.

2022-12-12 08:30 UTC, slc-softwareag commented on content/reference/notifications-bundle/overview.md
> +Subscriptions are always unaware of the nature and number of their consumers: any number of shared and exclusive tokens can created for the same subscription and they all operate independently, each
`tokens can created` -> `tokens can be created`?

2022-12-12 09:51 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +Subscriptions are always unaware of the nature and number of their consumers: any number of shared and exclusive tokens can created for the same subscription and they all operate independently, each
Will change ...

2022-12-12 10:00 UTC, gapa-c8y commented on content/reference/notifications-bundle/overview.md
> +Subscriptions are always unaware of the nature and number of their consumers: any number of shared and exclusive tokens can created for the same subscription and they all operate independently, each
Done

2022-12-12 11:33 UTC, slc-softwareag approved these changes

2022-12-12 20:55 UTC, sag-tjegorow approved these changes

2022-12-13 08:53 UTC, rssag requested changes

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +they will be *separate*, independent subscriptions. Such subscriptions can vary by any other body parameters they choose: they do not *have* to be
```suggestion
they are *separate*, independent subscriptions. Such subscriptions can vary by any other body parameters you choose. They do not have to be
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +persistent and non-persistent variations of the same notification data, although to avoid confusion it is recommended to keep such subscriptions identical except for the `nonPersistent` parameter.
```suggestion
persistent and non-persistent variations of the same notification data. However, we recommend you to keep such subscriptions identical except for the `nonPersistent` parameter to avoid confusion.  
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +When both a persistent and a non-persistent subscription are created with the same name, that is, with the same `subscription` body parameter value in the request,
```suggestion
If you create both a persistent and a non-persistent subscription with the same name, that is, with the same `subscription` body parameter value in the request, 
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +it **must** distinguish which type of subscription it is targeting by use of the `non-persistent` body parameter in the token creation request.
```suggestion
it must distinguish which type of subscription it is targeting by using the `non-persistent` body parameter in the token creation request.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Like for the subscription, this body parameter defaults to `false`, making the token target a persistent subscription.
```suggestion
For the subscription, this body parameter defaults to `false`, making the token target a persistent subscription. 
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +### Shared tokens
```suggestion
### Shared tokens

```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +It has no impact on the rate of notification throughput within, and thus their egress from, Cumulocity core.
```suggestion
It has no impact on the rate of notification throughput within, and thus their egress from, {{< product-c8y-iot >}} core.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +When creating a token, an optional Boolean `shared` body parameter can be added to the request,
```suggestion
When you create a token, you can add the optional Boolean body parameter `shared` to the request.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +and, if that is set to the value `true`, the created token will be shared.
```suggestion
If it is set to `true`, the created token is shared.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +If this body parameter is not present or `false`, a token will be exclusive (not shared) by default.
```suggestion
If it is not present or `false`, the token is exclusive (not shared).
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +If a consumer's token is *not* shared, the consumer is an **exclusive** consumer.
```suggestion
If a consumer's token is not shared, the consumer is an *exclusive* consumer.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Only one consumer client can connect using an exclusive token: attempts to connect further consumers with the same exclusive token will result in error.
```suggestion
Only one consumer client can connect using an exclusive token. An attempt to connect further consumers with the same exclusive token results in an error.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +An exclusive consumer will receive a copy of all notifications from the subscription its token is for.
```suggestion
An exclusive consumer receives a copy of all notifications from the subscription its token is for.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +If a consumer's token is shared, the consumer is a **shared** consumer. Additional consumer clients can connect using the same token.
```suggestion
If a consumer's token is shared, the consumer is a *shared consumer*. Additional consumer clients can connect using the same token.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +When only one shared consumer is connected, it receives a copy of all notifications from subscription.
```suggestion
If only one shared consumer is connected, it receives a copy of all notifications from the subscription.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Collectively, the ensemble will receive all notifications for the subscription.
```suggestion
Collectively, the set receives all notifications for the subscription. 
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +The collective ensemble of consumers sharing a token can be thought of as one logical consumer.
```suggestion
The set of consumers sharing a token can be thought of as a single logical consumer.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +The notification load is spread across the shared consumers according to the id of the source that generated the notification, typically a device id.
```suggestion
The notification load is spread across the shared consumers according to the ID of the source that generated the notification, typically a device ID.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +All notifications for a given id will be delivered to the same consumer, and each consumer may be receiving notifications for many different ids.
```suggestion
All notifications for a given ID will be delivered to the same consumer. Each consumer may receive notifications for many different IDs.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +This means there is no benefit using shared tokens unless the notifications feeding the subscription are coming from multiple sources.
```suggestion
This means that there is no benefit using shared tokens unless the notifications feeding the subscription are coming from multiple sources.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Note that the load spreading algorithm may result in an asymmetric balance of notification load across the shares when there are few source ids in the subscription.
```suggestion
Note that the load spreading algorithm may result in an asymmetric balance of notification load across the shares when there are few source IDs in the subscription.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Load should generally become more evenly distributed as the number of sources increases.
```suggestion
The load should generally become more evenly distributed as the number of sources increases.
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +In order to help keep the messages from a given set of source ids "sticky" to shared consumers in the face of connection interruptions, the consumer clients can provide an
```suggestion
In order to help keep the messages from a given set of source IDs stick to shared consumers in the face of connection interruptions, the consumer clients can provide an 
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +For example: two consumers identifying themselves as *instance1* and *instance2* would connect using URL paths
```suggestion

For example: two consumers identifying themselves as *instance1* and *instance2* connect using URL paths
```

2022-12-13 08:53 UTC, rssag commented on content/reference/notifications-bundle/overview.md
> +Subscriptions are always unaware of the nature and number of their consumers: any number of shared and exclusive tokens can be created for the same subscription and they all operate independently, ea
```suggestion
Subscriptions are always unaware of the nature and number of their consumers: any number of shared and exclusive tokens can be created for the same subscription and they all operate independently, each receiving their own copy of the notifications. This means you can have multiple shared tokens for the same subscription and their load is only divided within the scope of each shared token.
```

2022-12-13 13:54 UTC, rssag approved these changes

2022-12-15 08:13 UTC, merged