updated roles & permission level for workflow, neural network & code …
SoftwareAG/c8y-docs pull request #743
Opened 2022-12-15 15:07 UTC by amsosag

PR to update the roles & permission for neural network, workflow & code execution.

2022-12-16 15:02 UTC, SAGCCHI approved these changes

2022-12-16 15:10 UTC, SAGCCHI requested changes
https://github.com/SoftwareAG/c8y-docs/blob/develop/content/machine-learning/machine-learning-introduction-bundle/mlw-overview.md#machine-learning-manager

The description of the Machine Learning Manager group needs an update.

2022-12-20 08:00 UTC, MWindel approved these changes

2022-12-21 11:52 UTC, closed without merging

2022-12-21 11:53 UTC, amsosag commented
no longer needed, changes will be cherry-picked from develop branch