updated roles & permission for jnb-session, jnb content, neural netwo…
SoftwareAG/c8y-docs pull request #746
Opened 2022-12-21 11:48 UTC by amsosag

updated roles & permission for jnb-session, jnb content, neural network, workflow & code execution apis

2022-12-21 12:23 UTC, BeateRixen approved these changes

2022-12-23 07:13 UTC, VRAN016 approved these changes

2022-12-23 07:15 UTC, VRAN016 commented
These changes need to be cherry-picked for the 10.15 and 10.13 branches as well.

2022-12-23 10:20 UTC, SAGCCHI requested changes
https://github.com/SoftwareAG/c8y-docs/blob/MLW-fix-release-for-roles/content/machine-learning/machine-learning-introduction-bundle/mlw-overview.md#machine-learning-manager

The Machine Learning Manager group's description is inappropriate after some API endpoints' role changes.

2023-01-03 10:10 UTC, SAGCCHI approved these changes

2023-01-03 10:51 UTC, BeateRixen approved these changes

2023-01-03 10:52 UTC, merged