Feature/cdh 10 16 release
SoftwareAG/c8y-docs pull request #747
Opened 2022-12-22 09:02 UTC by cheinz-sag

Hi,

can you pls review the 10.16 DataHub update and merge it to develop and into the 10.16 branch? I'd propose that Tim should do an initial review as he also checks the correctness of the updates.

Thanks
Christoph

2022-12-23 15:48 UTC, MWindel commented on content/datahub/setting-up-datahub-bundle/setting-up-dremio-users.md
> +Dremio refers to the permissions as [privileges](https://docs.dremio.com/software/security/rbac/privileges/). Privileges include for example `SELECT`, `ALTER`, `CREATE TABLE`, or `DROP`. Given a Drem
"Given a Dremio user with the corresponding permissions, permissions to other users can be granted via the Dremio UI." --> This sounds a bit complicated. 

Would "A Dremio user with the corresponding permissions can grant permissions to other users via the Dremio UI." work as well?

2022-12-23 15:48 UTC, MWindel commented on content/datahub/setting-up-datahub-bundle/setting-up-initial-configuration.md
> +Click **Delete** in the action bar to delete the settings. During deletion, all Dremio artifacts which were created when saving the settings are deleted, including the Dremio API user as well as addi
```suggestion
Click **Delete** in the action bar to delete the settings. During deletion, all Dremio artifacts which were created when saving the settings are deleted, including the Dremio API user as well as additionally created Dremio users. Also the artifacts created by a corresponding Dremio user, like views, are deleted. All offloading pipelines and their histories are deleted; active pipelines are deleted after completing the current offloading. As mentioned in the previous section, you can use the import/export functionality to backup your offloading configurations. The data lake and its contents are not deleted, only the Dremio artefacts connecting to the data lake. To delete the data lake and its contents you must use the tooling of your data lake provider.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +The two paths *c8y_TemperatureMeasurement.T* and *c8y_temperaturemeasurement.T* are equal in terms of case-insensitivity. Without name sanitization, one column *c8y_TemperatureMeasurement.T.unit* wil
```suggestion
The two paths *c8y_TemperatureMeasurement.T* and *c8y_temperaturemeasurement.T* are equal in terms of case-insensitivity. Without name sanitation, only the column *c8y_TemperatureMeasurement.T.unit* will be created to store all unit entries. Analogously, one column *c8y_TemperatureMeasurement.T.value* will be created, which stores all value entries. In the latter case, the column would have a mixed type of DOUBLE and VARCHAR.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +With name sanitization, two columns *c8y_TemperatureMeasurement.T.unit* and *c8y_temperaturemeasurement.T.unit_6bfa* will be created for unit entries. Then the unit entries will be stored in the colu
```suggestion
With name sanitation, two columns *c8y_TemperatureMeasurement.T.unit* and *c8y_temperaturemeasurement.T.unit_6bfa* will be created for unit entries. The unit entries will then be stored in the column with the associated path. Analogously, two columns *c8y_TemperatureMeasurement.T.value* and *c8y_temperaturemeasurement.T.value_490d* will be created for value entries.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +In case one offloading run processes multiple fragments with corresponding column names being equal with respect to case-insensitivity, the sanitization also generates distinct column names, with eac
```suggestion
In the first case an offloading run processes multiple fragments with the corresponding column names being equal with respect to case-insensitivity, the sanitation also generates distinct column names, with each name having a unique suffix.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +The two paths *c8y_TemperatureMeasurement.T* and *c8y_temperaturemeasurement.T* are equal in terms of case-insensitivity. Without name sanitization, one column *c8y_TemperatureMeasurement.T.unit* wil
@cheinz-sag What does "name sanitation" refer to?

This section (as well as below) sounds quite complicated.

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +**Completion of offloading configuration**
```suggestion
**Completing the offloading configuration**
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/refining-offloaded.md
> +Such a view is per default not materialized, that is, it is not stored persistently. Each time you query the view, the underlying query defining the view is run against the source data. For the pre-d
```suggestion
Such a view is per default not materialized, that is, it is not stored persistently. Each time you query the view, the underlying query defining the view is run against the source data. For the pre-defined alarms/events/inventory views, you can optionally activate view materialization during the offloading configuration.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/overview-offloading.md
> +
The following entries should better be formatted as a table to improve readability.

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +You should try to ensure that the data you feed into the measurements base collection is consistent. If measurements of
```suggestion
Try to ensure that the data you feed into the measurements base collection is consistent. If measurements of the same type vary in the fragment structures, the resulting target table might not have the expected schema. A common problem, for example, are varying data types of the values like one value being 2.079 and another one NaN.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +the same type vary in the fragment structures, the resulting target table might not have the expected schema. A common
Combine to one entry (see suggestion above).

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +The *childDevices* and *childAssets* fields are not part of the default offloading columns. They were included in previous versions, but lead to problems for a high number of list items in those fiel
```suggestion
The fields **childDevices** and **childAssets** are not part of the default offloading columns. They were included in previous versions, but lead to problems for a high number of list items in those fields. In such a case, the columns were no more readable by Dremio. If they need to be included in the offloaded data, they can be defined as additional result columns. However, you have to ensure that the number of list items in those fields does not exceed the Dremio limit configured in your environment.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +* **events_all**:  A view with  all states of all events.
```suggestion
* **events_all** -  A view with all states of all events.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +* **events_latest**: A view containing only the latest state of all events without prior states.
```suggestion
* **events_latest** - A view containing only the latest state of all events without prior states.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
>  * **events_c8y_cdh_latest_materialized**: An optional view which materializes the **events_latest** view if the offloading configuration has view materialization enabled.
```suggestion
* **events_c8y_cdh_latest_materialized** - An optional view which materializes the **events_latest** view if the offloading configuration has the view materialization enabled.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +The alarms collection keeps track of alarms. An alarm may change its status over time. The alarms collection also
@cheinz-sag In this section the term "view" is used a lot. To avoid confusion, what does "view" refer to in this context?

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +The following tables summarize the resulting schemas for each of the {{< product-c8y-iot >}} base collections. These schemas additionally include virtual columns *dir0*, ..., *dir3*, which are used f
```suggestion
The following tables summarize the resulting schemas for each of the {{< product-c8y-iot >}} base collections. These schemas additionally include the virtual columns *dir0*, ..., *dir3*, which are used for internal purposes. The columns are generated during the extraction process, but neither do they have corresponding data in the operational store of {{< product-c8y-iot >}}, nor are they persisted in the data lake. Do not use *dir0*, ..., *dir3* as additional columns or rename them accordingly in your offloading configuration.
```

2022-12-23 15:48 UTC, MWindel commented on content/datahub/working-with-datahub-bundle/datahub-best-practices.md
> +**Alarms/events**
@cheinz-sag Why was the level 5 heading removed?

2023-01-10 08:07 UTC, doernemt commented on content/datahub/integrating-datahub-with-other-products-bundle/integration-powerbi.md
> +As prerequisite you need an Azure Active Directory tenant. If you do not have an Azure Active Directory, follow the instructions in the [Microsoft documentation](https://docs.microsoft.com/en-us/powe
AD TENANT is better, yes

2023-01-10 08:10 UTC, doernemt commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +* **events_latest**: A view containing only the latest state of all events without prior states.
Need to be careful! "A view with  all states of all events." implies that we capture ALL state changes (Change Data Capture, CDC), but we actually might miss a few transitions.

=> A view with all CAPTURED states of all events.

(2): there's an extra space between "with" and "all" => "with__all"

2023-01-10 08:19 UTC, doernemt commented on content/datahub/running-datahub-on-the-edge-bundle/operating-datahub-edge.md
> +Browse to the data lake folder **/opt/mongodb/cdh-master/datalake**. The data within the data lake is organized hierarchically. Delete the temporal folders you deem adequate to be deleted. After that
After that**,** you must run the following query in Dremio **using the administrator account** to refresh the metadata

2023-01-10 08:23 UTC, doernemt commented on content/datahub/working-with-datahub-bundle/managing-offloading-jobs.md
> +The scheduler is configured per default to run the offloading pipeline once an hour. The precise minute of the hour at which the offloading starts is shown in the pipeline configuration. This minute
I remember that in other places, it was suggested to lower case "Operational Store"

2023-01-10 08:25 UTC, doernemt commented on content/datahub/working-with-datahub-bundle/refining-offloaded.md
> +Terminology-wise, {{< product-c8y-iot >}} DataHub replicates data from the Operational Store of {{< product-c8y-iot >}} into the data lake. For Dremio the data lake, comprising the target tables, is
operational store

2023-01-10 08:26 UTC, doernemt requested changes
Looks good in general, just very minor changes required; see comments

2023-01-10 09:19 UTC, BeateRixen commented on content/datahub/working-with-datahub-bundle/managing-offloading-jobs.md
> +The scheduler is configured per default to run the offloading pipeline once an hour. The precise minute of the hour at which the offloading starts is shown in the pipeline configuration. This minute
We use upper case throughout the entire documentation.

2023-01-10 14:40 UTC, cheinz-sag commented on content/datahub/integrating-datahub-with-other-products-bundle/integration-powerbi.md
> +{{< product-c8y-iot >}} DataHub leverages the native interaction between Microsoft Power BI and Dremio. Microsoft Power BI reports can consume data from data lakes using Dremio as query and data acce
Done

2023-01-10 14:41 UTC, cheinz-sag commented on content/datahub/integrating-datahub-with-other-products-bundle/integration-powerbi.md
> +The Microsoft Power BI datasets should use the *DirectQuery* mode, which prevents replicating and caching the data from the data lake.
Done

2023-01-10 14:46 UTC, cheinz-sag commented on content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge.md
> +<td>The UI can be accessed in the <strong>application switcher</strong> after you have logged into the {{< product-c8y-iot >}} Edge UI. Alternatively you can access it directly under <em>http://edge_
Done

2023-01-10 14:48 UTC, cheinz-sag commented on content/datahub/setting-up-datahub-bundle/setting-up-dremio-users.md
> +Dremio refers to the permissions as [privileges](https://docs.dremio.com/software/security/rbac/privileges/). Privileges include for example `SELECT`, `ALTER`, `CREATE TABLE`, or `DROP`. Given a Drem
Done

2023-01-10 14:53 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +The two paths *c8y_TemperatureMeasurement.T* and *c8y_temperaturemeasurement.T* are equal in terms of case-insensitivity. Without name sanitization, one column *c8y_TemperatureMeasurement.T.unit* wil
Done... This section is indeed complicated as this is an advanced setting with subtle flavors.

2023-01-10 14:54 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +With name sanitization, two columns *c8y_TemperatureMeasurement.T.unit* and *c8y_temperaturemeasurement.T.unit_6bfa* will be created for unit entries. Then the unit entries will be stored in the colu
Done

2023-01-10 14:57 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +**Completion of offloading configuration**
Done

2023-01-10 14:57 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/refining-offloaded.md
> +Such a view is per default not materialized, that is, it is not stored persistently. Each time you query the view, the underlying query defining the view is run against the source data. For the pre-d
Done

2023-01-10 14:59 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +You should try to ensure that the data you feed into the measurements base collection is consistent. If measurements of
Done

2023-01-10 15:01 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/overview-offloading.md
> +
Hmm, I tend to keep it like that as the descriptions are sometimes pretty lengthy and then I find a table less suitable...

2023-01-10 15:03 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +The *childDevices* and *childAssets* fields are not part of the default offloading columns. They were included in previous versions, but lead to problems for a high number of list items in those fiel
Done

2023-01-10 15:06 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +* **events_latest**: A view containing only the latest state of all events without prior states.
Done

2023-01-10 15:06 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
>  * **events_c8y_cdh_latest_materialized**: An optional view which materializes the **events_latest** view if the offloading configuration has view materialization enabled.
Done

2023-01-10 15:11 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/offloading-base-collections.md
> +The following tables summarize the resulting schemas for each of the {{< product-c8y-iot >}} base collections. These schemas additionally include virtual columns *dir0*, ..., *dir3*, which are used f
Done... Operational Store is consistently upper-case; it's defined upfront in CDH doc

2023-01-10 15:13 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/datahub-best-practices.md
> +**Alarms/events**
I thought it to look better like that, also for the others like Inventory. WDYT?

2023-01-10 15:14 UTC, cheinz-sag commented on content/datahub/running-datahub-on-the-edge-bundle/operating-datahub-edge.md
> +Browse to the data lake folder **/opt/mongodb/cdh-master/datalake**. The data within the data lake is organized hierarchically. Delete the temporal folders you deem adequate to be deleted. After that
Done

2023-01-10 15:15 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/refining-offloaded.md
> +Terminology-wise, {{< product-c8y-iot >}} DataHub replicates data from the Operational Store of {{< product-c8y-iot >}} into the data lake. For Dremio the data lake, comprising the target tables, is
See above

2023-01-10 15:39 UTC, BeateRixen commented on content/datahub/setting-up-datahub-bundle/defining-permissions.md
> +The permissions for the role "DataHub Reader" are defined as follows:
You use italics above for *DataHub Manager*. I would actually not use any special formatting at all.

2023-01-10 15:39 UTC, BeateRixen commented on content/datahub/setting-up-datahub-bundle/setting-up-dremio-users.md
> +Dremio refers to the permissions as [privileges](https://docs.dremio.com/software/security/rbac/privileges/). Privileges include for example `SELECT`, `ALTER`, `CREATE TABLE`, or `DROP`. A Dremio use
```suggestion
Dremio refers to the permissions as [privileges](https://docs.dremio.com/software/security/rbac/privileges/). Privileges include for example SELECT, ALTER, CREATE TABLE, or DROP. A Dremio user with the corresponding permissions can grant permissions to other users via the Dremio UI. In the UI, browse to the data lake or space and select **Edit details** in the context menu. In the editor, the list of privileges for all users is shown, with the option to update privileges and users. Alternatively, you can use the [Dremio SQL API](https://docs.dremio.com/software/sql-reference/sql-commands/rbac/) to modify privileges.
```

2023-01-10 15:39 UTC, BeateRixen commented on content/datahub/setting-up-datahub-bundle/setting-up-initial-configuration.md
> +|Azure Storage shared access key|The access key used for authentication if *Shared Access Key* is used as authentication type|
```suggestion
|Azure Storage shared access key|The access key used for authentication if "Shared Access Key" is used as authentication type|
```

2023-01-10 15:39 UTC, BeateRixen commented on content/datahub/setting-up-datahub-bundle/setting-up-initial-configuration.md
> +|OAuth 2.0 Token Endpoint|The authentication endpoint if *Azure Active Directory* is used as authentication type|
```suggestion
|OAuth 2.0 Token Endpoint|The authentication endpoint if "Azure Active Directory" is used as authentication type|
```

2023-01-10 15:39 UTC, BeateRixen commented on content/datahub/setting-up-datahub-bundle/setting-up-initial-configuration.md
> +|Client Secret|The client secret if *Azure Active Directory* is used as authentication type|
```suggestion
|Client Secret|The client secret if "Azure Active Directory" is used as authentication type|
```

2023-01-10 15:39 UTC, BeateRixen commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +Another setting, which applies only for the measurements collection, is the handling of duplicate column names. During offloading measurement values are transformed into a relational format. Correspo
```suggestion
Another setting, which applies only for the measurements collection, is the handling of duplicate column names. During offloading, measurement values are transformed into a relational format. Corresponding column names of measurement values are constructed by concatenating path and unit/value. This may lead to columns having the same name except for their case. Then the entries would all be offloaded into the same column. As this may be an unwanted behaviour or even imply mixed types in the offloading process, the names can be sanitized. When activated, for each generated column name, which would be equal to another column name in terms of case-insensitivity, a new column will be created, whose name includes the originally derived name plus a unique suffix.
```

2023-01-10 15:39 UTC, BeateRixen commented on content/datahub/working-with-datahub-bundle/managing-offloading-jobs.md
> +Use the **Active** toggle in an offloading configuration to stop the periodic offloading. Then the scheduler stops scheduling new jobs; currently running jobs will complete.
Above, you say "click the **Active/Inactive** toggle. Please make it consistent :-)

2023-01-10 15:40 UTC, BeateRixen commented
@cheinz-sag I have added a couple of additional minor comments.

2023-01-11 12:40 UTC, cheinz-sag commented on content/datahub/integrating-datahub-with-other-products-bundle/integration-powerbi.md
> +As prerequisite you need an Azure Active Directory tenant. If you do not have an Azure Active Directory tenant, follow the instructions in the Microsoft documentation [(https://docs.microsoft.com/en-
Done; changes have been rolled back

2023-01-11 12:40 UTC, cheinz-sag commented on content/datahub/setting-up-datahub-bundle/defining-permissions.md
> +The permissions for the role "DataHub Reader" are defined as follows:
Done

2023-01-11 12:41 UTC, cheinz-sag commented on content/datahub/setting-up-datahub-bundle/setting-up-dremio-users.md
> +Dremio refers to the permissions as [privileges](https://docs.dremio.com/software/security/rbac/privileges/). Privileges include for example `SELECT`, `ALTER`, `CREATE TABLE`, or `DROP`. A Dremio use
Done

2023-01-11 12:43 UTC, cheinz-sag commented on content/datahub/setting-up-datahub-bundle/setting-up-initial-configuration.md
> +|Azure Storage shared access key|The access key used for authentication if *Shared Access Key* is used as authentication type|
Done

2023-01-11 12:43 UTC, cheinz-sag commented on content/datahub/setting-up-datahub-bundle/setting-up-initial-configuration.md
> +|Application ID|The application ID used for authentication if *Azure Active Directory* is used as authentication type|
Done

2023-01-11 12:43 UTC, cheinz-sag commented on content/datahub/setting-up-datahub-bundle/setting-up-initial-configuration.md
> +|OAuth 2.0 Token Endpoint|The authentication endpoint if *Azure Active Directory* is used as authentication type|
Done

2023-01-11 12:43 UTC, cheinz-sag commented on content/datahub/setting-up-datahub-bundle/setting-up-initial-configuration.md
> +|Client Secret|The client secret if *Azure Active Directory* is used as authentication type|
Done

2023-01-11 12:44 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +Per default each active offloading pipeline is executed once an hour, at the same minute. You can adapt the offloading frequency by setting in the drop-down box the hours per day at which the offload
Done

2023-01-11 12:44 UTC, cheinz-sag commented on content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
> +Another setting, which applies only for the measurements collection, is the handling of duplicate column names. During offloading measurement values are transformed into a relational format. Correspo
Done

2023-01-11 13:30 UTC, BeateRixen approved these changes

2023-01-11 13:37 UTC, doernemt approved these changes

2023-01-12 15:09 UTC, merged