DM-1560 Added new config switch
SoftwareAG/c8y-docs pull request #750
Opened 2022-12-23 11:05 UTC by sag-eweingaertner

We now can configure LWM2M to remove old values in Generic UI

2022-12-29 07:50 UTC, rssag requested changes

2022-12-29 07:50 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/register-device.md
> +<td style="text-align: left">Controls if stale values are kept in the Objects tab. If this flag is set to <code>true</code>(default) the agent never removes a value. If set to <code>false</code> the
```suggestion
<td style="text-align: left">Controls if stale values are kept in the Objects tab. If this flag is set to <code>true</code> (default) the agent never removes a value. If set to <code>false</code> the agent will remove values in two cases:
```

2022-12-29 07:50 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/register-device.md
> +<li>Resources not contained in a discover response will be removed. This allows a discover operation to be used for purging out resources that do not exist on the device any longer</li>
```suggestion
<li>Resources not contained in a discover response will be removed. This allows a discover operation to be used for purging resources that do not exist on the device any longer.</li>
```

2022-12-29 07:50 UTC, rssag commented
to which releases does this apply?

2023-01-04 15:50 UTC, rssag approved these changes

2023-01-10 06:48 UTC, Oezge-Akin approved these changes

2023-01-10 08:01 UTC, sourajitsaha17 approved these changes

2023-01-10 08:47 UTC, merged

2023-01-10 09:46 UTC, sag-eweingaertner commented
Hallo Richard, nur 10.17+