[DM-1663] New branding screenshots update
SoftwareAG/c8y-docs pull request #763
Opened 2023-01-03 11:56 UTC by bozhidardedov

2023-01-09 13:51 UTC, catarino-sag commented
1. Not sure why but starting on devmgmt-devices-connectionstatus.png I can't see rendered images.
![Screenshot 2023-01-09 at 13 44 06](https://user-images.githubusercontent.com/89575566/211323198-01cca99f-1f56-4e77-bb7d-69d91f541d14.png)

2.  Have run the images thru a png compressor? (I don't think we this automated, do we?)

2023-01-10 09:30 UTC, BeateRixen commented
> 1. Not sure why but  I can't see rendered images starting on devmgmt-devices-connectionstatus.png
>    ![Screenshot 2023-01-09 at 13 44 06](https://user-images.githubusercontent.com/89575566/211323198-01cca99f-1f56-4e77-bb7d-69d91f541d14.png)
> 2. Have you run the images thru a png compressor? (I don't think we have this automated, do we @BeateRixen?)

@catarino-sag No, we still do images manually. There are some initial discussions ongoing with respect to automation but nothing has been implemented yet.

2023-01-10 14:07 UTC, catarino-sag commented
I pushed optimized imgs.

2023-01-16 15:00 UTC, dafkk approved these changes

2023-01-16 15:00 UTC, dafkk commented on content/protocol-integration/cloud-fieldbus-bundle/exporting-importing-protocols.md
>  2. In the resulting dialog box, either select a pre-defined protocol or upload a file with a previously exported device protocol.
Here the image right before the list, do we need it since we are only pointing out to the export button?

2023-01-16 17:47 UTC, rssag requested changes
about the changed screenshots:

* fieldbus-modbus-events-log.png has collapsed event items, while the old screenshot had them expanded
* devmgmt-at-register-device-pending-acceptance-ignored-security.png, devmgmt-at-register-device-pending-acceptance-optional-security-enter-token.png, devmgmt-at-register-device-pending-acceptance-optional-security.png, devmgmt-bulk-registration.png, devmgmt-device-list-configure-columns.png, devmgmt-device-protocol-add.png, devmgmt-device-protocol-import.png, devmgmt-device-protocols.png, devmgmt-device-registration-tenant.png, devmgmt-device-registration.png, devmgmt-devices-filter.png, devmgmt-devices-shell-precommands.png, devmgmt-dropdown-menu.png, devmgmt-group-assignment-new.png, devmgmt-group-filter.png, devmgmt-register-devices-custom.png, devmgmt-registration-general.png, devmgmt-search.png, devmgmt-services-status-filter.png, devmgmt-simulator-add.png, devmgmt-simulator-alarm.png, devmgmt-simulator-fragment.png, devmgmt-simulator-instructions.png, devmgmt-simulator-sleep.png, devmgmt-simulator-supported-operations.png, devmgmt-simulator.png, devmgmt-smartgroups-icon.png, connectivity-jasperadmin.png and connectivity-jasperarchitecture.png have no changes, but still show up as being altered in the PR. they are partially ok, but partially it's still the old design, please check.
* devmgmt-devices-config-putsnapshot.png is quite different, especially the right side preview
* in devmgmt-devices-deviceinfostatus.png, the push connection was "active" before

2023-01-17 09:49 UTC, bozhidardedov commented on content/users-guide/device-management-bundle/connectivity.md
> -* the SIM is activated. If the SIM card is not activated, you can activate it selecting "Activated" from the status drop-down menu. <br> ![Activate SIM card](/images/users-guide/connectivity/connecti
The text remains, only the screenshot is removed and the name of the dropdown is corrected.

2023-01-17 09:53 UTC, bozhidardedov commented on content/users-guide/device-management-bundle/connectivity.md
> +* the SIM is activated. If the SIM card is not activated, you can activate it selecting "Activated" from the "SIM status" drop-down menu. It may take a while until the SIM card is activated in the ne
My bad, it actually appears as "ACTIVE" in the dropdown.

2023-01-17 10:00 UTC, bozhidardedov commented
> these screenshots:
> * devmgmt-at-register-device-pending-acceptance-ignored-security.png
> * devmgmt-at-register-device-pending-acceptance-optional-security-enter-token.png
> * devmgmt-at-register-device-pending-acceptance-optional-security.png
> * devmgmt-bulk-registration.png
> * devmgmt-device-list-configure-columns.png
> * devmgmt-device-protocol-add.png
> * devmgmt-device-protocol-import.png
> * devmgmt-device-protocols.png
> * devmgmt-device-registration-tenant.png
> * devmgmt-device-registration.png
> * devmgmt-devices-filter.png
> * devmgmt-devices-shell-precommands.png
> * devmgmt-dropdown-menu.png
> * devmgmt-group-assignment-new.png
> * devmgmt-group-filter.png
> * devmgmt-register-devices-custom.png
> * devmgmt-registration-general.png
> * devmgmt-search.png
> * devmgmt-services-status-filter.png
> * devmgmt-simulator-add.png
> * devmgmt-simulator-alarm.png
> * devmgmt-simulator-fragment.png
> * devmgmt-simulator-instructions.png
> * devmgmt-simulator-sleep.png
> * devmgmt-simulator-supported-operations.png
> * devmgmt-simulator.png
> * devmgmt-smartgroups-icon.png
> * connectivity-jasperadmin.png
> * connectivity-jasperarchitecture.png
>   have no changes, but still show up as being altered in the PR. they are partially ok, but partially it's still the old design, please check.

They have probably been batch processed by @catarino-sag. They have not been updated as part of this PR (since it doesn't cover the whole EPIC/DM app) and will be updated in other PRs.

2023-01-17 10:20 UTC, bozhidardedov commented
> * devmgmt-devices-config-putsnapshot.png is quite different, especially the right side preview

The text in which the image is used explains how to apply configuration to a device, i.e. the lower part of the screen is relevant (the upper shows an operation to retrieve configuration from a device in progress). The new screenshot shows a different kind of configuration file (YAML) which is pretty common configuration file format.

2023-01-17 12:31 UTC, rssag commented
some notes:
* more PRs are good - github seems to have a problem rendering large amounts of image( delta)s. if we could split up the PRs a bit, that will make the review a bit easier as well
* changes to the german IMAGES are fine, however, the changes to the german TEXTS will get overwritten eventually because of the nature of our translation process. I'll remove the changes to those files from the PR (as commit).

2023-01-17 12:41 UTC, rssag approved these changes

2023-01-17 13:42 UTC, bozhidardedov commented
> * fieldbus-modbus-events-log.png has collapsed event items, while the old screenshot had them expanded

By default, all items are collapsed so I don't think a screenshot will all visible items expanded is absolutely correct.

2023-01-17 13:54 UTC, bozhidardedov commented on content/users-guide/device-management-bundle/grouping-devices.md
> -<img src="/images/users-guide/DeviceManagement/devmgmt-group-assignment-new.png" alt="new group">
Here I was lead by the rule that screenshots of small parts of the page are not especially useful. Imho, the text gives enough instructions on where to find the dropdown and how to assign the device.

2023-01-17 13:55 UTC, bozhidardedov commented on content/users-guide/device-management-bundle/monitoring-and-controlling-devices.md
> -![Alarm change status](/images/users-guide/DeviceManagement/devmgmt-alarms-status.png)
Done by merging one of the changes suggested by @rssag .

2023-01-17 14:04 UTC, bozhidardedov commented on content/users-guide/device-management-bundle/monitoring-and-controlling-devices.md
> -    ![Select a bulk operation type](/images/users-guide/DeviceManagement/devmgmt-devicecontrol-bulk-operation-type.png)
I removed the screenshot of step 3 since it's really not very consistent to display a single step only, moreover there are detailed instructions on how to use the device grid in other parts of the documentation. Step 2 differs way too much between the different operation types and isn't a good candidate for a screenshot too, I think. I find the descriptions of the single steps already pretty detailed enough. Do you have any concrete suggestions on what part to improve?

2023-01-17 14:08 UTC, bozhidardedov commented on content/protocol-integration/cloud-fieldbus-bundle/exporting-importing-protocols.md
>  2. In the resulting dialog box, either select a pre-defined protocol or upload a file with a previously exported device protocol.
I only kept it for the reason to have an overview image in the section.

2023-01-17 15:36 UTC, dafkk commented on content/users-guide/device-management-bundle/monitoring-and-controlling-devices.md
> -    ![Select a bulk operation type](/images/users-guide/DeviceManagement/devmgmt-devicecontrol-bulk-operation-type.png)
What I meant was to show more images on the custom steps but now when I think about it I am not so sure. So nvm that one.

2023-01-17 15:43 UTC, dafkk commented on content/users-guide/device-management-bundle/connectivity.md
> -* the SIM is activated. If the SIM card is not activated, you can activate it selecting "Activated" from the status drop-down menu. <br> ![Activate SIM card](/images/users-guide/connectivity/connecti
Yes, the text I saw I meant the image because it is important to be noted that the menu item selected should be "Activated", but if go with the rule everything that everything described does not need to be visualized than we don't need that as well.

2023-01-17 15:48 UTC, merged