Feature/mtm 50973 updated outdated info
SoftwareAG/c8y-docs pull request #804
Opened 2023-01-25 16:11 UTC by pyrocreators

updated screenshots and versions in WEB SDK guide -> Tutorials

2023-01-25 17:20 UTC, janhommes commented on content/web/tutorials-bundle/extend-an-existing-application.md
> +        ...UPGRADE_ROUTES], { enableTracing: false, useHash: true }),
formating here looks really strange, consider a return after `UPGRADE_ROUTES`

2023-01-25 17:20 UTC, janhommes commented on content/web/tutorials-bundle/extend-an-existing-application.md
> +        ...UPGRADE_ROUTES], { enableTracing: false, useHash: true }),
same as above.

2023-01-25 17:20 UTC, janhommes commented on content/web/tutorials-bundle/extend-an-existing-application.md
> +            provide: HOOK_NAVIGATOR_NODES, // 1
we have new convenience methods for the hooks. Can you maybe try to update the providers using them?

see e.g. this example: https://github.softwareag.com/IOTA/cumulocity-ui/blob/872f04c7056cdc698529a2c622d688f8c334abb7/packages/apps/tutorial/input/input.module.ts#L15-L19 

Both ways still work but the functions are now the preferred way. Maybe you also need to update then the text the numbers are referring to.

2023-01-25 17:20 UTC, janhommes commented on content/web/tutorials-bundle/requesting-data-from-a-custom-microservice.md
> +import {CockpitDashboardModule, ReportDashboardModule } from '@c8y/ngx-components/context-dashboard';
here and in other imports. the spacing seems incorrect. It should be:
`import { CockpitDashboardModule, ReportDashboardModule } from '@c8y/ngx-components/context-dashboard';`

Consider using prettier in your IDE (I know it might not work in HUGO)

2023-01-26 12:34 UTC, rssag requested changes

2023-01-26 12:34 UTC, rssag commented on content/web/tutorials-bundle/add-a-custom-widget.md
> +![A dashboard](/images/users-guide/cockpit/cockpit-dashboard-widgets-upd.png)
```suggestion
![A dashboard](/images/users-guide/cockpit/cockpit-dashboard-widgets-upd.png)
```
the screenshots may be replaced, but not renamed. remove all "-upd" suffixes to the file names, both for the files themselves and for the references in the documentation.

additionally: there's one new screenshot in static/images/users-guide/cockpit. why did it end up there instead of static/images/web-sdk?

2023-01-30 10:03 UTC, pyrocreators commented on content/web/tutorials-bundle/add-a-custom-widget.md
> +![A dashboard](/images/users-guide/cockpit/cockpit-dashboard-widgets-upd.png)
@rssag this screenshot actually was there so I just moved the new screen to the old one location, should I move it to web-sdk ?

2023-01-30 12:24 UTC, janhommes requested changes

2023-01-30 12:24 UTC, janhommes commented on content/web/tutorials-bundle/extend-an-existing-application.md
>  For example, to add a navigator node, use the `HOOK_NAVIGATOR_NODE`:
this chapter: https://cumulocity.com/guides/web/tutorials/#3-hooking-a-navigator-node

It needs an update, as we now not anymore use the HOOK_ functions.

maybe something like:

```md  
### 3. Hooking a navigator node
To allow the user to navigate to your newly created `hello.component.ts`, add some navigation to the navigator on the left.
To do so, you will use a so-called hook.
Hooks are providers that are bound to a certain injection token. To allow the addition of multiple providers, use the multi-provider concept of Angular. Explaining it in detail goes beyond the scope of this tutorial. Refer to the [angular.io documentation](https://angular.io/guide/dependency-injection-providers#predefined-tokens-and-multiple-providers).

The injection tokens can be received from the `@c8y/ngx-components` package by importing it.
They all start with `HOOK_` followed by what they are used for. An example of such a hook can look like this:


{
      provide: HOOK_NAVIGATOR_NODES,
      useValue: [{
        label: 'Hello',  
        path: 'hello',
        icon: 'rocket',
        priority: 1000
      }] as NavigatorNode[],         // 1
      multi: true
}

As you see in (1) you need to take care of the typing on your own. To avoid it, you can also use the `hookX` function, which allow the same but without taking care of the boilerplate code. The following example uses these functions, to add a navigator node, using `hookRoute` and `hookNavigatorNode`:
```

2023-01-30 13:26 UTC, janhommes approved these changes

2023-01-30 13:40 UTC, rssag commented
looks like the screenshot static/images/web-sdk/custom-client-service-upd.png is not referenced anywhere. it's also got the -upd suffix in the name

2023-01-30 13:46 UTC, pyrocreators commented
> looks like the screenshot static/images/web-sdk/custom-client-service-upd.png is not referenced anywhere. it's also got the -upd suffix in the name

fixed it

2023-02-03 16:51 UTC, rssag commented on content/web/tutorials-bundle/add-a-custom-widget.md
> +![A dashboard](/images/users-guide/cockpit/cockpit-dashboard-widgets-upd.png)
> @rssag this screenshot actually was there so I just moved the new screen to the old one location, should I move it to web-sdk ?

it's now in both locations. can the one in the users-guide be removed?

2023-02-03 16:59 UTC, pyrocreators commented on content/web/tutorials-bundle/add-a-custom-widget.md
> +![A dashboard](/images/users-guide/cockpit/cockpit-dashboard-widgets-upd.png)
> > @rssag this screenshot actually was there so I just moved the new screen to the old one location, should I move it to web-sdk ?
> 
> it's now in both locations. can the one in the users-guide be removed?

did it

2023-02-07 09:05 UTC, rssag approved these changes

2023-02-07 11:32 UTC, BeateRixen commented
@pyrocreators This PR could be merged but you first need to resolve the comments if they have been done

2023-02-13 10:40 UTC, merged

2023-02-14 15:54 UTC, rssag commented
cherry-picked this manually