DM-2000: Skip nodes without defined namespace
SoftwareAG/c8y-docs pull request #808
Opened 2023-01-27 08:54 UTC by torsSAG

2023-01-27 10:09 UTC, rssag requested changes

2023-01-27 10:09 UTC, rssag commented on content/protocol-integration/opcua-bundle/authentication.md
> +In the case a node is found with a non-existing name space entry the scan process skips this node and goes on.
```suggestion
In case a node is found with a non-existing name space entry the scan process skips this node and continues.
```

2023-01-27 10:09 UTC, rssag commented on content/protocol-integration/opcua-bundle/authentication.md
> +An error entry will be written to the log file to provide information for fixing it (more information available in debug level).
```suggestion
An error entry is written to the log file with information on how to fix the issue. Set the log level to DEBUG to add more information.
```
not sure if that is what the sentence was supposed to say.

2023-01-27 13:35 UTC, torsSAG commented on content/protocol-integration/opcua-bundle/authentication.md
> +In the case a node is found with a non-existing name space entry the scan process skips this node and goes on.
done

2023-01-30 09:02 UTC, rssag approved these changes

2023-01-31 14:39 UTC, torsSAG commented on content/protocol-integration/opcua-bundle/authentication.md
> +In case a node is found with a non-existing name space entry the scan process skips this node and continues.
fixed

2023-01-31 14:44 UTC, sourajitsaha17 approved these changes

2023-02-01 11:27 UTC, merged