DM-1832 MQTT Static templates 504, 505, 506 (updating operation by id).
SoftwareAG/c8y-docs pull request #824
Opened 2023-01-31 19:31 UTC by MaciekSoftwareAG

2023-02-01 08:16 UTC, rssag requested changes

2023-02-01 08:16 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +##### Set operation to EXECUTING by operation id (504)
```suggestion
##### Set operation to EXECUTING (504)
```

2023-02-01 08:16 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +Set the operation with given id to EXECUTING. The operation must exist and must have requesting device as the source.
```suggestion
Set the operation with the given ID to EXECUTING. The operation must exist and must have the requesting device as the source.
```

2023-02-01 08:16 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +##### Set operation to FAILED by operation id (505)
```suggestion
##### Set operation to FAILED (505)
```

2023-02-01 08:16 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +Set the operation with given id to FAILED. The operation must exist and must have requesting device as the source.
```suggestion
Set the operation with the given ID to FAILED. The operation must exist and must have the requesting device as the source.
```

2023-02-01 08:16 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +Set the operation with given id to SUCCESSFUL. The operation must exist and must have requesting device as the source.
```suggestion
Set the operation with given ID to SUCCESSFUL. The operation must exist and must have the requesting device as the source.
```

2023-02-01 08:16 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +##### Set operation to EXECUTING by operation id (504)
out of curiosity, why is this three templates, each with a fixed operation status, instead of a single template with the status as a 2nd parameter?

2023-02-01 09:41 UTC, MaciekSoftwareAG commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +##### Set operation to EXECUTING by operation id (504)
What do you think Philipp?

2023-02-01 13:43 UTC, rssag approved these changes

2023-02-07 11:29 UTC, BeateRixen commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +##### Set operation to EXECUTING by operation id (504)
@l2p- Please see comment above

2023-02-13 15:46 UTC, rssag commented
what are the target versions? @MaciekSoftwareAG

2023-02-13 21:49 UTC, MaciekSoftwareAG commented
> what are the target versions? @MaciekSoftwareAG

Not sure, waiting for the actual change to be merged.

2023-03-03 22:32 UTC, jkot-softwareag approved these changes

2023-03-13 17:58 UTC, l2p- approved these changes

2023-03-13 18:03 UTC, l2p- commented
> > > what are the target versions? @MaciekSoftwareAG
> > 
> > 
> > Not sure, waiting for the actual change to be merged.
> 
> alright, added the "on hold" label for the time being

This change is planned for 10.18

2023-03-14 08:54 UTC, rssag commented
> > > > what are the target versions? @MaciekSoftwareAG
> > > 
> > > 
> > > Not sure, waiting for the actual change to be merged.
> > 
> > 
> > alright, added the "on hold" label for the time being
> 
> This change is planned for 10.18

should we wait? since it's planned - sounds like it's not certain yet.

2023-03-21 08:53 UTC, merged