DM-1820 SmartREST static template 143.
SoftwareAG/c8y-docs pull request #825
Opened 2023-01-31 20:42 UTC by MaciekSoftwareAG

2023-02-01 08:17 UTC, rssag requested changes

2023-02-01 08:17 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +Set supported software types of the device. Ignores empty elements. Empty list removes c8y_SupportedSoftwareTypes fragment entirely.
```suggestion
Set the supported software types of the device. Ignores empty elements. An empty list removes the `c8y_SupportedSoftwareTypes` fragment entirely.
```

2023-02-01 13:42 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> ++ <a href="#143">143,supportedSoftwareType1,supportedSoftwareType2,…</a>
```suggestion
+ <a href="#143">143,supportedSoftwareType1,supportedSoftwareType2,...</a>
```

2023-02-01 13:42 UTC, rssag approved these changes

2023-02-01 19:04 UTC, l2p- approved these changes

2023-02-07 11:28 UTC, BeateRixen commented
@MaciekSoftwareAG Can this PR be merged? And to which releases does it apply?

2023-02-07 11:29 UTC, MaciekSoftwareAG commented
> @MaciekSoftwareAG Can this PR be merged? And to which releases does it apply?

Yes, I just waiting for the actual new code to be merged first.

2023-02-07 11:57 UTC, rssag commented
what are the target versions though?

2023-03-29 13:49 UTC, merged