DM-1821 SmartRest static templates 123 and 124.
SoftwareAG/c8y-docs pull request #826
Opened 2023-01-31 21:04 UTC by MaciekSoftwareAG

2023-02-01 08:25 UTC, rssag requested changes

2023-02-01 08:25 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +##### Get device managed object id (123)
```suggestion
##### Get the device managed object ID (123)
```

2023-02-01 08:25 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +Trigger sending of the id of the device managed object.
```suggestion
Retrieve the ID of the device managed object.
```

2023-02-01 08:25 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +##### Get device managed object id (124)
```suggestion
##### Get the device managed object ID (124)
```

2023-02-01 08:25 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +Gets the id of the device managed object.
```suggestion
Retrieve the ID of the device managed object.
```

2023-02-01 13:43 UTC, rssag approved these changes

2023-02-01 18:51 UTC, l2p- commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +106,id
```suggestion
124,12345
```
We use real examples in other places instead of placeholders + typo in the mesage ID

2023-02-01 18:55 UTC, l2p- commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> ++ <a href="#123">123</a>
```suggestion
+ <a href="#123">123 (Get internal ID, reply: 124,id)</a>
```

2023-02-06 10:31 UTC, MaciekSoftwareAG commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +106,id
Thanks

2023-02-14 20:57 UTC, jkot-softwareag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +Retrieve the ID of the device managed object.
I think this is called in the documentation `global ID` or `internal ID`. @rssag am I correct?

You can consider mentioning that it is based on serial of "current device" or "current connection", but maybe it is obvious or can be mentioned in 123.

2023-02-14 21:18 UTC, MaciekSoftwareAG commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +Retrieve the ID of the device managed object.
Is it based on the serial? I don't know this. How do you know?

2023-02-15 09:48 UTC, jkot-softwareag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +Retrieve the ID of the device managed object.
From the implementation. If I understand it correctly you are connecting device via MQTT, with some ClientId, and sending `123` message on static smartREST topic. 

Device ID (GId) is resolved in all such scenarios based on `c8y_Serial` which exactly fits `ClientId` header from mqtt client (or Managed Object is created if nothing found). This is how you can create all MEA stuff for a device without knowing its GID. I think your new feature just retrieves this GId and return it in `124` message.

@l2p- am I correct or missunderstand something?

2023-02-21 12:52 UTC, rssag commented on content/reference/smartrest-two-bundle/mqtt-static-templates.md
> +Retrieve the ID of the device managed object.
there's something about a global identifier here:
https://cumulocity.com/guides/concepts/domain-model/#object-identification

in the inventory API, managed objects just have a field "id" for the ID though.

2023-02-21 13:10 UTC, jkot-softwareag approved these changes

2023-02-22 13:07 UTC, rssag commented
what are the target versions? @MaciekSoftwareAG 
also, there's one more change request by @l2p-

2023-03-13 16:01 UTC, l2p- approved these changes

2023-03-13 18:04 UTC, l2p- commented
> what are the target versions?
10.18

2023-03-14 08:53 UTC, merged