[DM-1977] Update screenshots in Protocol Integration: LWM2M
SoftwareAG/c8y-docs pull request #828
Opened 2023-02-01 15:14 UTC by JacekGonera

Update screenshots, remove unnecessary ones and update texts

2023-02-01 16:41 UTC, rssag requested changes

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  The following operations may be available in each instance:
i think we should add a clue where to find the operations (the "three dots" icon at the end of each object row)

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  Additional information on recent operations can be viewed by clicking the operations button located at the right side of an instance card. The button is only visible if any operation has been perform
you deleted "the example below", i think this is referring to the screenshots.
i think the first screenshot below is actually useful - maybe not in full size, but maybe showcasing a single object with the button that is otherwise invisible.

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  To view the history of all operations, simply click **View history**. Note, that you will be redirected to the **Control** tab.
```suggestion
To view the history of all operations, click **View history**. Note, that you will be redirected to the **Control** tab.
```
also, this is referring to a screenshot that is no longer there. a description is required here where the user is in the UI, if it's no longer clear from the screenshots.

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  3. In the upcoming dialog select **LWM2M** as device protocol type. <br><br>
```suggestion
3. In the upcoming dialog select **LWM2M** as device protocol type.
```

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  If the DDF files for the default mappings are uploaded in the {{< management-tenant >}}, all subscribed user tenants will inherit this behavior. <br><br>
```suggestion
If the DDF files for the default mappings are uploaded in the {{< management-tenant >}}, all subscribed user tenants will inherit this behavior.
```

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  5. In the next dialog, you can see the name and description of the protocol. Click **Complete** to create the new device protocol. <br><br>
```suggestion
5. In the next dialog, you can see the name and description of the protocol. Click **Complete** to create the new device protocol.
```

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  In the device protocol page, you will see the description at the top left and the ID, the creation date and date of the last update at the top right.
```suggestion
In this page, you see the description at the top left and the ID, the creation date and the date of the last update at the top right.
```
Also make this one paragraph with "The device protocol will open in a new page."

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  Below, a list of resources configured for the device will be listed (which is empty when creating a new protocol), showing the ID, name and potentially configured functionalities for each resource.
```suggestion
Below that, there is a list of resources configured for the device (which is empty when creating a new protocol), showing the ID, name and potentially configured functionalities for each resource.
```

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  The functionalities that you may enable are the following:
```suggestion
See below for the functionalities that you may enable.
```

Not that it was particularly clear how to get here even with the screenshots, but now it's quite nebulous. A sentence is missing that explains how to access resource functionalities.

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  Actions that are relevant for Device (/3):
what does "(/3)" mean?
also, there might be an article missing and why is "Device" capitalized?
same for the line containing "(/4)" below (i can't comment it directly)

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  There are 2 types of alarms raised related to device protocol mapping failures.
```suggestion
There are 2 types of alarms raised related to device protocol mapping failures:
```

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> -![Resource](/images/device-protocols/lwm2m/lwm2m-autoobserve.png)
this screenshot had the information that there is an icon in the resources list that means "auto-observe active for the resource". without the screenshot, this information is lost, unless we add a sentence explaining it.

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/register-device.md
>  The bulk device registration operation will be displayed in the [LWM2M connector device](#connector-device) object created for the tenant.
make it one paragraph with line 50

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/validation-rules.md
>  Click **Save** to save your settings.
```suggestion
To delete a rule, click on the red delete icon on the right side of that rule. Click **Save** to save your settings.
```

2023-02-01 16:41 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/validation-rules.md
> -The screenshot above provides an example for the use of validation rule groups: User input is valid if the given string does not match "test" (equals not). It is also valid if it ends with "asd" and
an example might be actually be useful here :thinking:

2023-02-02 15:30 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
> -![Read Objects](/images/device-protocols/lwm2m/lwm2m-devices-readobject.png)
It is not. Removed.

2023-02-02 15:30 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
> -![Read Instance](/images/device-protocols/lwm2m/lwm2m-devices-readinstance.png)
It is not. Removed.

2023-02-02 15:30 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  The following operations may be available in each instance:
Clue added.

2023-02-02 15:30 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  To view the history of all operations, simply click **View history**. Note, that you will be redirected to the **Control** tab.
Removed the refference and added a small info about tooltip.

2023-02-02 15:30 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  3. In the upcoming dialog select **LWM2M** as device protocol type. <br><br>
Done.

2023-02-02 15:30 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  If the DDF files for the default mappings are uploaded in the {{< management-tenant >}}, all subscribed user tenants will inherit this behavior. <br><br>
Done.

2023-02-02 15:30 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  5. In the next dialog, you can see the name and description of the protocol. Click **Complete** to create the new device protocol. <br><br>
Done.

2023-02-02 15:31 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  In the device protocol page, you will see the description at the top left and the ID, the creation date and date of the last update at the top right.
Done.

2023-02-02 15:31 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  Below, a list of resources configured for the device will be listed (which is empty when creating a new protocol), showing the ID, name and potentially configured functionalities for each resource.
Done.

2023-02-02 15:31 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  There are 2 types of alarms raised related to device protocol mapping failures.
Done.

2023-02-02 15:31 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> -![Resource](/images/device-protocols/lwm2m/lwm2m-autoobserve.png)
Done.

2023-02-02 15:31 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/register-device.md
>  The bulk device registration operation will be displayed in the [LWM2M connector device](#connector-device) object created for the tenant.
Done.

2023-02-02 15:31 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/validation-rules.md
>  Click **Save** to save your settings.
Done.

2023-02-02 15:31 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/validation-rules.md
> -The screenshot above provides an example for the use of validation rule groups: User input is valid if the given string does not match "test" (equals not). It is also valid if it ends with "asd" and
Done.

2023-02-02 15:35 UTC, JacekGonera commented
Couldn't fix all yet - will continue on monday, because I faced a 502 bad gateway error on all tenants known to me (even local) and tomorrow I'm out of office.

2023-02-02 15:49 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  Additional information on recent operations can be viewed by clicking the operations button located at the right side of an instance card. The button is only visible if any operation has been perform
Fixed.

2023-02-02 15:57 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  The functionalities that you may enable are the following:
Added.

2023-02-06 10:31 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
>  Actions that are relevant for Device (/3):
They are object ID's for LWM2M shell commands. Added explanation and example.

2023-02-07 10:08 UTC, rssag requested changes

2023-02-07 10:08 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +To access resource functionalities you need to proceed to the device protocol page and click on one of the resources instances. See below for the functionalities that you may enable:
```suggestion
To access resource functionalities proceed to the device protocol page and click one of the resource instances. See below for the functionalities that you may enable:
```

2023-02-07 10:08 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +Actions that are relevant for device object (object id /3):
```suggestion
Actions that are relevant for a device object (object ID /3):
```
not sure if "a" or "the" (device) is better here?

2023-02-07 10:08 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +Actions that are relevant for connectivity monitoring (object id /4):
```suggestion
Actions that are relevant for connectivity monitoring (object ID /4):
```

2023-02-07 10:16 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> -![Resource](/images/device-protocols/lwm2m/lwm2m-autoobserve.png)
I brought back the screenshot in line above.

2023-02-07 15:23 UTC, sag-eweingaertner commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +The following operations may be available in each instance after clicking the "three dots" icon at the end of each object row:
Rather than writing three dots: Can't we simply include the three dots glyph (⋮) in the documentation?

2023-02-07 15:23 UTC, sag-eweingaertner commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +The following operations may be available in each instance after clicking the "three dots" icon at the end of each object row:
Alternatively, as an image: 
![image](https://user-images.githubusercontent.com/92789995/217286999-1e2962f4-cd87-4245-a088-94665636b723.png)

2023-02-07 15:27 UTC, sag-eweingaertner commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +More information can be acquired for each resource by hovering over the tooltip icon present on the right of the field name.
Again, here you are verbally explaining how a button looks like. You could simply add the glyph or a picture of the icon ![image|width=12px](https://user-images.githubusercontent.com/92789995/217288070-b2140f58-f1b4-4245-a093-470a812b7eb6.png)

2023-02-07 15:30 UTC, sag-eweingaertner commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +Additional information on recent operations can be viewed by clicking the operations button located at the right side of an instance card. The button is only visible if any operation has been perform
Use image 
<img width="56" alt="image" src="https://user-images.githubusercontent.com/92789995/217288819-a92775ce-fcf8-46b0-a3ae-b61ad70a16fa.png"> or glyph

2023-02-07 15:35 UTC, BeateRixen commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +The following operations may be available in each instance after clicking the "three dots" icon at the end of each object row:
We  use the term "menu icon" for this icon throughout the documentation. We can use an image in case of an icon as an add-on, but we still need to name it, otherwise the text is not readable.

2023-02-07 16:27 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +The following operations may be available in each instance after clicking the "three dots" icon at the end of each object row:
```suggestion
The following operations may be available in each instance after clicking themenu icon at the end of each object row:
```

2023-02-07 16:29 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +More information can be acquired for each resource by hovering over the tooltip icon present on the right of the field name.
> Again, here you are verbally explaining how a button looks like. You could simply add the glyph or a picture of the icon <img alt="" width="18px" src="https://user-images.githubusercontent.com/92789995/217288070-b2140f58-f1b4-4245-a093-470a812b7eb6.png">

see @BeateRixen 's comment on "menu icon". it's good to have a description in case the image doesn't render for whatever reason.

2023-02-07 16:30 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +Additional information on recent operations can be viewed by clicking the operations button located at the right side of an instance card. The button is only visible if any operation has been perform
> Use image <img alt="image" width="56" src="https://user-images.githubusercontent.com/92789995/217288819-a92775ce-fcf8-46b0-a3ae-b61ad70a16fa.png"> or glyph

see @BeateRixen 's comment on "menu icon". it's good to have a description in case the image doesn't render for whatever reason. the image is included in the screenshot below i think

2023-02-07 16:44 UTC, Oezge-Akin requested changes
Regarding screenshots:
- Please use a realistic looking lwm2m device name for the screenshots. lwm2m-test-nosec or lwm2m-test-psk doesn't look good.
You can check the syntax for the LWM2M endpoint name here:
https://md2html-tool.com/docs/OpenMobileAlliance/Test_LwM2M_v1_1/development/bb80921/TS_Core/OMA-TS-LightweightM2M_Core-V1_1_1-2019MMDD-D_full.html#7-3-1-0-731-Endpoint-Client-Name

- lwm2m-objects.png does not have resources for object /3 shown there but previous screenshot had more information, you can do a read operation after connecting our simulation device, it will show more info afterwards.

- lwm2m-post-operations.png the used /3002 and /301 objects does not exist if you check LwM2M Objects from here: https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html
you can do 
read /3303
discover /3
instead.

2023-02-07 16:44 UTC, Oezge-Akin commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +The device protocol opens in a new page. You can the description at the top left while the ID, the creation date and the date of the last update are at the top right.
verb is missing in "You can the description ..."

2023-02-07 17:14 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +The device protocol opens in a new page. You can the description at the top left while the ID, the creation date and the date of the last update are at the top right.
> verb is missing in "You can the description ..."

oh, should be "You can find the description.." - i think that was my bad

2023-02-08 07:12 UTC, dominikschmitz commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +There are 2 types of alarms raised related to device protocol mapping failures:
two instead of 2
@rssag can you confirm?

2023-02-08 09:07 UTC, sag-eweingaertner reviewed
static/images/device-protocols/lwm2m/lwm2m-objects.png shows an input validation error. This is a bug that was already fixed on develop. Maybe just enter a value to make this red error go away

2023-02-10 08:00 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +The following operations may be available in each instance after clicking the "three dots" icon at the end of each object row:
Added both text and glyph.

2023-02-10 08:00 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +Additional information on recent operations can be viewed by clicking the operations button located at the right side of an instance card. The button is only visible if any operation has been perform
Yes, it is visible in a screenshot below.

2023-02-10 08:00 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +The following operations may be available in each instance after clicking the "three dots" icon at the end of each object row:
Updated.

2023-02-10 08:00 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +The device protocol opens in a new page. You can the description at the top left while the ID, the creation date and the date of the last update are at the top right.
Updated.

2023-02-10 08:00 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +There are 2 types of alarms raised related to device protocol mapping failures:
Updated.

2023-02-13 16:41 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +More information can be acquired for each resource by hovering over the tooltip icon present on the right of the field name.
Added icon and text.

2023-02-14 13:48 UTC, rssag approved these changes

2023-02-20 15:18 UTC, Oezge-Akin commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  Some object cards show additional operations which can be performed. These operations become available after reading the object/instance, for example, device **Update**. In order to perform the opera
It is not device **Update** but device **Firmware update**. Since the image is removed now example sounds strange. 

The first sentence is good 
Some object cards show additional operations which can be performed. These operations become available after reading the object/instance.

Maybe after this you can list the possible options about "Write", "Execute" and "Execute with parameters"

2023-02-20 15:18 UTC, Oezge-Akin commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  If enabled, the agent will periodically look for starved operations of a tenant and fail them automatically.
Without the image this description is weird. This is not related to Objects tab, it is actually related to operations shown in the Control tab.
Please move the text to appropriate place maybe as an info in the end of "Shell command lifecycle" section

2023-02-20 15:18 UTC, Oezge-Akin commented on content/protocol-integration/lwm2m-bundle/validation-rules.md
> +Validation rules can only be added to resources which have "write" permissions. Resources which can have validation rules are marked by the grey icon on the right side of resource. When hovering over
Since there is an image already can you show in the image instead explaining the grey icon :)?

2023-02-22 08:43 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/validation-rules.md
> +Validation rules can only be added to resources which have "write" permissions. Resources which can have validation rules are marked by the grey icon on the right side of resource. When hovering over
Changed.

2023-02-22 08:43 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  If enabled, the agent will periodically look for starved operations of a tenant and fail them automatically.
Changed.

2023-02-22 08:43 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  Some object cards show additional operations which can be performed. These operations become available after reading the object/instance, for example, device **Update**. In order to perform the opera
Changed.

2023-02-22 08:44 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +The device protocol opens in a new page. You can find the description at the top left while the ID, the creation date and the date of the last update are at the top right.
Changed.

2023-02-22 08:44 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +5. In the next dialog, you can see the name and description of the protocol. Click **Complete** to create the new device protocol.
Changed.

2023-02-22 09:12 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> -![Example protocol](/images/device-protocols/lwm2m/lwm2m-protocol-example.png)
Added.

2023-02-23 07:52 UTC, Oezge-Akin commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +Some object cards show additional operations which can be performed. These operations become available after reading the object/instance. THe possible options are **Write**, **Execute** and **Execute
THe -> The

2023-02-23 07:52 UTC, Oezge-Akin commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  If enabled, the agent will periodically look for starved operations of a tenant and fail them automatically.
I meant to move the paragraph about
If enabled, the agent will periodically look for starved operations of a tenant and fail them automatically. ...
as a note.

You can keep the "To view the history of all operations, click **View history**. Note, that you will be redirected to the **Control** tab." as before

2023-02-23 08:16 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
>  If enabled, the agent will periodically look for starved operations of a tenant and fail them automatically.
Ok, changed.

2023-02-23 08:16 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-details.md
> +Some object cards show additional operations which can be performed. These operations become available after reading the object/instance. THe possible options are **Write**, **Execute** and **Execute
Done.

2023-02-24 13:07 UTC, Oezge-Akin reviewed
Regarding lwm2m-devices-bootstrap.png PSK selected but mandatory fields are not written. Can you retake the screenshot with NO_SEC?

2023-02-24 15:11 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/device-protocols.md
> +Below that, there is a list of resources configured for the device will be listed (which is empty when creating a new protocol), showing the ID, name and potentially configured functionalities for ea
Done.

2023-02-27 08:08 UTC, Oezge-Akin approved these changes

2023-02-27 08:26 UTC, sag-eweingaertner approved these changes

2023-02-27 08:27 UTC, merged