Added Partial Address Scan
SoftwareAG/c8y-docs pull request #839
Opened 2023-02-03 11:57 UTC by mstoffel-sag

Partial Address Space description
Rescan button

2023-02-03 13:22 UTC, rssag requested changes

2023-02-03 13:22 UTC, rssag commented on content/protocol-integration/opcua-bundle/connecting-gateway.md
> +8. Under Advanced Settings the mode of the OPC-UA Servers address scan can be configured. Is Auto Address Scan set to enabled the gateway will immediately start scanning after the new server connecti
```suggestion
8. You can configure  the mode of the OPC UA server address scan under **Advanced settings**. If automatic address scanning is enabled the gateway immediately starts the scan after the new server connection is saved.
```

2023-02-03 13:22 UTC, rssag commented on content/protocol-integration/opcua-bundle/connecting-gateway.md
> +You can add further Node Id's later and do a rescan in the Address Space tab of the Server Object afterwards.
```suggestion
    {{< c8y-admon-caution >}}
Be cautious with the address scan type. If it is set to "full", the gateway will scan the whole OPC UA server address space. Depending on the address space size and the speed of the OPC UA server this can take from minutes to days. We highly recommend you to set the address scan type to "partial" and configure only those node IDs you really want to scan.
You can add further node IDs later and do a rescan in the address space tab of the server object afterwards.
    {{< /c8y-admon-caution >}}
```

2023-02-03 13:44 UTC, mstoffel-sag commented on content/protocol-integration/opcua-bundle/authentication.md
> +To manually scan the address space (depending on the Address Scan Type Full / Partial) hit the rescan button. You can monitor the progress by checking the rescan operation under the control tab.
Its actually not dependent. Pease remove the sentence. Feel free using caps. 
After clicking the rescan button an operation is created and displayed under the control section. It will be named c8y_ua_command_ScanAddressSpace.

2023-02-06 17:20 UTC, rssag requested changes

2023-02-06 17:20 UTC, rssag commented on content/protocol-integration/opcua-bundle/authentication.md
> +To manually scan the address space hit the rescan button. You can monitor the progress by checking the rescan operation under the control tab.
```suggestion
To manually scan the address space click **Rescan**. You can monitor the progress by checking the rescan operation in the control tab.
```

2023-02-06 17:20 UTC, rssag commented on content/protocol-integration/opcua-bundle/operations.md
> +To do a partial address space scan, you can provide the `nodeIds` property which contains all nodes ID's that should be scanned.
```suggestion
To do a partial address space scan, you can provide the `nodeIds` property which contains all node IDs that should be scanned.
```

2023-02-06 17:20 UTC, rssag commented on content/protocol-integration/opcua-bundle/operations.md
> +The subaddress space starting from those nodes as well as the ancestor nodes will be persisted in the Cumulocity IoT inventory (unless `"skipSync": true` is provided) as well as in the local address
```suggestion
The subaddress space starting from those nodes as well as the ancestor nodes are persisted both in the {{< product-c8y-iot >}} inventory, unless `skipSync` is set to `true`, and in the local address space file of the gateway.
```

2023-02-06 17:20 UTC, rssag commented on content/protocol-integration/opcua-bundle/connecting-gateway.md
> +8. You can configure  the mode of the OPC UA server address scan under **Advanced settings**. If automatic address scanning is enabled the gateway immediately starts the scan after the new server con
```suggestion
8. You can configure the mode of the OPC UA server address scan under **Advanced settings**. If automatic address scanning is enabled the gateway immediately starts the scan after the new server connection is saved.
```

2023-02-07 09:10 UTC, rssag approved these changes

2023-02-07 09:10 UTC, rssag commented
what are the target versions? @mstoffel-sag

2023-02-07 09:53 UTC, mstoffel-sag commented
> what are the target versions? @mstoffel-sag

Actually I dont know. Please ask @Oezge-Akin

2023-02-21 10:09 UTC, BeateRixen commented
@Oezge-Akin We need approval for this PR from a developer and we need to know to which versions this should go.

2023-05-26 08:49 UTC, MWindel commented
@mstoffel-sag The screenshot static/images/device-protocols/opcua/opcua-new-server.png needs to be resized so the height (H) is max. 900 px.

2023-05-26 08:50 UTC, mstoffel-sag commented
> @mstoffel-sag The screenshot static/images/device-protocols/opcua/opcua-new-server.png needs to be resized so the height (H) is max. 900 px.

Thanks,  feel free to change that.

2023-05-26 12:07 UTC, rssag commented
can't checkout SoftwareAG:develop nor mstoffel-sag:feature/opcua-address-space-scan-UI-improvements as usual.
seems like you forked the develop branch?

2023-07-27 09:37 UTC, Oezge-Akin commented
@rssag @BeateRixen @MWindel fyi. the implementation change isn't merged to the product yet and due to other priorities this is delayed. Our team will take over this and will notify you when this is ready to be reviewed again.

2023-08-29 13:47 UTC, closed without merging