Fixed OpenAPI links
SoftwareAG/c8y-docs pull request #85
Opened 2021-11-11 16:24 UTC by JoshuaAdemola

2021-11-11 16:38 UTC, rssag commented
hm... i'm not sure the openapi spec is in a state where it's a proper replacement for the JSON file we currently have in the documentation. @manasesjesus ?

2021-11-11 16:48 UTC, manasesjesus requested changes
this Postman collection JSON is different from the OAS JSON. The first one contains many different examples of all core APIs, plus other examples such as SmartREST. The second one is only the OpenAPI Specification and not a Postman collection; importing/transforming it requires extra steps that we want to automate (those tasks are in my TODO list). Hence, this link should stay as it is, and when the OAS Postman is ready, it'll be included.

2021-11-15 08:58 UTC, BeateRixen commented
OK, @JoshuaAdemola then we should close this PR and add a comment to the BH task.

2021-11-23 12:46 UTC, manasesjesus reviewed
Postman got plenty of updates and that button part is not longer valid. Added suggestions to remove it and update the redaction.

2021-11-23 12:46 UTC, manasesjesus commented on content/microservice-sdk/rest-bundle/overview.md
>  {{< product-c8y-iot >}} provides numerous online API examples. If you want to make use of them, [download and install Postman](https://www.getpostman.com/). After starting Postman, you can choose to
```suggestion
{{< product-c8y-iot >}} provides numerous online API examples. If you want to make use of them, [download and install Postman](https://www.getpostman.com/). After starting Postman, you can choose to either create an account or click **Take me straight to the app**.
```

2021-11-23 12:46 UTC, manasesjesus commented on content/microservice-sdk/rest-bundle/overview.md
> +Import the {{< openapi >}} as a [JSON file](https://www.{{< domain-c8y >}}/api/{{< c8y-current-version >}}/dist/c8y-oas.json).
```suggestion
Download the [API examples](/files/rest/Cumulocity_API.postman_collection.json) and import them as a collection into Postman.
```

2021-11-23 14:56 UTC, manasesjesus approved these changes

2021-11-25 06:44 UTC, rssag approved these changes

2021-11-29 08:11 UTC, BeateRixen approved these changes

2021-11-29 08:12 UTC, MWindel approved these changes

2021-11-30 09:11 UTC, merged