DM-2000: Different wording
SoftwareAG/c8y-docs pull request #866
Opened 2023-02-10 13:14 UTC by torsSAG

For release after 10.17

2023-02-10 15:49 UTC, Oezge-Akin approved these changes

2023-02-10 15:51 UTC, sag-eweingaertner approved these changes

2023-02-10 15:52 UTC, sag-eweingaertner commented on content/protocol-integration/opcua-bundle/authentication.md
> +In case a node can not be read the scan process skips this node and continues.
, after read

2023-02-10 15:53 UTC, sag-eweingaertner requested changes
Please add the missing comma

2023-02-13 11:28 UTC, Oezge-Akin approved these changes

2023-02-13 15:42 UTC, rssag commented on content/protocol-integration/opcua-bundle/authentication.md
> +An error entry will be written to the opcua-device-gateway log file to provide information (more information available in debug level).
```suggestion
An error entry is written to the opcua-device-gateway log file to provide information (more information available in debug level).
```

2023-02-15 14:39 UTC, rssag commented on content/protocol-integration/opcua-bundle/authentication.md
> +In case a node can not be read, the scan process skips this node and continues.
```suggestion
In case a node cannot be read, the scan process skips this node and continues.
```

2023-02-15 14:39 UTC, rssag approved these changes

2023-02-15 15:04 UTC, sag-eweingaertner approved these changes

2023-02-16 05:44 UTC, merged