DM-1013 Fix properties in OPC UA failure handling
SoftwareAG/c8y-docs pull request #869
Opened 2023-02-13 13:02 UTC by sag-eweingaertner

Another OPC UA doc fix.

2023-02-13 15:35 UTC, rssag requested changes

2023-02-13 15:35 UTC, rssag commented on content/protocol-integration/opcua-bundle/device-protocols.md
> +|noRetryHttpCodes| Comma-separated list of HTTP response codes | 400,500 |  If retries are enabled (failureHandling.enabled=true), this setting allows retries to be skipped for certain HTTP response
```suggestion
|noRetryHttpCodes| Comma-separated list of HTTP response codes | 400,500 |  If retries are enabled (failureHandling.enabled=true), this setting allows retries to be skipped for certain HTTP response codes. In the given example invocations to the HTTP endpoint that receive a `400 Bad Request` or `500 Internal server error` response are skipped.|
```

2023-02-13 15:35 UTC, rssag commented on content/protocol-integration/opcua-bundle/device-protocols.md
> +|maxRetries| number | 5 | Number of retries for failed queues; if the maximum is reached the queue will be saved as permanently failed and never retried again, default is 5.|
```suggestion
|maxRetries| number | 5 | Number of retries for failed queues. If the maximum is reached the queue is saved as permanently failed and never retried again. Default is 5.|
```

2023-02-13 15:35 UTC, rssag commented on content/protocol-integration/opcua-bundle/device-protocols.md
> +All elements of the queue will be retried after the retry delay has passed. In effect, the count of the elements in the queue will be decreasing with each successful retried custom action.
```suggestion
All elements of the queue are retried after the retry delay has passed. In effect, the count of the elements in the queue is decreases with each successful retried custom action. 
```

2023-02-13 15:35 UTC, rssag commented
what are the target versions? @sag-eweingaertner

2023-02-14 09:58 UTC, sag-eweingaertner commented
> what are the target versions? @sag-eweingaertner

Added 10.17 and auto-backport.

2023-02-14 14:08 UTC, rssag approved these changes

2023-02-15 12:43 UTC, bggov approved these changes

2023-02-17 07:12 UTC, Oezge-Akin commented on content/protocol-integration/opcua-bundle/device-protocols.md
> +In the gateway configuration (see also [Gateway Configuration: Additional customization](#additional-customizations)) the following parameters can be configured:
property group information is not mentioned.
gateway.mappingExecution.http.failureHandling

2023-02-17 07:12 UTC, Oezge-Akin commented on content/protocol-integration/opcua-bundle/device-protocols.md
> +|enabled  | boolean (true/false) | true | Activate or deactivate the fail over for custom actions |
Information about the defaults are missing.

2023-02-21 10:14 UTC, merged

2023-02-21 10:16 UTC, rssag commented
cherry-picked manually.