[DM-1989] [DOC] Add availability and prerequisites of LWM2M
SoftwareAG/c8y-docs pull request #878
Opened 2023-02-14 12:31 UTC by JacekGonera

Add information about agent prerequsites

2023-02-14 14:47 UTC, BeateRixen commented on content/protocol-integration/lwm2m-bundle/overview.md
> +{{< c8y-admon-important >}}
@rssag I suggest to better create a requirement admonition here?

2023-02-14 15:22 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/overview.md
> +{{< c8y-admon-important >}}
in this exact place?

2023-02-14 15:24 UTC, rssag requested changes

2023-02-14 15:24 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/overview.md
> +In order to use LWM2M, you must be subscribed to the LWM2M-agent application. If the LWM2M-agent is not available in your tenant, please contact [product support](/welcome/contacting-support/).
```suggestion
In order to use LWM2M, you must be subscribed to the LWM2M-agent application. If the LWM2M-agent is not available in your tenant, [contact product support](/welcome/contacting-support/).
```

2023-02-14 15:24 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/overview.md
> +{{< c8y-admon-important >}}
```suggestion
{{< c8y-admon-req >}}
```

2023-02-14 15:24 UTC, rssag commented on content/protocol-integration/lwm2m-bundle/overview.md
> +{{< /c8y-admon-important >}}
```suggestion
{{< /c8y-admon-req >}}
```

2023-02-14 15:27 UTC, JacekGonera commented on content/protocol-integration/lwm2m-bundle/overview.md
> +{{< c8y-admon-important >}}
Commited the suggestions.

2023-02-21 10:17 UTC, rssag approved these changes

2023-02-22 06:50 UTC, dominikschmitz approved these changes

2023-02-22 08:16 UTC, merged