CIE-4483
SoftwareAG/c8y-docs pull request #894
Opened 2023-02-17 19:07 UTC by sharath-jk

2023-02-21 12:12 UTC, BeateRixen commented on content/edge/remote-connectivity.md
>  This section describes configuring and managing your Edge appliance remotely.
```suggestion
This section describes how to configure and manage your Edge appliance remotely.
```

2023-02-21 12:13 UTC, BeateRixen commented
@sharath-jk With this PR you changed several file names. How about links that might point to these files from inside and outside the Edge documentation? Do we need to adapt them somewhere? And do we need aliases to redirect to the new files?

2023-03-06 15:50 UTC, sharath-jk commented
@bbyreddy - here is the doc link for review:
http://vmbandoc.eur.ad.sag/c8y/edge/edge-introduction/

2023-03-31 05:51 UTC, bbyreddy approved these changes

2023-04-03 10:52 UTC, BeateRixen commented on content/edge/configuration-bundle/changing-domain-name.md
> +A key feature of the {{< product-c8y-iot >}} Edge is the ability to operate the {{< product-c8y-iot >}} platform using a custom domain name. This means that you can configure the Edge appliance to se
```suggestion
A key feature of {{< product-c8y-iot >}} Edge is the ability to operate the {{< product-c8y-iot >}} platform using a custom domain name. This means that you can configure the Edge appliance to serve you using a domain name of choice, for example *.iot.mycompany.com rather than the default URL of {{< product-c8y-iot >}} Edge. In addition, you can create subtenants
```

2023-04-03 10:52 UTC, BeateRixen commented on content/edge/configuration-bundle/changing-domain-name.md
> +using your domain. These will be using **\<subtenantName\>.iot.mycompany.com** as their host names.
```suggestion
using your domain. These will use **\<subtenantName\>.iot.mycompany.com** as their host names.
```

2023-04-03 10:53 UTC, BeateRixen commented on content/edge/configuration-bundle/configuring-karaf.md
> +To enhance the performance and resource allocation for Karaf, you can change the environment variables for Karaf (such as `JAVA_MAX_MEM` and the microservice proxy variables like `MICROSERVICE_RUNTIM
```suggestion
To enhance the performance and resource allocation for Karaf, you can change the environment variables for Karaf (such as `JAVA_MAX_MEM` and the microservice proxy variables like `MICROSERVICE_RUNTIME_PROXY_HTTP_HOST`, `MICROSERVICE_RUNTIME_PROXY_HTTP_PORT`), you must update the file */usr/share/cumulocity-core-karaf/bin/setenv.* To do so:
```

2023-04-03 10:56 UTC, BeateRixen commented on content/edge/configuration-bundle/configuring-the-hostname.md
> +The default hostname of the Edge appliance is **iot-edge-server**. You can define a unique hostname for your Edge appliance as per your requirements. A unique hostname ensures seamless communication
```suggestion
The default hostname of the Edge appliance is **iot-edge-server**. You can define a unique hostname for your Edge appliance as required. A unique hostname ensures seamless communication within the network, avoids any hostname conflicts with other network devices and improves the security of your Edge device.
```

2023-04-03 11:17 UTC, rssag requested changes

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +   mongofiles -d management --prefix cmdata get  APP_ID -l /tmp/apps/APP_NAME.zip
is this a single command? if it's two, it should be "commands" above.
also missing a closing line for the code listing

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +   ```
missing an opening line for the code listing for the example commands

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +   {{< c8y-admon-important >}} Create a backup of the streaming-analytics-app.zip file separately.{{< /c8y-admon-important >}}
```suggestion
   {{< c8y-admon-important >}}Create a backup of the *streaming-analytics-app.zip* file separately.{{< /c8y-admon-important >}}
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +   Do not include the *streaming-analytics-app.zip* file in the ZIP package.
content should not be indented (contrary to the indentation of the admonition tags themselves).

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +   Here:
might want to split into more code listings here

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +   Wait for Karaf to install the applications. After the installation is complete, the $UI_VERSION.zip.installed file appears at /webapps/2Install
arguably not part of the code listing

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +9. Copy the `/etc/opcua` directory from the Edge 10.7 appliance to the same location on the Edge 10.9 appliance.
```suggestion
9. Copy the */etc/opcua* directory from the Edge 10.7 appliance to the same location on the Edge 10.9 appliance.
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +
```suggestion
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +{{< company-sag >}} provides the `backup.sh` and `restore.sh` scripts for your reference. You may customize these scripts for your requirements and automate the migration process. These scripts are a
```suggestion
{{< company-sag >}} provides the *backup.sh* and *restore.sh* scripts for your reference. You may customize these scripts for your requirements and automate the migration process. These scripts are available at:
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +- [restore.sh](/files/edge/restore.sh) - you must run the restore.sh script as a **root** user.
```suggestion
- [restore.sh](/files/edge/restore.sh) - you must run the *restore.sh* script as a root user.
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +
```suggestion
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +
```suggestion
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +Before the data back up, ensure that there is sufficient disk space to save the backup in your Edge 10.7 appliance. The MongoDB backup requires the same amount of space as the database. For example,
```suggestion
Before the data back up, ensure that there is sufficient disk space to save the backup in your Edge 10.7 appliance. The MongoDB backup requires the same amount of space as the database. For example, if the size of the database is 100 GB, the MongoDB backup also requires 100 GB of disk space. You need an additional 100 GB of disk space to save the MongoDB backup in your Edge 10.7 appliance.
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +4. Run the `backup.sh` as a root user.
```suggestion
4. Run the *backup.sh* as a root user.
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +    {{< c8y-admon-info >}}If you do not specify any parameter, the backup archive is saved at */tmp* directory. The */tmp* directory is located on the installation disk. If the installation disk has
```suggestion
    {{< c8y-admon-info >}}If you do not specify any parameter, the backup archive is saved to the */tmp* directory. The */tmp* directory is located on the installation disk. If the installation disk has no space, the system can become unstable.{{< /c8y-admon-info >}}
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +2. Copy the `restore.sh` and `restore_analytics.sh` scripts to your Edge 10.9 appliance.
```suggestion
2. Copy the *restore.sh* and *restore_analytics.sh* scripts to your Edge 10.9 appliance.
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +3. Run the `restore.sh` script with the parameters:
```suggestion
3. Run the *restore.sh* script with the parameters:
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +    The `restore.sh` script fails if your Edge appliance is not connected to the internet. In such cases, ensure that the RPM package is available locally, and replace the command `rpm -ivh http://mi
```suggestion
    The *restore.sh* script fails if your Edge appliance is not connected to the internet. In such cases, ensure that the RPM package is available locally, and replace the command `rpm -ivh http://mirror.centos.org/centos/7/os/x86_64/Packages/zip-3.0-11.el7.x86_64.rpm` with `rpm -ivh zip-3.0-11.el7.x86_64.rpm` in the *restore.sh* script.
```

2023-04-03 11:17 UTC, rssag commented on content/edge/update-bundle/migration-107-to-109.md
> +   Here:
arguable not part of the listing

2023-04-03 12:22 UTC, sharath-jk commented on content/edge/update-bundle/migration-107-to-109.md
> +   Here:
@rssag - could you please elaborate on this comment?

2023-04-03 12:35 UTC, BeateRixen commented on content/edge/operating-edge-bundle/troubleshooting.md
> +* Perform a health check, see the [Health check](/edge/operating-edge/#health-check) section.
@rssag You suggest to remove the "section" at the end of the link which is fine, but then the article before the link should be removed as well, shouldn´t it?

2023-04-03 12:40 UTC, BeateRixen commented on content/edge/rest-api.md
> +For information about the REST APIs for {{< product-c8y-iot >}} Edge, see [OpenAPI documentation](https://cumulocity.com/api/).
@rssag @sharath-jk We have a shortcode for "Cumulocity IoT Open API specification". I suggest to use it here.

2023-04-03 12:42 UTC, sharath-jk commented on content/edge/operating-edge-bundle/troubleshooting.md
> +* Perform a health check, see the [Health check](/edge/operating-edge/#health-check) section.
I was making that change already in the source.

2023-04-03 12:55 UTC, sharath-jk commented on content/edge/using-edge-bundle/branding.md
> +<img src="/images/users-guide/enterprise-tenant/et-branding.png" alt="Branding tab">
@rssag - I've just used the text that was available here:
/users-guide/enterprise-tenant/#branding

Please let me know if I need to change to MD image?

2023-04-03 13:10 UTC, sharath-jk commented on content/edge/update-bundle/migration-107-to-109.md
> +
Done.

2023-04-03 13:10 UTC, sharath-jk commented on content/edge/update-bundle/migration-107-to-109.md
> +
Done.

2023-04-03 13:40 UTC, sharath-jk commented on content/edge/update-bundle/migration-107-to-109.md
> +   Do not include the *streaming-analytics-app.zip* file in the ZIP package.
Done.

2023-04-03 13:44 UTC, sharath-jk commented on content/edge/update-bundle/migration-107-to-109.md
> +   Here:
Done.

2023-04-03 13:46 UTC, sharath-jk commented on content/edge/update-bundle/migration-107-to-109.md
> +   Wait for Karaf to install the applications. After the installation is complete, the $UI_VERSION.zip.installed file appears at /webapps/2Install
Done

2023-04-03 13:49 UTC, sharath-jk commented on content/edge/update-bundle/migration-107-to-109.md
> +10. Copy the */var/lib/cumulocity-agent/credentials* file from the Edge 10.7 appliance to the same location on the Edge 10.9 appliance.
We tried doing that before and the migration looked a little confusing. We want the customer to follow steps in the exact order and not deviate. So retaining the steps.

2023-04-03 13:57 UTC, sharath-jk commented on content/edge/update-bundle/migration-107-to-109.md
> +   Here:
Done.

2023-04-03 14:06 UTC, sharath-jk commented on content/edge/rest-api.md
> +For information about the REST APIs for {{< product-c8y-iot >}} Edge, see [OpenAPI documentation](https://cumulocity.com/api/).
Done.

2023-04-04 09:24 UTC, rssag approved these changes
approved, but there is one additional suggestion :)

2023-04-04 09:24 UTC, rssag commented on content/edge/configuration-bundle/changing-domain-name.md
> +using your domain. These will use **\<subtenantName\>.iot.mycompany.com** as their host names.
```suggestion
using your domain. These will use *\<subtenantName\>.iot.mycompany.com* as their host names.
```

2023-04-04 09:24 UTC, rssag commented
what is the target version?

2023-04-04 10:01 UTC, merged