MTM-51772 revoke tokens to log out users
SoftwareAG/c8y-docs pull request #934
Opened 2023-03-06 18:56 UTC by mmed-softwareag

2023-03-07 08:06 UTC, Michal-Bak requested changes

2023-03-07 08:06 UTC, Michal-Bak commented on content/users-guide/administration-bundle/managing-users.md
> +Note that, if the "Basic Authentication" is used, the users logged with base64 token will logged out.
I guess it is not true.

2023-03-07 08:15 UTC, rssag commented on content/users-guide/administration-bundle/managing-users.md
> +To log out all users click **Log out all users**  at the right of the top menu bar. This will log out all users logged with "OAI-Secure" or "Single sign-on redirect". JWT tokens retrieved by all devi
```suggestion
To log out all users click **Log out all users**  at the right of the top menu bar. This logs out all users currently logged in via OAI-Secure or single sign-on redirect. JWT tokens retrieved by all devices in the current tenant are also invalidated.
```

2023-03-07 08:16 UTC, rssag commented on content/users-guide/administration-bundle/managing-users.md
> +Note that, if the "Basic Authentication" is used, the users logged with base64 token will logged out.
```suggestion
Note that, if basic authentication is used, users logged in via base64 token are logged out.
```

2023-03-15 09:18 UTC, rssag commented on content/users-guide/administration-bundle/managing-users.md
> +Note that, if the "Basic Authentication" is used, the users logged with base64 token will logged out.
```suggestion
Note that, if the "Basic Authentication" is used, the users logged with base64 token are logged out.
```

2023-04-03 14:25 UTC, Michal-Bak approved these changes

2023-04-03 14:42 UTC, BeateRixen approved these changes

2023-04-03 14:43 UTC, merged