OPC UA Gateway thin-edge.io integration
SoftwareAG/c8y-docs pull request #945
Opened 2023-03-21 13:09 UTC by PestusAtSAG

2023-03-21 13:20 UTC, sag-eweingaertner commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +  #
Why this empty comment?

2023-03-22 06:31 UTC, Oezge-Akin reviewed
Can you add a note in Registering the gateway as a Cumulocity IoT device section that for thinEdge installations this step will be automatically done?

2023-03-22 06:31 UTC, Oezge-Akin commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +    deviceId: My Gateway
- enabled is false by default, can you do the same here? 
- deviceId here should be the edge device name. Mqtt client ID desc. won't be understandable by the user and we need to mention that it should match with thinEdge device name. 
- There is a typo in mqttServerURL there.

Actually the application-default.yaml is more descriptive about all those fields and more understandable:
```
  thinEdge:
    # Enable thinEdge if OPC UA gateway is running next to thinEdge and should use thinEdge to connect to Cumulocity.
    # set enabled to false if OPC UA gateway is running without thinEdge
    enabled: false
    # MQTT Server URL of thinEdge (localhost)
    mqttServerURL: tcp://127.0.0.1:1883
    # Enables if mqtt client will use a steady and single connection. Beware that mqtt is only used to retrieve JWT, which is done depending how long JWT is valid. This is configurable (https://cumulocity.com/guides/device-sdk/mqtt/#jwt-token-retrieval)
    # It is recommended to use a steady connection only if the JWT is valid for a short time. Is the JWT for a longer time valid, standard 1h. It is not recommended to have a steady mqtt connection.
    mqttSteadyConnection: false
    # thinEdge deviceId must be changed, depends on the configured deviceId of the thin edge certificate, see https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/connect-c8y.md#create-the-certificate
    deviceId: my-thin-edge-device
```

2023-03-22 09:39 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +OPC UA Gateway can also be registered and operated via [thin-edge.io](https://thin-edge.io/). In contrast to standalone mode `thinEdge` configurations must be added to YAML file:
added

2023-03-22 09:40 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +  #
added comment

2023-03-22 09:41 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +    deviceId: My Gateway
Yes, you are right, i used the the documentation form application-default.yaml

2023-03-22 10:10 UTC, Oezge-Akin commented on content/protocol-integration/opcua-bundle/register-gateway-as-device.md
> +If you run the OPC UA Gateway in thin-edge mode, manual registration is not needed. Thin-edge will automatically register OPC UA Gateway at Cumulocity as subdevice.
-> as subdevice of the thinEdge device.

2023-03-22 14:01 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/register-gateway-as-device.md
> +If you run the OPC UA Gateway in thin-edge mode, manual registration is not needed. Thin-edge will automatically register OPC UA Gateway at Cumulocity as subdevice.
yes, makes sense, done

2023-03-22 14:14 UTC, sag-eweingaertner approved these changes

2023-03-22 14:51 UTC, rssag requested changes

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +The OPC UA Gateway can also be registered and operated via [thin-edge.io](https://thin-edge.io/). In contrast to standalone mode `thinEdge` configurations must be added to YAML file:
```suggestion
The OPC UA gateway can also be registered and operated via [thin-edge.io](https://thin-edge.io/). In contrast to the standalone mode, `thinEdge` configurations must be added to the YAML file:
```

which yaml file? *application-myTenant.yaml* from above? or another file?

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +    name: My Gateway
not saying it's wrong, but since there's no quotes here - the name contains a space character, and like this, the capitalization on "Gateway" (as the second word) goes against our capitalization rules.

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +        deviceId: My Gateway
see above (name)

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +With the configuration `gateway.thinEdge.enabled: true` you switch to the thinEdge mode. Which means the authentication and registration to the platform will be done via thin-edge. The OPC UA gateway
```suggestion
With the configuration `gateway.thinEdge.enabled: true` you switch to the thinEdge mode. This means that the authentication and registration to the platform will be done via Thin Edge. The OPC UA gateway is automatically registered and created as a sub-device under the Thin Edge device. `gateway.thinEdge.mqttServerURL` and `gateway.thinEdge.deviceId` are the connection information for the MQTT client to connect to the local Thin Edge MQTT broker. 
```

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +  # These settings configure and enable/disable thin-edge mode (registration and operating OPC UA Gateway via thin-edge)
```suggestion
  # These settings configure and enable/disable Thin Edge mode (registration and operating OPC UA Gateway via thin-edge)
```

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +    # Enable thinEdge if OPC UA gateway is running next to thinEdge and should use thinEdge to connect to Cumulocity.
```suggestion
    # Enable thinEdge if the OPC UA gateway is running next to Thin Edge and should use Thin Edge to connect to {{< product-c8y-iot >}}.
```

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +    # set enabled to false if OPC UA gateway is running without thinEdge
```suggestion
    # Set enabled to false if the OPC UA gateway is running without Thin Edge.
```

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +    # MQTT Server URL of thinEdge (localhost)
```suggestion
    # MQTT Server URL of Thin Edge (localhost).
```

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +    # Enables if mqtt client will use a steady and single connection. Beware that mqtt is only used to retrieve JWT, which is done depending how long JWT is valid. This is configurable (https://cumul
```suggestion
    # Enable this if the MQTT client uses a single steady connection. Note that MQTT is only used to retrieve the JWT, which is dependent on how long the JWT is valid. See https://cumulocity.com/guides/device-integration/mqtt/#jwt-token-retrieval.
```

We're in a code listing here, so we cannot use a normal reference:

`Refer to [Device integration using MQTT > Device certificates > JWT token retrieval](/device-integration/mqtt/#jwt-token-retrieval) in *Device integration* for information on how to configure this.`

i'm not sure if it is super helpful to add a URL that is not clickable.
how do we handle this in general? @BeateRixen

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +    # It is recommended to use a steady connection only if the JWT is valid for a short time. Is the JWT for a longer time valid, standard 1h. It is not recommended to have a steady mqtt connection.
```suggestion
    # We recommend you to use a steady connection only if the JWT is valid for a short time. If the JWT is valid for a longer time, the standard is one hour. It is generally not recommended to have a steady MQTT connection.
```

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +    # thinEdge deviceId must be changed, depends on the configured deviceId of the thin edge certificate, see https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/connect-c8y.md#cre
```suggestion
    # The Thin Edge deviceId must be changed, depending on the configured deviceId of the Thin Edge certificate, see https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/connect-c8y.md#create-the-certificate.
```

see above, unsure if not clickable URLs are user-friendly.

2023-03-22 14:51 UTC, rssag commented on content/protocol-integration/opcua-bundle/register-gateway-as-device.md
> +If you run the OPC UA Gateway in thin-edge mode, manual registration is not needed. Thin-edge will automatically register OPC UA Gateway at Cumulocity as subdevice of its device.
```suggestion
If you run the OPC UA Gateway in Thin Edge mode, manual registration is not needed. Thin Edge automatically registers the OPC UA Gateway at {{< product-c8y-iot >}} as a sub-device of its device.
```

2023-03-22 14:51 UTC, rssag commented
what are the target versions? @PestusAtSAG

2023-03-23 07:03 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +The OPC UA Gateway can also be registered and operated via [thin-edge.io](https://thin-edge.io/). In contrast to standalone mode `thinEdge` configurations must be added to YAML file:
changed to you suggestion

2023-03-23 07:03 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +    name: My Gateway
changed to Gateway_Device in both identitfier and name

2023-03-23 07:04 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +        deviceId: My Gateway
see above

2023-03-23 07:07 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +With the configuration `gateway.thinEdge.enabled: true` you switch to the thinEdge mode. Which means the authentication and registration to the platform will be done via thin-edge. The OPC UA gateway
changed to your suggestions

2023-03-23 07:08 UTC, PestusAtSAG commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +  # These settings configure and enable/disable thin-edge mode (registration and operating OPC UA Gateway via thin-edge)
changed to your suggestions

2023-03-23 07:29 UTC, PestusAtSAG commented
> what are the target versions? @PestusAtSAG
@Oezge-Akin  I don't know, can you tell what the target version is?

2023-03-23 07:56 UTC, Oezge-Akin commented
> > what are the target versions? @PestusAtSAG
> > @Oezge-Akin  I don't know, can you tell what the target version is?

@rssag it is 10.18.

2023-03-23 14:30 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +### Thin-Edge
```suggestion
### Thin Edge
```

2023-03-23 14:33 UTC, rssag commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +  # These settings configure and enable/disable Thin Edge mode (registration and operating OPC UA Gateway via thin-edge)
```suggestion
  # These settings configure and enable/disable Thin Edge mode (registration and operating OPC UA gateway via Thin Edge).
```

2023-03-27 07:17 UTC, Oezge-Akin commented on content/protocol-integration/opcua-bundle/gateway-register.md
> +        deviceId: Gateway_Device
shouldn't this value be the thinEdge deviceId?

2023-03-31 06:09 UTC, Oezge-Akin approved these changes

2023-03-31 06:47 UTC, merged