DM-2126 "Services" chapter fix.
SoftwareAG/c8y-docs pull request #946
Opened 2023-03-21 15:03 UTC by MaciekSoftwareAG

2023-03-21 16:15 UTC, rssag requested changes

2023-03-21 16:15 UTC, rssag commented on content/reference/device-management-library-bundle/services.md
> +Or using SmartREST static template 104 sent to topic `s/us/<serviceId>`:
```suggestion
Or using [SmartREST static template 104](/reference/smartrest-two/#104) sent to topic `s/us/<serviceId>`:
```

2023-03-21 16:15 UTC, rssag commented on content/reference/device-management-library-bundle/services.md
> +Or using SmartREST static template 200 sent to topic `s/us/<serviceId>`:
```suggestion
Or using [SmartREST static template 200](/reference/smartrest-two/#200) sent to topic `s/us/<serviceId>`:
```

2023-03-29 13:17 UTC, MaciekSoftwareAG commented on content/reference/device-management-library-bundle/services.md
>  |serviceType  | Yes       | An arbitrary string for organizing services|
Please click the "Content type" and change the content type to `application/vnd.com.nsn.cumulocity.managedobject+json`.

2023-03-30 09:06 UTC, MaciekSoftwareAG commented on content/reference/device-management-library-bundle/services.md
>  | ----  | ----      | ----    |
Same as the other one.

2023-04-02 20:57 UTC, MaciekSoftwareAG commented on content/reference/device-management-library-bundle/services.md
>  | ----  | ----      | ----    |
You are right. This should be PUT.

2023-04-02 20:59 UTC, MaciekSoftwareAG commented on content/reference/device-management-library-bundle/services.md
>  | ----  | ----      | ----    |
Fixed.

2023-04-03 09:17 UTC, rssag approved these changes

2023-04-05 10:48 UTC, l2p- commented on content/reference/device-management-library-bundle/services.md
> +    "id": "<managedObjectId>"
```suggestion
    "id": "<serviceManagedObjectId>"
```

2023-04-05 11:00 UTC, l2p- requested changes

2023-04-05 11:00 UTC, l2p- commented on content/reference/device-management-library-bundle/services.md
> +
There are several ways a HTTP connected device can fin their service child ID. This is one of them if the device also creates an external ID when it creates the service child object. Since we don't define how this must be done at the creation time I wouldn't go into it here
```suggestion
```

2023-04-06 09:26 UTC, merged