MQTT Cheatsheet part 2
SoftwareAG/c8y-docs pull request #95
Opened 2021-11-17 14:37 UTC by rssag

2021-11-17 14:47 UTC, BeateRixen commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +To use the templates listed in below, you need to publish the messages to the topic <kbd>s/us</kbd> (<kbd>t/us</kbd> for transient processing of published content, <kbd>q/us</kbd> for quiescent proce
listed in below > listed below

2021-11-26 15:04 UTC, karolkaczmarski-sag requested changes

2021-11-29 11:06 UTC, rssag commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +  Connect the device with serial "1234" and default template "myDevice_10" to tenant "acme" and user "device_1234"
done

2021-11-29 11:06 UTC, rssag commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +To use the templates listed in below, you need to publish the messages to the topic <kbd>s/us</kbd> (<kbd>t/us</kbd> for transient processing of published content, <kbd>q/us</kbd> for quiescent proce
done

2021-11-29 12:54 UTC, rssag commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +* `<protocol>` can be <kbd>s</kbd> (standard) or <kbd>t</kbd> (transient)
done

2021-11-29 15:36 UTC, rssag commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +* <kbd>CONNECT 1234:myDevice_10 acme/device_1234</kbd> \
i added the "d:" before "CONNECT, is that correct? @karolkaczmarski-sag

2021-11-29 15:44 UTC, rssag commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +#### Quick reference
ok, i created a new file quick-reference.md that is directly below "overview" in the navigation and placed the contents there, including the link table to the static templates

2021-12-02 16:52 UTC, karolkaczmarski-sag requested changes

2021-12-02 16:52 UTC, karolkaczmarski-sag commented on content/device-sdk/mqtt-bundle/quick-reference.md
> +* <kbd>d:CONNECT 1234:myDevice_10 acme/device_1234</kbd> \
it should be `CONNECT d:1234:myDevice_10 acme/device_1234`

2021-12-02 16:52 UTC, karolkaczmarski-sag commented on content/device-sdk/mqtt-bundle/quick-reference.md
> +* <kbd>SUBSCRIBE s/ds</kbd> - Receive built-in commands
built-in -> static

2021-12-02 16:52 UTC, karolkaczmarski-sag commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +#### Quick reference
Where it is linked? I can't see that in this PR. 
Please also remove changes from mqtt-static-templates.md or do we want to duplicate it?

2021-12-02 16:54 UTC, karolkaczmarski-sag commented
Please squash commits into single one and give meaningful description

2021-12-03 08:04 UTC, rssag commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +#### Quick reference
it's sorted via the weight field in the frontmatter header of the new file.
Screenshot:
![Screenshot from 2021-12-03 09-01-56](https://user-images.githubusercontent.com/67586553/144567026-63e219cc-8b2d-427b-952a-25defabe3c5c.png)

i only copied the quick links to the static templates.
those have been recently added as the cheatsheet drop 1.
i can see however, why it might be better to leave them there. what do you think?

2021-12-03 08:13 UTC, rssag commented on content/device-sdk/mqtt-bundle/quick-reference.md
> +* <kbd>d:CONNECT 1234:myDevice_10 acme/device_1234</kbd> \
right - done.

2021-12-03 08:14 UTC, rssag commented on content/device-sdk/mqtt-bundle/quick-reference.md
> +* <kbd>SUBSCRIBE s/ds</kbd> - Receive built-in commands
done

2021-12-03 08:20 UTC, rssag commented on content/device-sdk/mqtt-bundle/quick-reference.md
> +* <kbd>d:CONNECT 1234:myDevice_10 acme/device_1234</kbd> \
done

2021-12-03 08:21 UTC, rssag commented on content/device-sdk/mqtt-bundle/quick-reference.md
> +* <kbd>SUBSCRIBE s/ds</kbd> - Receive built-in commands
done

2021-12-03 08:22 UTC, rssag commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> +#### Quick reference
![Screenshot from 2021-12-03 09-01-56](https://user-images.githubusercontent.com/67586553/144569369-f76281bd-915e-4cf5-8072-be8564a2a50f.png)
it's sorted in the nav via the weight attribute of the frontmatter header of the new file.

right, i think my editor didnt save the removal. will do

2021-12-03 16:17 UTC, karolkaczmarski-sag approved these changes
I still don't see how it's linked in the menu, but content looks ok.

2021-12-03 16:17 UTC, karolkaczmarski-sag commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> -To use the templates listed below, you need to publish the messages to the topic <kbd>s/us</kbd> (<kbd>t/us</kbd> for transient processing of published content, <kbd>q/us</kbd> for quiescent processi
I would leave it here... It's specific to static templates

2021-12-06 07:51 UTC, rssag commented on content/device-sdk/mqtt-bundle/mqtt-static-templates.md
> -To use the templates listed below, you need to publish the messages to the topic <kbd>s/us</kbd> (<kbd>t/us</kbd> for transient processing of published content, <kbd>q/us</kbd> for quiescent processi
agreed, i restored this part here, and referenced it in the new file.

2021-12-06 07:57 UTC, BeateRixen approved these changes

2021-12-06 10:15 UTC, MWindel requested changes

2021-12-06 10:15 UTC, MWindel commented on content/device-sdk/mqtt-bundle/quick-reference.md
> +  Connect the device with serial "1234" and default template myDevice_10 to tenant "acme" and user "device_1234"
- Only one bullet point, does this need to be a list? 
- Add a full stop to keep layout/grammar consistent with other bullet lists in Device SDK guide.

2021-12-06 10:15 UTC, MWindel commented on content/device-sdk/mqtt-bundle/quick-reference.md
> +* <kbd>PUBLISH s/us</kbd> - Send a static template
- Add full stop or comma to keep consistent in layout with other bulleted lists in Device SDK guide.

2021-12-06 10:15 UTC, MWindel commented on content/device-sdk/mqtt-bundle/quick-reference.md
> +* `<protocol>` can be <kbd>s</kbd> (persistent), <kbd>t</kbd> (transient), <kbd>q</kbd> (quiescent) and <kbd>c</kbd> (CEP), see [processing modes](#processing-mode) for more information
see above

2021-12-06 10:31 UTC, MWindel approved these changes

2021-12-06 10:32 UTC, MWindel approved these changes

2021-12-06 10:44 UTC, BeateRixen approved these changes

2021-12-06 10:47 UTC, merged