MTM-52197 add remark on timed-out connections and retries
SoftwareAG/c8y-docs pull request #954
Opened 2023-03-28 10:45 UTC by Markus-SWAG

2023-03-28 13:18 UTC, mgrumann reviewed
Fine with me!

2023-03-28 15:56 UTC, rssag requested changes

2023-03-28 20:08 UTC, Markus-SWAG commented
Danke, jetzt einfach noch den "Approve"-Haken setzen...

Best regards
Markus Greiner
Sr. Architect
T +49-6151-92-1148
***@***.******@***.***>
Software AG, Uhlandstrasse 12, 64297 Darmstadt, Germany

[cid:e5f3bb0d-8e06-43da-9fb6-670fb462f5c1]<http://www.softwareag.com/>
[Icon  Description automatically generated]<https://www.linkedin.com/company/software-ag>
[cid:a4ddc16c-c762-4041-8ad0-f2c8ccb2f692]<https://twitter.com/SoftwareAG>
[cid:d197740a-eb1b-4b50-ba94-0d3992e0504f]<https://www.youtube.com/c/SOFTWAREAGglobal>
[cid:920f159f-6c5f-43ba-b826-73fbfe6d3105]<https://www.instagram.com/softwareag_life/>
[cid:7d5465f4-97ca-4101-838d-2f16c63b698a]<https://www.facebook.com/SoftwareAG>



[cid:a7fcb78c-4bdd-405a-b818-148ebba4bba3]

[cid:5c4bcaf3-5715-4d3f-a94b-addb84d245fc]<https://www.softwareag.com/en_corporate/company/connected-enterprise.html?at=navpromo_about?utm_source=sales&utm_medium=email&utm_region=hq&utm_campaign=swag-brand_umbrella&utm_subcampaign=empower_email_sig&utm_content=webpage_tce>

________________________________
From: mgrumann ***@***.***>
Sent: Tuesday, March 28, 2023 15:19
To: SoftwareAG/c8y-docs ***@***.***>
Cc: Greiner, Markus ***@***.***>; Author ***@***.***>
Subject: Re: [SoftwareAG/c8y-docs] MTM-52197 add remark on timed-out connections and retries (PR #954)


@mgrumann commented on this pull request.

Fine with me!

—
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSoftwareAG%2Fc8y-docs%2Fpull%2F954%23pullrequestreview-1361060970&data=05%7C01%7Cmarkus.greiner%40softwareag.com%7C70ff0225cb3c468b41ec08db2f8efff2%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C638156063451678172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xyGzM3xHs2vMY2RDJTc0BahigcNE4tMQyV2Vd4RjCMs%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVRILYR7NNDIS4V6OLTU4I3W6LQMLANCNFSM6AAAAAAWKMGMXQ&data=05%7C01%7Cmarkus.greiner%40softwareag.com%7C70ff0225cb3c468b41ec08db2f8efff2%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C638156063451678172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IxFPjK2S9VPtNcMfPOkTRwvVoX8oXf%2FMPgy5kxbiLyI%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Software AG – Sitz/Registered office: Uhlandstraße 12, 64297 Darmstadt, Germany – Registergericht/Commercial register: Darmstadt HRB 1562 - Vorstand/Management Board: Sanjay Brahmawar (Vorsitzender/Chairman), Daniela Bünger, Joshua Husk, Dr. Benno Quade, Dr. Stefan Sigg - Aufsichtsratsvorsitzender/Chairman of the Supervisory Board: Christian Lucas - https://www.softwareag.com

2023-04-03 08:40 UTC, BeateRixen commented on content/microservice-sdk/concept-bundle/microservice-runtime.md
> +The client used in the Microservice SDK performs the required retries. Using it avoids issues with timed out connections.
```suggestion
The client used in the Microservice SDK performs the required retries. Using it avoids issues with timed-out connections.
```

2023-04-04 09:21 UTC, BeateRixen approved these changes

2023-04-05 11:26 UTC, merged