MTM-50209 Added brief introduction to extensions
SoftwareAG/c8y-docs pull request #977
Opened 2023-04-11 16:14 UTC by eniosultan

2023-04-12 07:58 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-applications.md
> +Click **Extensions** in the **Ecosystem** menu in the navigator to display a list or grid of all extensions in your account.
```suggestion
Click **Extensions** in the **Ecosystem** menu in the navigator to display all extensions in your account.
```

2023-04-12 07:58 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-applications.md
> +Extensions provide better shareability and reusability of UI features across the different applications. UI features can be developed as plugins and added to an application without coding knowledge.
```suggestion
Extensions provide better shareability and reusability of UI features across different applications. UI features can be developed as plugins and added to an application without coding knowledge. There are two types of extensions:
```

2023-04-12 07:58 UTC, BeateRixen commented on content/users-guide/administration-bundle/managing-applications.md
> +Blueprint applications can be installed, while plugins can be added into any other application. This gives the ability to scaffold whole solutions or to extend existing ones.  Due to the micro fronte
```suggestion
Blueprint applications can be installed, while plugins can be added into any other application. This allows you to scaffold whole solutions or to extend existing ones. Due to the micro frontend technology, this can happen at runtime and no re-building is needed.
```

2023-04-12 08:48 UTC, BeateRixen approved these changes

2023-04-14 11:29 UTC, rssag requested changes

2023-04-14 11:29 UTC, rssag commented on content/users-guide/administration-bundle/managing-applications.md
> +Extensions provide better shareability and reusability of UI features across different applications. UI features can be developed as plugins and added to an application without coding knowledge. Ther
```suggestion
Extensions make it easier to share and reuse UI features across different applications. UI features can be developed as plugins and added to an application without coding knowledge. There are two types of extensions:
```

2023-04-14 11:29 UTC, rssag commented on content/users-guide/administration-bundle/managing-applications.md
> +Blueprint applications can be installed, while plugins can be added into any other application. This allows you to scaffold whole solutions or to extend existing ones. Due to the micro frontend techn
```suggestion
Blueprint applications can be installed, while plugins are added to other applications. This allows you to scaffold entire solutions or to extend existing ones. Due to the micro frontend technology, this can happen at runtime without rebuilding.
```

2023-04-14 11:29 UTC, rssag commented on content/users-guide/administration-bundle/managing-applications.md
> +Blueprint applications can be installed, while plugins can be added into any other application. This allows you to scaffold whole solutions or to extend existing ones. Due to the micro frontend techn
i'm not sure if "can be installed" is the right choice (for blueprint applications). maybe "must be installed"? or is there another way of making them work?

2023-04-14 11:57 UTC, eniosultan commented on content/users-guide/administration-bundle/managing-applications.md
> +Blueprint applications can be installed, while plugins are added to other applications. This allows you to scaffold entire solutions or to extend existing ones. Due to the micro frontend technology,
```suggestion
Blueprint applications must be deployed, while plugins are added to other applications. This allows you to scaffold entire solutions or to extend existing ones. Due to the micro frontend technology, this can happen at runtime without rebuilding.
```

2023-04-14 11:57 UTC, eniosultan commented on content/users-guide/administration-bundle/managing-applications.md
> +Blueprint applications can be installed, while plugins can be added into any other application. This allows you to scaffold whole solutions or to extend existing ones. Due to the micro frontend techn
Changed to "must be deployed"

2023-04-17 16:01 UTC, rssag approved these changes

2023-04-17 16:02 UTC, rssag commented
what are the target versions?

2023-04-18 08:40 UTC, eniosultan commented
> what are the target versions?

10.16, 10.17, 10.18 and all future versions :)

2023-04-18 08:52 UTC, merged

2023-04-18 09:05 UTC, BeateRixen commented
> > what are the target versions?
> 
> 10.16, 10.17, 10.18 and all future versions :)

Done